### ISSUE TITLE
Service Groups with different application names are grouped together

### ISSUE THREAD

**Issue by gscho** [chef/automate#1000]
## Describe the bug
When loading a new habitat service with event streaming enabled, the automate beta UI will group that service into any existing service group that matches the name, ignoring the `----event-stream-application` setting.

## To Reproduce
- Start one supervisor with event streams enabled and `--event-stream-application=app-1`
- Load up a redis server: `hab svc load core/redis`
- Start another supervisor on a different VM with event streams enabled and `--event-stream-application=app-2`
- Load up the same service as the first supervisor: `hab svc load core/redis`
- The automate UI will show 2 instances of redis.default grouped under `app-1`

## Expected behavior
I would expect there to be 2 groupings of redis.default in the UI. One showing `app-1` as the App name and the other showing `app-2`.

## Screenshots
TBD

## Versions (please complete the following information):
- OS: TBD
- Supervisor version 0.83.0
- Browser: firefox
- Automate Build Number: TBD

## Additional context
N/A

**Comment by danielsdeleo** [comment]
Working on this one, see the referenced PR for more

**Comment by danielsdeleo** [comment]
I didn't get the buildstamp of the first build with the patch applied, but the patch is present in the current dev build with buildstamp `20190731171254`. Any version after this will contain the fix. If we are able to keep to our normal promotion schedule, then the fix should be released to the acceptance channel on August 5 or 6.

**Comment by gscho** [comment]
Thanks @danielsdeleo !
