### ISSUE TITLE
Teams: Align _Add User_ with Policy _Add Member_

### ISSUE THREAD

**Issue by susanev** [chef/automate#1006]
## Overview

To improve consistency and the user experience this task aligns the _Add User_ flow in Teams with the _Add Member_ flow in Policies.

## Design Details

[Designs in Zeplin](https://app.zeplin.io/project/5ba808703eb54372d860c737?seid=5cb5e8d2e6267e081e743067)

### Team Detail Page
* Change _Add User_ button to _Add Users_

### Add Users to Team Full-page 
* Heading: _Add Users to `<team name>`_
* Subheading: _Only local users can be added to teams._
* Table headings: Name, and Username
* Top of table displays the count of the number of users selected
* The table has name, and username columns; the links for the name should open in a new tab (because it breaks the user out of their flow)
* After adding users, send back to the team detail page with on-page user notification of _Added 1 user._ or _Added `<n>` users._
* On the case where there are no local users or all the local users have already been added to the team hide the table and display _There are no more local users to add, create some more!_ with _users_ being a link to`/users` that opens in a new tab

#### Buttons
* Primary button: _Add User_ when disabled, _Add User_ when one selected and enabled, Add _`<n>` Users_ when more than one user is selected and enabled; after user-action on the button the label becomes _Adding User..._ or _Adding Users..._ with the loading icon
* Tertiary button: _Cancel_

**Comment by srenatus** [comment]
@tylercloke: ℹ️Assigned you since you've pull it from RFA.

**Comment by srenatus** [comment]
The card says
>Automate only displays local users.

the UI says
> Only local users can be added to teams.

I'm assuming this has been discussed. (Just because I think the latter, what the UI displays, is a tad better :wink:)

**Comment by susanev** [comment]
@srenatus yes, discussed. 😞. i will get better about updating things after discussions.
