### ISSUE TITLE
Give the ability to remove nodes from view in bulk via the GUI

### ISSUE THREAD

**Issue by jonong1972** [chef/automate#1014]
## User Story

As a user of Automate, I will use this work when I want to remove nodes that I accidently added within the Node Manager/Integration.

## Definition of Done
A User will be able to remove multiple nodes at a time.

## Demo Script / Repro Steps
1. Goto `/compliance/scan-jobs/nodes`
2. Click on Nodes Added tab
3. Click on multiple nodes that have a checkbox
4. Click on button that will remove nodes from view.

UX still needs to mock something up for this.

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
