### ISSUE TITLE
Give the ability to remove scan jobs from view in bulk via the GUI

### ISSUE THREAD

**Issue by jonong1972** [chef/automate#1015]
## User Story

As a user of Automate, I will use this work when I want to remove any scan jobs in bulk.

## Definition of Done
A user can remove multiple scan jobs by selecting which scan jobs, and initiating a bulk remove.

## Demo Script / Repro Steps
1. goto` /compliance/scan-jobs/jobs`
2. User can select multiple scan jobs via checkboxes
3. user can then bulk remove by a button.
4. system prompts confirmation dialogue
5. system removes scan jobs.
6. System displays success/fail message.

## Mock Ups
![Screen Shot 2019-08-01 at 12.53.12 PM.png](https://images.zenhubusercontent.com/5c58b40f704a793fa6c8d7b8/525ebc00-5750-4455-b5bc-e6d06e2f74c0)

Additional changes
1.) converting the buttons on each row to the standard ellipses button. This will be dynamic based on if the scan job failed or was successful. showing the error or the report button.
2.) Updates to the table header names
3.) removing the interstitial row with the 'Add' button and moving the button above the table header as defined in the mock up.

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
