### ISSUE TITLE
Users: General UI Fixes

### ISSUE THREAD

**Issue by susanev** [chef/automate#1016]
## Overview

The Users flows are currently inconsistent with the rest of the flows in settings. This work fixes that.

## Design Details

[Designs on Zeplin](https://app.zeplin.io/project/5ba808703eb54372d860c737/dashboard?seid=5cc0c2d7b9e34653fb741ac0)

### Users List View
* Change the _Name_ column to _Display Name_
* Change user notification on create of user to _Created user: <user's username>._

#### Create User Modal
* Update styles to match designs
* Automatically generate a username from the display name
* Change _Name_ label to _Display Name_
* _Display Name_ help text: _Don't worry, display names can be changed later._
* _Password_ help text: _Must be a minimum of 8 total characters with at least 3 distinct characters.  May include both upper and lower case letters, punctuation marks, and symbols._ (note the second sentence should be on its own line)
* Only show the password error if they leave the input without meeting the requirements; currently we show the error after the user types a single character
* When the full name field has an error (e.g. all blank) the error popup width should match the input field; right now it is longer.
* Any errors on user creation should be shown in the create modal, it should not close the modal and show them on the page. See Tokens for design and implementation details.

### User Detail Pages
* Remove delete functionality from the detail page
* Match styles to the designs
* Add 2 tabs: _Details_, and _Reset Password_
* Change user notification text on reset password to: _Password reset for user: <user's username>.
* Fix the bug that does not update the user's display name in the user name after an edit has been made (requires a browser refresh, but shouldnt)

#### Repro steps for edit to user's display name bug
* Log in
* Navigate to User Menu > Profile
* Use the Edit button, top-right
* Change the name to something else, Save
* Notice that the user menu still displays the old name

### User's Profile Page
* Update left-nav to match designs
    * Heading: _USER MENU_
    * Item: _Profile_
* Update profile page to match designs
    * Heading: _Profile: <user's display name>_
    * Content: label of _Username_ and display the user's username
    * Two tabs: _Details_ and _Reset Password_ that function just like the user detail page
* Bug fix: editing the user name should immediately be reflected upon save in the profile menu dropdown. Currently, you have to logout/login to have the change take effect.

### Adjust Add Users to Team Flow
* When adding users to a team if there are no local users or all the local users have already been added to the team, hide the table and display an empty message of _There are no more local users to add, create some more! _ with a primary button below it with the label _Create User_ (see [designs for adding user to team empty case](https://zpl.io/bz7Xq43))
* Interacting with the button should open the user create modal, after creation the user should land back on the add team members flow (not be sent to the user detail page) with an option to now select that user they just created (see [designs for creating a user from add users to team page](https://zpl.io/ag6pQl1))

**Comment by msorens** [comment]
Looks great @susanev. The only suggestion I have is regarding this help string from Zeplin: 
_"Minimum of 8 total and 3 distinct characters."_ 

I think it is just slightly more useful to phrase it as: 
_"Minimum of 8 and at least 3 distinct characters."_

**Comment by susanev** [comment]
@msorens, i collaborated with @mjingle and we decided on

```
Must be a minimum of 8 total characters with at least 3 distinct characters.
 May include both upper and lower case letters, punctuation marks, and symbols.
```
