### ISSUE TITLE
move protobufs to top-level api folder

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#1029]
## User Story
The Automate team agreed, many moons ago, to move all the protobufs to a top level api folder; see https://github.com/chef/automate/blob/master/dev-docs/adr/adr-2019-01-14.md

This work has been done for some of the services, but is not yet complete. 
The list of services whose apis still need to be moved includes:
 - compliance service
 - nodemanager-service

## Definition of Done
Proto files for compliance and nodemanager moved to the api folder.

**Comment by lancewf** [comment]
The nodemanager-service protobufs have already been move. I will be moving only the compliance-service protos.

**Comment by vjeffrey** [comment]
thank you!!
