### ISSUE TITLE
Apps View: Add wildcarding to applications filtering

### ISSUE THREAD

**Issue by danielsdeleo** [chef/automate#1037]
## Description

In #773 we are adding filtering of services based on exact matches. In this one, we want to add wildcarding. The wildcard behavior should match the behavior of the Chef (Infra) Client Runs view as much as possible to provide a consistent experience.

## Definition of Done
two options for wildcards, `*` and `?`
`*` will match 0 or more letters of anything and can go in the middle, end or beginning
`?` will match exactly 1 character and can go in the middle, end or beginning

## Demo Script / Repro Steps

(TBD: get a full list of wildcarding behaviors to implement.)

**Comment by vjeffrey** [comment]
https://github.com/chef/automate/pull/1540
