### ISSUE TITLE
Don't show _Dashboards_ when you don't have permission

### ISSUE THREAD

**Issue by susanev** [chef/automate#1044]
## Overview

Currently, we always show the Event Feed even if a user does not have permission. Instead, this page should be fully hidden from the user when they do not have permission to see it. If a user does not have permission to see the Event Feed page, they should not see the Dashboards top nav and they should be directed to the next available page (left-to-right).

![event-feed-permission-state.png](https://images.zenhubusercontent.com/5c58849f0b133e639c2b7211/684d0655-5ea7-4464-8a11-1d336a7d3d83)

 ## Design Details
### User has access to at least one page
* If a user does not have permission to see the Event Feed page they should be directed to the next available page (left-to-right).

### User has access to no pages
[Abstract designs](https://share.goabstract.com/4a1ce511-6d73-4b6b-9b64-78648b9143de?mode=design&sha=cd7079a0b77dd40e9416b6c1fc3da3ccba8cffd6)
* Hide the left-nav
* Hide the projects dropdown
* Change background color to `#fff`
* Display message (with both chef support and automate documentation being external links)...
```
It looks like you do not have permission to access any data in Automate.
Reach out to your administrator or contact Chef Support for help.

In the meantime, feel free to explore the Automate documentation.
```

![1044-no-permissions](https://user-images.githubusercontent.com/5489125/64186519-d12bda00-ce23-11e9-959b-37d64002ece7.png)

## References
* [Convert SettingsLandingComponent to reusable landing component](https://github.com/chef/a2/pull/5039)
* [Settings landing page for permission-based routing](https://github.com/chef/a2/pull/4642)

**Comment by srenatus** [comment]
💭 Could we have a similar behaviour for when the backend can't be reached? Right now, we've got a pop up saying that the license cannot be verified, I think.

**Comment by susanev** [comment]
content needs to be updated to:

```It looks like you do not have permission to access any data in Automate.
Reach out to your administrator or contact Chef Support for help.

In the meantime, feel free to explore the Automate documentation.```

as part of feedback from @mjingle

**Comment by susanev** [comment]
@susanev find out if auth can more simply communicate if a user has access to no pages

**Comment by susanev** [comment]
note: the screenshots are old, the top nav is now named _Dashboards_

**Comment by srenatus** [comment]
✅ I'll accept this. Logging in as a user with no perms whatsoever, I see the blank page. When then making my user a member of the "Compliance Viewers" policy, I see the topnav containing only the Compliance tab.

**Comment by msorens** [comment]
I hope you mean blank page **_with_** no-permissions message. 😉

**Comment by susanev** [comment]
i hope so too!
