### ISSUE TITLE
Improve member expression dialog experience

### ISSUE THREAD

**Issue by susanev** [chef/automate#1046]
## Overview

Currently, the member expression dialog experience is very difficult if not impossible to use without consulting the documentation. These updates move to a progressive form input approach to guide the user through creating a member expression making it possible for a user to create a member expression without consulting the documentation.

## Assumptions
* The modal dialog is already implemented
* Close and cancel buttons already function as intended
* `Add Expression` button already has some enable/disable functionality

## Designs

[Interactive prototype](https://fr7b9g.axshare.com/#c=2)

### Content

* Type: User, Team, Token, All members (`*`)
Type -> User, Identity provider: LDAP, Local, SAML, All users (`*`)
Type -> Team, Identity provider: LDAP, Local, SAML, All teams (`*`)
Type -> Token, Name input field which allows `*`
* With each interaction with the inputs, it builds up the member expression to help inform the user of the format of the member expression.
* When all required fields are completed, the `Add Expression` button becomes enabled, otherwise, it is disabled.

## Documentation Updates
This will need some updates on the associated docs page: https://automate.chef.io/docs/iam-v2-guide/#member-expressions

**Comment by SEAjamieD** [comment]
@susanev - Do you have the cubic-bezier available that you want to use in the animation from your prototype?

**Comment by susanev** [comment]
@SEAjamieD nah, i didnt put much thought into the animation. would you be okay choosing one you think is best?

**Comment by SEAjamieD** [comment]
@susanev - Totally.  And we can tweak it after until its perfect.
