### ISSUE TITLE
Admin user should not be able to delete themselves

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#1079]
## User Story

As an Automate User, I will use this work when I accidentally try to delete my own user while logged in as that user, which would in cutting off their own access to Automate.

## Definition of Done
- [ ] the Local Administrator (username: _admin_) cannot delete her own user _admin_ when she is logged in as that user. Only _bob_, a different user with user-delete permissions, can delete _admin_

## Demo Script / Repro Steps
1. log in as the _admin_ user
2. navigate to the User list page
3. attempt to delete the _admin_ user
4. get blocked by a 403 error
5. grant new user _bob_ admin permissions
6. log in as _bob_
7. navigate to the User list page
8. successfully delete the _admin_ user

**Comment by srenatus** [comment]
Is this _one specific way_ to cut yourself off of Automate standing out, though? You can still create a policy that kills your access, or delete one that enables your access. You can remove yourself from a a group, or add yourself to a group, which could have the same effect (qua policies for that group). Before, we've sometimes discussed this, and I still think that helping the user _unblock themselves_ is better than trying to foresee what they could do wrong, and forbid them doing it. (This is how they started with [HAL](https://en.wikipedia.org/wiki/HAL_9000), I'm sure.)

**Comment by bcmdarroch** [comment]
Looks like this functionality is already in place. I logged in as `admin` and tried to delete the `admin` user and got this error message: `Could not delete user: unauthorized: members ["team:local:admins" "user:local:admin"] cannot perform action "iam:users:delete" on resource "iam:users:admin" filtered by projects []`

**Comment by susanev** [comment]
whoa did it just start working? cool.
