### ISSUE TITLE
improve API validation

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#1099]
## User Story

As an Automate User, I will use this work when I want to manage any Automate IAM resource.

## Technical Notes
In order to achieve the goals of this card, we intend to combine teams-service and authz-service (possible tokens as well) into a single service. This will allow us to store all the related IAM resources (policies, projects, roles, teams, tokens) in one database and enforce relationships at the database level.

Note: users will have to wait until we're ready to take on the local-user-service refactor and stop using dex as user storage.

## Definition of Done
- ensure all ID input validation on the frontend matches validation enforced by the backend
- references to other A2 resource are validated for existence 
     - policy members: local users, tokens, local teams
     - team members: local users

## Demo Script / Repro Steps
1. create a policy with members that do not exist, should fail with an error describing what is missing
2. create a team with users that do not exist, should fail with an error describing what is missing
3. create a token with projects that do not exist, should fail with an error describing what is missing

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
