### ISSUE TITLE
Empty state component

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#1123]
## Problem
Inconsistent experiences related to visiting a page with no data makes using Automate annoying and frustrating.

## User Story

As a Developer, I will use this work when I want to update the visual styles of an empty page.

![Screen Shot 2019-07-31 at 9.03.54 AM.png](https://images.zenhubusercontent.com/5d236338fa967b04b3b34e1d/1110899c-99c6-40ca-be95-b268e8346714)

## Definition of Done
There exists an Angular page-component that can be used to show the empty state of a list page. This component the various `empty state` styling classes we have in the app. (examples: [project-list](https://github.com/chef/automate/blob/master/components/automate-ui/src/app/pages/project/list/project-list.component.scss#L9), [notifications-list](https://github.com/chef/automate/blob/master/components/automate-ui/src/app/pages/notifications/notifications.component.scss#L182))

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
