### ISSUE TITLE
minor UI issues with "Create Rule"

### ISSUE THREAD

**Issue by srenatus** [chef/automate#1130]
## Describe the bug

1. There's a scroll bar. Not sure if this could be avoided, but in the screenshot, there's nothing more to see when scrolling down, just some more white

![image](https://user-images.githubusercontent.com/870638/62278300-0ff6fa80-b448-11e9-8d0b-5d0b2ec775ae.png)

2. I've given my rules names, but when _creating them_, it says "Create rule rule-1"
![image](https://user-images.githubusercontent.com/870638/62278509-80058080-b448-11e9-8fa7-1f0ea20d7e48.png)

3. After having created rules,
![image](https://user-images.githubusercontent.com/870638/62278672-d4a8fb80-b448-11e9-95c7-69ff7edf461d.png)
the project list still says everything was up-to-date
![image](https://user-images.githubusercontent.com/870638/62278703-e68a9e80-b448-11e9-9cc2-10bbfda674d7.png)
and on refresh, my rules disappear:
![image](https://user-images.githubusercontent.com/870638/62278787-0cb03e80-b449-11e9-9011-0bdccb5beba4.png)

⚠️ This all appeared on acceptance, so this might not account for work in progress that I'm just not aware of. Just collecting this as I find it.

**Comment by srenatus** [comment]
✔️ (2.) seems resolved in `acceptance` now

**Comment by msorens** [comment]
As of 2019.12.11:
(1) and (3) are resolved but (2) is not.
That is the message upon creating a rule still shows the id, not the name.

**Comment by susanev** [comment]
@vinay033 only thing to do here is have the rule name displayed in the notification instead of the id.
