### ISSUE TITLE
Inconsistent API requests on browser reload vs browsing wrt. project headers (IAM v2.1)

### ISSUE THREAD

**Issue by srenatus** [chef/automate#1135]
###  Describe the bug

When reloading the browser on `/settings/policies`, different requests are sent to the backend, and the displayed results thus change.

## To Reproduce

- login as admin
- ensure it says "(unassigned)" in the project picker
- browse to `Settings > Policies`
- in dev tools, we'll find the request sent contained the header `projects: (unassigned)`
- keep dev tools open, hard refresh the page
- note that the last request to `/policies` (network tab) does **not** contain that header

Depending on the existing policies, this can affect which policies are shown and which are not. If you've got access to https://a2-iamv2p1-local-inplace-upgrade-dev.cd.chef.co/settings/policies, the difference is

![image](https://user-images.githubusercontent.com/870638/62294508-60338400-b46b-11e9-9b2f-933e08412094.png)

vs

![image](https://user-images.githubusercontent.com/870638/62294497-590c7600-b46b-11e9-812b-aefb481ae40f.png)

Where the missing policy is
```
{
  "name": "Baz",
  "id": "baz",
  "type": "CUSTOM",
  "statements": [
    {
      "resources": [
        "*"
      ],
      "actions": [
        "*"
      ],
      "projects": [
        "cypress-project-1"
      ]
    },
    {
      "resources": [
        "*"
      ],
      "actions": [
        "*"
      ],
      "projects": [
        "*"
      ]
    }
  ],
  "projects": [
    "cypress-project-1",
    "cypress-project-2"
  ]
}
```

## Expected behavior

The request should always contain the project header.

**Comment by susanev** [comment]
this has been deprioritized, so closing.
