### ISSUE TITLE
IAMv2 admin token CLI command should not create a token when run on IAMv1

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#1143]
## Problem
Users are being presented with an inconsistent experience which makes Automate frustrating to use. When creating a token from the CLI users are receiving errors indicating the token was not created, even though it was created it just does not have any permissions.

## User Story

As an Automate User, I will use this work when I want to generate an admin token while on IAM v1 or v2.

Currently if Automate is on IAM v1 and I use the v2 CLI command `chef-automate iam token create ADM --admin`, I get the error: 
```
APIError: An API error occurred during execution: `chef-automate iam token create NAME --admin` is an IAM v2 command.
For v1 use `chef-automate admin-token`.
```

However, if I curl for the token I just tried to create with `curl -kH "api-token: $TOK" https://localhost/apis/iam/v2beta/tokens/adm | jq`
it turns out the token was created, despite the error. But this token has no permissions beyond default token permissions.

## Definition of Done

- [ ] `chef-automate iam token create NAME --admin` does not create a new token when run on IAM v1

**Comment by susanev** [comment]
im closing this, as soon we will be force upgrading everyone to iam v2, so iam v1 bugs are no longer relevant.
