### ISSUE TITLE
in gateway, move Rules API under Project API

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#1148]
## User Story

As a Developer, I will use this work when I want to work on the Rules API.

The Rules GRPC API is separate from the Project GRPC API in the gateway. This makes it seem like rules are independent resources, when they actually are sub-resources of projects and cannot exist without a project.

## Definition of Done
- [ ] all rules APIs (specifically, CRUD and apply APIs) live under the Projects API in the gateway

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
