### ISSUE TITLE
Set background color to `#fff` on list pages without tabs

### ISSUE THREAD

**Issue by susanev** [chef/automate#1155]
## Overview
We are working to align all of the pages in Automate with the new designs that are present on the Applications page. This issue is a small step towards that goal—it involves setting the background colors of `page-body` to `#fff` on our list pages that do not have tabs.

## Design Details

For the following pages, on `page-body` set the background color to `#fff` and set the padding-top to `0`...

- `/event-feed`
- `/client-runs`
- `/settings/notifications`
- `/settings/node-integrations`
- `/settings/node-credentials`
- `/settings/node-lifecycle`
- `/settings/users`
- `/settings/teams`
- `/settings/tokens`
- `/settings/policies`
- `/settings/roles`
- `/settings/projects`

_Note: We are excluding the compliance-related pages, and the profile page from this work as those pages need to be redesigned to not have tabs before we remove the background color._

#### Event Feed
_Note: The shadow appearing on the right-side of the event feed page will be removed in #679._
![event-feed](https://user-images.githubusercontent.com/5489125/62395719-f0ce9a80-b525-11e9-800f-2f83bd5cae74.png)

#### Client Runs
![client-runs](https://user-images.githubusercontent.com/5489125/62395717-f0ce9a80-b525-11e9-9f06-5416372c9e02.png)

#### Users
![users](https://user-images.githubusercontent.com/5489125/62395716-f0360400-b525-11e9-8239-34a62a37f88f.png)

**Comment by vinay033** [comment]
@susanev  I applied the CSS changes on my local and I found that `padding-top: 0px or 0` is not works on some of the pages,  we need to change 0 to 1 like `padding-top: 1px`  
![Screenshot from 2019-08-06 16-26-27](https://user-images.githubusercontent.com/12297653/62534749-6e1c4700-b867-11e9-8891-50f64b4a796f.png)

**Comment by susanev** [comment]
@vinay033 could you push up a branch so i can take a closer look?

**Comment by susanev** [comment]
it looks like maybe an issue with the empty messages?
