### ISSUE TITLE
Add pop-up to `Unrecognized` badge for future Habitat update strategy

### ISSUE THREAD

**Issue by apriofrost** [chef/automate#1157]
Related issue: #902 
This issue is specific for the UI part. 
# Problem
There could be cases where Habitat could introduce a new update strategy and Automate is not capable to understand it, an example is when a customer upgrades Habitat to the latest version with a new update strategy but not upgrades Automate, in such cases we would like to have an UNRECOGNIZED tag/label/enum that will cover any other strategy that Automate doesn't know about.

# Suggested Solution
- Apply the `chef-badge` component with the general/informational style to the tag.
- Add a `pop-up` to the tag with content and link:
Chef Habitat is ahead of Chef Automate, please [update Chef Automate](https://automate.chef.io/docs/install/#upgrades).

![image](https://user-images.githubusercontent.com/9401459/62403623-66952f00-b543-11e9-9b1c-8e8587b0d8b4.png)

**Comment by susanev** [comment]
this has been deprioritized.
