### ISSUE TITLE
API Token Details: active/inactive does not mark form as prestine

### ISSUE THREAD

**Issue by srenatus** [chef/automate#1169]
## Problem
Users are not informed when the form has no changes to be saved, making it more difficult and frustrating to use the form.

##  Describe the bug

When changing the name input to what it was before, the _Save_ button will be disabled. When flipping the status to what it was before, it won't.

## To Reproduce

1. go to token details
![image](https://user-images.githubusercontent.com/870638/62525874-74df9580-b838-11e9-90df-ae904c6d8819.png)

2. click "inactive", the _Save_ button is enabled
![image](https://user-images.githubusercontent.com/870638/62525978-a0628000-b838-11e9-9a8b-8e1a286d8a1a.png)

3. click "active", the _Save_ button stays enabled:
![image](https://user-images.githubusercontent.com/870638/62526006-b07a5f80-b838-11e9-93a4-20ae5f2127ff.png)

## Expected behavior

The _Save_ button would be disabled:
![image](https://user-images.githubusercontent.com/870638/62525874-74df9580-b838-11e9-90df-ae904c6d8819.png)

**Comment by srenatus** [comment]
@scottopherson would the WIP you have apply to `<chef-radio>` in any way? 😎

**Comment by susanev** [comment]
seems to have been fixed.
