### ISSUE TITLE
Manual Deletion of Services in the Applications View

### ISSUE THREAD

**Issue by danielsdeleo** [chef/automate#1192]
_(Note: the following content was edited by @apriofrost, reach out to her if anything is not clear.)_

## Problem
Currently, after users have set up the Applications Dashboard and be able to view the service health status in the dashboard, there isn't an easy way for them to remove the services from the dashboard if they were intentionally decommissioned. 
We have provided users the ability to automatically remove disconnected services after a period set by the user. However, if they want to remove a service immediately, no matter if it has been marked as disconnected or not, they are unable to accomplish it. 

## Solution

Allow users to delete any services in the Applications Dashboard, so they are not alerted about disconnected services that were intentionally decommissioned.

## Acceptance Criteria
- [x] Replace the current `node` icon in the service instance card with a checkbox, update the position to align with the node FQDN on the top (the current is central vertically).
_(Note: the checkbox state only persist for one page, if users navigate to another page, the checkbox states on the prior page is reset to default/unselected.)_
<img src="https://images.zenhubusercontent.com/5a721a104b5806bc2bc51768/92cac177-8608-446e-b9e7-f7532c43345d" width="300">

- [x] Add a bulk action bar above the service instance cards on the right-side panel. The bulk action bar is consists of two types of elements: 1. the `Select All` selector, 2. the available actions, in this case,`Delete Services`. See screenshot below:
![image.png](https://images.zenhubusercontent.com/5a721a104b5806bc2bc51768/b97ff303-a0b9-4beb-8f3d-721a67f58ff6)
The bulk action bar can have three states:
_(Note: the bulk action bar state only persists for one page, if users navigate to another page, the bulk action bar state is reset to default.)_
1. When no service instance is selected, the `Select All` selector is in the `unselected` state. The available actions are disabled.
![image.png](https://images.zenhubusercontent.com/5a721a104b5806bc2bc51768/95b0eb29-c09a-4d3b-8d27-54bca47fab9b)
2. When there is any service instance selected but not all on a page, the `Select All` selector is in the `intermediate` state. The available actions are enabled. In this case, the `Delete Service` button label updates to reflect the number of service instances selected.
![image.png](https://images.zenhubusercontent.com/5a721a104b5806bc2bc51768/e79d6e8b-56e9-46f9-a3d3-99fd1d686ef6)
3. When all service instances on a page are selected, the `Select All` selector is in the `selected` state. The available actions are enabled. In this case, the `Delete Service` button label updates to reflect the number of service instances selected (25 instances per page).
![image.png](https://images.zenhubusercontent.com/5a721a104b5806bc2bc51768/20be3fda-0f36-4d0e-995c-a10274af2543)

- [x] When there is service instance selected, clicking the `Delete <service-instance-count> Services` button shows a `warning` confirmation modal that describes the service(s) to be deleted.
Modal content:
> You are about to delete `<service-instance-count>`.
> This will delete all data about them from the Applications view, but they will show up again if a new health check report from the service is received.

![image.png](https://images.zenhubusercontent.com/5a721a104b5806bc2bc51768/8d3e3b3c-995b-43cc-aae3-d7586c4882c5)
- [x] Clicking on the `Cancel` button will dismiss the modal without affecting the existing selecting state.
- [x] Clicking on the `Delete <service-instance-count> Service` button, show an `in progress` status on the right-side panel with the heading `Deleting <service-instance-count> service...` and a `chef-spinner` animation on the top. Hide all the previous service status filters and the count.
![image.png](https://images.zenhubusercontent.com/5a721a104b5806bc2bc51768/96013e2a-104f-419d-a863-1a03734155a8) 
- [x] If the delete operation is successful, show a `success` banner with text `<service-instance-count> services deleted.` Get the latest service instance count in the filters, and set the bulk action bar to the default state (nothing selected, all actions disabled)
![image.png](https://images.zenhubusercontent.com/5a721a104b5806bc2bc51768/afbf4da6-2073-4445-ba92-52c36de0f2c1)
- [x] If the delete operation is not successful, show a `failure` banner with text `Unable to delete service. Please try again, or contact Chef Support.` Get the latest service instance count in the filters. The bulk action bar and the service instance card checkbox selection status remain the same as before the delete operation unless the disconnected services were automatically removed.
![image.png](https://images.zenhubusercontent.com/5a721a104b5806bc2bc51768/cba5ca23-e9c0-41c0-a121-c16a4403b84c)

## Demo Instruction
1. Navigate to `Applications` tab - `Service Group` page in Automate
2. Select a service group in the service group table
3. On the right-side panel, select one service instance card with the checkbox, see the bulk action bar status update as described in the Acceptance Criteria
4. Select one more service instance card
5. Click on the `Select All` button, see that all the service instance on the current page is selected.
6. Navigate to another page, see the `Select All `button is set to `unselected`, and the `Delete Service` button changed to `disabled`. Toggle the `Select All` checkbox, see that all services on the page are selected. Toggle the button again, see all services are deselected.
7. Select a random number of services on the page, click on the `Delete Service` button.
8. In the confirmation modal, click on the `Cancel` button, see the modal dismissed, and the previous selection state persists.
9. Click on the `Delete Service` button again, this time, confirm the deletion in the modal.
10. See that the right-side panel changes to a `deleting` state. 
11. Simulate two situations where the delete operation is failed and successful, show the two banners as described in the Acceptance Criteria. 

## Mockup
- InVision link: https://chef.invisionapp.com/share/A4W5D6CJHDG#/406682726_manual_Delete_Service-Unselected
- Video demo: https://drive.google.com/open?id=1fzHb2W8dEDmOEOaHWgS5hEXMv2Q5JYyX

**Comment by nfisher-chef** [comment]
API is done, we need to get this prioritized for the UI team

**Comment by apriofrost** [comment]
(more UX details to be added by liz)
InVision mockup:
https://chef.invisionapp.com/share/C3T08NGNKEQ#/379258337_multi-Select-Disconnected-Sidebar-Disconnected
