### ISSUE TITLE
Event Feed Grouping error on Acceptance

### ISSUE THREAD

**Issue by susanev** [chef/automate#1207]
_This issue was originally reported by @lancewf_
_Note: This issue is still in the product/ux phase and is not ready for engineering work, though, as always, comments are welcome._

## Overview
The number of environment events is not correct on acceptance. Below is a gif showing the problem. The select tool displays that there are 126 environment events. The feed shows 100 grouped together. Then when loading the last 26 events it loads another 100 in a group. If you look in both groups you will see duplication of events.

My guess of what the problem is. The load more button should trigger a request that sends a before from the last item in the group. Either the grouped end_date is correct or the UI is not using it. 

## Screenshots
![06c53e62-2cef-4e64-9375-9cef17a558c9](https://user-images.githubusercontent.com/5489125/62814923-8dfe7580-bac8-11e9-91d4-d685a568223a.gif)
![event-feed-woes-2](https://user-images.githubusercontent.com/5489125/62814919-8d65df00-bac8-11e9-9870-e2bb522e79cc.png)
![event-feed-woes-1](https://user-images.githubusercontent.com/5489125/62814920-8d65df00-bac8-11e9-90b2-c36c5b0b9499.png)
![6a71890f-7927-481d-b7ec-00777f2e7e1a](https://user-images.githubusercontent.com/5489125/62814921-8d65df00-bac8-11e9-97c2-46f42afdfeb9.png)
![8d010a80-e44f-4b09-ae5b-1f0a54a101dc](https://user-images.githubusercontent.com/5489125/62814922-8d65df00-bac8-11e9-8943-a262870867d7.png)

**Comment by vjeffrey** [comment]
is this still a problem?

**Comment by susanev** [comment]
this work has been deprioritized.
