### ISSUE TITLE
Add Status Filters to Compliance Reporting Profile Tab View

### ISSUE THREAD

**Issue by jonong1972** [chef/automate#1230]
# User Story

As a Automate User, I want to filter my Profile on the Compliance Reporting tab view so that I may see which Profiles are failing.

# Definition of Done
The Profile Tab within a compliance report will have our standard filter buttons above the profiles table.

For now we will just limit to:
All Profiles | Failed Profiles | Skipped Profiles

# Demo Script / Repro Steps
1. User navigates to Compliance > Profiles Tab
2. User can then click on a status filter above the Profiles data table
3. System filters Profiles within table

**Comment by jonong1972** [comment]
counts for failed/passed/skipped are returned as part of the api response: "counts":{"total":3,"failed":3,"skipped":0,"passed":0} for a2-url/api/v0/compliance/reporting/profiles

**Comment by vjeffrey** [comment]
work is complete
