### ISSUE TITLE
Properly filter packages in service groups

### ISSUE THREAD

**Issue by kmacgugan** [chef/automate#1231]
## User Story

As a user, I will use this work when I want to see a properly filtered list of packages when search on origin or version in a service group that contains more than one of these. 

## Demo Script / Repro Steps
Have a service group with 2 origins (it will show two pacakges)
Search for one of the origins, and see only the origin you searched for.

**Comment by vjeffrey** [comment]
https://github.com/chef/automate/pull/1193
