### ISSUE TITLE
Health check messages not saved

### ISSUE THREAD

**Issue by kmacgugan** [chef/automate#1232]
## User Story

As a user, I will use this work when I want to be able to search on health check messages.
Currently status is saved as health and health checks are not saved at all.

**Comment by kmacgugan** [comment]
We also want to update the docs to include some info about writing good health checks. There is a thread with some code examples that Eric C has provided here: 
https://chefio.slack.com/archives/CGY5RJ7SL/p1574277005248300?thread_ts=1574261855.231400&cid=CGY5RJ7SL

**Comment by vjeffrey** [comment]
@danielsdeleo is this card ready to be closed?

**Comment by vjeffrey** [comment]
api is done.
ux needs to be refined and then ui change needs to be made

**Comment by vjeffrey** [comment]
moving this card to backlog while ux work is being done

**Comment by apriofrost** [comment]
I created a new card #2554 just for the UI task.
