### ISSUE TITLE
remove protoc-gen-mock and all `pb.mock.go` files, update tests a bit

### ISSUE THREAD

**Issue by srenatus** [chef/automate#1241]
When `protoc-gen-mock` was introduced, it was meant to serve one purpose: 

> Be able to mock one method of a service only, without having all your tests break when the service definition gets a new method, or has one removed, that doesn't matter for your tests.

With the latest release of go-grpc, there's a builtin way to serve the same purpose: embed the `UnimplementedXYZServiceServer` struct into the test struct. (See here for an example of the code that gets generated for these: https://github.com/chef/automate/pull/1237/commits/c413b84f97539ca606c715178e2e69b8fa147008#diff-4805c7efa5e3fb413b0011d7af23bce9R1204)

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
