### ISSUE TITLE
Project details page improvements

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#1249]
## User Story

As an Automate User, I will use this work when I want to manage projects from the UI.

A couple minor issues we should fix:

- while the update rule modal is open, if you refresh, usually the create modal shows instead of the update modal (probably due to a race condition loading the current rule)
- if I have selected `equals` for my condition operator, I can still add multiple values in the `values` field. The API just drops all but the first value

## Definition of Done
- If I have opened the modal to update a rule and I refresh, I should see the same update modal
- when I have chosen the equals operator for a condition, I should only be able to add a single value (not a comma separated list)

**Comment by susanev** [comment]
moved this to the product backlog since fixing it will improve the user's experience

**Comment by susanev** [comment]
this work has been deprioritized.
