### ISSUE TITLE
Enforce project assignment permissions on IAM resources

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#1256]
## User Story

As an Automate User, I will use this work when I want to create/update the projects of any IAM resource.

## Related Issues
https://github.com/chef/automate/issues/833

## Technical Notes

We discussed 4 approaches to this problem:
1. Individual ProjectAssign API endpoints for each resource (request flow: `gateway->authz->domain`)

2. We ask the gateway to calculate a diff of the change in projects and send that as part of the request (request flow: `gateway->domain->gateway->authz->domain`)

3. We ask domains to calculate whether project assignment authz is needed, and for what projects (the delta on update/create) (request flow: `gateway->authz->domain->authz->domain`)

4. On create/update requests that may involve project changes, have authz pass along a list of all allowed projects along with the original request (so `gateway -> authz -> domain`). We’d either recognize these calls by looking for the projects field or adding an annotation to the grpc code.

More details on the pros and cons in [this doc](https://docs.google.com/document/d/1vHI7qzP6QQGNnMnM1wQs7Iq_2ZJNQTAjPRGDqeh5uM4/edit) and [this comment](https://github.com/chef/automate/issues/833#issuecomment-513311461).

We decided to proceed with **approach 3**, primarily because it seems best for our architecture that the domain service, not the gateway, be responsible for calculating the project delta. 

## Definition of Done

On create and update requests for IAM resources, the backend verifies that the user is allowed to assign all of the projects in the request. If they include one project that they do not have permission to assign, the request is rejected with a 403 (with the disallowed project included in the error message)

## Demo Script / Repro Steps

1. `curl -kH "api-token: $TOK" -d '{"id": "allowed", "name": "allowed project"}' https://a2-dev.test/apis/iam/v2beta/projects | jq`
`curl -kH "api-token: $TOK" -d '{"id": "not-allowed", "name": "not allowed project"}' https://a2-dev.test/apis/iam/v2beta/projects | jq`

2. save this policy as `pol.json` (corrected 2019.10.02)
```
{
   "name": "testpolicy",
   "id": "test-1",
   "members": [
     "user:*"
   ],
   "statements": [
     {
       "effect": "ALLOW",
       "actions": ["iam:projects:assign"],
       "projects": [
         "allowed"
       ]
     },
    {
       "effect": "DENY",
       "actions": ["iam:projects:assign"],
       "projects": [
         "not-allowed"
       ]
     },
   ],
   "projects": []
 }
```
3. `curl -kH "api-token: $TOK" -d @pol.json https://a2-dev.test/apis/iam/v2beta/policies | jq`

4. `curl -kH "api-token: $TOK" -d '{"id": "new-team", "name": "brand new team", "projects":["not-found"]}' https://a2-dev.test/apis/iam/v2beta/teams | jq`
get 403 error that project "not-found" cannot be assigned, create fails

5. `curl -kH "api-token: $TOK" -d '{"id": "new-team", "name": "brand new team", "projects":["allowed"]}' https://a2-dev.test/apis/iam/v2beta/teams | jq`
succeeds

4. `curl -kH "api-token: $TOK" -X PUT -d '{"name": "brand new team", "projects":["not-allowed"]}' https://a2-dev.test/apis/iam/v2beta/teams/new-team | jq`
get 403 error that project "not-allowed" cannot be assigned, update fails

(rinse and repeat with other resources)

## Subtasks
- [x] Teams @tylercloke #1431
- [x] Tokens @blakestier & @bcmdarroch  #1551
- [x] Policies #1424 @tylercloke 
- [x] Roles #1340 @blakestier @tylercloke

**Comment by msorens** [comment]
Added "Vet Perms" tab to the "Auth Acceptance Testing" spreadsheet enumerating equivalence classes for roles, teams, tokens, and policies -- all check out fine!
