### ISSUE TITLE
Applications: Apply Filters to Service Detail Panel

### ISSUE THREAD

**Issue by danielsdeleo** [chef/automate#1296]
## User Story

When using the filter bar, we want to only show matching services on the right side detail panel. This should help users focus on only the services they are actually interested in; for example, when filtering on `site`, users only wish to see services from the given site.

## Definition of Done

* A service group where all services match the given criteria is shown unchanged compared to the unfiltered view, and all of its services appear in the right-side panel;
* A service group where some of the services match is shown in the left side table, but the content is modified to include only the services matching the filter criteria; that is the Health, Service Group and Release columns reflect only the services that match the filter criteria. The right side services list should show only the services that matched the filter criteria.

**Comment by apriofrost** [comment]
Add @tarablack01 as assignee to track the front end development.
