### ISSUE TITLE
compliance reporting ui: controls list

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#1310]
# User Story

As an Automate user, I want to be able to see a list of the controls being used in my infrastructure scans, the same way I can currently see a list of all the nodes and profiles (https://a2-local-inplace-upgrade-acceptance.cd.chef.co/compliance/reports/overview).

Providing users with a controls list view would allow them to 
- easily see controls that were executed as part of the scans, as an extension of the nodes and profiles list views
- easily view all controls that have the same tag (across multiple profiles) in combination with https://github.com/chef/automate/issues/519
- easily apply a control + profile filter to enable deep filtering

## Considerations
- backend work for the api is currently in progress: https://github.com/chef/automate/issues/521

## Designs
![AUTOMATE-1310-Compliance - Controls](https://user-images.githubusercontent.com/1316587/64985119-04855480-d879-11e9-82ce-99943444aa80.png)

Query Result Set Too Long Message
![Screen Shot 2019-10-08 at 9 58 27 AM](https://user-images.githubusercontent.com/1316587/66416308-591c7b00-e9b2-11e9-9316-1552a53d5a86.png)

# Definition of Done
Controls list view in Automate

**Comment by vjeffrey** [comment]
the pr with the backend work has not yet merged but is up in pr form: http://github.com/chef/automate/pull/1601

the pr introduces a new endpoint:

`https://a2-dev.test/api/v0/compliance/reporting/control-items -d '{}'`

which gives response:
```
{ 
   "control_item":[ 
      { 
         "id":"/etc/group must exist",
         "title":"Checking for /etc/group",
         "profile":{ 
            "name":"",
            "title":"My Demo Linux successful profile",
            "id":"1de944869a847da87d3774feaacb41829935a2f46b558f7fc34b4da21586ae27",
            "version":"1.8.9",
            "status":""
         },
         "impact":0.3,
         "end_time":"2019-09-15T14:55:52Z",
         "control_summary":{ 
            "total":4,
            "passed":{ 
               "total":4
            },
            "skipped":{ 
               "total":0
            },
            "failed":{ 
               "total":0,
               "minor":0,
               "major":0,
               "critical":0
            }
         }
      },
      { 
         "id":"/etc/passwd must exist",
         "title":"Checking for /etc/passwd",
         "profile":{ 
            "name":"",
            "title":"My Demo Linux successful profile",
            "id":"1de944869a847da87d3774feaacb41829935a2f46b558f7fc34b4da21586ae27",
            "version":"1.8.9",
            "status":""
         },
         "impact":0.6,
         "end_time":"2019-09-15T14:55:52Z",
         "control_summary":{ 
            "total":4,
            "passed":{ 
               "total":4
            },
            "skipped":{ 
               "total":0
            },
            "failed":{ 
               "total":0,
               "minor":0,
               "major":0,
               "critical":0
            }
         }
      },
      { 
         "id":"apache-01",
         "title":"Apache should be running",
         "profile":{ 
            "name":"",
            "title":"DevSec Apache Baseline",
            "id":"3e1310b071dc4d706263e9d07083e10a92b4b69e4a36cffa1eda7eaecc09969a",
            "version":"2.0.2",
            "status":""
         },
         "impact":1,
         "end_time":"2019-09-15T14:55:52Z",
         "control_summary":{ 
            "total":2,
            "passed":{ 
               "total":0
            },
            "skipped":{ 
               "total":2
            },
            "failed":{ 
               "total":0,
               "minor":0,
               "major":0,
               "critical":0
            }
         }
      }
   ]
}
```

**Comment by vjeffrey** [comment]
pls message @vj or ask in #superteam if you have any questions while working on this

**Comment by jonong1972** [comment]
Added back the Control status per node.

**Comment by vjeffrey** [comment]
NOTE: this endpoint does *not* support pagination. we will be returning the first 100 (maybe more) results.  the aggregation being used in elasticsearch doesn't support pagination.

```
# controls with control tag status filter
curl --silent --insecure -H "api-token: token" https://a2-dev.test/api/v0/compliance/reporting/controls -d '{"filters":[{"type": "control_status", "values": ["skipped"]}] }'
```

i'll add more examples of playing with filters later.
when the user clicks the "filter by" button, we should apply the profile + control filter. ill add an example of that too.

**Comment by vjeffrey** [comment]
ok, here is a better set of examples:
```
# control list, all controls available:
curl --silent --insecure -H "api-token: $A2_TOKEN" https://a2-dev.test/api/v0/compliance/reporting/controls -d '{}'


# response:
{"control_items":[
    {"id":"/etc/group must exist","title":"Checking for /etc/group","profile":{"name":"","title":"My Demo Linux successful profile","id":"1de944869a847da87d3774feaacb41829935a2f46b558f7fc34b4da21586ae27","version":"1.8.9","status":""},"impact":0.3,"end_time":"2019-09-25T15:09:49Z","control_summary":{"total":1,"passed":{"total":1},"skipped":{"total":0},"failed":{"total":0,"minor":0,"major":0,"critical":0}}},
    {"id":"/etc/passwd must exist","title":"Checking for /etc/passwd","profile":{"name":"","title":"My Demo Linux successful profile","id":"1de944869a847da87d3774feaacb41829935a2f46b558f7fc34b4da21586ae27","version":"1.8.9","status":""},"impact":0.6,"end_time":"2019-09-25T15:09:49Z","control_summary":{"total":1,"passed":{"total":1},"skipped":{"total":0},"failed":{"total":0,"minor":0,"major":0,"critical":0}}}
    ]
}

# control list, filtered by control status:
curl --silent --insecure -H "api-token: $A2_TOKEN" https://a2-dev.test/api/v0/compliance/reporting/controls -d '{"filters":[{"type": "control_status", "values": ["skipped"]}] }'


# control list accepts the same filters all compliance reporting calls do, i.e.:
curl --silent --insecure -H "api-token: $A2_TOKEN" https://a2-dev.test/api/v0/compliance/reporting/controls -d '{"filters":[{"type":"environment","values":["Dot.Comma,Big;\"Trouble"]},{"type":"profile_id","values":["1de944869a847da87d3774feaacb41829935a2f46b558f7fc34b4da21586ae27"]},{"type":"start_time","values":["2019-09-15T00:00:00Z"]},{"type":"end_time","values":["2019-09-25T23:59:59Z"]}]}'

# apply a filter when the "filter by" button is clicked 
curl --silent --insecure -H "api-token: $A2_TOKEN" https://a2-dev.test/api/v0/compliance/reporting/controls -d '{"filters":[{"type":"profile_id","values":["1de944869a847da87d3774feaacb41829935a2f46b558f7fc34b4da21586ae27"]},{"type":"control","values":["/etc/group must exist"]},{"type":"start_time","values":["2019-09-15T00:00:00Z"]},{"type":"end_time","values":["2019-09-25T23:59:59Z"]}]}'

```

**Comment by scottopherson** [comment]
@rickmarry @vjeffrey 

To display the node and profile counts in the reporting view tab links:

![](https://user-images.githubusercontent.com/479121/66076198-82ed2200-e51a-11e9-8528-73c1b99d0cbb.png)

The UI currently uses `/compliance/reporting/stats` to get these total counts from `report_summary.stats`:

![](https://user-images.githubusercontent.com/479121/66076217-8bddf380-e51a-11e9-8035-962dd2bb8e4f.png)

(which for some reason `nodes` is returning as a string instead of a number). Are we able to include `controls` total count in this response as well?

**Comment by scottopherson** [comment]
If "yes", I guess a follow-up question for product/design would be: do we want to include a `controls` count somewhere in the 'report metadata' UI as well?

![Screen Shot 2019-10-02 at 2 03 09 PM](https://user-images.githubusercontent.com/479121/66077686-afef0400-e51d-11e9-8d0c-e988cd1d21b8.png)

**Comment by jonong1972** [comment]
> If "yes", I guess a follow-up question for product/design would be: do we want to include a `controls` count somewhere in the 'report metadata' UI as well?
> 
> ![Screen Shot 2019-10-02 at 2 03 09 PM](https://user-images.githubusercontent.com/479121/66077686-afef0400-e51d-11e9-8d0c-e988cd1d21b8.png)

@scottopherson good catch. yeah, we should add the count to the report metadata

**Comment by rickmarry** [comment]
> which for some reason `nodes` is returning as a string instead of a number

The reason for this is that in our proto def, we have nodes set to type int64 and some browsers cannot handle full 64 bit number
see this for more info https://github.com/protocolbuffers/protobuf/issues/2679#issuecomment-278006898

In my opinion, we can change this type to int32 and if the day comes when we need to support more than 2billion nodes, revisit then

**Comment by vjeffrey** [comment]
i def support changing that string to an int32 - but it would have to be a new field in order to not ships breaking api change

**Comment by vjeffrey** [comment]
we can totally add a new field, populate it with the same info, and make it int32. and then just mark the string one as deprecated (a simple comment in the proto works), and one day when we go to a new api version we can remove the old string field

**Comment by rickmarry** [comment]
will do @vjeffrey thanks

**Comment by rickmarry** [comment]
> we can totally add a new field, populate it with the same info, and make it int32. and then just mark the string one as deprecated (a simple comment in

will do @vjeffrey thanks

**Comment by rickmarry** [comment]
> which for some reason `nodes` is returning as a string instead of a number

@scottopherson - we now have a field node_cnt that of type number
#1806

**Comment by jonong1972** [comment]
Added message to bottom of list table to show we cant handle more than 100 rows.
Design attached to description
