### ISSUE TITLE
compliance reporting ui: search by control tags

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#1311]
# User Story
As an Automate user, I want to be able to filter my nodes by control *tags*
Why?
InSpec provides a mechanism that can be used for 'grouping' controls across profiles (tags)
Users would like to filter their set of nodes being scanned in Automate by selecting a control tag, so they can narrow their query to a group of controls across several profiles.

## Considerations
backend work is in progress: https://github.com/chef/automate/issues/519 
the work for this card will include extending the search bar to include control tag filter option and properly handling that filter for communication with the api

## Designs
**Filter Functionality**
Follow the same pattern as the Events Page Search component when choosing Event Type, but expanding to 3rd tier drop down menu.

**Step 1:** Default state of search box
![Screen Shot 2019-08-21 at 11 06 32 AM](https://user-images.githubusercontent.com/1316587/63456814-9ded5200-c404-11e9-917b-439726f2d86c.png)

**Step2:** User clicks or tabs to search box, category drop down displays.
![Screen Shot 2019-09-11 at 11 09 20 AM](https://user-images.githubusercontent.com/1316587/64723093-ae816d00-d484-11e9-8e9a-1fbd09db94fa.png)

**Step 3:** User chooses Tag category, system then prompts user to choose Tag Key from dropdown
![Screen Shot 2019-09-11 at 11 13 20 AM](https://user-images.githubusercontent.com/1316587/64723364-41baa280-d485-11e9-973d-fd759e01c94e.png)

**Step 4:** System then shows category|tag Name label in search box, and then prompts user to enter in a Tag Key value.
![Screen Shot 2019-09-11 at 11 16 06 AM](https://user-images.githubusercontent.com/1316587/64723622-b7267300-d485-11e9-921e-3f9350e76727.png)

**Step 5:** user can then type in a value with/without wild card, and system can suggest values.
![Screen Shot 2019-09-11 at 11 22 31 AM](https://user-images.githubusercontent.com/1316587/64724026-7844ed00-d486-11e9-957d-956c8fd19be3.png)

**Step 6:** after user enters in desired value, system displays filter criteria tag below.
![Screen Shot 2019-09-11 at 11 21 42 AM](https://user-images.githubusercontent.com/1316587/64723978-64998680-d486-11e9-9e17-bd19d1d024f6.png)

# Definition of Done
Can search (get suggestions and filter on) control tags in Automate

**Comment by alexpop** [comment]
This PR allows the compliance API calls to be filtered by control tags: https://github.com/chef/automate/pull/1374

I'm looking into control_tag suggestions next...

**Comment by vjeffrey** [comment]
https://github.com/chef/automate/pull/1505

**Comment by vjeffrey** [comment]
to get suggestions for the control tag key: 
```
GRPC reporting, :list_suggestions, Reporting::SuggestionRequest.new(
      type: 'control_tag_key',
      text: 'scope',
      filters: [
        Reporting::ListFilter.new(type: 'start_time', values: ['2018-02-01T23:59:59Z']),
        Reporting::ListFilter.new(type: 'end_time', values: ['2018-03-04T23:59:59Z'])
      ],
      size: 10
    )
```

to apply the control tag key filter:
```
Reporting::ListFilter.new(type: 'control_tag:scope', values: [])
*note that the key value is attached to the control_tag type via colon. this is because the control tag values will go in the values part
```

to get suggestions on control tag value:
```
GRPC reporting, :list_suggestions, Reporting::SuggestionRequest.new(
      type: 'control_tag_value',
      filters: [
        Reporting::ListFilter.new(type: 'start_time', values: ['2018-02-01T23:59:59Z']),
        Reporting::ListFilter.new(type: 'end_time', values: ['2018-03-04T23:59:59Z']),
        Reporting::ListFilter.new(type: 'control_tag:satisfies', values: []),
      ],
      size: 5
    )
```

to apply control tag value filter:
```
Reporting::ListFilter.new(type: 'control_tag:scope', values: ['test'])
```

**Comment by vjeffrey** [comment]
PLEASE NOTE: this issue is HIGH PRIORITY -- we need to get this done ASAP to fulfill promises made to customers

**Comment by vjeffrey** [comment]
(backend pr has not yet merged but should in the coming days)

**Comment by susanev** [comment]
@jonong1972 @vjeffrey did y'all want to put this in prioritized? the ux team organized priority and we kept the prioritized column nice and small this week. so theres prolly room to move this over if y'all would like to.

**Comment by susanev** [comment]
also curious, @jonong1972 should the label in step 2 be _Control Tag_ to differentiate it and make clear that it's different from _Chef Tag_?

**Comment by vjeffrey** [comment]
> did y'all want to put this in prioritized?

ya, works for me! the reason i didn't yet is the backend work is not yet merged but i imagine it won't be too much longer/will be merged by the time ppl get around to it

**Comment by vjeffrey** [comment]
> should the label in step 2 be Control Tag to differentiate it and make clear that it's different from Chef Tag?

i'm +1 on that ^

**Comment by jonong1972** [comment]
> also curious, @jonong1972 should the label in step 2 be _Control Tag_ to differentiate it and make clear that it's different from _Chef Tag_?

Yes. I will update the mock up. thanks

**Comment by vjeffrey** [comment]
pls message @vj or ask in #superteam if you have any questions while working on this

**Comment by vjeffrey** [comment]
in case it helps, here's an example playing with the api: 
<img width="1290" alt="Screen Shot 2019-09-19 at 11 10 57" src="https://user-images.githubusercontent.com/10341541/65265432-32afa200-dace-11e9-8b51-5339cfbe15a0.png">
