### ISSUE TITLE
no auto-login for SAML users on IAMv2.1 when session expires

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#1318]
_Problem: Users do not want to have re-login after their SAML session has expired when using iamv2._

## User Story 

As an Automate User, I will use this work when I am logged in via SAML.

In [this PR](https://github.com/chef/automate/pull/1246), we updated session-service to keep track of the user's chosen login connector (SAML, LDAP, local, etc). While on IAM v1 and IAM v2, the following expected behavior occurs:
- I log in via SAML
- after some time, the id token expires
- on expiration, I am automatically re-logged in to Automate. I do not have to interact with login screen at all.

While on IAM v2.1, this doesn't happen. On token expiry, the user is logged out. They must click SAML and enter their credentials to log in again.

## Definition of Done
- the expected session behavior works regardless of IAM version

## Demo Script / Repro Steps
- update `components/automate-dex/habitat/templates/config.yml` with `idTokens: 1m`
- `rebuild components/automate-dex`
- log in as a SAML user
- wait a minute for the token expire
- get logged back in automatically

**Comment by srenatus** [comment]
reopening for zendesk
