### ISSUE TITLE
Convert the action buttons on the compliance list table to the standard "more actions" button with the ellipses

### ISSUE THREAD

**Issue by jonong1972** [chef/automate#1331]
## User Story

As a Automate user I will use this work when I want to perform actions on a table row object in a standard way.

## Definition of Done
The actions within the table rows are rolled up within a drop down of the ellipses button.

Pages that needed to be done are:
`/compliance/reports/nodes`
`/compliance/reports/profiles`
`/compliance/reports/profiles`
`/ac3735092676fe76843e312cbc917ccad958ead6bbf227a109c6e848d8533fc1`

## Demo Script / Repro Steps
TBD

**SCREEN DESIGNS**
TBD - @jonong1972

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
