### ISSUE TITLE
ui: displayed report reflects exception status of controls

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#1337]
## User Story
The InSpec team is working on some new logic for waivers.  As part of this work, they will be creating a waiver format and will introduce a way for users to include a waiver as part of an InSpec run.  The final report will include details about controls that have exceptions, such as waived y/n, reason, duration/expiration.  There will be an option to run or skip the excepted control, so we may or may not have test results for the excepted control.

This issue covers the work needed to display that control in Chef Automate (node details page). 

### Controls List Page
![V2 5-Compliance - Report - Controls](https://user-images.githubusercontent.com/1316587/66332172-f3b08780-e8e8-11e9-9eca-98b315f59468.png)

### Hover Elements over Badges
![Screen Shot 2019-10-07 at 9 57 14 AM](https://user-images.githubusercontent.com/1316587/66332180-f8753b80-e8e8-11e9-8443-d62c27783148.png)

![Screen Shot 2019-10-07 at 9 57 24 AM](https://user-images.githubusercontent.com/1316587/66332189-fca15900-e8e8-11e9-94b5-981d36853b6e.png)

### Profile Details Page
![V2 -Compliance - Report - Profile Details](https://user-images.githubusercontent.com/1316587/66417710-70a93300-e9b5-11e9-9982-1552d2d47cd0.png)

## Definition of Done
Displayed node report reflects exception status of controls.

## Demo Script / Repro Steps
N/A yet. Will fill in when we have more information

**Comment by jonong1972** [comment]
Closing this issue since @alexpop and I are breaking this out into smaller cards with up to date designs.
