### ISSUE TITLE
IAM Action Documentation

### ISSUE THREAD

**Issue by susanev** [chef/automate#1345]
_Problem: Users do not have the information they need to define custom roles and policies._

## Overview
Currently, we do not provide a reference for the many actions that are possible to use when defining a role to be used in a policy. Let's autogenerate a table of those actions that include the action identifier, and a brief optional description based on annotations. The descriptions will be important for anything that has different names then what is displayed in the ui, some examples are _node manager_ vs _node integration_ and _event_ vs _action_.

## Design Details
* New page in the iamv2 beta docs, possibly titled _Actions_, need to work with docs folks on name
* Page should contain a brief introduction, and then a table of actions with 2 columns, 1 for the identifier, and 1 for the optional description
* Find places in the rest of the IAM v2 docs to reference and link to the actions page
* Use [Hugo Data Template](https://gohugo.io/templates/data-templates/)
    * Data goes into a folder in `automate/components/automate-chef-io/data/docs/`
    * Rendered by a layout in `automate/components/automate-chef-io/layouts/`
    * Page structured like [Automate CLI Docs](https://github.com/chef/automate/blob/master/components/automate-chef-io/content/docs/cli-chef-automate.md)
    * Reach out to @kagarmoe for related questions

## Subtasks
- [ ] autogenerate what API endpoints + methods are permissions
- [ ] _what they do_ manual documentation work

## Reference
* [internal spreadsheet of prolly incorrect actions](https://docs.google.com/spreadsheets/d/1ccaYDJdMnHBfFgmNC1n2_S1YOnMJ-OgkYd8ySbb-mS0/edit?usp=sharing)
* [aws iam actions](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_identityandaccessmanagement.html)

**Comment by srenatus** [comment]
💭 I believe we already have a card for this somewhere. The problem is that autogenerating what API endpoints + methods are permissions is simple, but _what they do_ will be manual documentation work.

I wonder how this ties in with the current state of our API docs efforts... 😃 I'd think it would make sense if both "this is the action permission required to use this endpoint" and "this is what the endpoint does" was part of the API docs.

**Comment by srenatus** [comment]
<details><summary>WIP</summary>

### 📜 some notes for backlog grooming

for the first part,

> autogenerate what API endpoints + methods are permissions

#### desirables

1. there is only a single source of truth for this, no separate document to keep in sync

#### possible approaches

Right now, the information lives sprinkled all over the place in our external API proto3 definitions, like 
</details>

**Comment by srenatus** [comment]
💭 It would be really cool if the UI gave you an idea about what's up given your permissions... I.e. if some UI elements weren't hidden when you don't have the permissions to use them, but **disabled** instead, with the mouseover text (or something similar) indicating which permissions your lacking...

**Comment by srenatus** [comment]
@msorens since you've asked in our discussion today, this would allow us to also take the `google.api.http` annotations out of the proto files, too: https://grpc-ecosystem.github.io/grpc-gateway/docs/grpcapiconfiguration.html But there's currently no way to put extra openapi (swagger) information into that, see https://github.com/grpc-ecosystem/grpc-gateway/issues/701#issuecomment-501163040

**Comment by srenatus** [comment]
@phiggins I've considered adding action/resource (or only action) to the swagger docs, but it seems the grpc-gateway code generator doesn't support such arbitrary key/val metadata additions on pairs of HTTP endpoint + HTTP method. (That is, I've asked around in the grpc-gateway channel of the gopher slack today...) -- This is the background for why I'd go with another YAML file instead. We could weave these together in the template, maybe...? 💭

**Comment by phiggins** [comment]
The tools we're using to generate the swagger from proto files seem limited in their flexibility so I'm not sure how much value there is in pursuing that route. There is likely going to need to be post-processing scripting done to get all the stuff we want supported so using separate files to list the auth information seems ok to me.

**Comment by kagarmoe** [comment]
Before we develop something bespoke, I would like the opportunity to work with you on what you've developed. We need to make sure it conforms to API documentation standards as well as the needs of user documentation. Thanks!

**Comment by srenatus** [comment]
OK so there are a few things here:

1. For **authorization**, we _need_ a single place to put mappings between GRPC methods and authz actions.

   Right now, this place is the proto3 `options` shown above. The proposal is to move them into a YAML file to simplify processing them outside of their current use and expanding.
2. There's API docs.

   They're currently generated from the swagger (openapi2) json files (created by `protoc-gen-swagger`), fed into a hugo template, if I understand correctly.
3. There's IAM/Authorization docs.

  They **should** explain _what kind of access an action grants you_. In our system, actions roughyl map 1-to-1 to GRPC methods, and thus HTTP endpoint+verb pairs.

What was outlined so far, would amount to _using the source of truth created in (1) for (3).

From the discussion, it looks like what's generated "for free" in (2) is not what we want for API docs, so there's OpenAPI 3. I'm not sure what to make of that -- If we had OpenAPI 3 specs, and they would allow for an arbitrary field attached to a endpoint+verb pair, we could use them as source-of-truth for our needs in (1) and (3). However, I don't know if this is something the spec allows, and I don't know how close we are in terms of having an OpenAPI 3 spec at all, so I'd lean towards a very simple solution to (1) and (3), that, even if bespoke, will be **nowhere near any kind of complete API docs**.

@kagarmoe @phiggins Am I misrepresenting the state of affairs wrt. API docs? What do you think about this ☝️?

**Comment by srenatus** [comment]
ℹ️Some notes from looking around...

- [OpenAPI3 "Specification extensions"](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#specification-extensions) could be interesting for adding what we need for authz docs directly into our API spec
- [gnostic](https://github.com/googleapis/gnostic/) is an interesting framework. It's like protobuf, with different generator plugins processing stuff they're fed, but with an OpenAPI spec (version 2 or 3) as the central artifact to generate stuff from.
   - [gnostic-grpc](https://github.com/googleapis/gnostic-grpc) finally turns the stuff we currently do _upside down_: it'll generate GRPC proto files from an OpenAPI spec 😄 **Including** grpc-gateway, [see this example](https://github.com/googleapis/gnostic-grpc/tree/master/examples/end-to-end-grpc-gateway)

**Comment by phiggins** [comment]
@srenatus Your assessment is accurate, AFAIK. OpenAPI 3 looks like a nice evolution of the standard but we're limited in supporting it because of the tools we're using.

**Comment by srenatus** [comment]
ℹ️ We've opted for **approach 2**. Having the authz mappings in a YAML file will also not lock us in in any way when we'd later want to weave this information into some OpenAPI 3 spec.

**Comment by kagarmoe** [comment]
I'm not sure that I completely understand the proposed documentation. Is the plan to create a document mapping the GRPC methods and HTTP endpoint+verb pairs? Who is the audience for this documentation? What information question does it answer for our customers that wouldn't be answered by good API documentation?

**Comment by susanev** [comment]
@kagarmoe @srenatus would y'all be down for a zoom call sometime soon to go over our proposal?

**Comment by srenatus** [comment]
@kagarmoe one by one 😃 
>  Is the plan to create a document mapping the GRPC methods and HTTP endpoint+verb pairs?

Besides the one-to-one mapping between GRPC methods and HTTP endpoint+verb pairs, there's a third thing: IAM actions and resources. And **that mapping** is what we're looking to shine a light on.

> Who is the audience for this documentation?

Anyone writing IAM policies who wants to understand what _granting a user access to `foo` a `bar`_ means concretely -- in terms of API methods (GRPC or HTTP).

> What information question does it answer for our customers that wouldn't be answered by good API documentation?

The mentioned mapping of IAM action/resource pairs to HTTP endpoints+verbs. There's a table somewhere, I believe, for IAMv1, which is likely outdated and wrong.

**Ideally**, this would find a place in good API docs, for sure. However, from the stuff above, it seems that OpenAPI v2 doesn't allow for putting arbitrary key-val pairs anywhere.

@susanev happy to zoom if that's what everyone prefers 😃 (Time[zones] permitting.)

**Comment by kagarmoe** [comment]
I'm not sure that these ideas about the limitations of the OpenAPI 2.0 spec are correct. This spec can handle [OAuth2 Security requirements](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#oauth2-security-requirement). OpenAPI is also [extensible](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions.html). 

Security 
[OpenAPI 2.0 Security Definitions Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#securityDefinitionsObject)
[OpenAPI 2.0 Security Scheme Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#securityDefinitionsObject)
[OpenAPI 2.0 Scopes Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#scopes-object)
[OpenAPI 2.0 Scopes Object](https://swagger.io/docs/specification/2-0/authentication/)
[Swagger 2.0 Auth](https://swagger.io/docs/specification/2-0/authentication/) docs
[OpenAPI 3.0 Security Scheme Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#security-scheme-object)
[OpenAPI 3.0 OAuth Flows Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#oauthFlowsObject)
[OpenAPI 3.0 Oauth Flow Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#oauthFlowObject)
[Swagger 3.0 Auth](https://swagger.io/docs/specification/authentication/) docs

Extensions
[Swagger 2.0 extensions](https://swagger.io/docs/specification/2-0/swagger-extensions/) documentation
[Extension registry](https://github.com/OAI/OpenAPI-Specification/issues/1351)
[AWS API Gateway)(https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions.html)
[Google Cloud Extensions](https://cloud.google.com/endpoints/docs/openapi/openapi-extensions)
[Microsoft OpenAPI 2.0 metadata support in Azure Functions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-api-definition). Also, search MS docs for OpenAPi. Azure is on 3.0
[Microsoft OpenAPI.NET SDK](https://github.com/microsoft/OpenAPI.NET)

API Handyman blog by Arnaud Lauret on [Extensions](https://apihandyman.io/writing-openapi-swagger-specification-tutorial-part-9-extending-the-openapi-specification/)
I'd Rather Be Writing blog by Tom Johnson on [Security Object](https://idratherbewriting.com/learnapidoc/pubapis_openapi_step6_security_object.html)

RBAC
[DreamFactory 2.10 adds OpenAPI 3.0 and Admin App RBAC](https://blog.dreamfactory.com/dreamfactory-2-10-release/) Uses 3.0

I think that I'm having trouble visualizing what this doc needs to be. I'd love it if someone could mock up some content for me, so I can understand the information need and solution a bit better. Could you whip something up (not a full doc, just an example) so we can meet on it? Thanks!

**Comment by susanev** [comment]
this is a good example of the general concept needed
https://docs.aws.amazon.com/IAM/latest/UserGuide/list_identityandaccessmanagement.html

**Comment by srenatus** [comment]
@kagarmoe thanks for all those resources! 😃 

> I'm not sure that these ideas about the limitations of the OpenAPI 2.0 spec are correct. 

Ok, I might have been inexact here: I've been looking at openapi 2 through the lense of what grpc-gateway's code generator lets us use _right now_. This doesn't meant that we cannot either improve that one (we've done that before), or find other ways to amend our generated openapi2 docs.

It looks like @phiggins already has started doing that for custom endpoints.

> This spec can handle [OAuth2 Security requirements](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#oauth2-security-requirement).

The example linked to looks like it could be (ab)used for our purposes: 
> If the security scheme is of type "oauth2" or "openIdConnect", then the value is a list of scope names required for the execution. For other security scheme types, the array MUST be empty.

So we could say that _what is a scope in the spec_ is an _action_ in our Automate API docs. We'd ignore that there's resources.

However, it's OpenAPI 3.0. Not sure if v2 knows of the same thing.

This, however, 

> [Swagger 2.0 extensions](https://swagger.io/docs/specification/2-0/swagger-extensions/) documentation

looks like pretty much what we'd need 💡 -- @phiggins do you know a way to add some of these extension fields, too? Either using proto3 method options or using some post-processing step?

------
For this card, however, I'd uphold that _unless we can use `protoc-gen-swagger`-supported fields today (or come up with a plan for extending the tools so that we can)_, we'd be better off moving our IAM action/resource mappings into a YAML file. From there, they can be mixed in in a post-processing step, etc.

**Comment by srenatus** [comment]
**Update** I've looked a little deeper into this, see https://github.com/grpc-ecosystem/grpc-gateway/pull/1033.

**Comment by susanev** [comment]
an additional option for this as we need to complete something to inform folks of the actions possible is to manually document a subset of the possible actions until we can come back and autogenerate it.

**Comment by msorens** [comment]
Discussion with @susanev, @tylercloke, and @msorens:
The approach that for auto-generation that had early promise turns out will not fly (per @tylercloke). Instead, we decided to manually add annotations (possibly with a one-off script) to all relevant proto files (but only the ones that have been doc-annotated already; as others get documented they will need to add the portion for actions too). May also end up writing a unit test to ensure integrity of the copied data, but not very high priority for the test, since these are not likely to change.

**Comment by susanev** [comment]
the rest of this work has been deprioritized, so closing.
