### ISSUE TITLE
automate-ui: concurrent requests can cause undesired logouts

### ISSUE THREAD

**Issue by srenatus** [chef/automate#1354]
## Describe the bug

When a session times out, i.e., the user's ID token expires, an ordinary API request can get a 401 response *while* or *before* the session refresh request (`GET /session/refresh`) has gotten the browser a fresh ID token. This will lead to a signout that is avoidable. For local and LDAP users, that means they'll have to provide their credentials again. SAML users with active IdP-session might just "flicker through" the process, but may still lose UI state (like filled in forms).

👉 This affects any IAM version (and any API request), but it's most prevalent in IAM v2.1 because of the periodic call to `apply-rules`.

## To Reproduce
- TODO

## Expected behavior
A description of what you expected to happen.

Ideally, the same entity response for session refresh would also handle API requests. It could then react to 401s in a better way than a call to `logout()`.

## Additional context

This is not new, it's only become more apparent through the periodic API requests.

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
