### ISSUE TITLE
Nightly tests are failing on compliance APIs

### ISSUE THREAD

**Issue by lancewf** [chef/automate#1362]
## Describe the bug
The nightly tests ran on 08/26 failed with the below error
```
  ×  compliance-nodes: /api/v0/nodes/search (1 failed)
     ✔  POST /api/v0/nodes/search nodes call should succeed
     ×  POST /api/v0/nodes/search nodes call should include the three nodes from the three ingested reports
     expected [] to include (include {:name => "automate-delivered.cd.chef.co"}), (include {:name => "policyfile-fixture-1-delivered.cd.chef.co"}), and (include {:name => "runner-1604-1-delivered.cd.chef.co"})
     Diff:
     @@ -1,4 +1,2 @@
     -[(include {:name => "automate-delivered.cd.chef.co"}),
     - (include {:name => "policyfile-fixture-1-delivered.cd.chef.co"}),
     - (include {:name => "runner-1604-1-delivered.cd.chef.co"})]
     +[]
```
Below is a link to the buildkite test that failed. 
https://buildkite.com/chef/chef-automate-master-nightly/builds/155#2a7acea6-5fb0-40e4-a9b6-b5f0ae04d82c

**Comment by lancewf** [comment]
@phiggins could not get this test to fail again. So we decided to not change anything and to watch if the test starts to fail again.

**Comment by phiggins** [comment]
In case this comes up again, I was able to get the tests to pass by bumping a timeout in the test file:

https://github.com/chef/automate/commit/ab18ddd0a8a1876095beb9958a93b800b12f43df

The failure was not reliable reproducible though so this might be a coincidence.
