### ISSUE TITLE
on object details pages, call getProjectsByIDs to populate projects dropdown

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#1366]
## User Story

As an Automate User, I will use this work when I want to see a resource's (like a Team or Token) projects.

Currently the projects dropdown is populated by GetProjects, which returns all allowed projects. However, eventually we could have as many as 1000 projects, making this call extra burdensome. 

This card aims to modify an existing or add a new API endpoint that accepts a list of project IDs and returns the list of project objects. This call should be used anywhere in the UI that needs to show some resource's projects' names/details (i.e. the projects dropdown on the details page)

The functionality behind this API will be implemented at the storage layer as part of [this project validation card](https://github.com/chef/automate/issues/1256).

## Discussion

Potential solutions:

A. Fetch each project associated with a team individually (GetProject)
Work needed:
change ngrx/store for GetProject to allow multiple calls in progress simultaneously
Considerations:
Adds complexity to team-detail component, and similar for each other resource that we will add the project picker to.

B. Fetch all projects (GetProjects)
Work needed:
almost none (just revert a couple changes from last commit)
Considerations:
Once we go to unlimited projects a large payload returned from this call could impact performance.
However, right now, we are fetching all projects every 2 minutes for the global projects filter so adding just one more, one-off call will have little impact.

C. Fetch all projects just for the team (GetProjectsForTeam)
Work needed:
implement GetProjectsForTeam front-end and back-end, then one-line change to swap GetProjects with GetProjectsForTeam in team details component itself
Note that we already have GetUsersForTeam as a precedent and good pattern to follow.

I would like to go with B or C because it makes the team details component simpler.
C would be more resilient in the long term but takes more work now. B would need little work now, but would likely need to change to C down the road when we go to unlimited projects.- @msorens 

D. Fetch Projects by list of IDs
Instead of adding GetProjectsForObject APIs to each resource, we could add an optional parameter to GetProjects that's a list of IDs. Or else just add a new endpoint GetProjectsByIDs.
For any Team, Token, etc, we'd fetch the object's details, including the project IDs, and pass those IDs along to this new GetProjectsByIDs call.
I suggest this because blake and I discussed implementing this new GetProjectsByIDs call at the storage later in authz-service to support the new validateProjects API, since it would be faster to have the database check for a list of project IDs, rather than make a database call for each project ID. If we add it internally, might as well add it to the gateway and make it available to the UI too - @bcmdarroch 

I like that. Also all the logic that combines what’s in the project filter and the additional projects you have to fetch doesn’t need to be copy pasta’ed as @msorens summary suggests. It’s completely generic between objects. We just need to make a function that takes in the project list you want and returns a promise. Then each details page can call that after it loads the base object. - @tylercloke

**Comment by blakestier** [comment]
Where do we get the list of `ID`s? Do we first fetch those for the object and then use those for the call to get the full project object? But we don't even need that, do we? We just need the ids?

In other places, we make a `GetXbyY` kind of call for relational objects-- like `GetUsersForTeam`. We don't need that here?

**Comment by bcmdarroch** [comment]
The list of project IDs is attached to the object we're looking at. So this would be similar to GetUsersForTeam, but for projects.

**Comment by bcmdarroch** [comment]
The storage function that I was thinking we could expose is [this one](https://github.com/chef/automate/pull/1424/files#diff-d28b0cc9c342bf1da873bddba25960f6R1554). We could either modify that function to return the projects it finds, or just add a new one

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
