### ISSUE TITLE
Correct project update status for other users

### ISSUE THREAD

**Issue by msorens** [chef/automate#1368]
## User Story

As an Automate User in a multi-user environment, I want the Project Update Status column on the projects list page to reflect accurate information.

With this pull request (https://github.com/chef/automate/pull/1309) the project update status column on the projects list page started reflecting live data. It accurately provides information to the user who instigated the project update, but it will not for other users who view the projects list page from the time the update has started until it has completed.

Let's call the user that pressed "Update Projects" user Artemis. Elsewhere, user Apollo is also looking at the projects list page. Adaptive polling will automatically kick-in for both users, so checking the apply-rules status will occur more frequently when an update in progress. That's all good.

Say we have project P1 edited by Artemis so Artemis saw "Needs update" for the project update status. Artemis then kicks off the update. The database change from staged to applied happens right away, so P1 goes from "edits pending" to "applied" right away in the Ingest Rules column. That change will also be seen by Apollo, so that is all good, too.

Because Artemis pressed "Update Projects", her Automate remembered that this project was dirty, so even though it has now changed to "applied" Automate uses the cached "edits pending" to know that "Project Update Status" should display "updating..." until, sometime later it eventually sets it to "OK". 

The problem is in the "Project Update Status" column for Apollo. His Automate instance does not know P1 was dirty and is now being updated, so it will be immediately reported as "OK" rather than the correct "updating...". 

Second problem:
For all users, if an update is cancelled or an update fails, then for each project with rules, "Project Update Status" is supposed to revert back to "needs updating". But that is true only for the projects that previously had edits pending. There is no way to distinguish projects that had edits pending and those that did not once the former change to "applied" early in the update process; both types now say "applied".

## Definition of Done

1. The "Project Update Status" column shows "updating..." while an update is in progress for all users, not just the one who initiated the update.
2. The "Project Update Status" column shows "needs updating" for all users if the update failed or was cancelled.

## Demo Script / Repro Steps

Load lots of data (e.g. `chef_load_nodes 10000` in hab studio). That helps the update progress slow down enough to be able to watch it (one hopes!). 
Edit a project for user A. 
-> Observe user A shows "edits pending" and "needs updating".

If necessary refresh the project list for user B, who should see the same two values.

Start an update by user A.

-> Observe user A shows "applied" and "updating..."

Refresh the project list for user B who should also see "applied" and "updating..." rather than "applied" and "OK".

**Comment by bcmdarroch** [comment]
How will the `update status` field be set? Is it set to `updating...` while the ingest update happens? or only while the projects table gets updated?

**Comment by msorens** [comment]
I revised the issue description, adding a second aspect of the same issue.

Possible solution:
Right now, the db function `query_project` returns the tuple `[id, name, type, status]`, where `status` is a computed field (based on whether the project is in the staged table or the applied table). We still need that field to be able to correctly populate the "Ingest Rules" column on the projects page.
But we need an additional field--perhaps call it `update_status`--to drive what populates the "Project Update Status" column. It will be set to `edits pending` when an entry is created in the staging table.
When the project update starts, that staging entry is moved to the applied table, but the value of the `status` field will remain `edits pending`. That solves the first problem (users other than the one who pressed "update" will be able to see the project as "updating...").

Now, what happens when the project update completes?
Happy path (successful completion): `update_status` is set to `applied`.
Sad path (update fail or cancel): `update_status` remains at `edits pending`. This solves the second problem (distinguishing unapplied projects from applied projects).

**Comment by bcmdarroch** [comment]
how would `status` be different from `update status`?

**Comment by bcmdarroch** [comment]
Makes sense. Let's try to come up with more distinct names for the two fields when we get into this

**Comment by msorens** [comment]
Here is the question from last week's discussion:

Say we have this initial set of project states:
p1 - needs updating
p2 - needs updating
p3 - ok
p4 - ok

If we start an update then cancel it, we do not know the state of ALL of these. Consider the two cases:

p3 and p4: Clearly it is legitimate to return p3 and p4 to reporting `ok`--cancelling the update did not affect them--this is what this issue would fix.

p1 and p2: We cannot know the state of either of these; thus, both of them should be returned to a state of `needs updating`.

And to return to the bigger question, because we cannot know the state of p1 or p2, does it really make sense to report status on each project individually, or should there be a single project status (e.g. at the top of the page)?

**Comment by nfisher-chef** [comment]
Per our discussion during backlog grooming we decided that this is a GA feature versus Beta 2.1

**Comment by susanev** [comment]
closing for now, may be addressed with design changes. will reopen if needed.
