### ISSUE TITLE
add link to create new node from automate nodemanager details page

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#138]
# User Story

original issue: https://github.com/chef/automate/issues/72

In order to make it easier for our users to navigate to adding nodes to the Automate nodemanager, give them a way to get there by adding a link to the "add nodes" page from the Automate nodemanager details screen.

![Screen Shot 2019-05-10 at 11 16 37 AM](https://user-images.githubusercontent.com/1316587/57548167-255efb80-7315-11e9-968a-7a41da009101.png)

url for automate details page: `a2-url/settings/node-integrations/e69dc612-7e67-43f2-9b19-256afd385820`

url for add nodes page: `a2-url/compliance/scanner/nodes/add`

# Definition of Done
Automate nodemanager details page has a link (as shown above) to the add nodes page.

**Comment by susanev** [comment]
@tarablack01 @jonong1972 We are trying to standardize title case for our button labels, so if we could use _Add Nodes_ and _Remove Nodes_ (even though I missed that before it merged).. id super appreciate it.

**Comment by jonong1972** [comment]
@susanev good catch, I will update my mocks. thanks!

**Comment by phiggins** [comment]
> We are trying to standardize title case for our button labels, so if we could use Add Nodes and Remove Nodes (even though I missed that before it merged).. id super appreciate it.

Since most of these use chef-button, we could enforce that in the code with something like https://angular.io/api/common/TitleCasePipe

This might be an extremely over-engineered solution though :)

**Comment by susanev** [comment]
that would be awesome, from my perspective at least.
