### ISSUE TITLE
Error pop-up width should align with input field

### ISSUE THREAD

**Issue by msorens** [chef/automate#1384]
## User Story

As an Automate User, when entering an invalid value in a field, the error popup width should match the width of the input field.

![image.png](https://images.zenhubusercontent.com/5d07f7b39943fc312156c891/957c1b47-3d30-4f5f-bf54-bf7b03bbe995)

## Definition of Done

Width of error popup aligns with field above it.

## Demo Script / Repro Steps

Go to Settings >> Users >> (user) >> Edit

Empty the input field and the error popup will appear.

**Comment by susanev** [comment]
@msorens would you mind adding this issue to #1016 instead of making it a new issue?

**Comment by msorens** [comment]
Incorpoarated as part of #1016.
