### ISSUE TITLE
Keyboard navigation enhancements with project dropdown

### ISSUE THREAD

**Issue by msorens** [chef/automate#1386]
## User Story

As an Automate User who is not able to use a mouse or other pointing device, I want to be able to more effectively use the keyboard.
Teams is the first resource where we have added a dropdown to the create modal.

![image.png](https://images.zenhubusercontent.com/5d07f7b39943fc312156c891/f86950de-590d-45d9-ad0e-dab26c399b81)

Once you have tabbed to the dropdown, you can open it by pressing return or space. Pressing return or space again will close it. You can move around the items in the dropdown with tab or up/down arrows. Once you have moved off the dropdown "home" the only way to close the dropdown (with the keyboard) is to make your way back to that "home" position and then press return or space. 

Would be useful if Escape could close the dropdown. Right now, Escape will close the whole modal. Should be able to add another Escape handler in the dropdown library component so that it will process the escape first rather than the whole modal.

## Definition of Done

Can close an open dropdown in a modal with Escape and still keep the modal itself open.

## Demo Script / Repro Steps

Detailed above.

**Comment by susanev** [comment]
there's already a card for the accessibility of this component, the original issue was not fully implemented. i think it may still be over on jira though. ill assign myself to get all the info transferred over.

**Comment by susanev** [comment]
this work has been deprioritized.
