### ISSUE TITLE
Escape should close full page form

### ISSUE THREAD

**Issue by msorens** [chef/automate#1387]
## User Story

As an Automate User I want to be able to close the full page create form for project rules just like I can for the smaller, modal forms. Note that the other use of full-page form, Policy >>Add Members, does accept Escape to close it, so this would add consistency with that, too.

Note: The same issue occurs on Add Users To Teams page.

![image.png](https://images.zenhubusercontent.com/5d07f7b39943fc312156c891/2f719e29-0f17-46e4-8332-7877e0387f1c)

## Definition of Done

Escape can be used to close the create/edit form for project rules.

## Demo Script / Repro Steps

Go to Settings >> Projects
Select Create Project (or Edit Project).
Pressing escape is currently ignored.

**Comment by susanev** [comment]
this is behaving as intended.

**Comment by msorens** [comment]
@susanev Could you clarify: does that mean escape is now closing the form, or that escape does not close the form and is not supposed to? If the latter, does that mean that Policy>>Add Members is not behaving as intended (per note in the original description)?
