### ISSUE TITLE
authentication: make ID token expiry configurable when SAML is used

### ISSUE THREAD

**Issue by srenatus** [chef/automate#1391]
## User Story

Now that we pre-select the sign in method based on the previous session, the be-signed-out-and-have-to-sign-in-again dance for users authenticating with SAML isn't as cumbersome anymore. We could thus open it up for configuration; currently, it is hardcoded to 24hrs.

## Definition of Done

- The value is already configurable, but what is configured is ignored when any of the configured connector is SAML. It should _not_ be ignored.
- Any docs are adjusted.
- There's other hardcoded timespans, that might be worth revisiting, in `session-service`.

## Demo Script / Repro Steps

TBD

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
