### ISSUE TITLE
config-mgmt-service suggestions are lowercased

### ISSUE THREAD

**Issue by lancewf** [chef/automate#1396]
## Describe the bug
All suggestions from the config-mgmt-service are being returned as lowercase even if they include uppercase. For example, if a user has an organization name of "Ultimates" the suggestion returned will be "ultimates". This is confusing for the user.  

## To Reproduce
1. `chef_load_nodes 100`
1. Go to https://a2-dev.test/infrastructure/client-runs
1. Search on "chef organization" and all the suggestions incorrectly show lowercase only.

## Expected behavior
Suggestions with uppercase letters should not be changed to lowercase letters. 

## Screenshots
![Screen Shot 2019-08-29 at 10 55 09 AM](https://user-images.githubusercontent.com/1679247/63964231-8ab53480-ca4b-11e9-947f-4b54c3d00f69.png)

**Comment by nfisher-chef** [comment]
Is this high priority?

**Comment by vjeffrey** [comment]
@nfisher-chef sounds like there are some diff opinions on whether or not this is ok behaviour or not. i'm going to remove this card from the board for now while wee figure it out.

**Comment by vjeffrey** [comment]
i just noticed this issue is part of the Beta 2.1 release, which makes me think the reason this is an issue is b/c ingest rules for iamv2 are case sensitive so we want suggestions to show the original value -- is that correct @susanev ?

**Comment by susanev** [comment]
oh whoa, i was tagged in this 7 days ago, sorry for missing it.

this came out of a user reported issue with some folks who had early access to 2.1. they were making an ingest rule that matched the way they named the thing but then were not seeing that thing in the suggestions list. it be cool to get this in before the 2.1 release, but let me know if thats not possible.

cc/ @vjeffrey @nfisher-chef

**Comment by vjeffrey** [comment]
### compliance reporting, list shows case of item as defined by user:
<img width="570" alt="Screen Shot 2019-10-14 at 05 21 37" src="https://user-images.githubusercontent.com/10341541/66748215-d8db9700-ee43-11e9-99cf-6fc7f7680261.png">

### client runs, list does NOT show case of item as defined by user (shows lowercase):
<img width="552" alt="Screen Shot 2019-10-14 at 05 21 51" src="https://user-images.githubusercontent.com/10341541/66748216-d9742d80-ee43-11e9-8739-c5fa7afc3384.png">

###  compliance, case insensitive search
<img width="609" alt="Screen Shot 2019-10-14 at 05 27 38" src="https://user-images.githubusercontent.com/10341541/66748219-d9742d80-ee43-11e9-9969-d1ebe6d90f20.png">

### client runs, case insensitive search
<img width="543" alt="Screen Shot 2019-10-14 at 05 27 12" src="https://user-images.githubusercontent.com/10341541/66748218-d9742d80-ee43-11e9-88ec-0d6bb786bbec.png">

**Comment by vjeffrey** [comment]
^ a bunch of us were confused about case sensitive/display case current state in the app. so including that here as a reference

**Comment by vjeffrey** [comment]
yay! thank you!   ![Screen Shot 2019-10-21 at 20.45.45.png](https://images.zenhubusercontent.com/5cfebc28d99ac71fbfbdcb73/1a712586-ffb1-4210-8e23-667de310c853)
