### ISSUE TITLE
Add data to client run node detail pages + ui consistency

### ISSUE THREAD

**Issue by susanev** [chef/automate#1406]
## Overview
Add _Chef Organization_, _Chef Server_, _Chef Roles_, _Chef Tags_, and _Projects_ to client run node detail pages and some ui consistency work.

### General
- Remove _Node_ from the heading text
- Remove the subheading

### Visualization Changes
- Change the radial chart to be 175px instead of 200
- Change the label and percentage to use `chef-primary-dark`

#### Data Changes
- Add _Chef Organization_, _Chef Server_, _Chef Roles_, _Chef Tags_, and _Projects_
- Change _Deprecations_ to _Cookbook Deprecations_
- Change _Uptiime_ to _Node Up Time_
- If a node has zero _Cookbook Deprecations_ display _None_ instead of zero
- For _Chef Tags_, _Chef Roles_, and _Projects_ if a node has more than 1, then display the count instead of the names of those things (e.g., 2 Chef tags, or 3 projects, or 17 Chef roles)
- if a client run node does not have an FQDN, IP address, chef org, chef server, chef roles, chef tags, policy group, policy name, policy revision then those pieces of data along with their labels should be hidden
- _Projects_ should only be displayed if the iam version is 2.1

#### Data Structure
- sections, _Run Information_, _Node Information_, and _Metadata_
- use `text-transform` for the uppercase headings

##### Run Information
- _Run Duration_
- _Run ID_
- radial chart

##### Node Information
- _Chef Client Version_
- _FQDN_
- _IP Address_
- _Node ID_
- _Node Up Time_
- _Platform_

##### Metadata
- _Chef Organization_
- _Chef Roles_
- _Chef Server_
- _Chef Tags_
- _Cookbook Deprecations_
- _Enviornment_
- _Policy Group_
- _Policy Name_
- _Policy Revision_
- _Projects_

#### Status Content
- left align the content
- change content to read _Run failed <datetime>: <error>_ or _Run succeeded <datatime>. ... removing the rest of the filler words.

#### Accordion Behaviour
- status message should be transformed into an accordion, interacting anywhere on the status message should toggle the accordions state
- default when visiting a node detail page should be that the accordion is open
- when the accordion is open display _View less -_ on the right, when closed display _View more +_
- should be responsive, if there is room for 3 columns display then, otherwise display 2 columns, otherwise, display 1 column
- if the screen size dictates a single column, the accordion should be open and the closing behvaiour should be hidden

### Changes to error log button
- change label to _Error Log_
- base styles `color: #fff; border: #fff 1px solid; background-color: transparent;`
- hover styles `background-color: rgba(255, 255, 255, 0.25);` .. or similar

![error-log-hover](https://user-images.githubusercontent.com/5489125/68091052-fb077a00-fe2f-11e9-9609-d96a81144aae.png)

### Styles
- column headings `font-size: 15px; text-transform: uppercase;`
- data labels `font-weight: 600;`
- work with @susanev on space between data/labels and columns
    - when columns wrap down, they should get at least 10px of top margin added
- add border around the entire accordion that uses the status color

#### 3-col
![client-runs-node-detail-3-cols](https://user-images.githubusercontent.com/5489125/68091636-e24e9280-fe36-11e9-9420-cfaa40342402.png)

#### 2-col
![client-runs-node-detail-2-cols](https://user-images.githubusercontent.com/5489125/68091638-e67ab000-fe36-11e9-80cb-f4fd49974e9d.png)

#### 1-col
![client-runs-node-detail-1-col](https://user-images.githubusercontent.com/5489125/68091645-eaa6cd80-fe36-11e9-90fa-f7fa3b3aaf7d.png)

**Comment by lancewf** [comment]
The Chef Role and Chef Tags fields are a list of strings, so we would have to deal it overflowing the page.

**Comment by susanev** [comment]
@lancewf sorry i havent had a chance to annotate anything yet, anything that has more than 1 would display the count of things instead of the list. e.g., if there are 2 projects associated it will say _2 projects_ instead the project names. hoping to use the same pattern for chef roles and tags.

**Comment by vjeffrey** [comment]
I took a quick look at the api, looks like we're currently returning all fields _except projects_ on the api right now (pls correct me if i missed something). so we'll need to do a small amount of work to expose that on the api response.
