### ISSUE TITLE
Display service status in the ui

### ISSUE THREAD

**Issue by susanev** [chef/automate#1407]
_Note: This is still in the product/ux phase and is not ready for engineering work, though as always, comments are welcome._

## Overview
Display service status in the ui

## Design Details
_Coming soon..._

**Comment by srenatus** [comment]
As extra gimmicks, I'd like
- maybe some API response header, too, conveying that half the system is on fire if that's the case?
- a feature where there's a nag banner that can't be removed if someone skips preflight checks during installation (not entirely serious)

**Comment by moutons** [comment]
woo the status endpoint is available! thanks @yzl!

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
