### ISSUE TITLE
Send Report returned: 429 "Too Many Requests" from Automate Server

### ISSUE THREAD

**Issue by devcrops-official** [chef/automate#1417]
## Describe the bug
When i tried to follow this configuration : https://github.com/chef-cookbooks/audit#direct-reporting-to-chef-automate to send audit report directly to Chef Automate Server i had this error:

```
[2019-09-02T18:31:40+02:00] WARN: Compliance report size is 10.09 MB.
[2019-09-02T18:31:41+02:00] ERROR: send_report: POST to https://chefauto01.xxx.com/data-collector/v0/ returned: 429 "Too Many Requests"
```

## To Reproduce
- use **Chef Infra Client: 15.2.32** 
with this client.rb configuration:
```
data_collector.server_url "https://chefauto01.xxx.com/data-collector/v0/"
data_collector.token ".."
```

- use **Audit cookbook version 8.1.1**
with this attributes:
```
"audit": {
      "reporter": "chef-automate",
      "fetcher": "chef-server",
      "profiles": {
        "cis-rhel7-level1-server": {
          "compliance": "admin/cis-rhel7-level1-server"
        }
      }
    }
```

## Versions 
- OS: rhel7
- Automate Build Number: 20190820163129

**Comment by stevendanna** [comment]
We'd have to see the logs to be sure, the 429 error is likely the result of the large compliance report size.  Internal to Automate there is a 4MB limit on the size of various messages and it is likely that your 10MB report is hitting that limit somewhere in the system.  Hitting that limit produces a ResourceExhausted gRPC error, which is translated into HTTP 429 for HTTP requests.

**Comment by devcrops-official** [comment]
I tried to reduce the size of the report disabling any ohai plugins, but without success. Are there any solutions for report bigger than 4MB ?

**Comment by devcrops-official** [comment]
Update:

I understand why my report is so big. I'm using this report profile :
**CIS Red Hat Enterprise Linux 7 Benchmark Level 1 - Server** 
and when he process this control :

```ruby
control "xccdf_org.cisecurity.benchmarks_rule_1.8_Ensure_updates_patches_and_additional_security_software_are_installed" do
  title "Ensure updates, patches, and additional security software are installed"
  desc  "
    Periodically patches are released for included software either due to security flaws or to include additional functionality.
    
    Rationale: Newer patches may contain security enhancements that would not be available through the latest full update. As a result, it is recommended that the latest software patches be used to take advantage of the latest functionality. As with any software installation, organizations need to determine if a given update meets their requirements and verify the compatibility and supportability of any additional software against the update revision that is selected.
  "
  impact 1.0
  describe command('yum check-update --security') do
    its('stdout') { should include "No packages needed for security" }       
  end
end

```

the output produced is around 9MB.

**Comment by stevendanna** [comment]
> Are there any solutions for report bigger than 4MB?

Unfortunately none that I am aware of at this time.  The relevant limits are not configurable.

> I understand why my report is so big.

That's good news!  @chef/compliance-team or @james-stocks might have more thoughts on a good path forward.

**Comment by james-stocks** [comment]
There's a suggestion for InSpec to not output diffs for failing tests: https://github.com/inspec/inspec/issues/1535

**Comment by devcrops-official** [comment]
Hi @stevendanna,

> Unfortunately none that I am aware of at this time. The relevant limits are not configurable.

it may be useful to specify the 4 MB limit per report in the Automate documentation or in the troubleshooting section. What do you think about it ?

Thanks for the support.

**Comment by stevendanna** [comment]
> it may be useful to specify the 4 MB limit per report in the Automate documentation or in the troubleshooting section. What do you think about it ?

100% agree.

**Comment by btm** [comment]
@stevendanna can we chunk or is 4mb a hard limit?

**Comment by stevendanna** [comment]
@btm 4MB is the limit of a single gRPC request. The limit is configurable inside the gRPC library so we could just increase it.  We could teach various parts of the system to split up large messages and/or use streaming requests but I'm unsure on what is advisable there.

**Comment by vjeffrey** [comment]
https://github.com/chef-cookbooks/audit/pull/393

**Comment by susanev** [comment]
converted to [aha idea](https://chef-software.ideas.aha.io/ideas/A2-I-112).
