### ISSUE TITLE
workflow-ctl root check happens too late

### ISSUE THREAD

**Issue by stevendanna** [chef/automate#142]
The root check in the workflow-ctl code happens too late. Attempts to run the command as a non-root user results in:

```
/bin/workflow-ctl: line 2: /hab/svc/automate-workflow-server/config/automate-ctl-config.sh: Permission denied
/bin/workflow-ctl: line 8: bundle: command not found
```

The workaround is to run the command as root which is what is required anyway, but we should be displaying a nicer message to the user.  The issue here is that the configuration file is owned by hab and can get created with rather restrictive permissions.

**Comment by susanev** [comment]
deprioritized, so closing.
