### ISSUE TITLE
signin-related error pages are all over the place

### ISSUE THREAD

**Issue by srenatus** [chef/automate#1422]
## Describe the bug

Our Sign-In system is complex, and has a few players: session-service, automate-dex, automate-ui. Depending on what fails, you'll see a differently-styled (or _not styled at all_) error page:

### dex:

![image](https://user-images.githubusercontent.com/870638/64184824-5b982c00-ce6c-11e9-977b-4557b9b26f82.png)

☝️ it would look similar when for example the LDAP server was unreachle

### session-service:
![image](https://user-images.githubusercontent.com/870638/64184637-0d832880-ce6c-11e9-9b79-c21687dfd518.png)

### automate-ui:

> Something went wrong. 😢

👉 [signin.component.html](https://github.com/chef/automate/blob/e794922e6310008dca8e0e74f3f683a80d48c1f3/components/automate-ui/src/app/pages/signin/signin.component.html#L1)

## To Reproduce
- depends on the different subsystems, TODO

## Expected behavior

It would be nice if we had a consistent UI/UX around these.

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
