### ISSUE TITLE
IdP-initiated sign in

### ISSUE THREAD

**Issue by susanev** [chef/automate#1445]
_Note: This issue is old and needs to be cleaned up._

## Overview
Click Okta tile and login to Automate (vs going to A2 and logging in with SAML)

**Comment by srenatus** [comment]
This is called "IdP-initiated sign in", and there's a Dex contributor working on it here: 👉 https://github.com/dexidp/dex/pull/1514

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
