### ISSUE TITLE
Expose beta functionality as GA (docs, GUI, CLI, API, etc.) while leaving beta endpoints in place to allow customer migration.

### ISSUE THREAD

**Issue by susanev** [chef/automate#1450]
## Overview

At the beginning of the 30-day IAMv1 grace period, we’ll create the GA endpoints that will reference the same handler as the beta endpoint, and then drop the beta endpoint (HandleFunc) after the grace period is over. This will allow beta and GA endpoints to share the handler AND and underlying database, and seamless migration for beta customers to GA at the time GA is released.

**Comment by bcmdarroch** [comment]
details saved: https://github.com/chef/automate/issues/1843
