### ISSUE TITLE
Refactor chef-button with nested links to work with Angular

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#147]
original issue: https://chefio.atlassian.net/secure/RapidBoard.jspa?rapidView=261&modal=detail&selectedIssue=UI-85

# User Story

Currently the way that `chef-button` works when a `url` is applied to it causes a page refresh when the buttons are used in automate. I am guessing that this is because the nested link uses `href` where Angular expects `routerLink`. We should figure out a way to have links that look like buttons so it doesn't cause a page refresh.

**Comment by susanev** [comment]
links that look like buttons is an anti-pattern in design. links should look like links, and buttons like buttons. but i may be missing the context of this request.

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
