### ISSUE TITLE
Cleanup license lockout modal and add sign out functionality 

### ISSUE THREAD

**Issue by susanev** [chef/automate#1484]
## Overview
If a user signs in as a non-admin user before a license is applied, they will get a license popup that they can't get past as only the admin can apply a license. They also can't get to the log out button to re-login as admin.

The current workaround is opening an incognito window or using the CLI to set a license key.

## Repro steps
h/t @bcmdarroch 

1. Set up environment
1. Log in as admin user
1. Create a non-admin user
1. Log out as admin user
1. Remove license in studio using `remove_dev_license`
1. Log in as non-admin user
1. Can’t get past license modal and can’t log out

### Current Screenshot
![current-lockout-trail-modal](https://user-images.githubusercontent.com/5489125/67165776-f033ec00-f33d-11e9-8019-8dbd1eebcac6.png)

## Design Details
- Remove #3864F2 from heading
- Adjust subtitle content to use the word _Register_ and add contact link
- Remove note about required fields
- Remove all placeholder text
- Change primary button label to _Register_
- Add two tertiary buttons to the bottom of the form: _Apply Non-Trial License_ and _Sign Out_ (and remove the other footer content)

### Future Screenshot
![future-lockout-trail-modal](https://user-images.githubusercontent.com/5489125/67165721-7bf94880-f33d-11e9-8e4a-95f4f8bbf043.png)

**Comment by sachin-msys** [comment]
@susanev : can you please provide the `Apply Non-Trial License` URL.

**Comment by susanev** [comment]
@sachin-msys oh that should open the apply license modal its licenseApplyReason 3
