### ISSUE TITLE
Rules are incomplete when fetched on the command line

### ISSUE THREAD

**Issue by msorens** [chef/automate#1488]
Required behavior:
Rules are applied

Actual behavior:
Rules are partially applied

Notes:

After creating rules and updating projects, here is what I see on the command-line--note the incomplete second condition:
```
# chef-automate dev grpcurl authz-service --  chef.automate.domain.authz.v2.Projects/ListRulesForAllProjects
{
  "projectRules": {
    "cypress-project-2": {
      "rules": [
        {
          "id": "r1",
          "projectId": "cypress-project-2",
          "name": "r1",
          "type": "EVENT",
          "conditions": [
            {
              "attribute": "CHEF_ORGANIZATION",
              "values": [
                "1"
              ],
              "operator": "EQUALS"
            },
            {
              "values": [
                "e"
              ]
            }
          ],
          "status": "applied"
        }
      ]
    }
  }
}
```

And here is what I see on the screen--notice there are two correct conditions in the rule: 
![image.png](https://images.zenhubusercontent.com/5d07f7b39943fc312156c891/3c2d8089-3014-4144-a492-72a1199991cf) 

## Definition of Done
Command-line output matches on-screen output.

## Demo Script / Repro Steps
Create a project with a rule having multiple conditions.
Update projects.
Compare on-screen with command-line output.

**Comment by bcmdarroch** [comment]
Does this only happen when creating rules from the UI?

**Comment by msorens** [comment]
The key here is that the command-line uses `grpcurl` rather than `curl`, meaning that the endpoint is exposed over gRPC but not HTTP. What we are seeing is simply the result of gRPC calls suppressing _zero values_. That is,
the `Operator` field allows values of type `ProjectRuleConditionOperators`, which is effectively an `enum`, and the symbol `ProjectRuleConditionOperators_MEMBER_OF` has value zero.
Similarly, the `Attribute` field allows values of type `ProjectRuleConditionAttributes` and the symbol `ProjectRuleConditionAttributes_CHEF_SERVER` has value zero.

So: we have gRPC configured globally to suppress fields with zero values; that is the reason for the seemingly arbitrary truncated output!

The remaining question is: does this cause an issue to other  services (ingest, compliance), which are the only consumers of `ListRulesForAllProjects` ?
Checked with @lancewf, and he confirmed that absence of the field is not a problem; it assumes they are the correct zero values.

Thus, no issue here.
