### ISSUE TITLE
Suppress line about migrating when attempting to change to the version already applied

### ISSUE THREAD

**Issue by msorens** [chef/automate#1489]
## User Story

Related to:
Issue: https://github.com/chef/automate/issues/1061
PR: https://github.com/chef/automate/pull/1322

Required behavior:
When already on v2.1 should see this:
```
# chef-automate iam upgrade-to-v2 --beta2.1
Enabling IAM v2.1...
Error: You are already using IAM v2.1.
```

Actual behavior:
```
There is an extra note about migrations included:
# chef-automate iam upgrade-to-v2 --beta2.1
Enabling IAM v2.1...
Migrating v1 policies...
Error: You are already using IAM v2.1.
```

Notes:
Same discrepancy when on 2.0 and attempting to change to 2.0.

## Definition of Done
Line "Migrating v1 policies..." should not be present when already on the same version.

## Demo Script / Repro Steps
As described above.

**Comment by susanev** [comment]
closing this as we will soon be force upgrading to iam v2, so iam v1 bugs are no longer relevant.
