### ISSUE TITLE
Projects should be sorted in projects dropdown

### ISSUE THREAD

**Issue by msorens** [chef/automate#1490]
## User Story

As a user creating or updating a team or token, when I open the projects dropdown they should be sorted. Notice they are out of order in the image.

![image.png](https://images.zenhubusercontent.com/5d07f7b39943fc312156c891/16e1f1a5-73b7-4b0b-b204-ccbcf80edb2b)

Should probably be a fix to the library component; all consumers of it would want the same behavior.

## Definition of Done

Projects appear sorted.

## Demo Script / Repro Steps
Create or update a team or token and open the dropdown.

**Comment by SEAjamieD** [comment]
@susanev I was able to hijack the natural sort work done in [[A2-338] fix admin UI list sorting](https://github.com/chef/a2/pull/4434) , thanks for sharing!

Would it make sense to roll #1506 into this ticket and refactor as a helper function to close out two at once?

**Comment by susanev** [comment]
@seajamied yah, that sounds like a great idea!
