### ISSUE TITLE
Compliance report shows wrong date when filtering by Scan Jobs ID

### ISSUE THREAD

**Issue by jonong1972** [chef/automate#1492]
## Describe the bug
When a user filters a report by a scan job id, the date in the Meta Data box is incorrect.

## To Reproduce
1. Go to Compliance > Scan Jobs
2. Find a scan job that completed a few days ago. Click on the "Report" button.
3. System will take you to the report page.
4. Expand the "Report Metadata" box
5. Notice the Report date is today's date. 
6. Notice the date picker in the filter field.

## Expected behavior
The date in the filter should reflect the date of the Scan Job.
The date in the Report Metadata should reflect the date of the Scan Job.

## Screenshots
Today is Sept 6, 2019

Step 1: on the Scan Jobs page, notice the 'Test' scan job with 16 nodes. Says this happened 9 days ago.
<img width="1235" alt="Screen Shot 2019-09-06 at 9 41 01 AM" src="https://user-images.githubusercontent.com/1316587/64445164-a98a7b00-d08a-11e9-8343-c8086c55265d.png">

Step 2: After click on the Report button, taken to the Report. The date in the filter bar is still Sept 6, 2019.  Notice in the Metadata box, date is still Sept 6, 2019. 
![Screen Shot 2019-09-06 at 9 41 34 AM](https://user-images.githubusercontent.com/1316587/64445224-cfb01b00-d08a-11e9-862f-a5550c6ccd37.png)

 In the trend graph though, shows this scan job happened August 28th, 2019
<img width="632" alt="Screen Shot 2019-09-06 at 9 44 56 AM" src="https://user-images.githubusercontent.com/1316587/64445287-025a1380-d08b-11e9-82aa-7ec25beb4cfb.png">

## Versions (please complete the following information):
- OS: MacOS
- Browser Chrome
- Automate Build Number 20190904132002

**Comment by lancewf** [comment]
This problem was fixed with the https://github.com/chef/automate/pull/1268 PR. Now when a user clicks the "report" button on a scan job the last scan date is added to the filter.

**Comment by lancewf** [comment]
Here is the line that fixes this problem https://github.com/chef/automate/pull/1268/files#diff-758b14b9e55977ae2c1148baaa5b457aR124

**Comment by lancewf** [comment]
Demo of the date being added to the filter when a scan job report is selected. 
![scan_jobs_date](https://user-images.githubusercontent.com/1679247/64722429-4e3dfb80-d483-11e9-9487-8f5208db407a.gif)
