### ISSUE TITLE
Deleting a rule should indicate that the project needs to be updated

### ISSUE THREAD

**Issue by susanev** [chef/automate#1501]
## Overview
Deleting a rule on a project should indicate that a project needs to be updated, this includes (1) the link back to the projects list page, (2) project update status should change to _Needs updating_, and (3) _Update Projects_ button should become enabled.

For (1) please also change the link text to `Edits are pending: update projects to apply edits`.

Subtasks:

- [x] ListRules returns correct status when deletes are pending @tylercloke https://github.com/chef/automate/pull/1590
- [x] Have link show up in project details page on delete and change copyright @tylercloke https://github.com/chef/automate/pull/1605

**Comment by bcmdarroch** [comment]
Are there any backend changes needed here? Does deleting a rule change a project's `status`?

**Comment by msorens** [comment]
Verified
