### ISSUE TITLE
add natural sort library function

### ISSUE THREAD

**Issue by susanev** [chef/automate#1506]
_Originally reported by @bcmdarroch_

## Overview
This was implemented individually on each of the setting pages: https://github.com/chef/a2/pull/4434

it’d be a great refactor opportunity to pull the sorting logic out of those components into some shared library function that all of automate-ui could use. 

as part of this work, we could also investigate where we want library functions to live. another good library candidate would be copy (see slack discussion starting here). we might consider these functions like an extension of the ui-library

**Comment by SEAjamieD** [comment]
@msorens - Advice on where to place this function would be greatly appreciated.  I see a helpers folder in `app/components` but I don't see anywhere yet that would be a good placement for it there.

**Comment by msorens** [comment]
My suggestion would be components/automate-ui/src/app/helpers/auth/sorter.ts since this particularly sorting mechanism is used solely by auth components.
