### ISSUE TITLE
Define and publish a supported browser matrix

### ISSUE THREAD

**Issue by susanev** [chef/automate#1507]
## Overview

We should identify the list of platforms and browsers we support, and publish that list as part of the UI library documentation and on additional sites where appropriate (e.g., automate.chef.io, habitat.sh).

**Comment by kagarmoe** [comment]
I would suggest defining it in the UI library & having the the local sites conform to that. Individual sites tend towards entropy, so linking back to the one true way tends to be more effective.

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
