### ISSUE TITLE
Auto-suggest fails when filtering by cookbook

### ISSUE THREAD

**Issue by susanev** [chef/automate#1520]
_Originally reported by @trickyearlobe_

## Overview
An issue with autocomplete in the filter bar in the client runs view.

When a user has many cookbooks (more than 200) the auto-suggest doesn't show all matches as they start typing in the filter bar.

## Example
1. Cookbook called `db_chef_server_ha`
1. Set a cookbook filter and type `db_chef_server` into the search bar, notice that  autocomplete fails to suggest it
1. Enter `db_chef_server*` wildcard, notice nothing is suggested, hit enter, nodes running `db_chef_server_ha` are returned.

## Resources
[Jira issue with customer context](https://chefio.atlassian.net/browse/A2-893)

**Comment by lancewf** [comment]
This is a duplicate issue that was completed in July. 
https://github.com/chef/automate/issues/690

**Comment by vjeffrey** [comment]
yay!
