### ISSUE TITLE
Whitespace-only values should be disallowed for inputs

### ISSUE THREAD

**Issue by msorens** [chef/automate#1555]
[Migrated from Jira -- originally reported by @msorens on 2018.09.11]

This has been substantially completed in prior PRs.

Remaining work:

whitespace-only is disallowed but needs to pop-up an error bar under the field for these:
 - Token name / create
 - Project name / create

## To Reproduce
 - Settings >> Tokens >> Create
 - Settings >> Projects >> Create

## Expected behavior
Entering just spaces should show an error bar under the field.

## Screenshots
![image](https://user-images.githubusercontent.com/6817500/64667495-d46c2a80-d40e-11e9-8223-778ee803f5f7.png)

## Versions (please complete the following information):
- OS - any
- Browser - any
- Automate Build Number 20190910223032

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
