### ISSUE TITLE
Trim leading/trailing whitespace from auth inputs

### ISSUE THREAD

**Issue by msorens** [chef/automate#1559]
[Migrated from Jira -- originally reported by @srenatus on 2019.02.02]

## Describe the bug
If a user inadvertently includes leading or particularly trailing spaces in a field, it could cause difficult-to-diagnose headaches for them.
An audit of current auth field inputs shows that this is no longer an issue in the browser but it is not implemented at all for the API.

| Field Input            | UI     | API   |
| ---------------------- |:------:|:-----:|
| user/create/full name  | OK     | X     |
| user/create/name(id)   | OK (*) | X     |
| user/update/full name  | OK     | X     |
| team/create/name       | OK     | X     |
| team/create/id         | OK (*) | X     |
| team/update/name       | OK     | X     |
| token/create/name      | OK     | X     |
| token/create/id        | OK (*) | X     |
| token/update/name      | OK     | X     |
| policy/add/member      | OK     | X     |
| project/create/name    | OK     | X     |
| project/create/id      | OK (*) | X     |
| project/update/name    | OK     | X     |
| rule/create/name       | OK     | X     |
| rule/create/id         | OK (*) | X     |
| rule/update/name       | OK     | X     |
| condition/single value | OK     | X     |
| condition/array value  | OK     | X     |

(*) = editable but spaces are disallowed, so case is covered

## To Reproduce
Add some leading or trailing whitespace to a name or other value when creating it.

## Expected behavior
All leading/trailing whitespace should be stripped before being stored.

## Versions (please complete the following information):
- OS - any
- Browser - any
- Automate Build Number 20190911145323

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
