### ISSUE TITLE
Second login attempt (in tabs) makes the first one fail with "expected state X got Y"

### ISSUE THREAD

**Issue by tylercloke** [chef/automate#1561]
## Describe the bug

When creating a new session, we generate a relay state, and track it with the session id.
When the user is returned to session-service from dex, we compare the relay state with the one we've stored.

Opening a second tab overwrites the first tab's relay state.

We've also explicitly opted for deleting any previously existing sessions when accessing /session/new.

## To Reproduce

1. Open two tabs with https://a2-dev.test/session/new (or some env of your choosing); so that they both present you the username/password entry UI
1. Log in in tab 1 (the one opened first)
 
❌ the last step will fail with something like
```
expected state "Mj5b-Vh6wI_0Lw==" got "_UPP2JfuUKCEDw=="
```
from
https://a2-dev.test/session/callback?code=k6nisdxmri4wbga7vcdl2jgm6&state=_UPP2JfuUKCEDw%3D%3D

✅ Note that login in the tab opened second works.

**Comment by srenatus** [comment]
✔️ I believe we've fixed that one.

**Comment by tylercloke** [comment]
https://github.com/chef/automate/pull/596
