### ISSUE TITLE
Partial-eval-optimize authz introspection

### ISSUE THREAD

**Issue by tylercloke** [chef/automate#1562]
## Description

Paying more on policy updates, but having faster query responses, similar to what we do with `IsAuthorized`, could help UI performance a lot.

**Comment by srenatus** [comment]
For completeness' sake, other things that'll likely improve authz introspection performance:

1. Generating all the mappings and inverse mappings between HTTP method+verb pairs and IAM resource+action pairs **once** and relying on that for processing.
2. Baking those mappings  into OPA's store.

Currently, these are calculated (twice, IAM v1 and v2, I believe) at run time in automate-gateway for each and every request, and _sent down the request path_ to authz-service (and thus OPA).

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
