### ISSUE TITLE
Combine local-user-service and team-service and enforce cascading deletes

### ISSUE THREAD

**Issue by tylercloke** [chef/automate#1563]
## Description

We've talked about combining those two services for awhile. It'd let us actually do relational things with user-team membership. It'd also let us properly do cascading and transactional deletes inside of postgres which would get us most of the way to those deletes being transactional (there is still the problem of authz containing references to users and teams that might not be deleted).

We also do not enforce that local users and teams actually exist, cascade delete, etc.

We'll need to determine the implications of how this will affect dex and authentication. Right now we create and store users in dex. This will change once we add a user database table in postgres.

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
