### ISSUE TITLE
Automate does not export tags with client runs

### ISSUE THREAD

**Issue by tommybonobo** [chef/automate#1565]
## Automate does not export tags with client runs
Automate can show tags while on the web gui's `Client Runs` page but doing the following:
    - Select a node that has been tagged
    - Navigate to `Attributes`
    - Find `tags` array and expand it
    - Tag will show in array as expected

However if the `Client Runs` data is exported to `json` by  clicking the `Download JSON` link, the same node will now not have any elements in the `tags` array within the json. The `tags` array still shows but is always `null` and will look like this.

```
"tags": null
```

## To Reproduce
    - Navigate to the web gui's `Client Runs` page
    - Click the download button
    - Click `Download JSON`
    - Open the json and locate the `tags` for a node which has a tag defined as found in the web gui the method outlined above.
    - Despite having tags in the web gui, the `tags` array will be `null` like so: `"tags": null`
    - If the tag is searched for. It will not be found any where else in the exported json.

## Expected behavior
Tags which are on the gui should show somewhere inside the exported json data, preferably in the `tags` array.

## Versions (please complete the following information):
- OS: macOS
- Browser: chrome
- Automate Build Number 20190711110747

## Additional context
I have also exported the client run data via a curl using an API as documented. I found that this downloads the exact same json (no deltas) so it doesn't seem to be an issue with the way the web gui or browser downloads the file.

**Comment by lancewf** [comment]
Thank you for submitting this bug!

I will try to reproduce it in the dev environment and get back to you.  I hope it is an easy fix.

**Comment by lancewf** [comment]
I am seeing the same problem locally. I will see if it is an easy fix.

**Comment by lancewf** [comment]
@tommybonobo turns out there was an easy fix for the problem! https://github.com/chef/automate/pull/1578. 

Thank you again for submitting the bug.
