### ISSUE TITLE
Define password complexity rules and reuse rules and lockout rules

### ISSUE THREAD

**Issue by susanev** [chef/automate#1571]
## Overview
Admin security section: password complexity: using e.g. standard: Lass Pass complexity settings

### is not
- retroactively changing passwords that already exist
- Password rotation: e.g 30 days
- Password lockout attempt, duration

### Discussion
- DEX: doesn’t support locking users out, password rotation
- We could get away from Dex, but ???
- We’d really like to get away from DEX and this could tackle the password rotation.
- Database or TOML file via config. If DB, then 5pts, TOML, 3pts.

**Comment by srenatus** [comment]
https://keratin.tech/ looks like a decent `local-user-service` that supports these things. There's currently **no** connector for keratin in Dex, but we could contribute one. (This seems preferrable to any NIH approach to the issue.)

(Also note that keratin is a decent replacement for `session-service`, but in the bigger picture with Dex, and LDAP/SAML users, it doesn't quite fit: its sessions would be for local users only.)

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
