### ISSUE TITLE
Prevent deletion of project until it has no rules, is up-to-date

### ISSUE THREAD

**Issue by tylercloke** [chef/automate#1588]
## User Story

As an Automate Admin, I only want to delete a project when there is no longer any ingested data attached to it.

## Definition of Done

A user is not allowed to delete a project that has staged or applied rules. If they try to, they will get an error message saying they need to remove all rules from the project and re-apply the rules before deletion.

## Demo Script / Repro Steps

* Create a project with rules
* Attempt to delete project and get error
* Apply rules
* Attempt to delete project and get error
* Stage removal of all rules
* Attempt to delete project and get error
* Apply rule deletion
* Successfully delete project

**Comment by susanev** [comment]
will be fixed by #2460
