### ISSUE TITLE
integration tests for Compliance node and event filtering

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#1594]
## User Story

As a Developer, I will use this work when I want to verify through automated testing that ingest rules are applied correctly to Compliance nodes and Events (aka Actions).

We already have similar testing with infra nodes in this Cypress spec [01_projects_api.spec.ts](https://github.com/chef/automate/blob/master/e2e/cypress/integration/api/iam/01_projects_api.spec.ts).

[Compliance node fixture example](https://github.com/chef/automate/blob/master/components/compliance-service/ingest/examples/compliance-success-tiny-report.json)
[Event (Action) fixture example](https://github.com/chef/automate/tree/master/components/ingest-service/examples/actions)

Map of Rule Attributes to Corresponding Node/Action Fields
<img width="543" alt="Screen Shot 2019-09-19 at 8 39 51 AM" src="https://user-images.githubusercontent.com/21015366/65259185-1c4b1b80-dab9-11e9-8578-414e147c522e.png">

## Definition of Done
Test scenarios should run roughly like this:

1. Using a Compliance node fixture:
- we can create ingest rules for each of the following attributes: Chef Organization, Chef Server, Environment, Chef Role, Chef Tag, Chef Policy Group, Chef Policy Name
- when rules are applied, the Compliance node is tagged with the correct project

2. Using an Event fixture
- we can create ingest rules for each of the following attributes: Chef Organization, Chef Server
- when rules are applied, the Event is tagged with the correct project

## Demo Script / Repro Steps
- run integration tests

**Comment by bcmdarroch** [comment]
I looked into starting these tests last week, and the main hurdle I ran into was figuring out how to load Compliance nodes via curl. [This example](https://github.com/chef/automate/blob/master/.studio/automate-gateway#L283) looked promising. Haven't found any examples for actions yet, so we should reach out to superteam about that

**Comment by sdelano** [comment]
Sprint planning notes:
- @lancewf says we also have the nodemanager API that's implemented with project filtering as well
- current example test:
  - sends client runs
