### ISSUE TITLE
Infrastructure and Compliance tabs show different Platforms for Nodes

### ISSUE THREAD

**Issue by mattray** [chef/automate#1596]
On the Infrastructure tab there are nodes listed as "debian 10" and on the Compliance tab under Nodes those same machines are listed as "debian 10.0" or "debian 10.1". It would be nice to have this granularity on the Infrastructure tab, especially when sorting nodes by platform.

## Versions (please complete the following information):
Automate Build: 20190827222442

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
