### ISSUE TITLE
Fix event feed filter suggestions

### ISSUE THREAD

**Issue by susanev** [chef/automate#1623]
## Overview
Currently, the suggestions on the event feed filter come from the client-run suggestions. This was done to save time, but now that we have a search filter on that page the user experience can be pretty confusing. This issue is to have the event-feed have their own suggestions instead of reusing the client-run suggestions.

**Comment by vjeffrey** [comment]
@lancewf was this work completed as part of the event feed migration prs?

**Comment by susanev** [comment]
this has been deprioritized.
