### ISSUE TITLE
Default policies docs page nav/content overlap

### ISSUE THREAD

**Issue by susanev** [chef/automate#1625]
## Overview
On the default policies page the docs left-nav sometimes overlaps the content. Specifically, if you scroll down to a wide table and then scroll right you will notice that the left-nav overlaps the content.

### Desired behaviour
The left-nav does not overlap the content.

## Screenshot
![default-policies-issues](https://user-images.githubusercontent.com/5489125/64995974-7f5a6980-d891-11e9-9d9a-09c6d075df1e.png)

**Comment by kagarmoe** [comment]
Thank y'all for taking on this work! I'd love to ride along--if not actually pair. If it is possible, I'd like the tables in docs to end up responsive for smaller screens. It would be a good pattern for our Hugo docs going forward.
