### ISSUE TITLE
Form Label Text Edit on Node Integrations

### ISSUE THREAD

**Issue by jonong1972** [chef/automate#1650]
## Describe the bug
Currently when creating a new node integrations, the form labels for Azure are not consistent with the other cloud services. We should make them consistant.

## To Reproduce
- Go to https://a2-dev.test/settings/node-integrations/add
- Take notice of form labels for the AWS Keys.
  - "Enter your AWS access key ID"
  - "Enter your AWS secret access key"
- Click on the Azure service
- Take notice of form labels
  - "Client ID"
  - "Client Secret"
  - "Tenant ID"

## Expected behavior
To be consistent, we should update the label text to:
  - "Enter your Client ID"
  - "Enter your Client Secret"
  - "Enter your Tenant ID"

![Screen Shot 2019-09-18 at 11 31 52 AM](https://user-images.githubusercontent.com/1316587/65176129-03832d00-da09-11e9-9f4c-fa7939f4f7fe.png)

**Comment by susanev** [comment]
@jonong1972 could you add a screenshot? and the specifics you want to be changed to this issue?

**Comment by jonong1972** [comment]
@susanev yeah, I misfired accidentally. it posted too soon. its updated now

**Comment by susanev** [comment]
@jonong1972 would you be open to dropping the "Enter your" on the aws form instead? That would make the form more scannable since everything doesn't start the same way.

**Comment by jonong1972** [comment]
@susanev, @msorens and I were just talking about this.  Its inconsistent everywhere. 
for instance:
Credentials:
"Assign a unique name for your key *"
"SSH Username *"
"SSH password *"

Notifications:
"Assign a unique name for your notification *"
"Select a failure type *"
"Enter your Slack webhook *"

Teams
"Name *"
"ID: "

So. this ticket may be a small thing just for Integrations, but we ultimately need to decide on what our voice is like across all of automate.

**Comment by susanev** [comment]
I def have opinions on the input labels and placeholders. id be happy to take on this work if you are cool with that.

**Comment by jonong1972** [comment]
@susanev sweet. Go for it.

**Comment by susanev** [comment]
im closing this in favor or #1656 which im still filling out with details
