### ISSUE TITLE
Refactor and re-enable AuthZ functional tests

### ISSUE THREAD

**Issue by tylercloke** [chef/automate#1652]
## User Story

As part of the cereal PR to cerealize ApplyRules, we had to comment [out some tests](https://github.com/chef/automate/blob/master/components/authz-service/server/v2/rules_property_test.go#L125) because we did not want to either mock cereal service or write artisanal go code in the test setup to make cereal-as-a-service work in the tests.

Related, there is a ton of flaky setup and spindown code in `testhelpers.go` and elsewhere in all of our functional testing (property based and GRPC server testing).

What we should do is run the tests against a running instance of automate (aka start_all_services) instead of mocking and setting up the server (there is an example in applications-service that I can't find, we should reach out to Dan).

## Definition of Done

All tests uncommented and we don't duplicate any server setup code (besides the postgres tests, those are fine to just run against a database and don't need the whole stack).

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
