### ISSUE TITLE
setting a scan job schedule to 12pm resets to 12am on edit

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#1660]
## Describe the bug
This issue was reported by a customer: https://chefio.atlassian.net/browse/TRI-897

Creating a scan job with a schedule set to any date at 12pm, on edit, sets the scan job to 12am.  I created a scan job to test this in:
https://a2-local-fresh-install-acceptance.cd.chef.co/compliance/scan-jobs/jobs
and was able to easily reproduce.

## To Reproduce
- create a scan job set to start any day at 12pm
- edit the scan job
- notice that AM is selected in the time field

## Expected behavior
Time selected is true to time set for scan job

## Screenshots
<img width="967" alt="Screen Shot 2019-09-18 at 22 05 13" src="https://user-images.githubusercontent.com/10341541/65212747-9e5b2600-da60-11e9-9339-42b6ae541b72.png">
^ 12pm for me at 1800 UTC

## Versions (please complete the following information):
- Browser: chrome
- Automate Build Number: 20190917213830

**Comment by susanev** [comment]
this is no longer an issue because this was changed to utc and there is no am or pm.
