### ISSUE TITLE
Chef Automate EAS Applications Documentation

### ISSUE THREAD

**Issue by kagarmoe** [chef/automate#1673]
The Chef Automate EAS Applications Beta Documentation is getting ready for GA.

- [x] Convert from GDoc to Markdown
- [x] Test it out
- [x] Edits and reviews

**Comment by vjeffrey** [comment]
i believe this is a duplicate of https://github.com/chef/automate/issues/1651 ?

**Comment by susanev** [comment]
this work has been completed
