### ISSUE TITLE
Compliance Report Download Returns Empty CSV

### ISSUE THREAD

**Issue by bnwoods** [chef/automate#1675]
## Describe the bug
After running a scan job and browsing scan results on automate, clicking the "download" button and downloading as CSV returns an empty CSV. This also happens when downloading as JSON.

## To Reproduce
- Run scan job
- Click Report
- Click the download button next to the search bar
- Download as CSV

(Also made sure to click "nodes" then "scan results" and ensured there were actual results showing in the UI)

## Expected behavior
Expected all controls and their pass/fail status to show up in the CSV/JSON downloaded

## Screenshots
![image](https://user-images.githubusercontent.com/21341907/65342071-8df99700-db97-11e9-8ae6-6ed3f9b344f7.png)

![image](https://user-images.githubusercontent.com/21341907/65342082-9520a500-db97-11e9-8b9d-20bfdb518be2.png)

![image](https://user-images.githubusercontent.com/21341907/65342087-9baf1c80-db97-11e9-9ec4-7d9065b1bf3f.png)

![image](https://user-images.githubusercontent.com/21341907/65342101-a5d11b00-db97-11e9-8690-b4b96940f1a1.png)

![image](https://user-images.githubusercontent.com/21341907/65342121-ad90bf80-db97-11e9-94cc-95a6a54ea03c.png)

## Versions (please complete the following information):
- OS: [MacOS 10.14.1, Windows 10]
- Browser [Chrome, Firefox]
- Automate Build Number [20190904132002]

**Comment by vjeffrey** [comment]
hi @bnwoods - thank you for submitting the issue!

i've attempted to reproduce the issue, following the steps you provided, in a test environment with version 20190917213830. 

i was unable to repro the issue (the report had the correct info). 
I'm wondering if you could try to export via curl to see the results of that?  
```
curl --silent --insecure -H "api-token: token" https://a2-url/api/v0/compliance/reporting/export -d '{"type":"json","filters":[{"type":"start_time","values":["2019-09-16T00:00:00Z"]},{"type":"end_time","values":["2019-09-18T23:59:59Z"]}]}'> out.txt
```
would it also be possible to check the console in the dev tools to see if any errors pop up?

**Comment by bnwoods** [comment]
Hey @vjeffrey! 

Exporting via curl does pull the results of that and everything else that's run as intended. 

Also, weirdly enough, I ran another identical scan job this morning and it's exporting to CSV and JSON fine. Not sure what was up with the 2 I attempted last week. 

This _might_ be a false alarm? Sorry about that!

**Comment by vjeffrey** [comment]
i'm gonna close out the issue, but if you ever see this again, please make a note and re-open this issue or a new one! 
i'm still very curious about why it didn't work that one time.
