### ISSUE TITLE
Compliance Reporting Calendar UTC date

### ISSUE THREAD

**Issue by lancewf** [chef/automate#1677]
## User Story

As an automate compliance user, I want to see the calendar on the compliance reporting search bar display the current date was the UTC date no my local date. Currently the calendar display the users local date and not the UTC date. With this work we also want to look into if a UTC label is needed on the calendar. 

## Definition of Done
The compliance reporting search bar calendar displays the UTC date with a UTC label. 

## Demo Script / Repro Steps
1. Change your local computers timezone to New Zealand. 
1. Open https://a2-dev.test/compliance/reporting 
1. Click the calendar control in the search bar. 
1. Ensure the date is the UTC date.

**Comment by susanev** [comment]
resolved by #2048
