### ISSUE TITLE
Fix date/time in trial license applied modal

### ISSUE THREAD

**Issue by susanev** [chef/automate#1679]
## Goal
Consistent date/time display across automate, that displays the day of the month, before the month.

## Overview
Currently, the date/time format on the trial license accept modal does not match the consistency pattern we have developed. Specifically, it should be displayed as...
    `<Day of week:word as abbreviation>, <Day: num, prepend w/ 0> <Month:word as abbreviation> <Year: num> <Time: 00:00:00> UTC`
    e.g., `Wed, 03 Jul 2019 17:08:53 UTC`

## Repro steps
- `chef-automate dev psql chef_license_control_service -- -c "UPDATE licenses SET active=NULL"` to remove the current license
- refresh browser
- fill out the trial license form and submit
- observe the trial expriation modal

### Trial license accept modal
Current api response is: `"licensed_period":{"start":"2019-09-20T18:02:28Z","end":"2019-11-19T18:02:28Z"}`

_Note: Please also remove the period from the pink, strong text and place it outside._

#### Before

![trial-license-before](https://user-images.githubusercontent.com/5489125/65349181-aa95cf00-db97-11e9-8bda-917c358edcad.png)

#### After
![trial-license-after](https://user-images.githubusercontent.com/5489125/65349339-03fdfe00-db98-11e9-9b32-a5a419c4ff3e.png)

**Comment by SEAjamieD** [comment]
@susanev - I noticed the same messaging in the `license-lockout` component as well, should I update the time formatting in the modal there as well?  The two are running off of the same parsing function.

**Comment by susanev** [comment]
yes, thank you!!
