### ISSUE TITLE
re-architect tokens in authn-service

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#1680]
## User Story

As an Automate Developer, I will use this work when I want to work in authn-service.

`authn-service` is one of our oldest services and it's due for an update. To start, we'd like to make our tokens server look a little more like our servers in authz-service (policies, projects, etc).

## Definition of Done
- `authn-service` implements `NewGRPCServer(...)` to work in the same way as authz-service's implementation. In more specific terms, this means the tokens API no longer uses the TokenConfigs struct to initialize different token backends. Instead, separate functions for each type of storage should be implemented, like in authz-service's [project.go](https://github.com/chef/automate/blob/master/components/authz-service/server/v2/project.go#L38)
- the various tokens test files make use of go's `testify` library and testing patterns we've developed in our authz-service tests
- maybe as a bonus: we drop the `mock` tokens adapter

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
