### ISSUE TITLE
Improve error when creating v2 policy while on IAM v1

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#1691]
## User Story

As an Automate User, I will use this work when I try to create a v2 policy while on IAM v1.

Currently, I get this confusing error if I try to create a v2 policy while on v1.
```
root@a2-local-inplace-upgrade-acceptance:~# curl -kH "api-token: $TOK" -d '{"id":"team-view-pol", "name":"team viewer", "members":["user:local:coolbean"], "statements": [{"role": "team-viewer"}]}' "$TARGET_HOST/apis/iam/v2beta/policies?pretty"
{
  "error": "project not found: ~~ALL-PROJECTS~~",
  "message": "project not found: ~~ALL-PROJECTS~~",
  "code": 3,
  "details": [
  ]
}
```

## Definition of Done
In the above case, the user should get an error that makes it clear they can only create v2 policies while on IAM v2 or v2.1.

## Demo Script / Repro Steps
- on v1, try the curl above. get informative error
- upgrade to v2 or v2.1, try the curl again. success!

**Comment by susanev** [comment]
closing because we are moving away from v1
