### ISSUE TITLE
Consistency of UI confirmations

### ISSUE THREAD

**Issue by msorens** [chef/automate#1744]
## User Story

As an Automate User, I want user confirmations to appear consistent. Here's a portion of them (may be some others, too):

![image.png](https://images.zenhubusercontent.com/5d07f7b39943fc312156c891/b0a568cd-7ec2-4c33-90d4-0e91cb9476d1)

From the above observe these inconsistencies:

1. Start with "Successfully..." or not.
2. Identify the class of thing (e.g. just "team") or identify the individual thing (e.g. "rule ${id}").
3. End with period or not.
4. Phrasing: "created a new team" vs "updated team",
So a few things to iron out.

## Definition of Done

From @susanev :
1. no "successfully"; if a thing happened sure hope it was successful otherwise why are we saying the thing happened?
2. individual thing whenever possible
3. periods, for accessibility, screenreaders will pause before reading the next thing if it ends in a period
4. lets drop the "new"

Just to clarify on point 4, in conjunction with point 2, means that "Created a new team" would become `"Created team ${some-id-variable-here}"`

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
