### ISSUE TITLE
Object Name Consitency: Node Integration to Node Manager

### ISSUE THREAD

**Issue by jonong1972** [chef/automate#1745]
## Goal
Currently, on the Automate UI we have the term "Node Integration" across the board. While on the APIs and backend we have the term "Node Managers". To get a better consistency for learning purposes, we should align the GUI with the back end labeling for better understanding and change out the term "Node Integration" with "Node Manager"

## Definition of Done
Across Automate's UI replace the term "Node Integration" with "Node Manager"

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
