### ISSUE TITLE
Deleting a project, like adding one, should reflect immediately in the global filter

### ISSUE THREAD

**Issue by msorens** [chef/automate#1756]
## User Story

As an Automate User, I expect the global project filter to be updated as projects are added or deleted. It is true for adding projects, but not for deleting. It would eventually re-sync at the next periodic refresh but it should be done immediately.

## Definition of Done
Global project filter updates immediately upon adding and deleting projects.

## Demo Script / Repro Steps
Add a project. Open the global projects filter and observe the new project is present immediately.
Delete a project. Open the global projects filter and observe the deleted project is still present.

**Comment by susanev** [comment]
create project pr #1851
