### ISSUE TITLE
display message when control results are empty

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#1761]
## User Story

When viewing a node report on the node details screen of Automate, we show users "results" and "source" sections.
Sometimes a control does not have tests:
<img width="1170" alt="Screen Shot 2019-10-02 at 05 44 49" src="https://user-images.githubusercontent.com/10341541/66041715-c5d9d600-e4d7-11e9-8477-70eefffe48fd.png">

In these cases, the results section is empty and the ui appears broken.
I discussed this with ux (@jonong1972) and we concluded some kind of wording would be the best way to resolve this (i.e. "No tests were executed")

### Before
![Screen Shot 2019-10-02 at 12 19 30 PM](https://user-images.githubusercontent.com/1316587/66075032-7f07d280-e50f-11e9-9e9e-4c1b59b8d308.png)

### After
![Screen Shot 2019-10-02 at 12 22 46 PM](https://user-images.githubusercontent.com/1316587/66075042-85964a00-e50f-11e9-9d13-15db27416477.png)

## Definition of Done
UI shows _something_ /doesn't look broken when viewing a control with no results.

**Comment by SEAjamieD** [comment]
@vjeffrey - Any way to populate a result that doesn't have a test associated?  I've looked through the adding data documentation but this seems to be a far more specific scenario

**Comment by vjeffrey** [comment]
oh yes, let me spin up a quick profile -- you can then upload profile into automate and use it for a scan job to get an example report

**Comment by vjeffrey** [comment]
[my-test-tagging-0.2.0.tar.gz](https://github.com/chef/automate/files/5241328/my-test-tagging-0.2.0.tar.gz)
