### ISSUE TITLE
when viewing scan results for a single control on reporting profile details page, filter by profile+control

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#1762]
## User Story

This was suggested by @tmonk42 

> Ohai! If I’m looking at a compliance report, and navigate to results for a specific control, and then click to see results for just that control, the status icon for individual nodes reflects their overall status, not their status for the control. I would expect when I have some that passed and some that failed a control that I’d be able to visually tell the difference when viewing results.
Here I’m looking at control 1.1 Latest LTS OS Version and 4 failed and 3 passed, but when looking at the results for control, all seven nodes show the failed icon. If I expand results, I can see who failed and passed one by one, so it’s possible to get the info, and I feel like this could be better/clearer
![Screen Shot 2019-10-01 at 11 25 37](https://user-images.githubusercontent.com/10341541/66042916-04bd5b00-e4db-11e9-8e2e-3adfd6d38109.png)

We can solve this by applying the profile and control filters when a user selects the scan results for a control:
```
'{"filters":[
{"type":"profile_id","values":["1de944869a847da87d3774feaacb41829935a2f46b558f7fc34b4da21586ae27"]},{"type":"control","values":["/etc/group must exist"]}
]}'
```
This should also be removed from the filters when the scan results window is closed.

Relevant code: https://github.com/chef/automate/blob/master/components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profile/reporting-profile.component.ts#L119-L129

## Definition of Done
profile/control filter is applied when viewing scan results for a control from profile details view.

**Comment by SEAjamieD** [comment]
@vjeffrey @scottopherson @tarablack01 - Would be nice to get a second set of eyes on this.  When I started digging into it, it seems like this might be an issue with the API endpoint.

After the first call is made, every subsequent call to `reporting/nodes/search` returns a `status: failed`, regardless of which node its on.  Specifically referring to the `getNodes()` function in `stats.service.ts`

The html in `reporting-profile.component.html` is then reading this `status: failed` and showing the correct icon for what is coming back from the API.

**Comment by vjeffrey** [comment]
@SEAjamieD even after applying a profile and control filter for a passed or skipped control?

**Comment by vjeffrey** [comment]
i'll do some api calls locally

**Comment by SEAjamieD** [comment]
If I'm reading this correctly, we're already adding filters for profile and control in the getNodes() function here: https://github.com/chef/automate/blob/e9e2056f523b0725401203e56fa3875aefdf5ad7/components/automate-ui/src/app/pages/%2Bcompliance/%2Breporting/%2Breporting-profile/reporting-profile.component.ts#L131-L133

**Comment by vjeffrey** [comment]
oh, i had not noticed that!
ok, so given that, i went to acceptance to test. i see the network call:
<img width="702" alt="Screen Shot 2019-10-04 at 16 48 02" src="https://user-images.githubusercontent.com/10341541/66244669-cf756080-e6c6-11e9-87ab-374a3ef40ba3.png">
but it looks like a control id is getting added every time we open the scan results, without ever removing any -- so maybe the card is actually just about removing that filter on scan results window close?

**Comment by SEAjamieD** [comment]
Awesome!  I'll give that a shot now...stay tuned...

**Comment by SEAjamieD** [comment]
That did the trick!  🎉  Thanks for the help @vjeffrey!
