### ISSUE TITLE
applications endpoints becoming disabled between deployments

### ISSUE THREAD

**Issue by kmacgugan** [chef/automate#1767]
## User Story

As a automate admin, I will use this work when I want to have the applications endpoints enabled between deployments. 

It was discovered in acceptance environment that after a deployment the applications endpoints were disabled. They were enabled the week before by hand using the command `chef-automate applications enable`. The result was that the data was unable to be displayed. It might also be the case that we want to enable/disable the job running endpoints only and always allow the get endpoints?

**Comment by kmacgugan** [comment]
This is only an issue in acceptance, here's our options: 
1) add the enable command to the acceptance deployment script
2) make it on by default in preparation for GA (or like right before GA) and just turn on acceptance when we need it.

**Comment by vjeffrey** [comment]
i vote option #1 since that means the data will always be populated, making it easier for ux/product/field to check things

**Comment by vjeffrey** [comment]
is there still follow up that needs to be done on this issue?
