### ISSUE TITLE
Non-admin can create IAM resource that cannot be used

### ISSUE THREAD

**Issue by msorens** [chef/automate#1770]
## User Story

As an Automate User with permission to create a (role/team/token/policy) resource, I should also be able to use and to modify that resource. This is true when creating the resource with a non-empty project list, when the user has permissions on that project.
But if the resource is created with an empty project list when the user only has permissions on `project-1`, then the resource creation completes successfully but the object is not accessible to the user.

## Definition of Done

Should get an error if attempting to creating an object with an empty project list when the user does **not** have `(unassigned)` included in the project list on the policy statement.

## Demo Script / Repro Steps

Generate an ADMINTOK and a PLEBTOK (`plebtoken`) and define your TARGET_HOST.

Create some projects:
```
curl -sSkH "api-token: $ADMINTOK" -X POST -d '{"name": "allowed-1", "id": "allowed-1" }' $TARGET_HOST/apis/iam/v2beta/projects?pretty
curl -sSkH "api-token: $ADMINTOK" -X POST -d '{"name": "allowed-2", "id": "allowed-2" }' $TARGET_HOST/apis/iam/v2beta/projects?pretty
curl -sSkH "api-token: $ADMINTOK" -X POST -d '{"name": "disallowed", "id": "disallowed" }' $TARGET_HOST/apis/iam/v2beta/projects?pretty
```
Create a policy in `pol.json`:
```
{
  "name": "project test",
  "id": "project-test",
  "members": [
    "token:plebtoken"
  ],
  "statements": [
   {
     "effect": "ALLOW",
     "actions": [
          "iam:tokens:*",
          "iam:roles:*",
          "iam:teams:*",
          "iam:policies:*",
          "iam:projects:assign"
     ],
     "projects": [ "allowed-1","allowed-2" ]
   }
  ],
  "projects": []
}
```
```
curl -sSkH "api-token: $ADMINTOK" -X POST -d @pol.json $TARGET_HOST/apis/iam/v2beta/policies?pretty
```

Create a token with no projects
```
curl -sSkH "api-token: $PLEBTOK" -X POST -d '{"name": "token4", "id": "tok4", "active": true, "projects": [] }' $TARGET_HOST/apis/iam/v2beta/tokens?pretty
```
Attempt to modify that token
```
 curl -sSkH "api-token: $PLEBTOK" -X PUT -d '{"name": "token4", "active": true, "projects": ["allowed-1"] }' $TARGET_HOST/apis/iam/v2beta/tokens/tok4?pretty
```
Response:
```
{
  "error": "No token record found",
  "message": "No token record found",
  "code": 5,
  "details": [
  ]
}
```

**Comment by blakestier** [comment]
When we do this, we should see if we can design things to make it hard to introduce this kind of bug, assuming other domain services are going to need to implement similar logic
