### ISSUE TITLE
Token details missing when navigating via policy membership

### ISSUE THREAD

**Issue by msorens** [chef/automate#1771]
## User Story

As an Automate User, I should be able to open the details of any member of a policy, be it user, team, or token. That is true for users and teams, but a token displays with all fields empty, and an error.

![image.png](https://images.zenhubusercontent.com/5d07f7b39943fc312156c891/e31be8e3-a4ad-4c18-a26c-3c612cfb4fe7)

![image.png](https://images.zenhubusercontent.com/5d07f7b39943fc312156c891/8ce10f99-feb1-482b-8f56-9cbe4e163dda)

## Definition of Done

Can view token details when navigating via policy membership.

## Demo Script / Repro Steps

Create a policy.
Add a token as a member.
From the members list of the policy, select the token to open the token details.

**Comment by tylercloke** [comment]
Could not repro. Let's get some time from @msorens this week to see if we can just close.

**Comment by msorens** [comment]
I concur. If it is, in fact, a real issue, I missed recording pertinent setup.
More than likely it is a phantom; that error can legitimately manifest by deleting the token, by an incompatible global project filter setting, and probably other factors.
