### ISSUE TITLE
Hab Builder services can backup and restore

### ISSUE THREAD

**Issue by ryancragun** [chef/automate#1783]
We need to be able to backup and restore hab-builder services                   
                                                                                
Acceptance Criteria:                                                            
* The automate-postgresql builder database needs to backed up                   
* The hab-builder-minio assets need to be backed up                             
                                                                                
Questions?                                                                      
* How should we back up assets? Versioned aritifacts to the backup gateway?     
  A single compressed archive?

**Comment by sdelano** [comment]
Following up on the meeting I had w/ the Hab team yesterday and our desire to sync with them on the backup story, I told them that we'd put together a list of questions we had for them from both the product-level functionality perspective and the technical perspective. The goal is that we can meet with them tomorrow and discuss the space of backup and restore as it relates to Automate-deployed Builder and come to a clear understanding of what we want that feature to look like (given what we think is possible). From there (and not necessarily in that meeting) we can figure out what part of that backup story we can accomplish end-to-end for an MVP.

**Comment by stevendanna** [comment]
Current TODO list for the spike implementation of backup/restore

- [ ] Basic backup/restore test in place
- [ ] Issue a warning for anyone deploying the Depot that they are using a pre-release feature and that we don't make the same upgrade guarantees.
- [ ] Test upload the core packages into the depot and figure out how long backup & restore takes with that set of packages.
- [ ] low-hanging fruit: batch up the delete calls better
