### ISSUE TITLE
Deployment of a hab-builder is tested

### ISSUE THREAD

**Issue by ryancragun** [chef/automate#1792]
We need to deploy and verify that the hab builder works

## Acceptance Criteria:
* There is a pre-merge verification test that asserts that builder is minimally functional
* There is a post-merge acceptance environment that deploys builder with verification tests

## Questions:
* Are there any existing suites that we can re-use here?

**Comment by sdelano** [comment]
Sprint Planning Notes:
- we have a test that runs pre-merge and post-merge in a one-off environment
  - logs in
  - creates token
  - creates an origin
  - creates a package
  - uploads a package
  - takes a backup
  - uninstalls automate
  - restores from backup (reinstalls)
  - downloads the package
- what we need now
  - deployed to dev and acceptance environments
    - move current workflow environments to full-stack (but a funnier name)
      - workflow
      - chef-server (infra)
      - bldr
  - run a subset of the premerge tests
    - login
    - get a token
    - create an origin
    - upload a package
    - promote a package?
    - download a package
  - try and run the hab bldr api tests
  - bonus points
    - how can we get a token easier?
