### ISSUE TITLE
Hab builder should work inside an environment with proxies

### ISSUE THREAD

**Issue by ryancragun** [chef/automate#1793]
We need the services and tooling to work with proxies.

## Acceptance Criteria
* A user should be able to deploy, migrate, airgap deploy, and airgap migrated in an environment with proxies.

**Comment by sdelano** [comment]
Sprint planning notes:
- we're currently able to deploy all the bldr services but we haven't tested proxies
- just as a consequence of being services in the platoform they're getting:
  - `HTTP_PROXY` and `HTTP_NO_PROXY` env variables
- we can verify the functionality of the effectiveness of this with a test
  - for the `NO_PROXY` variable we can test internal auth to the auth service
  - we're not currently aware of a spot in the codebase that's going to need to talk outward through a proxy
- we don't currently have any tests that spin up bldr
- bldr has 2 levels of tests:
  - rust unit tests
  - end-to-end tests
    - likely very much tied to their particular CI setup
    - roughly on the order of dozens of assertions
  - makes more sense for us right now to write a handful of smoke tests
  - work with the bldr team to work towards something that could run in *both* CI systems eventually

For this sprint:
- commit to writing a small set of smoke tests that can run in a non-proxied environment to verify some level of functionality
  - stand it up
  - log in
  - create an origin
  - upload a package
- commit to also running that test behind a proxy (doesn't have to pass)
