### ISSUE TITLE
Automate deployed hab builder has docs

### ISSUE THREAD

**Issue by ryancragun** [chef/automate#1795]
We need to document how to use this

Acceptance Criteria:
* Docs should explain how to use all the builder functionality: deploy, ~migrate~, backup, restore, ~oauth~, ~analytics~, ~external postgres~, ~external artifact repo~
* The on-prem readme should reference the new way to deploy on prem builder
* The docs should reflect the scope of the MVP: local storage, local auth, etc. ([MVP scope](https://github.com/chef/automate/#workspaces/deploy-5d9260c6df37660001a11a0c/reports/release?release=5dbc8a204837610001eec54f))
* These should live in the Automate docs
* [OAuth page for Bldr](https://automate.chef.io/docs/oauth/) in Automate Docs should reflect that it's out of date

**Comment by sdelano** [comment]
Notes from Sprint Planning:

Questions from Sprint Planning:
- [ ] how should we refer to this thing?
  - if this first release is not for production use, how do we refer to it in the documentation to make that clear? @krasnow

**Comment by sdelano** [comment]
@yzl we just chatted that for now it's best to include the package population experience in the docs we have. Please reach out to @kagarmoe for any questions re: docs
