### ISSUE TITLE
Hab builder UI and API are routable throught the automate-load-balancer/automate-gateway

### ISSUE THREAD

**Issue by ryancragun** [chef/automate#1796]
We need the load balancer and gateway to properly route the hab builder services

## Acceptance Criteria
* When deployed with automate the load balancer can properly route UI assets.   
* The Automate UI and Builder UI are both accessible                            
  (we might need to build the hab builder assets with a specific base_href.     
* The hab-api-proxy and hab-api are routable from automate-load-balancer        
* A hab client can be configured and can use Automate as a builder/depot        

### Questions                                                                       
* How do we provide an admin token for users? Currently generating a token      
  requires doing a full oauth dance, could we do that automatically for the     
  user when using automate auth?                                                
* Are there any auth corner cases we need to worry about?                       
* Database namespacing in automate?

**Comment by sdelano** [comment]
Addressed by #1831
