### ISSUE TITLE
Automate UI and Hab Depot UI are happy together

### ISSUE THREAD

**Issue by ryancragun** [chef/automate#1797]
For the MVP we need the Automate UI and Hab Depot UI to be accessible at the address and port, but with different base_href's. We would like the experience to be better.

Acceptance Criteria:
* Don't have it, we need to work with product on what we want this experience to be.

**Comment by sdelano** [comment]
In the current implementation, you can get to the Bldr UI from `https://fqdn/bldr` and the API from `https://fqdn/bldr/v1`

@krasnow @apriofrost we need to decide what UX we want to ship with re: some sort of linking between the user interfaces.
