### ISSUE TITLE
Active tab indicator gets hidden when a filter is applied in Compliance Report

### ISSUE THREAD

**Issue by jonong1972** [chef/automate#1810]
## Describe the bug
On the Compliance Report, after filtering on something, the blue line indicator for the tab gets hidden. see #1993 for more context.

## To Reproduce

1. Steps to reproduce the behavior:
2. Go to https://a2-perf-test-single-local-inplace-upgrade-acceptance.cd.chef.co/compliance/reports/overview
3. Click on the Nodes Tabs 
4. Take notice of the blue line that indicates the tab is active
5. Apply a filter `environment`  and then choose a value.
6. Notice the tab. the underline is missing.

## Expected behavior
The active tab should retain the indicator

## Screenshots
<img width="1199" alt="Screen Shot 2019-10-04 at 11 09 04 AM" src="https://user-images.githubusercontent.com/1316587/66229807-82c66100-e697-11e9-8369-970fa455e130.png">

## Versions (please complete the following information):
- OS: Mac OS
- Browser Chrome
- Automate Build Number 20191001203421

**Comment by vjeffrey** [comment]
also: https://github.com/chef/automate/issues/2757

**Comment by SEAjamieD** [comment]
Closing - Already been fixed
