### ISSUE TITLE
Automate should ship Elasticsearch with OpenJDK instead of Oracle JRE

### ISSUE THREAD

**Issue by ryancragun** [chef/automate#1820]
Due: 2019Q4
Context: EOY commitment came up during EM offsite 6/2019

https://github.com/chef/automate/pull/1746
https://github.com/habitat-sh/core-plans/pull/3047
https://github.com/habitat-sh/core-plans/pull/3048

**Comment by jaym** [comment]
TODO:
- use jdk 11
- try not to depend on core plans elasticsearch during build

**Comment by stevendanna** [comment]
Top Minds are working on this.

**Comment by ryancragun** [comment]
![](https://vignette.wikia.nocookie.net/indianajones/images/1/1a/Eaton.jpg/revision/latest?cb=20190217133519)
