### ISSUE TITLE
Correct behavior when creating new project

### ISSUE THREAD

**Issue by msorens** [chef/automate#1827]
## User Story

As an Automate User, when I create a new project it should be auto-checked in the global projects filter.
Currently, if you create a project, it is added to the global projects filter list but *not* checked (selected), and yet the project shows up in the project list as shown, when the global projects filter dictates it should not.
![image.png](https://images.zenhubusercontent.com/5d07f7b39943fc312156c891/82939e5e-2d3c-47f3-ae91-24b957739314)

An alternate solution (though I think this is a poorer UX) would be leave the global projects filter alone, but then suppress the output of the new project in the list.

## Definition of Done

A new project is auto-checked to the global projects filter.

## Demo Script / Repro Steps

Create new project; observe it appears on the project list but is unchecked in the global projects filter.

**Comment by susanev** [comment]
closing in favor of a future issue, instead when creating a project if its not in their filtered view the user will be notified and then they can take action to change their filters.
