### ISSUE TITLE
Integration tests for project update (against an instance of automate?)

### ISSUE THREAD

**Issue by susanev** [chef/automate#1839]
## Overview
_More details coming soon..._

references:
https://github.com/chef/automate/tree/master/integration/tests

**Comment by bcmdarroch** [comment]
related (but maybe warrants its own card):

we should make sure all of these project assignment cases are tested: https://docs.google.com/document/d/1AKk53neDwzmI-iuBtUfffOLEchtR9jEvsILPSAC9wmA/edit

many of them are covered in https://github.com/chef/automate/blob/master/e2e/cypress/integration/api/iam/05_iam_integration.spec.ts
but could be moved into this new suite of tests.

**Comment by susanev** [comment]
resolved by #1594
