### ISSUE TITLE
_flip the switch_ for iam v2 ga

### ISSUE THREAD

**Issue by susanev** [chef/automate#1843]
## Overview

Crossing _t_ s and dotting _i_ s: confirm we've done all the GA things.

At the beginning of the 30-day IAMv1 grace period, we’ll create the GA endpoints that will reference the same handler as the beta endpoint, and then drop the beta endpoint after the grace period is over. This will allow beta and GA endpoints to share the handler AND and underlying database, and seamless migration for beta customers to GA at the time GA is released.

- add `v2` paths that map to their corresponding `v2beta` APIs
- Remove mention of `beta` from docs, UI, CLI, API
    - note the docs will be handled in #2275

**Comment by msorens** [comment]
I think we need a third bullet to force-upgrade users to IAM v2...?

**Comment by susanev** [comment]
@msorens the force upgrade is currently planned for 30 days after ga. You can apply a release filter on the board to see what is involved in that.
