### ISSUE TITLE
Performance test OPA, authorization

### ISSUE THREAD

**Issue by susanev** [chef/automate#1844]
## Overview

We did a great set of V1 and a few V2.0 [benchmark tests](https://github.com/chef/automate/blob/master/components/authz-service/engine/opa/opa_internal_test.go). A [single V2.1 benchmark](https://github.com/chef/automate/blob/master/components/authz-service/engine/opa/opa_internal_test.go#L303) was added to help debug terrible projects performance and was very helpful. Let's update all of the benchmarks to be for 2.1 since we've tested 1.0 and 2.0 in production at this point.

## Done Criteria

* [ ] Update all of the above benchmarks to run against 2.1 and add benchmarks for any other performance case we are concerned about (large number of teams, policies, etc) so we can feel confident what the limitations of AuthZ are when debugging customer issues and making recommendations.
* [ ] Have a plan for how we can track the benchmark performance over time and correlate that to changes in Automate

**Comment by sdelano** [comment]
Sprint planning notes:
- edge cases to test
  - 300 projects at least
  - lots of projects / subjects / policies
  - number of roles vs. action lists
  - introspection-related calls
- ideas
  - testing on a system that matches our recommended requirements for automate
  - how do we track the benchmark performance over time and relate it to changes?
  -

**Comment by msorens** [comment]
Responding to "how do we track the benchmark performance over time and relate it to changes?" 

The most promising tool looks like `benchplot`:

https://godoc.org/github.com/aclements/go-misc/benchplot
_"Command benchplot plots the results of benchmarks over time."_

That's an enticing headline... but no examples or docs at all--just source code to figure out what to do with it.

As a backup, this one does plots of benchmark output also, so could be used in a more manual fashion:

https://github.com/cep21/benchdraw
_"A CLI to turn Go's benchmark output into pictures"_

**Comment by bcmdarroch** [comment]
Looks like [applications-service](https://github.com/chef/automate/blob/master/benchmarks/README.md#comparing-benchmarks-benchstat) is using [benchstat](https://godoc.org/golang.org/x/perf/cmd/benchstat) to compare performance on master vs. an incoming pull request. It's not automated as part of the CI yet though

**Comment by bcmdarroch** [comment]
found a few more better documented benchmark charting options:

- [go-chart](https://github.com/wcharczuk/go-chart)
- [plot](https://github.com/gonum/plot) (with some [example plots](https://github.com/gonum/plot/wiki/Example-plots))

**Comment by bcmdarroch** [comment]
created [this issue for tracking OPA performance](https://github.com/chef/automate/issues/2519)
