### ISSUE TITLE
IAMv2 GA Documentation

### ISSUE THREAD

**Issue by susanev** [chef/automate#1845]
## Overview
- be specific about what is for iamv1, in page names and content; ~does not include ldap, or saml~ minimal changes to the ldap and saml pages
- remove beta label from iam v2 section
- move current beta changes to authorization section

**Comment by sdelano** [comment]
Question for @mjingle and @kagarmoe - do users have access to older versions of the documentation? In the scenario above, if a user hasn't upgraded, how would they get access to the documentation that corresponds to their particular version?

**Comment by susanev** [comment]
no, @kagarmoe wrote up an issue to address that https://github.com/chef/release-engineering/issues/896
