### ISSUE TITLE
[EAS] Reconfigure page to make sidebar static

### ISSUE THREAD

**Issue by Shadae** [chef/automate#185]
Jira link: https://chefio.atlassian.net/secure/RapidBoard.jspa?rapidView=314&projectKey=A2&modal=detail&selectedIssue=A2-768

Acceptance criteria:

The right hand side bar is persistent. it is visible when you load the apps tab and cannot be hidden

when I first load the applications tab, the first row on the left side table is selected and the right sidebar is populated with the right data for that row

persist the state of which row on the left is selected in the URL

persist the state of which filters are active on the right sidebar in the URL

persist the state of the pages on the right sidebar in the URL

when I select a new row on the left table, it resets the state of the sidebar things

**Comment by susanev** [comment]
fixed in #367
