### ISSUE TITLE
scan job with a recurrence schedule is rejected (400)

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#1864]
## Describe the bug
Creating a scan job with a recurrence schedule - in other words, setting it to start in the future, setting it up to repeat - gets rejected by the api
`{"error":"Invalid job recurrence rule wrong format","message":"Invalid job recurrence rule wrong format","code":3,"details":[]}`

## To Reproduce
- create a scan job with a recurrence schedule
- watch it not work (open dev tools to see error)

## Expected behavior
Expect scan job to be created

## Screenshots
<img width="687" alt="Screen Shot 2019-10-15 at 09 33 37" src="https://user-images.githubusercontent.com/10341541/66846338-ede12480-ef2e-11e9-81e2-1dc748bfa659.png">
<img width="425" alt="Screen Shot 2019-10-15 at 09 33 45" src="https://user-images.githubusercontent.com/10341541/66846340-ede12480-ef2e-11e9-837e-8a4635665232.png">

## Versions (please complete the following information):
- Automate Build Number [e.g. 20190701222009]

**Comment by vjeffrey** [comment]
the `:` should be an `=` sign: https://github.com/chef/automate/blob/master/components/compliance-service/api/tests/50_scheduler_spec.rb#L104

**Comment by scottopherson** [comment]
Not sure what's up. Been using https://github.com/jakubroztocil/rrule which doesn't seem to have any major changes recently.

**Comment by vjeffrey** [comment]
`=` still works. something on the front end seems to have started using `:` instead of `=`

**Comment by vjeffrey** [comment]
maybe we somehow started using rrule set instead of rrule? https://github.com/jakubroztocil/rrule

**Comment by vjeffrey** [comment]
@lancewf has graciously offered to look into this bug!

**Comment by lancewf** [comment]
I am going to test moving back to rrule version 2.4.1.

**Comment by scottopherson** [comment]
Ah, didn't notice we upgraded RRule along with the Angular upgrade. The two libraries in-use both say they implement iCalendar RFC and are based on python-dateutil. Seems like they would stay the same.

https://github.com/teambition/rrule-go#rrulerrule
https://github.com/jakubroztocil/rrule#usage

 I wonder why there's now a change 🤔

**Comment by scottopherson** [comment]
2.4.1 downgrade seems the way to go though. Readme in that version has `DTSTART=` instead of `DTSTART:`

**Comment by scottopherson** [comment]
Apparently it was to be more RFC-compliant? https://github.com/jakubroztocil/rrule/pull/269

**Comment by lancewf** [comment]
Downgrading fixed the problem. I am creating a PR now.

**Comment by vjeffrey** [comment]
THANK YOU!!
