### ISSUE TITLE
Workflow Link in Side Nav does not work in Automate

### ISSUE THREAD

**Issue by jonong1972** [chef/automate#1869]
## Describe the bug
When Workflow is turned on and the link appears in the side nav, clicking on the link takes the user to the Dashboard. 

In order to use the link, a user has to Shift+Click to open the window.

### Acceptance
1. goto `https://a2-workflow-local-inplace-upgrade-acceptance.cd.chef.co/infrastructure/client-runs`
2. Click on 'Workflow' in the side nav
3. System goes to Dashboard

### Local Dev
- in the studio you can use start_workflow_service
- if you've already started all services, you can chef-automate config patch with this file:

    ```
    [deployment.v1.svc]
    products = ["automate", "workflow"]
    ```

## Expected behavior
When clicking on 'Workflow' it should open a new tab with the workflow app.

## More Context
I did notice that if I hold down Shift+Click on Workflow it does open up the workflow page, but in a new window.

## Versions (please complete the following information):
- OS: Mac OSX
- Browser Chrome/Firefox
- Automate Build Number 20191009235207

**Comment by lancewf** [comment]
That could be the problem.

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
