### ISSUE TITLE
Auto-generate teams when project is created

### ISSUE THREAD

**Issue by susanev** [chef/automate#1882]
## Overview
When a project is created, automatically create `<project-name>-project-owner`, `<project-name>-editor`, and `<project-name>-viewer` local teams. The teams should leverage the associated policies, and automatically be moved into the associated project.

## Design Details

- In the UI.. add checkbox below policies checkbox, checked by default.
- Users should be able to uncheck the box if they don't want to create the teams
- Also add strong tags around _teams_ and _policies_
- If team creation fails for some reason, project creation should still succeed, with an error message about the failed team creation (this is a different UX than if the policies aren't created  bc that's a transaction in a shared db, and that's ok)

### Screenshot
![create-project-modal](https://user-images.githubusercontent.com/5489125/78412912-11c22080-75ca-11ea-8cf6-eecb7ca30984.png)

**Comment by blakestier** [comment]
Outstanding question: do we want the project creation to succeed even when team/policy creation does not?

**Comment by susanev** [comment]
yes
