### ISSUE TITLE
Expose service status via HTTP

### ISSUE THREAD

**Issue by moutons** [chef/automate#1883]
## User Story

As an Automate user, I want to be able to quickly check the health of Automate without signing into the node and running `chef-automate status`

As an Automate admin, I want to be able to easily monitor the health of Automate (and component services) without signing into the node and running `chef-automate status`

## Definition of Done

This work is considered Done when application health is exposed via a status endpoint similar to Chef Infra Server's `/_status`

## Demo Script / Repro Steps

n/a

**Comment by moutons** [comment]
This would enable https://github.com/chef/automate/issues/1407

**Comment by yzl** [comment]
This involves:

1. adding a handler to the gateway that takes in a response from the deployment service's `status` GRPC API and returns the actual status (and not the config)
2. adding an (http) API to the gateway for `/status` that uses the handler
3. adding a policy for authenticated access to the `/status` HTTP endpoint
4. adding docs for generating a token to be used when monitoring an Automate installation via the `/status` HTTP endpoint.
