### ISSUE TITLE
remove v2beta API paths

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#1887]
## User Story

As an Automate User, I should no longer be using `v2beta` paths.

## Definition of Done
- [ ] remove the `v2beta` IAM API paths

**Comment by susanev** [comment]
deprecate, then remove. figure out if we cant deprecate.

**Comment by susanev** [comment]
we do not believe that anyone is using these. we checked with folks who we thought might be and they said they are not. lets remove them.
