### ISSUE TITLE
refactor authz-service to use v2 exclusively + remove mention of v1

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#1888]
## User Story

As an Automate Developer, I will use this work when I want to work on authz-service. Removing v1 cruft will simplify authz-service's architecture and make it more maintainable.

## Definition of Done
- [ ] authz-service no longer has separate IAM versions
- [ ] v1 code is removed

**Comment by blakestier** [comment]
closing in favor of https://github.com/chef/automate/issues/2739
