### ISSUE TITLE
remove IAM versioning from teams and tokens

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#1889]
## User Story

As an Automate Developer, I will use this work when I want to work on teams-service or authn-service. Removing v1 cruft will simplify both service's architecture and make them more maintainable.

## Definition of Done
- [ ] teams-service no longer has separate v1 and v2 servers
- [ ] mentions of v1 and v2 are removed from both services

**Comment by susanev** [comment]
this will be solved in #2729
