### ISSUE TITLE
remove IAM version from UI

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#1891]
## User Story

As an Automate Developer, I will use this work when I want to work in the Automate UI. Removing v1 cruft will simplify auth's UI code and make it more maintainable.

## Definition of Done
- [ ] remove IAM version from the ngrx store and any dependent conditional rendering

## Demo Script / Repro Steps
- all auth pages should render IAM v2 UX designs by default

**Comment by bcmdarroch** [comment]
converted to sub-task of https://github.com/chef/automate/issues/1877

**Comment by bcmdarroch** [comment]
my b, this is for GA 😅

**Comment by susanev** [comment]
will be fixed in #2722
