### ISSUE TITLE
Upgrade to Hab 0.88.0+: hab-sup API changes

### ISSUE THREAD

**Issue by stevendanna** [chef/automate#1897]
During testing of the latest habitat, we identified a small API change:

https://github.com/habitat-sh/habitat/issues/6747

We need to investigate whether this is a blocker to upgrading hab and if so, fix it upstream.

**Comment by stevendanna** [comment]
Proposed fix: https://github.com/habitat-sh/habitat/pull/7087

From my understanding of this bug, this should be a relatively minor issue for the deployment-service and doesn't need to block the upgrade.  The issue only occurs between service-load time and the time of the first health check and only affects the /health endpoint specifically.

**Comment by sdelano** [comment]
Fixed by habitat-sh/habitat#7087
