### ISSUE TITLE
Upgrade to hab 0.90.6 or later

### ISSUE THREAD

**Issue by stevendanna** [chef/automate#1898]
To ensure we keep up with the latest hab bug fixes we want to upgrade Habitat.

While our Habitat version bump script is automated, testing discovered a number of potential blockers:

- https://github.com/chef/automate/issues/1896
- https://github.com/chef/automate/issues/1897

**Comment by susanev** [comment]
can we close this?

**Comment by stevendanna** [comment]
We can! Thanks.

We've fallen a bit behind again, but I think we can track that with the auto-generated PRs rather than a ticket, at least until we have a known set of issues to fix: https://github.com/chef/automate/pull/2747
