### ISSUE TITLE
"flip the switch" for apps tab in automate

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#1902]
## User Story 
This issue covers the work for flipping the switch on the backend feature flag to default to on as well as removing the frontend feature flag. This should be done after https://github.com/habitat-sh/habitat/issues/7017 is complete.

## Definition of Done
backend flag for apps tab data defaults to "on"
feature flag for apps tab is removed/apps tab is always viewable

**Comment by susanev** [comment]
any way we can get at a minimum the overlay from the event-feed onto the applications page when a user does not have view permissions, or ideally hide that page entirely when a user does not have permission to view it.

this is the current experience when a user does not have permission to view that page.
![sad](https://user-images.githubusercontent.com/5489125/67112594-714b8180-f18c-11e9-9c81-8c9c97d7a56a.png)

**Comment by kmacgugan** [comment]
Technical details that I am leaving here for my future reference: 

Currently we have three config settings that the backend flag toggles. We should remove these config settings as they won't be needed and strip the code of any logic that refers to them. These are the config settings: 

  [applications.v1]
    [applications.v1.sys]
      [applications.v1.sys.service]
        enable_nats_feature = true

[event_service]
  [event_service.v1]
    [event_service.v1.sys]
      [event_service.v1.sys.service]
        enable_nats_feature = true
      [event_service.v1.sys.log]

[event_gateway]
  [event_gateway.v1]
    [event_gateway.v1.sys]
      [event_gateway.v1.sys.service]
        enable_nats_feature = true

**Comment by kmacgugan** [comment]
Another detail, add port checks to preflight check for automate: 
Port 4222 must be available and accessible to external systems
Ports 10140, 10147, and 10148 must be available and accessible to internal Automate services.
