### ISSUE TITLE
Docs: decide on meta information for the documentation page

### ISSUE THREAD

**Issue by phiggins** [chef/automate#1917]
Followup to #1412. 

Several pieces of metadata for the API docs page have good enough placeholders but we should decide on the proper things to use. This includes but is not limited to:

* Window title (ie, the text that appears in the browser title / tab bar for the page)
* Page title (ie, the first line of text on the page) 
* The logo to use
* The proper "homepage" URL to refer back to the Automate project with.

Some of this is contained in the metadata static file:
https://github.com/chef/automate/blob/master/components/automate-chef-io/data/docs/api-static/00-meta.swagger.json

The window title is defined in the html file that loads redoc:
https://github.com/chef/automate/blob/master/components/automate-chef-io/layouts/_default/data-api.html

**Comment by susanev** [comment]
- for window title, i think `Chef Automate API Documentation` would be cool
- for the logo, it would be cool to do a modified version of the Chef Automate logo with the additional text of `API Documentation` similar to what is done on our release dashboards, or what was done for the beta version of automate 2

**Comment by susanev** [comment]
oh also..
- the logo desperately needs some white space around it
- and ive got feelings about interacting with the logo sending them to a totally different website, the general ux pattern is for it to send you to the landing page which i think should be `/docs/api/`

**Comment by vjeffrey** [comment]
https://github.com/chef/automate/pull/2246/files updates the window title and page title, but nothing else. 
can someone from ux create the logo with the "API Documentation" part added?

**Comment by phiggins** [comment]
Wanted to note that the current logo works in Chrome but not in Firefox.

Chrome:
<img width="395" alt="Screen Shot 2019-11-18 at 9 42 47 AM" src="https://user-images.githubusercontent.com/22962/69076208-d8f12880-09e7-11ea-8771-2115e79b9513.png">

Firefox:
![Screen Shot 2019-11-18 at 9 43 04 AM](https://user-images.githubusercontent.com/22962/69076215-dd1d4600-09e7-11ea-9843-b7ef738101ae.png)

**Comment by phiggins** [comment]
@susanev I don't know if getting the current logo to work is worth the effort if we're looking to replace it, but I wanted to point out that there might be some issue with file formats going on with redoc and logos.

**Comment by phiggins** [comment]
I got curious about the logo thing again and poked at it a bit, apparently using svgs in firefox is a known issue (https://github.com/Redocly/redoc/issues/1048) but I did not understand the proposed solution.

**Comment by susanev** [comment]
are you seeing the firefox thing locally? i was gonna try and fix it but then realized that the logo is showing for me locally. so i think i just happened to fix this when i fixed the white space around the logo in #3422

**Comment by susanev** [comment]
yall think we can close this? or do we still want to do some more things for this?
