### ISSUE TITLE
Docs: writeup the documentation process

### ISSUE THREAD

**Issue by phiggins** [chef/automate#1918]
Followup to #1412. 

In order to make writing API docs a more streamlined process and help other devs be more self sufficient, we should document our current process. The major points this should hit:

* How to build and view the docs locally, what the tools are that we're using, etc.
* The format that documentation should take and the proper place for things to live.
* Any gotchas or common stumbling blocks that can be avoided.

**Comment by vjeffrey** [comment]
https://github.com/chef/automate/pull/2000

**Comment by vjeffrey** [comment]
kimberly is doing final edits on this now
