### ISSUE TITLE
Add data to compliance report node detail + ui consistency

### ISSUE THREAD

**Issue by susanev** [chef/automate#1922]
## Overview
Add _Chef Organization_, _Chef Server_, _Chef Roles_, _Chef Tags_, and _Projects_ to compliance report node detail pages and some ui consistency work.

#### Data Changes
- Add _Chef Organization_, _Chef Server_, _Chef Roles_, _Chef Tags_, and _Projects_
- For _Chef Tags_, _Chef Roles_, and _Projects_ if a node has more than 1, then display the count instead of the names of those things (e.g., 2 Chef tags, or 3 projects, or 17 Chef roles)
- if a compliance report node does not have an FQDN, IP address, chef org, chef server, chef roles, chef tags then those pieces of data along with their labels should be hidden
- _Projects_ should only be displayed if the iam version is 2.1

#### Data Structure
- sections, _Report Information_, _Node Information_, and _Metadata_
- use `text-transform` for the uppercase headings

##### Run Information
- _Last Scan_

##### Node Information
- _FQDN_
- _Insepc Version_
- _IP Address_
- _Node ID_
- _Platform_

##### Metadata
- _Chef Organization_
- _Chef Roles_
- _Chef Server_
- _Chef Tags_
- _Cookbook Deprecations_
- _Enviornment_
- _Profiles_
- _Projects_

#### Status Content
- left align the content
- change content to read _Scan failed <datetime>: <error>_ or _Scan succeeded <datatime>. ... removing the rest of the filler words.

#### Accordion Behaviour
- status message should be transformed into an accordion, interacting anywhere on the status message should toggle the accordions state
- default when visiting a compliance report detail page should be that the accordion is open
- when the accordion is open display _View less -_ on the right, when closed display _View more +_
- should be responsive, if there is room for 3 columns display then, otherwise display 2 columns, otherwise, display 1 column
- if the screen size dictates a single column, the accordion should be open and the closing behvaiour should be hidden

### Styles
- column headings `font-size: 15px; text-transform: uppercase;`
- data labels `font-weight: 600;`
- work with @susanev on space between data/labels and columns
    - when columns wrap down, they should get at least 10px of top margin added
- add border around the entire accordion that uses the status color

#### 3-col
![compliance-node-3-cols](https://user-images.githubusercontent.com/5489125/68091553-14132980-fe36-11e9-870d-678ff1a133de.png)

#### 2-col
![compliance-node-2-cols](https://user-images.githubusercontent.com/5489125/68091556-183f4700-fe36-11e9-8e47-44c645279d1e.png)

#### 1-col
![compliance-node-1-col](https://user-images.githubusercontent.com/5489125/68091558-1bd2ce00-fe36-11e9-9560-89f891506298.png)

**Comment by vjeffrey** [comment]
took a quick look at the api. the endpoint that returns the information for that summary section is `api/v0/compliance/reporting/stats/summary`, which returns
```
{"controls_summary":null,"node_summary":null,"report_summary":{"stats":{"nodes":"15683","platforms":1,"environments":1,"profiles":3,"nodes_cnt":15683},"status":"failed","duration":0,"start_date":""}}
```

so we'll need backend work to add all the requested fields (Chef Organization, Chef Server, Chef Role, Chef Tags, and Projects) to that response
