### ISSUE TITLE
Create HOWTO guide for documenting *.proto files

### ISSUE THREAD

**Issue by schisamo** [chef/automate#1933]
## User Story

As an Automate Engineer, I want a HOWTO guide which discusses how I should document my `*.proto` files in order for my API resources to be automatically documented.

**Comment by vjeffrey** [comment]
related to https://github.com/chef/automate/issues/1918

**Comment by vjeffrey** [comment]
this is complete, correct?
can we close it?

**Comment by phiggins** [comment]
This is being done in #2000 but is not done yet.

**Comment by vjeffrey** [comment]
oh i forgot that hadn't merged yet, thank you!

**Comment by susanev** [comment]
this is done, closing.
