### ISSUE TITLE
Cannot view newly created project details when unassigned selected in filter

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#1937]
## Describe the bug 
When I create a project in the UI, I see the project appear in the project list. If `unassigned` is selected in the global project filter and I select the new project to view its details, I get stuck in this infinite loading state:

![Screen Shot 2019-10-21 at 6.01.18 PM.png](https://images.zenhubusercontent.com/5d236338fa967b04b3b34e1d/aec810e0-3172-48fb-8f97-5553e3f8b1c6)

## To Reproduce
- Make sure you're on IAM v2.1
- navigate to https://a2-dev.test/settings/projects
- select `unassigned` in the global projects filter & apply changes
- create a project `abc`
- select project `abc` when it appears in the project list
- you should see the screen above. you must navigate away from the page to reset the project filter

## Expected behavior
- if unassigned selected, new project should not show up in project list. need to refetch projects after creation
- open-ended TODO: think more about refreshing projects in session storage

## Versions
- OS: macOS
- Browser: chrome
- Automate Build Number: 20191021221120

**Comment by susanev** [comment]
unable to repro this, so closing
