### ISSUE TITLE
Attributes are not appearing on the Client Run page.

### ISSUE THREAD

**Issue by brywilliamsCF** [chef/automate#1955]
## Describe the bug
When view the client run history of a node the "Attributes" tab appears blank.  It does display the attribute type category buttons with correct counts on them, but clicking the buttons has no affect.  The attribute search bar also always returns "No results".

## To Reproduce
Under the Infrastructure tab, click on any node to bring up its client run history.  Click the Attributes tab under its run history.

## Expected behavior
Automate would previously list all of the attributes for a node and run.

## Screenshots
![image](https://user-images.githubusercontent.com/44782158/67422018-42bc1500-f597-11e9-90fc-4a6a923af13a.png)

## Versions (please complete the following information):
- OS: OSX
- Browser: Chrome
- Automate Build Number: 20191015190829

**Comment by vjeffrey** [comment]
i see the list is being returned by the api, which makes me think this is probably a ui bug. still investigating!

**Comment by SEAjamieD** [comment]
got them to come back - still investigating deeper.  Should have a fix in soon.

**Comment by vjeffrey** [comment]
yay! 
<img width="974" alt="Screen Shot 2019-10-23 at 16 39 16" src="https://user-images.githubusercontent.com/10341541/67439525-b3712a80-f5b3-11e9-8017-bc15792036c1.png">
