### ISSUE TITLE
Automate continues to mark services disconnected after receiving health-check 

### ISSUE THREAD

**Issue by ericcalabretta** [chef/automate#2003]
@kmacgugan 
## Describe the bug
Chef Automate continues to mark services disconnected after receiving an updated health-check. When a health-check is received the services should no longer be marked disconnected and instead should be marked with the appropriate health-check status. 

## To Reproduce
Enable application reporting
block port 4222 in AWS security group till Automate marks the service as disconnected
unblock port 4222
You can see a recent health-check but the service is still marked disconnected. 

## Expected behavior
Service would not longer be marked disconnected

## Screenshots
<img width="1191" alt="screenshot" src="https://user-images.githubusercontent.com/22911544/67605956-979d8e00-f745-11e9-8a8d-f5350611e483.png">

## Versions (please complete the following information):
Automate 20191015190829
Habitat 0.88

**Comment by vjeffrey** [comment]
having trouble with repro-ing the issue, but lots of customer evidence it's a real bug. 
small? t shirt size (mostly unknown around the investigation)

**Comment by ericcalabretta** [comment]
@vjeffrey I reproduced it in my lab, Would any other details about the lab setup help here?

**Comment by vjeffrey** [comment]
sure! @kmacgugan will be working on this - she mentioned the times she tried to repro she was trying to use the fake data. whatever info you can't share publicly pls feel free to send it to her in a dm!
