### ISSUE TITLE
Reset projects on ingested resources on IAM reset-to-v1

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#2006]
## Describe the bug
We are not resetting projects on ingested resources after `chef-automate iam reset-to-v1` runs. While the nodes with projects appear as expected while on v1, they disappear if the system is again upgraded to v2.1.

## To Reproduce
- load some nodes into your environment (local, acceptance, dev)
- `chef-automate iam upgrade-to-v2 --beta2.1`
- create a project
- add some ingest rules that will associate some of your nodes with the new project
- update projects from `/settings/projects`
- ensure the nodes were added to the project correctly
- as an admin who can see all nodes, verify that the list of nodes on Infrastructure and Compliance includes the new project's nodes
- `chef-automate iam reset-to-v1`
- as an admin, verify that the list of nodes on Infrastructure and Compliance doesn't change and you can still the project's nodes
- `chef-automate iam upgrade-to-v2 --beta2.1`
- as an admin, since only the`(unassigned)` project is available, you should not see the project's nodes
- to see them, create any new project, add some random rule, then update projects
- now that you can select all projects, you should be able to see the original project's nodes again

## Expected behavior
Reseting to IAM v1 should reset all resources and delete all v2.1 related data. Each time the customer upgrades to IAM v2.1, it should be like they've upgraded for the first time.

## Screenshots
on v2.1 (first time), the Compliance node `debian(2)-zeta...` with the environment `DevSec Prod Zeta` exists:
<img width="1431" alt="Screen Shot 2019-10-25 at 4 04 06 PM" src="https://user-images.githubusercontent.com/21015366/67610165-d3d0ee80-f745-11e9-8797-0a6c109c9cc9.png">

after resetting to v1 and upgrading to v2.1 again, it's gone! 😮 
<img width="1423" alt="Screen Shot 2019-10-25 at 4 08 40 PM" src="https://user-images.githubusercontent.com/21015366/67610173-db909300-f745-11e9-809a-d4922bd3d51d.png">

on v2.1 (first time), Infra node `example-node.lxc`with the environment `DevSec Prod Zeta` exists:
<img width="1429" alt="Screen Shot 2019-10-25 at 4 04 16 PM" src="https://user-images.githubusercontent.com/21015366/67610175-de8b8380-f745-11e9-93b5-8d9199f4962e.png">

after resetting to v1 and upgrading to v2.1 again, it's gone! 😮 
<img width="1423" alt="Screen Shot 2019-10-25 at 4 07 53 PM" src="https://user-images.githubusercontent.com/21015366/67610180-e1867400-f745-11e9-82ec-6e3610c24b52.png">

## Versions (please complete the following information):
- OS: [e.g. rhel6]
- Automate Build Number [e.g. 20190701222009]

**Comment by vjeffrey** [comment]
> Reseting to IAM v1 should reset all resources and delete all v2.1 related data. Each time the customer upgrades to IAM v2.1, it should be like they've upgraded for the first time

so in other words..the tl;dr is that when a user resets to IAMv1, we should clear all projects data from nodes. correct?

**Comment by susanev** [comment]
Yes

**Comment by vjeffrey** [comment]
- when the command is run, trigger update on elasticsearch and postgres to clear all projects data. projects data on client runs is node state only, on compliance it is historical. postgres should be pretty quick. for es, it may be a longer process

**Comment by vjeffrey** [comment]
* not handling this for any archived data/migration paths

**Comment by vjeffrey** [comment]
small tshirt size. mostly testing. if all projects/rules are deleted, the project update process will automagically reset all the projects data.

**Comment by lancewf** [comment]
During downgrade of IAMv2.1 to IAMv1.0 we need to kick off a project update where all the project rules are removed. This will clear all the project tags on the compliance reports, client runs nodes, ..

**Comment by susanev** [comment]
not part of our iam v2 ga scope, because when we force people to iamv2 they will not be able to reset to iam v1.
