### ISSUE TITLE
cookbook version # blank when no resources from that cookbook executed 

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#2014]
## User Story
original issue: https://chefio.atlassian.net/secure/RapidBoard.jspa?rapidView=278&modal=detail&selectedIssue=A2-273

start with reviewing https://github.com/chef/chef/pull/8893

the work linked above modifies the run information to included cookbook details. we need to see what else is needed on the automate side of things to ensure this information is returned to the user, and then do that!

## Definition of Done
cookbook version numbers included in log from automate even when no resources from cookbook executed

**Comment by vjeffrey** [comment]
@vsingh-msys are you planning on modifying the automate client runs code as well?
just trying to see if we should bring this onto our board or not

**Comment by vsingh-msys** [comment]
Sure will take it up, Thanks!

Earlier I tried on the Automate side but can't help it. Now I have a bit understanding of request flow of A2 :smiley:

**Comment by vjeffrey** [comment]
awesome, thank you! feel free to drop any questions you have in #superteam slack channel or dm me on slack (@vj)

**Comment by vsingh-msys** [comment]
Hi @vj
I did a required analysis of this issue seems that we don't need any attribute i.e. `cookbooks` from the chef-client run side. we have already `run.VersionedCookbooks` ref https://github.com/chef/automate/blob/2711512d2baaef84bb967710addf098aca6bfa5a/components/config-mgmt-service/grpcserver/response_conversion.go#L16 
in order to fetch versioned cookbooks.

Following way we can solve this issue:

1. Modify existing cookbooks(Array of string) attribute to Array of {name, version}

example:
```
"cookbooks": [
    "starter"
  ],
```
TO
```
"cookbooks": [
    {
      "name": "starter",
      "version": "1.0.13"
    }
  ]
```

2. Add new `versioned_cookbooks` attribute in the response Run message.
 
So, for sol 1. we require a couple of refactoring but I think it's good. 

Sample API after code changes for sol 2:

```
=> chef-automate dev grpcurl config-mgmt-service chef.automate.domain.cfgmgmt.service.CfgMgmt.GetNodeRun -- -d '{"node_id": "2e2a4842-9c61-466d-b1ca-222717b669c1", "run_id":"123cbd18-e244-4954-9bc3-6b4c88485bb0"}'
{
  "id": "123cbd18-e244-4954-9bc3-6b4c88485bb0",
  "nodeId": "2e2a4842-9c61-466d-b1ca-222717b669c1",
  "nodeName": "node1.test",
  "organization": "4thcoffee",
  "startTime": "2019-11-25T17:20:06Z",
  "endTime": "2019-11-25T17:20:15Z",
  "source": "chef_client",
  "status": "success",
  "chefVersion": "15.5.17",
  "uptimeSeconds": 3276,
  "environment": "_default",
  "fqdn": "node1.test",
  "sourceFqdn": "chef-server.test",
  "ipaddress": "10.0.2.15",
  "runList": [
    "recipe[starter]"
  ],
  "error": {
    
  },
  "recipes": [
    "starter",
    "starter::default"
  ],
  "cookbooks": [
    "starter"
  ],
  "platform": "ubuntu 16.04",
  "platformFamily": "debian",
  "platformVersion": "16.04",
  "expandedRunList": {
    "id": "_default",
    "runList": [
      {
        "type": "recipe",
        "name": "starter"
      }
    ]
  },
  "versionedCookbooks": [
    {
      "name": "starter",
      "version": "1.0.13"
    }
  ]
}
```
Please let me know your thoughts on this?

Thanks

**Comment by vjeffrey** [comment]
will modifying the cookbooks (option 1)  field require an elasticsearch migration? 
it sounds like it to me.
i would prefer option 2 if it means we can skip doing a migration

**Comment by vsingh-msys** [comment]
I think we don't require any migration changes, As I am only concern with the changing response attribute here https://github.com/chef/automate/blob/2711512d2baaef84bb967710addf098aca6bfa5a/components/config-mgmt-service/grpcserver/response_conversion.go#L42

**Comment by vjeffrey** [comment]
we can't break the apis, so if we need a field response to change at the api level that will need to be a new field

**Comment by vsingh-msys** [comment]
okay got it thanks.

**Comment by kmacgugan** [comment]
The concern I have around solution 1 is that we use cookbooks for search bar autocomplete (suggestions), I believe this is why we have separate fields for cookbooks and versionedCookbooks. It is simpler to ensure the version is included in versioned_cookbooks.
