### ISSUE TITLE
Run History list shows run time for all runs as "a few seconds ago". 

### ISSUE THREAD

**Issue by brywilliamsCF** [chef/automate#2026]
## Describe the bug
When viewing the run history for a node all of the runs say "a few seconds ago" below their run time.

## To Reproduce
- Go to the Infrastructure tab.
- Click on any node to view its client run details.
- Click the Run History button.

## Expected behavior
Previously showed the duration of each client run.

## Screenshots
![image](https://user-images.githubusercontent.com/44782158/67771388-336d1980-fa26-11e9-820a-eb70c46310fb.png)

## Versions (please complete the following information):
- OS: OSX
- Browser: Chrome
- Automate Version: 20191024135531

## Additional context
Appeared between versions 20191001203421 and 20191024135531.

**Comment by susanev** [comment]
fixed by #2036
