### ISSUE TITLE
Make tooling around sharing tls certs 

### ISSUE THREAD

**Issue by kmacgugan** [chef/automate#2030]
Currently if a user wants to retrieve the frontend tls certificate to set up encrypted communication with automate they have to look into the configuration and copy paste the certificate out of there. 
This process needs some ergonomic tooling around cert setup to make it easier for users. On the automate side: 
-Add a CLI command to show the certificate (or save it to a file as an option)

-Create a tool to pull the certificate from automate and store it in a way that can be easily utilized by the supervisor.

**Comment by ericcalabretta** [comment]
@kmacgugan Would this require nodes be in the same supervisor ring as Automate to pickup the certificate?

**Comment by vjeffrey** [comment]
https://github.com/chef/automate/pull/2504
