### ISSUE TITLE
Add health checks for builder services

### ISSUE THREAD

**Issue by jaym** [chef/automate#2072]

**Comment by jaym** [comment]
This is probably optional. Builder doesn't have any healthcheck hooks from what i can tell

**Comment by sdelano** [comment]
Sprint Planning Notes:
- there are currently no health check in the bldr services
- the only way to know they're not working is that the services *could* be cycling and have low uptimes
- if there's a status endpoint for the services, we should call it
- memcached should also have a status endpoint
- we'll have a converstaion w/ the bldr team on getting a status endpoint into the bldr-api if it doesn't exist

**Comment by stevendanna** [comment]
- [ ] automate-minio
- [ ] automate-builder-api-proxy
- [ ] automate-builder-api
- [ ] automate-memcached
