### ISSUE TITLE
Introspection does not check project permissions

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#2095]
## User Story

As an Automate user, I will use this work when I want to use the UI without running into unexpected 403 errors.

We've introduced introspection as a way for our UI to pre-calculate user permissions and hide buttons/interactable elements that they aren't allowed to use.

Now that projects are always enabled on `IAM v2`, they need to be included in the introspection calculation. 

## Definition of Done
When a user logs into Automate, they should only see buttons they have access to, even when they have different levels of permissions on projects.

So when a user has permission to create/update/delete teams and assign them to project `boo`, and they only have permission to view teams in project `woo`.
As a specific example, on the team list page, this user should see a list of teams in projects `boo` and `woo`. However, the control menu should only display for teams in project `boo`

## Demo Script / Repro Steps
- create the user `ghost`
- create a policy:
```
{
  "policy": {
    "name": "test2",
    "id": "dottie-create-update-policy",
    "type": "CUSTOM",
    "members": [
      "user:local:dottie"
    ],
    "statements": [
      {
        "effect": "ALLOW",
        "actions": [
          "iam:teams:*",
          "iam:projects:assign"
        ],
        "role": "",
        "resources": [
          "*"
        ],
        "projects": [
          "boo"
        ]
      },
      {
        "effect": "ALLOW",
        "actions": [
          "iam:teams:list",
          "iam:teams:get"
        ],
        "role": "",
        "resources": [
          "*"
        ],
        "projects": [
          "woo"
        ]
      }
    ],
    "projects": [
      "boo",
      "woo"
    ]
  }
}

curl -k -X POST -d '{"name":"test2", "id":"ghost-create-update-policy", "members":["user:local:ghost"], "projects": ["boo", "woo"],  "statements":[{"effect":"ALLOW", "actions":["iam:teams:*", "iam:projects:assign"], "projects":["boo"]}, {"effect":"ALLOW", "actions":["iam:teams:list", "iam:teams:get"], "projects":["woo"]}]}' -H "api-token: $TOK" $TARGET_HOST/apis/iam/v2beta/policies | jq
```
- navigate around the teams pages. any elements that should be hidden by `app-authorized`, i.e. the control menus on the list page, should respect differences in project permissions

## Technical Notes
-  this part of the rego needs to be updated to include project matches: https://github.com/chef/automate/blob/692f5a5ee87b825f6b7525f05741a5ef7d114057/components/authz-service/engine/opa/policy/introspection_v2.rego#L29
- we should pay attention to how this affects introspection performance

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
