### ISSUE TITLE
NGRX Store: Delete Items Before Details Page Load (tokens, users, teams)

### ISSUE THREAD

**Issue by sdelano** [chef/automate#2103]
The current behavior of our UI (specifically on the Projects pages) is that we load the entire contents of all the objects via the list APIs. Those objects are then stored in NGRX. When we visit the details page for one of these projects, the following happens:

- we render the details page with the already-loaded data from NGRX
- we make an HTTP request to fetch the data from the API
- re re-render parts of the details page once that HTTP request is successful

This render->fetch->rerender scenario results in the page flickering. Because of other slowness issues (#2105) this can cause a very substantial delay for the user.

The proposed solution, one that we've used in other parts of the UI, is to delete the data from the NGRX store before loading the details page.

**This card covers these pages:**

- tokens
- users
- teams

@lancewf and @tylercloke confirmed that this is how other parts of the app work.

**Comment by lancewf** [comment]
That is correct. Before requesting data from the backend we first clear the data in NGRX store. This ensures that the user is not seeing stale data.
