### ISSUE TITLE
Expose the data-lifecycle purge interfaces in the gateway

### ISSUE THREAD

**Issue by ryancragun** [chef/automate#2108]
## User Story

As a Automate User, I will use this work when I want to configure data retention in Chef Automate.

UI have a story to expose the existing purge interfaces for the compliance, event-feed, and ingest services in the Automate UI, however the API's are not current exposed in the gateway.

Relates to #1208

## Definition of Done
A user with admin privileges can configure, show, and run the purge RPC's for event-feed, compliance, and ingest through the gateway

## Open Questions Before Development

- [x] What's the shape of the API look like at the gateway level? Do we have any prior art in Automate to go by? Let's propose something here before we get started
  
  _A_: Most services use `HTTP NOUN {NOUN..} {VERB}` when defining actions, eg:
  `GET /auth/tokens`
  `POST /auth/tokens`
  `PUT /iam/v2beta/roles`
  `POST /compliance/profiles/search`

  However, in the case of node and service group retention, a new top level resource called `retention` was used in a VERB NOUN fashion:

  `GET /retention/nodes/missing-nodes/config`
  `GET /retention/service_groups/delete_disconnected_services/config`

  As we're allowed to annotate any route with a policy resource and action, either strategy can be effective when introducing new behavior that we wish to scope to new policies. For example:

  The `GET /compliance/purge` and `GET /purge/compliance` could both be annotated with the `purge:compliance` resource and the `purge:compliance:show` action.

  As the `chef-automate` CLI and the majority of API endpoints use NOUN VERB, I (@ryancragun) suggest we use NOUN VERB:

  ```
  POST /compliance/purge // run
  PUT /compliance/purge // configure
  GET /compliance/purge // show
  ```
- [x] What is the authorization namespace for this? Do we want to reuse an existing namespace or create a new one? What should the new one be called?

  _A_: I (@ryancragun) think we should create a new top-level auth namespace called `purge`.

- [x] How do we get this new namespace and actions into the admin role? Will that apply to all admin roles that currently exist in IAM versions 1 and 2?

  _A_: The admin aka owner has access to everything in both V1 and V2. If we don't write a migration to add `purge` resource and actions into the existing default policy IDs, only admins would be able to access these routes by default.

- [x] Should we allow viewers to see purge settings?
  _A_: @susanev i think no, we should prolly hide the page entirely from non-admins

## Demo Script / Repro Steps

TBD

**Comment by sdelano** [comment]
@ryancragun let's have a conversation down here instead of continuing to edit the body of the issue back and forth.

From the body above, when you say:

```
POST /compliance/purge // run
PUT /compliance/purge // configure
GET /compliance/purge // show
```

Are you suggesting a `POST` to ` /compliance/purge` will start a purge of the data but a `PUT` there will change the config? That seems unacceptable to me. In a more traditional REST API (I'm not arguing that we've built anything close to that) a `POST` is used to create a resource while a PUT will update it. Using `PUT` and `POST` to the same URI while doing completely different things feels to me like it's leaving lots of room for improvement.

**Comment by ryancragun** [comment]
We can do `GET /compliance/purge/run` if that makes more sense. I think the `GET` and `PUT` for configure and show are okay.

**Comment by susanev** [comment]
update from the ux team, we are all aligned that..
- access to the data lifecycle page should be an admin action
- we don't want `compliance:*` to give permissions to the data lifecycle page

**Comment by susanev** [comment]
if we go with `retention` im wondering if we should rename the page to `Data Retention`
alternatively, could we use `data-lifecycle` instead?

**Comment by ryancragun** [comment]
Those seem completely fine. We could even make data lifecycle a subkey in retention:
`retention:datalifecycle:compliance`

**Comment by nfisher-chef** [comment]
Sorry if these questions are stupid, but I don't think I have enough background info. What is this? What are we trying to accomplish and why? How was this identified? Is this something that we've been meaning to do and haven't done? Or was this something discovered later?

**Comment by susanev** [comment]
ref in aha: https://chef.aha.io/epics/A2-E-131

**Comment by sdelano** [comment]
Notes from today's discussion on this topic:

We currently have four APIs that manage data lifecycle and retention configuration:

```
/retention/nodes/missing-nodes/config
/retention/nodes/missing-nodes-deletion
/beta/retention/service_groups/disconnected_services/config
/beta/retention/service_groups/delete_disconnected_services/config
```
The work here will, as scoped, would add another data lifecycle related configuration endpoint. This results in the propose UI changes in #1208 needing to make five API requests to fetch config and another 5 to set the config. We believe that this approach adds too much complexity to the frontend code and we have the opportunity to significantly reduce that complexity by consolidating the configuration APIs at the API gateway.

The new proposed API layout would look something like the following:

```
/data-lifecycle
  /config # GET, PUT
  /run # POST: run all the data lifecycle operations
  /nodes
    /config # GET, PUT
    /run # POST: run all the missing nodes lifecycle events
  /services
    /config # GET, PUT
    /run # POST: run all the disconnected services events
  /retention
    /config # GET, PUT
    /run # POST: run all the data retention / purge operations
```
The top-level `/config` and `/run` APIs consolidate the lower level APIs for the convenience of the UI and the users. The lower-level APIs could also be used individually.

We should have authorization actions that also map to these APIs.

/cc @kmacgugan @vjeffrey @susanev @ryancragun @apriofrost

**Comment by Shadae** [comment]
This would make the UI work more streamlined and understandable.

**Comment by ryancragun** [comment]
I certainly agree that aggregating data lifecycle into a unified API makes sense. I think the shape @sdelano described is a great starting place, but I propose we break it down slightly differently.

The data that we can either configure, show, and purge with the API is as follows:
* {Get,Configure} nodes missing
* {Get, Configure} nodes deleting
* {Get, Configure} missing nodes deleting
* {Get, Configure} disconnected service groups
* {Get, Configure} delete disconnected service groups
* Purge nodes
* Purge compliance scans and reports
* Purge event-feed

Eventually I reckon' we'll configure purge service groups as well.

Given that, I think we should break it down by type, eg:
```
/data-lifecycle
  /config # GET, PUT
  /run # POST: run all the lifecycle operations
  /infra
    /config # GET, PUT
    /run # POST: run all the nodes {missing,delete} lifecycle events and purges infra
  /service-groups
    /config # GET, PUT
    /run # POST: run all the disconnected services events
  /event-feed # GET, PUT
    /config # GET, PUT
    /run # POST: purges event feed
  /compliance
    /config # GET, PUT
    /run # POST: purges reports and scans
```

You'll notice that I replaced `nodes` with `infra`, which more closely aligns us with the both what data we're removing ("nodes" contains all chef infra server data, not just nodes) and with the updated the IAM v2 resources. I don't think we _have_ to change it to infra, but if we're starting this API from scratch we may as well make it align better.

**Comment by ryancragun** [comment]
One more thing to add. `/run` will really only run purging with the first pass of this API as immediately triggering the nodes missing, nodes deleted, service groups disconnected, etc isn't currently supported by the backend services that perform those actions.

**Comment by sdelano** [comment]
@ryancragun I like your proposed updates, it maps closer to both the UI mockup that we have and the language we use elsewhere, e.g. `infra` vs `nodes`.

@susanev one thing I noticed is that in #1208 we're not exposing the config for compliance retention? Is that an oversight or is there a reason that's missing.

**Comment by kmacgugan** [comment]
I am supportive of consolidating these data lifecycle related endpoints under a common root such as /data-lifecycle. I want to be careful to refer to the entities in the EAS dashboard that we are acting on as services, since the marking and deleting applies to the level of services and not service-groups (it is kind of confusing and we have probably crossed wires in places). 

Some additional questions to consider: 
Do we want to make a distinction between retention configurations that apply to individual data members vs whole indices? 
Do we want to highlight when we are making updates to data (mark missing, mark disconnected) vs when we are deleting (a destructive action).

**Comment by susanev** [comment]
@kmacgugan could you expand what you mean here? something related to the ui, or something else?

> Do we want to highlight when we are making updates to data (mark missing, mark disconnected) vs when we are deleting (a destructive action).

**Comment by sdelano** [comment]
I think @kmacgugan is referring to what @apriofrost was talking about in our meeting today: eventually we're going to want different policies for whether a service (or service group) is deemed missing on a per-service basis. For instance I'd like my internal datacenter applications to show up as missing if they're not there after an hour but for my applications that are deployed out in the field in some less-connected space, they could check in every day and I'd be okay with that.

@kmacgugan - that's not currently supported at all in the API, is it?

**Comment by kmacgugan** [comment]
@sdelano @susanev I mean I would like to somehow note when a configuration is going to result in a deletion of data, preferably at the API level but maybe just at the UI level is fine. Like if the URL had /purge or /delete in it somewhere that'd be sufficient. 

@sdelano That is also a thing we have talked about, that we would want configurations for EAS to apply at the app level. It is not currently supported at all.
