### ISSUE TITLE
IAMv2 API Docs: `apply-rules`

### ISSUE THREAD

**Issue by susanev** [chef/automate#2121]
As an administrator of a Chef Automate install using IAMv2 and configuring my projects and rules via the API, I'd like to have a reference to the `apply-rules` endpoint so that I can ensure that any changes that I make take effect in my system.

The API documentation for IAMv2 does not currently include any reference to the `apis/iam/v2beta/apply-rules`

We also want to include a link to the `apply-rules` API documentation in the [Assigning Projects to Ingested Rescoures](https://automate.chef.io/docs/iam-v2-guide/#assigning-ingested-resources-to-projects) section of the user guide section

**Comment by susanev** [comment]
@susanev add this item to the iam v2 ga card

**Comment by sdelano** [comment]
Example: https://gist.github.com/sdelano/ef3dd71e7445d28617924d8c8e2914da#applying-rules

**Comment by susanev** [comment]
@mjingle will be completing this task for us starting the week of 11/18
