### ISSUE TITLE
Stencil to Angular component: chef-control-menu

### ISSUE THREAD

**Issue by SEAjamieD** [chef/automate#2127]
An ongoing effort to convert Stencil components over to Angular components.

## User Story

As a Developer, I will use this work when I want to build out any html template that uses an `<chef-control-menu` component.  This will allow us to re-use a component with minimal effort and consistent styling across automate, while at the same time increasing performance.

## Definition of Done
- [ ] Angular component built that returns a `<chef-control-menu>` 
- [ ] Chef specific styles applied
- [ ] current `chef-control-menu` stencil is replaced where used across the site

**Comment by susanev** [comment]
@SEAjamieD sorry i still havent had time to create the design file, but the general idea behind what we want to change is...
- remove the border
- leverage styles from the tertiary primary button, so the background turns blue on hover (but no blue color on rest)
- increase the icon size

ill get that added today though, i promise.

**Comment by susanev** [comment]
@SEAjamieD [abstract control menu button styles](https://share.goabstract.com/1cb60110-9d68-4873-922b-60a43949081a?mode=design&sha=8c00b34b79b8a7b29a46043d7fbc3ece6f730461)

**Comment by susanev** [comment]
oh also, currently when this stencil component is added to a table row it causes the table row to grow in height. we would like the table row height not to change when the row has a control menu.
