### ISSUE TITLE
improve data retention docs

### ISSUE THREAD

**Issue by susanev** [chef/automate#2136]
## Overview
A customer took the time to provide some feedback on the data retention docs, lets see if we can improve these docs.

## Customer Feedback
- update https://automate.chef.io/docs/cli-chef-automate/ to include relevant commands and sub commands for data retention
- provide use case examples of data retention usage if possible
- add information that its possible to pass @ to the grpcurl command and pipe in your json from STDIN

**Comment by yzl** [comment]
Current docs: https://github.com/chef/automate/commit/5712fac6dac8e92ee1dc26c61cd42bf340e1982f

**Comment by susanev** [comment]
when the ui functionality is released we will move the data retention section to the data-lifecycle page under settings in the automate docs; we will remove any reference grpcurl commands

**Comment by susanev** [comment]
@susanev will move relevant content to the ui card where the additional docs will be written

**Comment by susanev** [comment]
this is going to be fixed in other issues, so closing.
