### ISSUE TITLE
Provide release note information in a format that supports users not upgrading from version N to version N+1

### ISSUE THREAD

**Issue by yzl** [chef/automate#2141]
Our release notes cover changes between the new release and the one immediately before it. This may not be ideal for users who are updating from version N to version P, where P != N+1. Use cases that happen to have come up recently: 

1. A customer mentioned in Slack that they have an airgapped installation that they only update when the new release contains features or changes that they need. One of the releases they skipped included a compatibility change that did in fact affect their installation.
2. As a data point, a colleague at another company (not a customer) who is coordinating a software upgrade of some large clusters happened to mention that they find reading through non-incremental release notes painful but necessary. I asked what they would prefer, and they said, "Reverse chronological lists of new features, breaking changes, and bug fixes."

**Comment by yzl** [comment]
In case it matters, same customer situation as #2136.

**Comment by kagarmoe** [comment]
Our goal is to document the current release in Automate and this is reflected in our release notes.
