### ISSUE TITLE
Selecting a new row in the service group table causes the page to lose its scroll position

### ISSUE THREAD

**Issue by apriofrost** [chef/automate#2149]
## Describe the bug
In the service group page, scroll down the service group table, and select a new row there.
The table refreshes and goes back to the top of the table and loses its scroll position.

## Expected behavior
Expect the scroll position to remain the same whether a new row is selected or not.
Expect the table to not refresh when a new row is selected.
Expect another scroll bar to appear right near the table, in addition to the scroll bar for the side panel.

**Comment by susanev** [comment]
is it possible to do that selection without refreshing the main table?

**Comment by apriofrost** [comment]
@susanev that would be ideal. Only the content in the right-side panel needs refreshing.
