### ISSUE TITLE
Can create policy with non-real local users

### ISSUE THREAD

**Issue by blakestier** [chef/automate#2154]
## User Story

As an Automate User, I can create a policy/update a policy to have members and know that the users I've added to the policy exist and therefore the policy is active/valid.

## Current Behavior

After creating a local team `zeta` and a project `zeta`, using the command line, I attempt to create a policy with a non-existent local user: 

```curl -k -XPOST -d '{"name":"zeta pol", "id":"zeta-policy", "members":["user:local:zeta", "team:local:zeta"], "projects": ["zeta"], "statements":[{"effect":"ALLOW", "role":"project-owner", "projects":["zeta"]}]}' -H "api-token: $TOK" $TARGET_HOST/apis/iam/v2beta/policies```

The creation succeeds. I can navigate to the UI and view the policy members with those users. User names (even of non-existent `user:local:zeta`) have links to view. When I click on the user, however, I can navigate to the user details page *but* cannot see any information and have an error banner (image attached).

## Desired Behavior

Using the command line, I attempt to create a policy with a non-existent local user: 

```curl -k -XPOST -d '{"name":"zeta pol", "id":"zeta-policy", "members":["user:local:zeta", "team:local:zeta"], "projects": ["zeta"], "statements":[{"effect":"ALLOW", "role":"project-owner", "projects":["zeta"]}]}' -H "api-token: $TOK" $TARGET_HOST/apis/iam/v2beta/policies```

I receive an error message (not found?). ![Screen Shot 2019-11-07 at 11.08.17 AM.png](https://images.zenhubusercontent.com/5d24fdf9dc67db59a676ebc6/d3774270-8f6d-4f6f-bb76-8cbdfe60a9d4)![Screen Shot 2019-11-07 at 11.08.04 AM.png](https://images.zenhubusercontent.com/5d24fdf9dc67db59a676ebc6/c2b7a33d-10f1-462b-ac52-8a7661fb0698)

**Comment by susanev** [comment]
this work has been deprioritized.
