### ISSUE TITLE
Not seeing 'unauthorized' error banner when attempting to update/create rule without permission

### ISSUE THREAD

**Issue by blakestier** [chef/automate#2155]
## User Story

As an Automate User I will use this work when I want to create a project rule.

## Current Behavior

In the browser, I create a new project, navigate to view that project, and attempt to create or update a rule for that project. When I click "Save", the page flickers briefly, but the modal does not close and I see no notification. (Behind the scenes, the save fails because I am not authorized to update this project)

## Desired Behavior

As a project owner of Project Foo, I can view Project Foo but cannot create/update rules for that project. If I attempt to do so, I see an "Unauthorized" banner and the editing modal closes (or maybe just never opens, ideally).

**Comment by susanev** [comment]
this work has been deprioritized.
