### ISSUE TITLE
Use `chef-table` Angular component for all auth tables

### ISSUE THREAD

**Issue by sdelano** [chef/automate#2161]
PR #2153 introduced an Angular equivalent of the StencilJS `<chef-table>` and applied it to the token list page. Temporarily, this Angular component uses `<chef-table-new>` as its root-level element, which is necessary until the UI team is ready to examine all the call sites of `<chef-table>` and drop the StencilJS version.

In the meantime, auth team decided to swap in the Angular component for all Auth tables (Token list already complete):

- Policy list
- Project list
- Role list
- User list
- Team list
- Policy member list
- Team users list
- Project rule list

To swap in the Angular component, change the tags in each template per this table:

StencilJS  | Angular
-----------|--------
chef-table | chef-table-new
chef-thead | chef-table-header
chef-tbody | chef-table-body
chef-tr    | chef-table-row
chef-th    | chef-table-header-cell
chef-td    | chef-table-cell

Check the corresponding Cypress test file for the same substitutions.

**Comment by blakestier** [comment]
closed by https://github.com/chef/automate/pull/2196
