### ISSUE TITLE
Provide contextual information for services marked as disconnected

### ISSUE THREAD

**Issue by apriofrost** [chef/automate#2168]
_Designer note: this issue is still under discovery, any feedback is welcome!_

## Problem
As a developer who looks at the service group view every day to monitor the health status of my application, they may want to understand _why_ a certain service is marked as disconnected.

Currently, the threshold for marking services as disconnected is only editable and viewable by users who have the "admin" access. It's likely that developers, who are the primary user of the service group view, does not overlap with the group of people who have the "admin" access. It may seem unclear why a certain service is marked as disconnected for the developer if they don't have access to the threshold information. 

Moreover, we have heard feedback such as https://github.com/chef/automate/issues/1947 that users wish to be able to configure the disconnected threshold by applications in an environment (what we now call a "deployment"). That means there could be many threshold values, and exposing the threshold information to developers become much more helpful in understanding why a certain service is marked as disconnected. 

## Proposed solution
Provide the threshold information for a specific app in an environment in the context of services in it being marked as disconnected.

**Comment by ericcalabretta** [comment]
@apriofrost having some paper trail for disconnected is helpful, Like when was the last good health-check? How long has it been, etc. We have some of that already but sometimes its hard to understand when the last good one was, this is helpful for not disconnected services too since it helps you build trust in the information .

**Comment by apriofrost** [comment]
@ericcalabretta that's a great idea!  Could you tell me a bit more about how you would expect using the "last good health check timestamp" information? How it relates to building trust in the information?

**Comment by susanev** [comment]
this has been deprioritized.
