### ISSUE TITLE
waivers: api changes

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#2175]
## User Story

follow up to https://github.com/chef/automate/issues/2174

need to make the api changes for waivers data for:
- Stats Summary
- Stats
- Nodes Trend
- Controls Trend
- Control List
- Nodes
- Profiles
- Reports

## Definition of Done
api reflects waived control/profile/node statuses

**Comment by vjeffrey** [comment]
t shirt size large

**Comment by vjeffrey** [comment]
is there more work remaining for this card or can it be marked as merged/closed?

**Comment by alexpop** [comment]
Closing this ticket as work is complete. Thanks for the heads up Victoria!
