### ISSUE TITLE
Chef Automate not filtering/displaying on policy_name 

### ISSUE THREAD

**Issue by carav008** [chef/automate#2194]
## Describe the bug
As an option on Chef Automate under Compliance, filtering for _policy_name_ doesn't filter on the policy you choose. The filter option pops up and the url changes showing the query
> _https://automate_url.com/compliance/reports/overview?policy_name=policy_

but no filter is actually applied on the UI. 

## To Reproduce
- Select Compliance on Chef Automate 2 instance 
- Select filter option for policy_name and select policy
- Notice that filter is not applied 

## Expected behavior
When policy_name is selected, Chef Automate should display nodes attached to the specific policy

## Versions (please complete the following information):
- OS: RHEL7
- Browser [e.g. chrome, safari] Chrome
- Automate Build Number [e.g. 20190701222009]: 20191104205453

**Comment by vjeffrey** [comment]
hi @carav008 -- sorry we didn't explicitly respond when you created the ticket. It looks like this is a ui issue, and it is on the board. thanks for reporting!

**Comment by vjeffrey** [comment]
tested the fix in our pre-acceptance env. 
https://a2-local-inplace-upgrade-dev.cd.chef.co/compliance/reports/overview?policy_name=test_policy_name correctly applies the filter now.
closing the issue, it is fixed as of build number 20191217231323
