### ISSUE TITLE
automate stale nodes left behind after chef-server node delete.

### ISSUE THREAD

**Issue by epackorigan** [chef/automate#2211]
Deleting a node from the chef server doesn't delete the node from automate.
(the delete event shows in the event feed, but the node entry still shows in automate post-deletion)

Steps to reproduce:
* bootstrap a node called 'testnode' in a given chef-server/org
* run the client
* observe the node in automate with run data
* delete the node in chef-server
* note that the testnode entry is still present under infrastructure in automate.
* re-create the node called 'testnode' in the same chef-server/org
* note that there are two testnode entries now. 

The original entry will eventually get deleted by the reaping process (once missing for long enough). 

I would expect that the node be removed from the chef-server and chef-automate in concert (so as not to have duplicated nodes)

- Automate Build Number: 20191104205453

**Comment by vjeffrey** [comment]
thanks for opening the issue @epackorigan -- i've added this to our backlog board in hopes that we can pull this in to attempt to repro and fix or further advise in our next sprint

**Comment by vjeffrey** [comment]
support issue: https://getchef.zendesk.com/agent/tickets/23797

**Comment by vjeffrey** [comment]
i am going to take this issue out of our backlog until support has confirmed they can repro

**Comment by epackorigan** [comment]
At this point, I cannot repro on the newly deployed aws native chef infra. It's got to be something we have done on our chef server that's preventing that from working (either version incompatibility or something along those lines). Investigation continue, but this is likely not a bug as previously thought, but an implementation error of some kind... I'll follow up with support there and close this bug.

**Comment by vjeffrey** [comment]
thanks for closing!!!

**Comment by mcascone** [comment]
I can verify that on chef automate/server 
Version: 2
Build: 20200831163517

A node still shows up in Automate after deleting node and client in the server. 
I have a hunch that this is actually by design, but it's confusing.
