### ISSUE TITLE
Error from adding policy members & team users needs better formatting

### ISSUE THREAD

**Issue by msorens** [chef/automate#2215]
## User Story

When an error occurs during adding members to a policy, the error needs to be presented in a more tidy format.

Rendering flows with screenwidth, but both of these need UX improvement:

![image.png](https://images.zenhubusercontent.com/5d07f7b39943fc312156c891/021c0f10-2df8-4af7-af6c-5fa14937604e)
![image.png](https://images.zenhubusercontent.com/5d07f7b39943fc312156c891/4e4bc08a-a2b8-4f17-b7e6-3c1ddde14313)

## Design Details

For these types of errors (and because we are limited to a specific error notification design pattern currently), the user should be navigated back to the list page they were on prior and the error should show as usual in the on-page user failure notification.

## Demo Script / Repro Steps

One way to force an add-member failure is to add this to components/authz-service/server/v2/policy.go::AddPolicyMembers just after the test for not nil (L329).
```
if err == nil {
		return nil, status.Errorf(codes.InvalidArgument, "parse member: %s", "hello")
	}
```
Then `go_update_component authz-service` in hab studio to compile that change.

Once that reloads, any attempt to add members will result in a failure.

**Comment by bcmdarroch** [comment]
We should address this on `team-add-users` as well:
<img width="1086" alt="Screen Shot 2019-11-15 at 12 05 32 PM" src="https://user-images.githubusercontent.com/21015366/68972307-57f42000-07a0-11ea-928c-fe68afb10157.png">
