### ISSUE TITLE
fix styling project and policy details headers

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#2225]
![Screen Shot 2019-11-14 at 3.41.37 PM.png](https://images.zenhubusercontent.com/5d236338fa967b04b3b34e1d/961c38e1-3ae8-4ec4-b7ee-751fd72fc72d)![Screen Shot 2019-11-14 at 3.41.22 PM.png](https://images.zenhubusercontent.com/5d236338fa967b04b3b34e1d/1a2fe9b3-d3af-4ef1-aecc-4647210ca15f)

need to restore these CSS classes: 
- https://github.com/chef/automate/pull/2196/files#diff-ae5854874eb09f4aa98607aedb9f1cc0
- https://github.com/chef/automate/pull/2196/files#diff-014e708598e16c5a831eb6c4a9e6674d

**Comment by susanev** [comment]
as a note, `chef-page-header` really shouldnt have `color: var(--chef-dark-grey);` anymore. none of the uses of that use that text color anymore.

**Comment by bcmdarroch** [comment]
fixed in: https://github.com/chef/automate/pull/2261
