### ISSUE TITLE
event feed right panel does not open

### ISSUE THREAD

**Issue by susanev** [chef/automate#2237]
## Overview
When using the buttons that look like links on the event feed the panel on the right does not open.

## Repro steps
- Create some events (get a few profiles, or something else)
- Navigate to the event feed
- Use a button that looks like a link
- Notice the right panel does not open

**Comment by vjeffrey** [comment]
error in console:
<img width="904" alt="Screen Shot 2019-11-15 at 17 52 01" src="https://user-images.githubusercontent.com/10341541/68985029-d5d01f80-07d0-11ea-8ee4-8fba630f07a0.png">
