### ISSUE TITLE
right panel positioning issue

### ISSUE THREAD

**Issue by susanev** [chef/automate#2238]
## Overview
The run history panel, compliance/scan-job error panel, and compliance/reports scan results panel are not positioned correctly. They seem to not correctly take up the right space vertically.

## Repro steps
- navigate to `infrastructure/client-runs` and go to a node detail page
- scroll down
- then open the run history panel
- notice that the top is cut off

#### Client runs
<img width="1438" alt="run-history-panel" src="https://user-images.githubusercontent.com/5489125/68982253-1e7cde00-07bb-11ea-8a7b-7271a76d1806.png">

#### Compliance scan jobs
<img width="1438" alt="scan-jobs-error-panel" src="https://user-images.githubusercontent.com/5489125/68982391-a5ca5180-07bb-11ea-953b-4af85dbc7f36.png">

**Comment by vjeffrey** [comment]
same deal with the scan results sidebar:
<img width="1396" alt="Screen Shot 2019-11-15 at 17 51 06" src="https://user-images.githubusercontent.com/10341541/68985019-c18c2280-07d0-11ea-8f3f-1d53a425e35a.png">
