### ISSUE TITLE
[spike] apply rules api response is complex and confusing

### ISSUE THREAD

**Issue by susanev** [chef/automate#2241]
## Overview
Think about and document what is complex and confusing along with some ideas for a better response.

## Reference

```
{
  "state": "not_running",
  "estimated_time_complete": "0001-01-01T00:00:00Z",
  "percentage_complete": 1,
  "failed": false,
  "failure_message": "",
  "cancelled": false
}
```

**Comment by msorens** [comment]
_Note that at the time I am writing this, there is no description above other than one sample output, so these comments could easily get out-of-date:_

All the fields of that output are used by the front-end to be able to present accurate details to the user in the UI. As such, that structure was intended for machine consumption, not human consumption, per se. So we could, for example, provide a separate command that provides a response more palatable to humans, but I am not sure what that would look like.

**Comment by susanev** [comment]
an idea...
- estimated_time_remaining:
- percentage_complete: 0 – 100
- current_state: preparing, updating, done, failed, canceled
- message: ""

questions
- if the estimated time remaining is 0, and the percentage is 100, can we assume it is not running?
- do we need to maintain the last state when a new apply rules starts?

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
