### ISSUE TITLE
Policy member add modal renders incorrectly when navigated to directly

### ISSUE THREAD

**Issue by tylercloke** [chef/automate#2253]
## Describe the bug

When you navigate directly to the policy member add modal, it renders incorrectly:

<img width="1205" alt="Screen Shot 2019-11-18 at 1 41 52 PM" src="https://user-images.githubusercontent.com/1899715/69096413-3b0e5580-0a09-11ea-933c-4199dd968b96.png">

The modal renders properly if you navigate directly from the policy details page via the `Add Members` button.

## To Reproduce

On IAM v2.1 navigate directly to:

```
/settings/policies/administrator-access#members
```

You'll see the bottom of the modal does not render.

**Comment by susanev** [comment]
this also doesnt render correctly when using the member expression button

**Comment by SEAjamieD** [comment]
the good news here is that the modal is rendering all the content correctly.  The bug is a layout issue - it just hiding below the fold
