### ISSUE TITLE
ui: filters do not persist on compliance reporting pages when navigating to subpages

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#2254]
## Describe the bug
When navigating from the compliance reporting list views into the subpage views, such as reporting profile details and reporting node details, and then back to the list views, the filters are not persisted.

## To Reproduce
- from compliance overview/list pages, set a date filter
- click on a node to view the details
- click on the "Reports" breadcrumb, notice the date filter disappears (note that clicking back in the browser maintains the filter, but clicking the breadcrumb resets to empty filters)
- repeat the same for reporting profile list/profile details

## Expected behavior
Clicking on the breadcrumbs to move back to a list view in the app persists the filters.

## Versions (please complete the following information):
- Automate Build Number 20191112230549

**Comment by SEAjamieD** [comment]
Note:  one thing I noticed, is that if a user visits the filtered node URL directly. i.e. someone filters the view, clicks on the node, and then sends that URL to someone else, we can't apply the filters on the second viewers return.

I think this makes sense, but wanted to state for clarity.
