### ISSUE TITLE
specifying a control filter without a profile filter does not filter the exported report

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#2255]
## Describe the bug
When exporting the reports, all search filters should be respected.
Specifying a profile and control filter results in an exported report that only has the specified control.
However, specifying a control filter *without* the profile filter does not filter down to only that control.

We used to the profile and control filtering manually, but changed that with deep filtering. Since a single control filter does not trigger deep filtering, we'll need to do manual filters when a control id but no profile id filter is selected.
While we're at it, we should probably take a look at all those "only one profile/one control" filter rules. Are they really necessary? Could we allow the users to specify more than one? We've had questions about this.

## To Reproduce
- add a filter for a profile and control
- export the report, notice only that one control is included
- remove the profile filter, leave the control filter in place
- export the report, notice all controls are included

## Expected behavior
Specifying a control filter exports a report with only that single control

## Versions (please complete the following information):
- Automate Build Number: 20191112230549

**Comment by phiggins** [comment]
tshirt size medium
