### ISSUE TITLE
EAS Apps tab scroll position is not retained

### ISSUE THREAD

**Issue by kmacgugan** [chef/automate#2259]
When scrolled halfway through the service-groups table, if you select a middle of the table service-group it does not maintain the scroll position and you are shown the top of the table. You have to scroll down again to see the service-group you selected and that is showing in the sidebar. 

## To Reproduce
- Start up automate
- Run `applications_populate_database` in the studio to create fake service-group data
- Scroll down through service groups and select a service-group towards the bottom
- Note that the service group you selected is highlighted but you have to scroll back down to get to it. 

## Expected behavior
I expect that when selecting a service-group from the table that the scroll position is maintained.

**Comment by susanev** [comment]
@apriofrost @kmacgugan are these dups? #2149

**Comment by kmacgugan** [comment]
Yes! They are!
