### ISSUE TITLE
can scroll right to see hidden panel of Scan Jobs page

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#2264]
## Overview
I can scroll right on the [Scan Jobs](https://a2-local-fresh-install-dev.cd.chef.co/compliance/scan-jobs/jobs) page to see a hidden panel

## To Reproduce
- navigate to `/compliance/scan-jobs/jobs`
- try to scroll to the right of the page

## Screenshots
<img width="1428" alt="Screen Shot 2019-11-18 at 4 55 04 PM" src="https://user-images.githubusercontent.com/21015366/69106793-520e7100-0a24-11ea-93d8-41ca1769cf5d.png">
<img width="1434" alt="Screen Shot 2019-11-18 at 4 57 27 PM" src="https://user-images.githubusercontent.com/21015366/69106878-913cc200-0a24-11ea-8eba-3d7ccac34a43.png">

**Comment by susanev** [comment]
this is also a problem on...
- reports/nodes/{node-id}
- compliance/reports/profiles
-
