### ISSUE TITLE
setting sidebar no longer reacts to IAM version change without refresh

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#2278]
## Describe the bug
Previously, the settings sidebar was subscribed to the IAM Version on the store and would instantly react to IAM version changes, displaying the correct menu items for each version. 

Since the layout update, a refresh is required to display the correct sidebar.

## To Reproduce
**Reset: IAM v2 -> IAM v1**
- your local env will start on IAM v2.1 by default
- navigate to any settings page
- run `chef-automate iam reset-to-v1`
- you can still navigate to the V2-only pages (roles, projects, policies) but they will be empty
- to see the V1 sidebar, refresh

**Upgrade: IAM v1 -> IAM v2**
- now run `chef-automate iam upgrade-to-v2`
- you will not see any V2 sidebar items unless you refresh or navigate to a V2 URL directly (https://a2-dev.test/settings/policies)

## Expected behavior
When I upgrade to V2, the UI should react quickly and display the Access Management links.
```
Access Management
- Policies
- Roles
- Projects
```

When I reset to V1, the UI should react quickly and remove the Access Management links, so that I only see
```
Identity
- Users
- Teams
- API Tokens
```

**Comment by susanev** [comment]
also, if a user has access to nothing under node management, or identity, or access management those headings should be hidden. it seems they always appear after the layout change.

![settings-nav-bug](https://user-images.githubusercontent.com/5489125/69268538-302c0000-0b84-11ea-964b-f64bb835afc6.png)
