### ISSUE TITLE
workflow left nav item missing

### ISSUE THREAD

**Issue by susanev** [chef/automate#2281]
## Overview
Previously, on the infrastructure left nav there was a workflow nav item, its gone now.

missing in dev: https://a2-workflow-local-fresh-install-dev.cd.chef.co/infrastructure/client-runs
there in acceptance: https://a2-workflow-local-fresh-install-acceptance.cd.chef.co/infrastructure/client-runs

**Comment by tarablack01** [comment]
@susanev The logic is to show the workflow menu item if workflow is enabled. Here is shows it's not. When should it be enabled in the state?
![Screen Shot 2019-11-21 at 11.02.26 AM.png](https://images.zenhubusercontent.com/5d080de65af8b352a1b5732d/54e88309-64f0-43b0-ba76-14b2883306c3)

**Comment by susanev** [comment]
@tarablack01 in the studio you can use `start_workflow_service`

if you've already started all services, you can `chef-automate config patch` with this file:

```
[deployment.v1.svc]
products = ["automate", "workflow"]
```

is that helpful to you?
