### ISSUE TITLE
escalation: data discrepancies between Automate GUI vs. exported data (client runs)

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#2284]
## Describe the bug
When exporting nodes from the Infrastructure tab, the results differ from what is seen in the WebUI (specifically, the total count of nodes is about 10% less when exporting)

## To Reproduce
_please note that support has been unable to reproduce this issue_
- load up a bunch of nodes in client runs
- export the data
- note any differences in node counts in the export vs gui

## Expected behavior
export and gui reflect same information

## Versions (please complete the following information):
- Automate Build Number:  20191024135531

## Additional context
https://github.com/chef/customer-bugs/issues/12
https://getchef.zendesk.com/agent/tickets/23731
https://getchef.zendesk.com/agent/tickets/23783

**Comment by vjeffrey** [comment]
from @teknofire :
```
curl -k https://localhost/api/v0/cfgmgmt/nodes/export -H 'api-token: token' -d '{"output_type":"csv","filter":[],"sorting":{"field":"name","order":0}}'

curl -k https://localhost/api/v0/cfgmgmt/nodes/export -H 'api-token: token' -d '{"output_type":"csv","filter":[],"sorting":{"field":"checkin","order":0}}'

The first curl only returns 240ish nodes and the second one returns all 744 nodes.
```

**Comment by phiggins** [comment]
tshirt size medium
