### ISSUE TITLE
ingest-service should verify that id is set before sending message to Elasticsearch

### ISSUE THREAD

**Issue by thomascate** [chef/automate#2309]
## Describe the bug
Currently if a client sends a message with a blank uuid, it will get through ingest-service and then be rejected by Elasticsearch. Leaving a pair of log messages similar to this.

```
Nov 20 14:41:27 test hab[31921]: ingest-service.default(O): time="2019-11-20T14:41:27-06:00" level=error msg="Message failure" error="elastic: Error 400 (Bad Request): Validation Failed: 1: id is missing;2: id is missing; [type=action_request_validation_exception]"

Nov 20 14:41:27 test hab[31921]: automate-load-balancer.default(O): - [20/Nov/2019:20:41:27 +0000]  "POST /data-collector/v0/ HTTP/1.0" 500 "0.264" 164 "-" "Chef Client/14.12.9 (ruby-2.5.5-p157; ohai-14.8.11; x64-mingw32; +https://chef.io)" "10.1.1.11:2000" "500" "0.263" 94712
```

However, since we use the bulk endpoint. There are usually other valid messages in that bundle that got rejected. So a single misconfigured server can cause 500 data-collector errors for any other nodes that happen to be sending reports around the same time.

## To Reproduce
Create a blank file at `/etc/chef/chef_guid` on a node running chef-client. Run chef-client and confirm that the data-collector fails with a 500. Then confirm on the Automate server that the message was rejected by Elasticsearch, causing any messages in that bulk ingest to fail.

## Expected behavior
If a client sends a message with an empty UUID, the ingest-service should reject it and not attempt to insert it into Elasticsearch. In this case only the misconfigured client would receive the 500 errors.

## Additional context
This is a pretty minor issue, since the clients can just retry. However, on large environments these 500 errors will happen consistently and trigger alarms.

**Comment by phiggins** [comment]
tshirt size small
