### ISSUE TITLE
Create API for parameterized introspection

### ISSUE THREAD

**Issue by tylercloke** [chef/automate#2310]
# Description

Right now, we have `GET /introspect` which returns the permission map for all non-parameterized endpoints the requesting user has permission on, `GET /introspect_some` which does the same thing but for a subset of non-parameterized endpoints, and `POST /introspect`, which allows you to introspect on a single endpoint -- which can be parameterized or not, but it does not work with multiple parameters and the parameters field is borderline broken.

Let's update `/introspect_some` to work with both parameterized and non-parameterized input. Long-term, we want to get rid of `POST /introspect` since it would now be redundant (but that will be future work).

# WIP

Tyler has a rough WIP here that should work with both parameterized and non-parameterized paths but it's not very tested and doesn't work because [introspection is broken with projects](https://github.com/chef/automate/issues/2340).

Here's the wip: https://github.com/chef/automate/compare/automate-2310/parameterized-introspection?expand=1

# Acceptance Criteria

`/introspect_some` handles both paramed and non-paramed paths.

**Comment by susanev** [comment]
closing in favor of rethinking introspection with projects entirely as discussed in sprint planning 11/25.
