### ISSUE TITLE
Add ability to bulk introspect parameterized paths in the UI for projects list

### ISSUE THREAD

**Issue by tylercloke** [chef/automate#2313]
# Description

For our list pages, we want to be able to make a single API request to populate the NGRX store with the user's level of permissions on multiple parameterized endpoints. The first use case is we want to be able to conditionally show or hide the dropdown for project deletion for each project in the project's list page. Currently, we are using the `app-authorized` component per drop down, which makes a separate API request for each one:

https://github.com/chef/automate/blob/master/components/automate-ui/src/app/pages/project/list/project-list.component.html#L48

In https://github.com/chef/automate/issues/2310, we are adding an endpoint to be able to get a map of permissions based on multiple parameters.

We either need a new component like app-authorized to use this new endpoint (and the underlying [authorized helper](https://github.com/chef/automate/blob/master/components/automate-ui/src/app/helpers/auth/authorized.ts) or we need a way to update the store outside of the app--authorized component and a way to use such a component without re-triggering a fetch per project list table entry.

We have `anyOf` and `allOf`, but those are a bit different in that they restrict a single bit of HTML based on several entries, instead of several bits of HTML based on several results of the `introspect_parameterized` call. There's a few different ways we could solve this, but we'll want to be able to update the store with the single API call. Would be helpful to be familiar with these bits of UI code:

https://github.com/chef/automate/blob/master/components/automate-ui/src/app/helpers/auth/authorized.ts

https://github.com/chef/automate/blob/master/components/automate-ui/src/app/components/authorized/authorized.component.ts

https://github.com/chef/automate/tree/master/components/automate-ui/src/app/entities/userperms

# Done Criteria

Maybe we can break this card into further subtasks as we settle on exactly how we want the UI interfaces to look.

* We have a way of updating the `userperm` store with multiple entries based on the results of the endpoint created in https://github.com/chef/automate/issues/2310.
* We have a way of filtering specific, multiple parts of the DOM out like `app-authorized` does without re-querying the parameterized store results populated by the above (this can potentially both be done in a new component, but that's an implementation detail you'll have to decide).
* The project's list component uses the above to make a single API call to [filter which project dropdowns are shown](https://github.com/chef/automate/blob/master/components/automate-ui/src/app/pages/project/list/project-list.component.html#L48) (maybe this can be its own subtask)

**Comment by susanev** [comment]
closing in favor of rethinking introspection with projects entirely as discussed in sprint planning 11/25.
