### ISSUE TITLE
Post-GA remove `POST /introspect` endpoint in favor of `POST /introspect_some`

### ISSUE THREAD

**Issue by tylercloke** [chef/automate#2314]
As of https://github.com/chef/automate/issues/2310, `POST /introspect_some` will handle both parameterized and non-parameterized inputs. `POST /introspect` also has a redundant, confusing `parameters` field which does not always work.

Let's remove this now redundant endpoint (since `introspect_some` will handle parametrized input after  https://github.com/chef/automate/issues/2310 is finished). Also remove any places it might still exist in the UI in favor of `introspect_some`.

**Comment by susanev** [comment]
this has been deprioritized, so closing.
