### ISSUE TITLE
Rethink service group health status and its filters

### ISSUE THREAD

**Issue by apriofrost** [chef/automate#2321]
## Current definition of the service group health status
In the table view, the status reported for a service group will reflect the “most critical” status reported by any individual instance of that service (e.g. if one instance is in “critical” status, the entire group is in “critical” status). By default, the table rows are sorted by the percentage of OK services from the smallest to the largest. The sidebar cards are sorted by criticality, from the “most critical” status to the “least critical” status (“critical,” “warning,” “unknown”,  and “OK”). 
A picture with examples illustrating the hierarchical relationship among the health status and how the individual instance status affect the group status: 
![image](https://user-images.githubusercontent.com/9401459/69290200-038fdc80-0bb4-11ea-8c96-26f5a23f69b4.png)

## Problems
As we follow the current model of the service group health status, there are a few problems we observed so far:

1. If a service group contains any service instance that is in "critical" status, the "warning" or "unknown"  status for other instances in the group get lost when transforming into the group status, which is only the most critical status of the instance in the group. This makes it impossible to filter on "warning" or "unknown" status for services in the group even when they exist. When asking users what they expect to see when the "warning" filter is applied, they said:

    > When I click on “warning” I expect to see all the apps that are showing the warning. 
  
   This indicates that users expect all service groups that contain _any_ instances that are in a "warning" status should show up when the "warning" filter is applied. However, the current rule will only show all service groups that have the most critical status as "warning", meaning they couldn't contain any service instance that is "critical".

2. We started to realize that it is unnecessary to assign a single status to a group. Instead, the group status should be a status spectrum: reflecting the status of the instances in it, which spans from a range of "critical", "warning", "unknown" and "OK". If a service group has 90 service instances, and only one of them is "critical" while the rest are "OK", it is not worth rendering the entire group as "critical". But if 80 of the 90 services are in a "warning" status while the rest 10 are "OK", it might worth more attention from the user than the former scenario. In addition, we found out that it is the individual service status that the users truly care about. We heard them saying:

   >... I would prefer it (service group "warning" filter) to not only filter on that (the service group), but the ones over here (service instance panel)  that are warning. I would expect to filter on this (table) and this (side panel). If I have a service group that has a warning, and there are 90 of them. I don’t want to have to go here (side panel) and click on warning again. I’m clearly trying to find which system is under warning.

   This indicates that not only the group status is unnecessary, so are the group status filters. From an efficiency standpoint, we should focus on helping users narrow down to the worrisome service instances (either "warning" or "critical") quickly. This could mean less click in the interface, and filters that efficiently narrow down the problem areas. 

## Solutions
We've done some design exploration around the above problem, the current solution is to:
- remove the rules and construct for the service group status, leave it be the donut chart that visualizing the individual service instance status within it.
- remove the "OK" filter, since it is not the area that users care about. They come to the view to figure out what went wrong. But it's good to keep the count somewhere in the interface.
- redefine the target for the status filter, for both the filters above the service group table and within the sidebar.
- ...

@apriofrost is working on getting more feedback and inspirations to not only address the problems identified here but also play harmoniously with other status filters in Automate for infrastructure and compliance. 

Feel free to post your comments and feedback below! 😃

**Comment by susanev** [comment]
this has been deprioritized.
