### ISSUE TITLE
Nodes API missing nodes

### ISSUE THREAD

**Issue by Doltair** [chef/automate#2334]
# Redirect Alert!

## Submit your feature request via the [Chef Ideas Portal](https://chef-software.ideas.aha.io/)

**Nodes API**

Ohai Team,!

It will be a good feature if we add also a filter for node missing? or unless there's a suggestion to get those using API (without using Automate's UI)

Thank you Chef!

**Comment by vjeffrey** [comment]
hi @Doltair -- going forward, pls visit the aha idea portal for new feature ideas. we do this b/c that's what product looks at and we want to make sure new feature requests are being prioritized appropriately by product.
for this issue, we will be able to filter by missing nodes on the "nodes api" (`api/v0/nodes/search`) once  https://github.com/chef/automate/issues/616 is completed. in the meantime, you can use the cfgmgmt api to find this:
`api/v0/cfgmgmt/nodes?pagination.page=1&pagination.size=100&sorting.field=name&sorting.order=ASC&filter=status:missing`

**Comment by Doltair** [comment]
Oh very cool @vjeffrey and that is acknowledged, my apologies for that, moving forward I will go there @ idea portal.

Anyhow would this path will be changed overtime after #616?. We're gonna use the path for missing nodes that you gave in the meantime.

**Comment by vjeffrey** [comment]
no, that path won't change. the story is:
- cfgmgmt nodes api: has all the information that comes from the chef infra (chef-client) runs on your nodes
- compliance reporting nodes api: has all the information that comes from the chef inspec scans on your nodes
- nodes api: has general node metadata and last/penultimate run and scan metadata for your nodes.  it's basically a node store (and the api that drives this epic: https://github.com/chef/automate/issues/911)

**Comment by vjeffrey** [comment]
i'm going to close this issue since the work requested will be addressed by https://github.com/chef/automate/issues/616
