### ISSUE TITLE
Fix introspection with projects

### ISSUE THREAD

**Issue by tylercloke** [chef/automate#2340]
With two projects, test and test2, we expect POST instropsect to return the correct permissions based on project access.

Given this policy:

```
{
  "name": "tyler test project",
  "id": "tyler",
  "type": "CUSTOM",
  "members": ["user:local:tyler"],
  "statements": [
    {
      "effect": "ALLOW",
      "actions": ["*"],
      "projects": [
        "test"
      ]
    }
  ],
  "projects": [
  ]
}
```

We'd expect POST /introspect to return all true for '{"path":"/iam/v2beta/projects/test", "parameters":[]}' and all false for '{"path":"/iam/v2beta/projects/test2", "parameters":[]}'.

However, this is not the case:

```
curl 'https://a2-dev.test/api/v0/auth/introspect' -H 'authority: a2-dev.test' -H 'accept: application/json, text/plain, */*' -H 'authorization: Bearer ...' --compressed --insecure -d '{"path":"/iam/v2beta/projects/test2", "parameters":[]}'
{"endpoints":{"/iam/v2beta/projects/test2":{"get":true,"put":true,"post":false,"delete":true,"patch":false}}}
```

This is because, introspection is purely looking at resource / action pairs and not projects to make its decision.

**Comment by susanev** [comment]
closing in favor of rethinking introspection with projects entirely as discussed in sprint planning 11/25.
