### ISSUE TITLE
Cancelling export reports from UI doesn't actually stop cancel the api call

### ISSUE THREAD

**Issue by rickmarry** [chef/automate#235]
# User Story
when the export reports button on the compliance tab of the UI is depressed, a modal window is displayed, giving the user feedback that the export is underway and also, offering an opportunity to close the modal window with the normal close button.  When the modal is closed, the api request for export should be cancelled but is not.

**Comment by vjeffrey** [comment]
should it be cancelled?  i never thought that was the intent...
@jonong1972 what do you think?

**Comment by rickmarry** [comment]
Fair point @vjeffrey. The problem with the way it operates now is that that, once the modal is closed, the download stream continues to do its work.  The user has no idea that the work is continuing and may do what is so common which is to continue to try over and over again to invoke export by repeatedly pressing that export button, resulting in many simultaneous duplicates of this expensive operation. 

I think that the modal dialogue window should have two buttons on it:
1 - Run in Background
2 - Cancel

If we have add these two buttons, then we may remove the close button as both buttons will close the modal box after invoking their respective action.

It would be nice to also have a progress indicator somewhere on the screen.

**Comment by vjeffrey** [comment]
Agreed on button options! 
Progress indicator would be nice someday too -- let's talk with jon in standup
