### ISSUE TITLE
govcloud support for aws node integrations

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#2358]
## User Story
Users would like to be able to use node integrations with their govcloud aws accounts (api + ec2). 
At first glance, it seems like allowing a user to specify a region to target when creating the integrations should be sufficient.
Things to test:
- aws api integration with govcloud creds, run a scan and ensure results are as expected
- aws ec2 integration with govcloud creds, run a node scan and ensure results are expected
- ensure required perms suggested in our docs work for govcloud
- ensure ssm jobs work with govcloud

## Definition of Done
All aws integration functionality checked with govcloud

**Comment by vjeffrey** [comment]
large t shirt size

**Comment by jonong1972** [comment]
Update the label:
Specify a default region to target:

Pre-fill the text field with:
us-west-1 (or whatever our default is today)


Note: I would like to revisit this for a solution to pull the list of regions to put into a drop down.

**Comment by vjeffrey** [comment]
noting repro/testing steps here for later

- create IAM user in aws govcloud with the following perms:
```
{"Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeInstances",
                "ssm:*",
                "ec2:DescribeRegions",
                "sts:GetCallerIdentity",
                "ec2:DescribeInstanceStatus",
                "iam:ListAccountAliases"
            ],
            "Resource": "*"
        }
    ]
}
```
create aws integration:
- api
- ec2

- ensure both work
- ensure nodes are attached to each one
- run a scan job on each one

**Comment by vjeffrey** [comment]
from my testing so far, it looks like ssm scanning does not work in govcloud

**Comment by vjeffrey** [comment]
validated in dev: https://a2-dev.test/settings/node-integrations
