### ISSUE TITLE
error when calling export reports when there are a lot of reports to be exported

### ISSUE THREAD

**Issue by rickmarry** [chef/automate#236]
# User Story
When there are a large number of reports available for export and export is run, sometimes there is an error returned due to the fact that there are not any elastic search connections available.

**Comment by vjeffrey** [comment]
probably related to this issue we've spoken about @rickmarry ? https://github.com/chef/automate/issues/251

**Comment by rickmarry** [comment]
good catch @vjeffrey.. closing this one as it's just a duplicate of #251
