### ISSUE TITLE
Have domain services return error if they ever receive an empty projects filter

### ISSUE THREAD

**Issue by tylercloke** [chef/automate#2369]
# Description

Right now, nodemanagers proceeds as normal if it gets an empty projects filter:

https://github.com/chef/automate/pull/2347/files#diff-b2a3dd676e11d57d07f0673b6e08ac3aR99

This should never happen. authz-service should either return a 403 and it should never get to the domain, or the projects filter has a specific set of projects or `*`.

We should throw an error from all the domains if we ever get into this bad state (nodemanagers, compliance, and I think ingest all needed cleaned up).

**Comment by susanev** [comment]
this has been deprioritized, so closing.
