### ISSUE TITLE
Reject project deletions while project update in progress

### ISSUE THREAD

**Issue by msorens** [chef/automate#2408]
## Overview

While a project update is in progress (which may be up to 12 hours), we want to reject project deletion requests (both in the UI and the API) so as to avoid a race-type condition where a project update and a related project deletion may occur in an indeterminate order.

### Project Update Modal
Change project update modal text to `Updating projects will apply all pending edits by moving ingested resources into the correct projects. During this background process you will be unable to delete projects and it can take up to 12 hours to complete.`

![project-update-modal](https://user-images.githubusercontent.com/5489125/70265624-a701f500-174f-11ea-9ee9-6b050af95867.png)

### Project Deletion Error Message
If a user trys to delete a project during a project update allow them to try to complete that task and then display an error with the error notification in the ui. Possible error text: `Deleting a project is not allowed during a project update.` feel free to edit and change that as needed and work with @susanev on final wording.

**Comment by susanev** [comment]
@susanev...
- add info about project delete to project update modal
- write error message
