### ISSUE TITLE
Link Between Automate Apps Tab and the Depot

### ISSUE THREAD

**Issue by sdelano** [chef/automate#2417]
## User Story

As a user of the Automate-deployed On-Prem Habitat Depot, I'd like to be able to reach the Depot user interface without knowing the specific link. I'd like to be able to visit my Automate UI and be shown a link to the Depot.

As a benefit to Chef, by putting the link to the Depot inside the Applications tab, we'll be able to show Habitat users the functionality that is enabled when they connect their supervisors to Automate.

## Definition of Done

* Link to Builder is in the Apps tab as shown in the mockup
* If Builder is not deployed, link to the SaaS depot

## Resources

* [Invision Mockup](https://chef.invisionapp.com/share/62UZ4YG3VPJ#/screens/394830697_applications-Service_Groups-Builder_Link-Active)
* [Recording](https://drive.google.com/open?id=1Qf8zbxLr__pLol8gBcCJEzOcFYfmpb49)
* Icons come from our Material icon set and are `build` (the wrench) and `open-in-new` (the link). @apriofrost can help if needed here.

## Notes and Considerations

* Apps Tab Beta: currently the Apps tab is in Beta. It's intended to go GA soon, but we will potentially have a timing issue between when this work is ready and when the Apps tab is no longer hidden behind a feature flag. We should coordinate with @danielsdeleo on the timing here.

**Comment by susanev** [comment]
@sdelano did you mean to add this to the iam v2 release? i undid that, but let me know if that was intentional.
