### ISSUE TITLE
Project Delete Performance Testing

### ISSUE THREAD

**Issue by lancewf** [chef/automate#2419]
## User Story

We currently have some questions about how long it will take for a project to be fully deleted with the addition of deleting the project from ingested nodes. 

Below are the tests we want to run for the average user and high load user:
* How long would it take to delete one project that is on all the resources. 
* How long would it take to delete one project that is on half the resources.
* How long would it take to delete one project that is on 1/4 of the resources.
* How does running multiple project deletes at the same time affect the delete times.  

A high load user would be 90 days with 24 compliance reports per day. How many nodes?
An average user would be 30 days with 6 compliance reports per day. How many nodes?

## Definition of Done
A writeup showing the high load and average users project delete times. 

## Open Questions
- do we need a special case for if a project has zero ingest rules and is up-to-date?
- Does Elasticsearch filtering for only resources that have the project that is going to be deleted speed up deletion?

**Comment by lancewf** [comment]
@susanev We do not need this issue any longer with the new path of project delete.

**Comment by susanev** [comment]
i dont think so, @sdelano what do you think?
do we have a parallel card for project update? if not, prolly good to at least create that..

**Comment by susanev** [comment]
closing based on convo here, can reopen if needed.
