### ISSUE TITLE
Project percentage complete does not update

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#2436]
## Describe the bug
Project percentage complete does not update. In the UI, it sits at 0% then turns to `Projects Up-to-Date` after a period of time.

The problem stems from the API, which is not returning updated percentage complete values.

## To Reproduce
API:
- `chef_load_nodes 500`
- ` curl -kH "api-token: $TOK" -XPOST -d '{"name":"project1", "id":"project1"}' https://a2-dev.test/apis/iam/v2beta/projects`
- `curl -kH "api-token: $TOK" https://localhost/apis/iam/v2beta/projects/project1/rules -d "$(jq -n '{ id: "rule1", name: "my foo rule", type: "NODE", project_id: "project1", conditions: [{ operator: "EQUALS", attribute: "CHEF_ORGS", values: ["The Misfits"]}]}')" | jq .`

- start a project update then keep curling the status endpoint until it stops running
```
[40][default:/src:0]# curl -kH "api-token: $TOK" -X POST https://localhost/apis/iam/v2beta/apply-rules | jq
{}

[47][default:/src:0]# curl -kH "api-token: $TOK" https://localhost/apis/iam/v2beta/apply-rules | jq
{
  "state": "running",
  "estimated_time_complete": "0001-01-01T00:00:00Z",
  "percentage_complete": 0,
  "failed": false,
  "failure_message": "",
  "cancelled": false
}

[48][default:/src:0]# curl -kH "api-token: $TOK" https://localhost/apis/iam/v2beta/apply-rules | jq
{
  "state": "running",
  "estimated_time_complete": "0001-01-01T00:00:00Z",
  "percentage_complete": 0,
  "failed": false,
  "failure_message": "",
  "cancelled": false
}

# ... status response stays the same, until it stops running:

[49][default:/src:0]# curl -kH "api-token: $TOK" https://localhost/apis/iam/v2beta/apply-rules | jq
{
  "state": "not_running",
  "estimated_time_complete": "0001-01-01T00:00:00Z",
  "percentage_complete": 1,
  "failed": false,
  "failure_message": "",
  "cancelled": false
}
```

UI:
- chef_load_nodes 500
- create a project or two
- add some rules to those projects
- on the project list page, select `Update Projects`
- the percentage complete never changes on the update button or in the stop update modal

## Expected behavior
The `apply-rules` status API returns increasing values of percentage complete as the operation takes place.

The `Update Projects` button should show increasing percentage complete as time passes.
In the `Stop Updating Projects` modal, the percentage should display.

## Screenshots
<img width="766" alt="Screen Shot 2019-12-05 at 10 40 23 AM" src="https://user-images.githubusercontent.com/21015366/70263679-c72fb500-174b-11ea-8c6b-15ffdf1f14a1.png">
<img width="1035" alt="Screen Shot 2019-12-05 at 10 42 43 AM" src="https://user-images.githubusercontent.com/21015366/70263792-0100bb80-174c-11ea-95ab-6af627d964ea.png">

## Versions (please complete the following information):
- OS: mac
- Browser: chrome
- Automate Build Number: Build: 20191205181539

**Comment by msorens** [comment]
1. Confirmed this issue on my box as well.
2. This used to work, but I would say it has been a couple months since I last observed that specifically.

**Comment by susanev** [comment]
In sprint planning, this work has been scoped to determining if it is a bug and fixing it if so, otherwise, a new issue will be created.
