### ISSUE TITLE
Prevent project deletion API

### ISSUE THREAD

**Issue by lancewf** [chef/automate#2447]
## User Story

Only allowing a user to delete a project when the project has no ingest rules and no pending edits. 

## Definition of Done

The API request for the endpoint "/iam/v2beta/projects/{id}" validates if a user is allowed to delete a project with the two requirements of
* No pending edits on that project
* The project has no ingest rules

## Demo Script / Repro Steps
1. Create a project with ingest rules.
1. Apply the rules. 
1. Try to delete the project with this endpoint "/iam/v2beta/projects/{id}". Ensure an error is returned and the project is not deleted
1. Remove the ingest rules from the project and apply rules. 
1. Try again to delete the first project and ensure no error is returned and the project is deleted.

**Comment by susanev** [comment]
Note from conov with lance and michael
- if there are pending edits on any project, then you cannot delete **any** project. this is because we do not know if an individual project is up-to-date.
- project delete needs to be atomic, lance and michael are going to pair on this
    - they cannot add rules to a project that is being deleted

**Comment by msorens** [comment]
Single user:
If there are rules (staged or applied) for a given project, that project cannot be deleted. The API should return an error to the effect of "cannot delete a project containing any applied or staged ingest rules". Once the user has removed all rules, they will be allowed to do the delete.

Multiple users:
Say user A starts a delete of project 1. Meanwhile, user B attempts to add a rule to project 1 simultaneously.

 - User A's `delete project` occurs first => user B will receive an error (either from authz or from the DB itself) saying that the project does not exist.

 - User B's `add rule` occurs first => the delete will then come along right after and delete the project. I believe this cascade deletes any rules, too. So User B will think their `add rule` succeeded, but if they refresh the browser the new rule will not be there. While this is not ideal UX it is a known limitation of our system for multiple users attempting to manipulate the same IAM resource (e.g. one editing a team name while another deleting the team).
