### ISSUE TITLE
Document to manually start all services without using hab studio

### ISSUE THREAD

**Issue by saampandit** [chef/automate#2458]
## Describe the bug
A clear description of what the bug is.

## To Reproduce
- in list form if possible

## Expected behavior
A description of what you expected to happen.

## Versions (please complete the following information):
- OS: [e.g. rhel6]
- Automate Build Number [e.g. 20190701222009]

**Comment by sdelano** [comment]
Hi @saampandit - can you please provide us with a bit more context on what you're attempting to accomplish here? The Habitat studio is used as the development environment for Chef Automate, so we're interested in knowing what your use case is for starting the services outside of the studio.

If you're looking to start Automate itself, then there are some docs you can follow here: https://automate.chef.io/docs/quickstart/

**Comment by saampandit** [comment]
Hi @sdelano ,

I am trying to start all the services in background. Right now the `start_all_services` command exists in `hab studio enter`. But if I exit from shell or if accidentally  shell gets closed then have to perform after same procedure.
My use case is after modifying components, want to stand up open source chef-automate in my test environment. So that all services run in background forever. 
Also, wanted to know if there is any document that can tell which services to start in sequence.
Got interested after reading this link https://blog.chef.io/now-available-chef-automate-source-code/.

**Comment by jaym** [comment]
You wouldn't want to be using the studio to have a long running instance of automate. If you want to spin up an instance with your changes, you have couple options. Assuming you've built the hab package for your changes, you can:
1. Create an airgap bundle using `chef-automate airgap bundle create --override-origin YOUR_HAB_ORIGIN --hartifacts PATH_TO_YOUR_BUILD_DIR`. Then you can install/update your running automate as normal.

2. Deploy automate with `chef-automate deploy --override-origin YOUR_HAB_ORIGIN --hartifacts PATH_TO_YOUR_BUILD_DIR`. Once deployed, automate will watch that directory. By default, i think it will check once every 5 mins for changes and update as necessary. You can run `chef-automate upgrade run` to make it pick up the changes right away. You may also want the following bit of config to avoid running into any caches that may prevent your change from getting picked up or being automatically deleted:
```
[deployment.v1.svc]
manifest_cache_expiry = "0s"
package_cleanup_mode = "disabled"
```

3. If you already have an automate deployed, you can patch it with the following config to achieve the same effect as above:
```
override_origin = "YOUR_HAB_ORIGIN"
hartifacts_path = "/full/path/to/your/build"
manifest_cache_expiry = "0s"
package_cleanup_mode = "disabled"
```

**Comment by susanev** [comment]
@saampandit is the info jay shared helpful to you? do you have any more questions?

**Comment by susanev** [comment]
gonna close this, feel free to open a new issue if anything else comes up
