### ISSUE TITLE
generate an effortless report for investigative purposes

### ISSUE THREAD

**Issue by susanev** [chef/automate#2463]
This is a fact-finding mission to investigate how to create project rules that match effortless client runs and effortless InSpec nodes. 

- Run effortless for Client Runs and InSpec and store the JSON report in the Automate repo for future testing.
- With the effortless Client Run report, test if project rules can be created to match only effortless nodes. 
- Check if we can create a project that matches only effortless InSpec reports.
- Get an example effortless InSpec report

**Comment by susanev** [comment]
**q**: do you know if theres a way to determine if a node is an effortless node?
**a (from vj)**:
> only by the fact that the chef-server on it will be localhost
> which really means it could also be any chef solo run
> there’s no way to differentiate between effortless and chef solo afaik
> from the inspec report you would only see that it doesn’t have any chef server info/additional info on it

**Comment by lancewf** [comment]
More information about decerning if the Chef Client Run is an effortless run or not
https://docs.google.com/document/d/1PAcw5nAXpywtyo6iql1UYpmb0rt2jYyb4aNAI8lLKds/edit?usp=sharing

**Comment by lancewf** [comment]
I created an effortless CCR example here https://github.com/chef/automate/compare/lancewf/effortless_ccr_example. 

I am able to create project ingestion rules to match only Chef Solo runs. If the user creates a rule that matches the "Chef Server" = "localhost". 

I am investigating how to change the environment for an effortless infra run.

**Comment by lancewf** [comment]
I have confirmed that the effortless InSpect report's environment field exists and can be changed. There are no other fields in the report that are used for IAMv2 project filtering. There is no way to target only Effortless InSpect reports without changes to InSpec. 

Attached is the effortless InSpect report. 
[https://app.zenhub.com/files/179318179/11501592-d522-46f6-83fa-ae789e05df88/download](https://app.zenhub.com/files/179318179/11501592-d522-46f6-83fa-ae789e05df88/download)

**Comment by lancewf** [comment]
Recommendations
Write up documentation on ways to match only Effortless Infra nodes. 
Consider making updates to Chef Solo to add the chef-tag field to its config file. 
Also, consider making updates to InSpec to add the chef-tag field in the "Automate Reporter" section of the config file (https://www.inspec.io/docs/reference/reporters/). 

If we add this field to Effortless Infra and Effortless InSpec then users can create projects to match this field.
