### ISSUE TITLE
set the project limit to 300

### ISSUE THREAD

**Issue by susanev** [chef/automate#2472]
## Overview
We did the work to support 300 projects now lets change the limit to 300.

## Documentation Updates
We will also need to update the docs where it says six projects to now say 300 projects.

**Comment by lancewf** [comment]
Below is a link to where the project limit count is in the docs 
https://automate.chef.io/docs/iam-v2-guide/#configuring-project-limit

**Comment by msorens** [comment]
## Note for testing

You can easily generate (or remove) hundreds of projects from the command-line with these commands:
```
# Generate 500 starting with id 101
authGen projects create 500 101
# Remove them after testing
authGen projects delete 500 101
```
That will work inside or outside hab studio with a couple prerequisites:
1. Point at your A2 instance and authorize it:
```
export TOK="aWJNbhmqxqzOBMNhy1ptWEU2Ybc="
export TARGET_HOST=https://a2-dev.test
```
2. Cherry-pick commit `0784ca05` into your PR that tweaks the existing script.
3. Source the script (`. ./scripts/auth_collections.sh`)
