### ISSUE TITLE
chef/automate-builder-api logging should be set to error by default

### ISSUE THREAD

**Issue by chefsalim** [chef/automate#2480]
Currently after installing Builder via chef automate, and looking at the logs, it looks like the log level is set to DEBUG for automate-builder-api.

We should default this to the 'error' setting.

**Comment by jaym** [comment]
the default log level for automate is info. For automate, the order is `debug`, `info`, `warning`, `error`, `fatal`, and `panic`

**Comment by jaym** [comment]
also, the configuration for builder-api is currently hardcoded until we figure out this mapping

**Comment by chefsalim** [comment]
The levels are the same for Builder.  However builder-api logs a lot of info (every URL, that is not configurable), so it's best to set the level to error for that service.
