### ISSUE TITLE
SAML user can not logout with no license 

### ISSUE THREAD

**Issue by lancewf** [chef/automate#2492]
## User Story

When a SAML user logs in to an Automate without a license they can not logout. This is not the case for local users. The only way for a user to log out is to apply the license with the `chef-automate license apply` command on the server. 

## Definition of Done
A SAML user can logout on an Automate server without a license. 

## Demo Script / Repro Steps
1. Remove the Automate license with `chef-automate dev psql chef_license_control_service -- -c "UPDATE licenses SET active=NULL"`
1. Log in with a SAML user. 
1. Try to log out. 

![signout.gif](https://images.zenhubusercontent.com/5d1a3fbf1449416ed898598a/af3b06a0-414d-4092-a5f4-45b5957676d6)

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
