### ISSUE TITLE
Non-admin local user can not edit full name

### ISSUE THREAD

**Issue by lancewf** [chef/automate#2493]
## User Story

When logged in as a local non-admin user, the profiles page does not allow editing the full name. This does work for the admin. 

## Definition of Done

Non-admin local users will be allowed to edit their full names. 

## Demo Script / Repro Steps
1. Navigate to Your Profile in name drop down menu
1. Click Edit. There is not an Edit button. 
1. Enter new full name
1. Click Save

**Comment by bcmdarroch** [comment]
I noticed I can repro this for any user in the IAM v1 environments. 

On IAM v2 environments, I can only repro with a new user who's unattached to any policies. But as an Editor or Viewer user, the edit button is visible.

**Comment by susanev** [comment]
moving this out of sprint5 cause not as many people are going to be around

**Comment by susanev** [comment]
@lancewf i think this is resolved in your work, i tested and doesnt seem to be an issue anymore; but would like you to verify then we can close this

**Comment by lancewf** [comment]
That is correct. This [PR](https://github.com/chef/automate/pull/2652) resolves this issue.
