### ISSUE TITLE
Not able to switch the activation of a token in the details page

### ISSUE THREAD

**Issue by lancewf** [chef/automate#2494]
## User Story

The API Tokens details page is not allowing users to switch from deactivated to activated. Below is a video showing the problem. 

## Definition of Done
Admin can switch a token from deactivated to activated in the API Tokens details page. 

## Demo Script / Repro Steps
1. Navigate to Settings > API Tokens
1. Deactivate a token
1. Open the tokens details page by clicking on the tokens name
1. Select the Activate radio button
1. Try to select save. 

Below is a short clip of the behavior: 
https://drive.google.com/file/d/1EDMETrtw-woL1MaT4DU89uLURYlqmbJj/view?usp=sharing

**Comment by susanev** [comment]
@lancewf this one is a dup of #1169
could you add ur details to that one along with the video
and then close this?

**Comment by lancewf** [comment]
@susanev I think this is a different problem than #1169, because when changing the state the save button does not enable. The user can not save the new state. Where #1169 is wanting a feature where if the state is changed back to the same state as before the save should be disabled.

**Comment by susanev** [comment]
oh i see! thanks for clarifying

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
