### ISSUE TITLE
Setting page not removing empty sections left sidebar

### ISSUE THREAD

**Issue by lancewf** [chef/automate#2501]
## User Story

On the Automate settings page, if a user does not have permission to see any of the "Identity" or "Access Management" pages then the header should not be displayed. Below is a screenshot of this case. 

## Definition of Done
When a user does not have permission to see a section on the settings page that section should not be displayed. 

## Demo Script / Repro Steps
![Screen Shot 2019-12-12 at 9.37.36 AM.png](https://images.zenhubusercontent.com/5d1a3fbf1449416ed898598a/70385347-f374-4845-8590-fafc5f14bb89)

**Comment by susanev** [comment]
@lancewf can you double-check that this won't be resolved by #2467 ?

**Comment by lancewf** [comment]
I will test it out.

**Comment by lancewf** [comment]
The below image was on #2467 branch and it does not look like it fixes the problem. 
![Screen Shot 2019-12-16 at 3 05 10 PM](https://user-images.githubusercontent.com/1679247/70950455-79516180-2015-11ea-981d-6ddbb0c8c919.png)

**Comment by susanev** [comment]
thanks @lancewf it is intended for that pr to fix this, @tarablack01 is gonna take another look

**Comment by susanev** [comment]
this has been fixed.
