### ISSUE TITLE
Automatic Upgrades are not perfect

### ISSUE THREAD

**Issue by ryancragun** [chef/automate#2502]
In a default install automatic upgrades of Chef Automate are enabled by default.
In order to facilitate that we have to guarantee that any version of Chef Automate
can be upgraded to the latest version.

There are many considerations that make that contract difficult to fulfill, including:

* Some software embedded in Chef Automate cannot upgrade between multiple major
  versions. eg: ElasticSearch
* Some software can introduce new system configuration requirements. For example,
  ElasticSearch recently started enforcing sysctl settings instead of just
  recommending them. We cannot allow as system that worked before to not work
  with an automatic upgrade.

Automatic upgrades also introduce a lot of risk to an operational cluster:

* There is no way "preflight check" an update before it occurs
* Releases come out whenever Chef Software publish a new release manifest, users
  cannot schedule a time window for upgrades.
* While highly tested, upgrades could introduce bugs. Users might like the option
  to backup before an upgrade so that in the event an upgrade goes wrong there
  is a sane recovery strategy. They'll also likely want that backup to restore and
  _not_ auto upgrade again.

There are many potential solutions to these issues, and many might be able to
fixed using hammers, but we'd like to avoid them if at all possible. For example,
We could manage sysctl settings by configuring them through systemd, or change
the hab user for some software to root and set sysctls in the run hook before dropping
privileges. We need to determine a baseline for what Chef Automate is responsible
for setting and what the operator is responsible for setting. We need to provide
a solution that allows an operator to safely upgrade if those settings change.

For major softare upgrades, we'll have to build some sort of multi-step upgrade
machinery that doesn't exist yet.

## A user experience that is delightful

I can imagine a user experience that is rather delightful. Upgrades can still
be automatic but in a much safer way:

* Upgrades should be UI driven
* Admins see upgrades and release notes in the UI
* Admins run updated "preflight checks" for the new software before proceeding.
  * If we decide _not to manage_ sysctls (probably a good idea) then we could
    have remediation steps a user could run if the preflight check fails.
    * Bonus, we could have the user "run" them from that very same UI by agreeing
      to the command that we'll run.
* Admins could have an option to auto upgrade if the preflights run succesfully
* Admins could enforce a mandatory backup before the upgrade takes place
* Admins could set an upgrade time window
* A chef-automate CLI interface that can do these things, along with the web UI,
  would be fantastic.

**Comment by susanev** [comment]
this work has been deprioritized.
