### ISSUE TITLE
Track OPA performance over time in CI

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#2519]
## User Story

As Automate auth developers, we would like to know how changes to our OPA logic affect the performance of our key authorization queries (ProjectsAuthorized, FilterAuthorizedProjects, etc).

## Definition of Done
- [ ] we have a way to compare performance on master vs. performance on a PR making changes to OPA

## Brainstorming

Comparing benchmarks
- The most promising tool looks like [benchplot](https://godoc.org/github.com/aclements/go-misc/benchplot):
"Command benchplot plots the results of benchmarks **over time**."
That's an enticing headline... but no examples or docs at all--just source code to figure out what to do with it.
- The [applications-service](https://github.com/chef/automate/blob/master/benchmarks/README.md#comparing-benchmarks-benchstat) uses [benchstat](https://godoc.org/golang.org/x/perf/cmd/benchstat) to compare performance on master vs. an incoming pull request. It's not automated as part of the CI yet though

Charting benchmarks
- [benchdraw](https://github.com/cep21/benchdraw), "A CLI to turn Go's benchmark output into pictures". Most promising since it's designed to work with benchmarks.
- [go-chart](https://github.com/wcharczuk/go-chart) and [plot](https://github.com/gonum/plot are two other options but they would require extra code to work with benchmark data

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
