### ISSUE TITLE
[data-lifecyle] style data lifecycle tab and page

### ISSUE THREAD

**Issue by Shadae** [chef/automate#2523]
## Design Details
[UX Designs in Abstract](https://share.goabstract.com/47da49f4-55df-4be0-be66-018952857ae3?mode=design&sha=84902a48f104fe6bb5f4cefa3754cc83a72ccbe0)

### Settings Left-Nav Updates
- [x] add new _General Settings_ heading, please use text-transform for the casing
- [x] move _Node Lifecycle_ up to that section and rename it to _Data Lifecycle_
- [x] move _Notifications_ up below _Data Lifecycle_

### Page Content
- [x] heading: Data Lifecycle
- [x] subheading: Manage the retention of events, service groups, Chef Client runs, compliance reports and scans in Chef Automate.
- [x] other headings on the page are `font-size: 16px; font-weight: 600`; and should be h2s semantically

## Definition of Done
The above steps are completed.

**Comment by SEAjamieD** [comment]
This portion is finished, going to link all data-lifecycle cards under this one
