### ISSUE TITLE
Document supported and not supported LDAP and SAML providers

### ISSUE THREAD

**Issue by tylercloke** [chef/automate#2530]
## User Story

We know for sure some LDAP and SAML providers are in wide use with IAM V2 and we know a few that will not work (due to Dex not supporting idP initiated SSO for example).

It won't be the full long-term support matrix, but let's document what we know works and what we know doesn't for our own sake and so customers don't go down a route that we know won't work to begin with.

## Overview

- Make sure the public docs clearly state what we **do** support
    - this should include updates to https://automate.chef.io/docs/ldap/ and https://automate.chef.io/docs/saml/
- Maybe make an internal doc (maybe google doc?) that lists what we **dont** support
    - internal cause the docs standard is to document what we do support, not what we dont

## Reference
- [dex supported connectors](https://github.com/dexidp/dex#connectors)
- @bcmdarroch 
    > we don't support SAML with Azure AD because Automate can't consume SAML IdP metadata, which Azure relies on to rotate keys.

**Comment by kagarmoe** [comment]
This is a good idea for internal-facing documentation, which are docs that you write for your own team or for use by another internal org. In nearly all cases, the @chef/docs-team's scope of work follows the technical writing maxim: "Doc what you do, not what you don't".

**Comment by jmassardo** [comment]
Would it be possible to list the known/supported SAML providers on this page (https://automate.chef.io/docs/saml/)?

**Comment by bcmdarroch** [comment]
[dex's support matrix for reference](https://github.com/dexidp/dex#connectors)

we might use this work as a jumping off point for discussing how we could add more connectors (like Azure)

**Comment by sdelano** [comment]
Within this team, we know some things that are being used by customers right now. Let's start by documenting these things. One of the big motivators for this is that people keep trying to use one of the multiple forms of Azure LDAP and SAML providers. Hopefully by clearly stating what we support, it will be clear that the other solutions will not work.

Internal documentation on what doesn't work can live in the codebase.

Quick list of things we know based on meeting:
* MSAD
* Okta
* ... more

For asking customer facing teams. places to inquire:
* #support-team
* Customer Success, Architects, etc.

**Comment by msorens** [comment]
Before the break, I posted in `customer-eng` and `customer-success` to see what customers are using.
Will Fisher provided this partial list (responding in customer-eng):

- Okta
- AZure AD (LDAP/SAML)
- Tivoli Federated Identity Manager
- onelogin

Due to the break, I reposted today in `customer-success` and in `architects`.
