### ISSUE TITLE
Project Update percentage complete and estimated time is not consistent

### ISSUE THREAD

**Issue by lancewf** [chef/automate#2540]
## User Story

During a project update, the percentage complete and estimated time are not consistent. 

Some reasons for this might be:
* The percentage of work complete provided by Elasticsearch during the first minute or so from when the job has started fluctuates. This is calculated in the JobStatus function here https://github.com/chef/automate/blob/12c71d8da50bbfcf0e940a57bbddbb47cf7ae062/components/ingest-service/backend/elastic/elastic.go#L63. 
* Switching between tracking the completion of one domain service task to the other. For example, if the client runs is first predicted to end the latest with %50 complete and then the compliance service is predicted to end the latest with %10 complete. 

## Definition of Done
The reporting of the domain services project update percentage complete and estimated time to complete is more consistent and does not backtrack. 

## Demo Script / Repro Steps
1. Add a lot of data to compliance with `chef_load_compliance_scans -N1000 -D10 -M2 -T20000`
1. Create a project
1. Apply the rules
1. Ensure the percentage complete only increases and the estimated time only decreases.

**Comment by lancewf** [comment]
Some solutions to make this experience more intuitive. 
* Have an initializing status for each domain that shows if all their jobs have started and are reporting percentage complete. 
* Report the lowest percentage complete. Where we are currently reporting the percentage complete of the job that has the latest estimated time complete.

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
