### ISSUE TITLE
ui: Waivers - Profile list reflects the new Waived Status of a profile 

### ISSUE THREAD

**Issue by jonong1972** [chef/automate#2545]
## User Story

As an Automate User, I will use this work when I want to see which profiles have been waived.

## Problem Statement
In the rare case, if a profile has all waived controls within it, we need to show that the profile itself has been waived.

## Definition of Done
1. A user can see if a Profile is waived based on the new status that the API returns for a profile
2. A user can filter by status of Waived

## Mock Ups
![V3 - Compliance - Report - Profiles](https://user-images.githubusercontent.com/1316587/71296588-0574c900-2335-11ea-9219-692b1c910724.png)

**Comment by vjeffrey** [comment]
this work involves: 
- adding the "waived" icon for profiles with a status of waived:
![Screen Shot 2020-02-26 at 05.36.24.png](https://images.zenhubusercontent.com/5cfebc28d99ac71fbfbdcb73/6e9fe230-df5e-43cc-b373-3e0575afae73) 
- ensuring the logic for showing status of a profile accounts for waived profiles
- add status filter buttons to the reporting profiles list page, as shown above. api response already has the info:
![Screen Shot 2020-02-26 at 05.35.28.png](https://images.zenhubusercontent.com/5cfebc28d99ac71fbfbdcb73/9031cd29-0031-41c5-83ab-285c649c27aa)
```
curl -s --insecure -H "api-token: $ACCEPTANCE_TOKEN" https://a2-local-inplace-upgrade-acceptance.cd.chef.co/api/v0/compliance/reporting/profiles -d '{"filters":[{"type":"status","values":["passed"]}]}'
{"profiles":[{"name":"apache-baseline","title":"DevSec Apache Baseline","id":"41a02784bfea15592ba2748d55927d8d1f9da205816ef18d3bb2ebe4c5ce18a8","version":"2.0.0","status":"passed"}],"counts":{"total":1,"failed":0,"skipped":0,"passed":1,"waived":0}}
```

**Comment by vjeffrey** [comment]
load data by using the `load_compliance_reports` command from your studio dev env

**Comment by vjeffrey** [comment]
status filters blocked by https://github.com/chef/automate/issues/3178
