### ISSUE TITLE
ui: Waivers - Profile list shows the waived control within the slide out panel

### ISSUE THREAD

**Issue by jonong1972** [chef/automate#2546]
## User Story

As an Automate User, I will use this work when I want to drill down to the control and see which control was waived.

## Definition of Done
1. A user can click on "Scan Results" on the Profile list page, and then choose a node - which will then show controls that have been waived.
2. Waived control will be displayed at the bottom of the control list.

## Mock Ups
Showing the waived control at the bottom of the list.
![V3 - Compliance - Report - Profiles - Test Results Drawer - Nodes - Controls](https://user-images.githubusercontent.com/1316587/71296658-3c4adf00-2335-11ea-8082-13d68a37ab71.png)

Showing the waived control expanded.
![v3 - Component - Compliance - Report - Profile List - Control Drawer](https://user-images.githubusercontent.com/1316587/71296687-5684bd00-2335-11ea-9e25-8d7f447ad46b.png)

**Comment by vjeffrey** [comment]
this work involves:
- ensure the scan results logic recognizes "waived" status and applies it to controls with waived status
- ensure the scan results logic puts waived controls at the bottom of the list of controls (order is failed, passed, skipped, waived)

**Comment by vjeffrey** [comment]
load data by using the `load_compliance_reports` command from your studio dev env
