### ISSUE TITLE
all new installs of automate should automatically be using iamv2

### ISSUE THREAD

**Issue by susanev** [chef/automate#2547]
## Overview
all new installs of automate should automatically be using iamv2... we should also prolly document this fact.

@stevendanna 
> OK.  There are at last two paths you could take.  A potentially "easy" path is to upgrade installations to v2 as the last step of the deploy command.  Another path would be to build the logic into your service initialization (i.e. if you start the service and see that there is no existing auth database, initialize things with v2 by default, otherwise use what is there)

### Notes from team discussion 2019.12.20

During the interim between GA and force-upgrade-to-v2, we will use the first approach: have the deploy command do the upgrade to v2 for new installations.

Once we do the force-upgrade-to-v2, we will remove that mechanism and add Sqitch migrations into each of the auth-team's services (teams, tokens, authz) to do the same operations that `upgrade-to-v2` command does (making sure it does not interfere with installations of users that have already upgraded to v2).

This second approach would be much more complicated if we did it in the interim between GA and force-upgrade-to-v2 because, by definition, we do not yet want to _force_ the upgrade at that time. Combined with the fact that the interval between GA and force-upgrade-to-v2 is short, it makes sense to do the deploy approach for that period.

**Comment by sdelano** [comment]
Notes: 2020-01-13

* user needs a fresh install of Chef Automate
* user runs `chef-automate deploy`
* magic happens (all the deploy things - plus what we need to make things IAMv2)
* Chef Automate is using IAMv2

* [ ] fix body of story to reflect the work for just this spring (first release)
* [ ] make sure there's a story in the next release to capture the sqitch migrations

**Comment by blakestier** [comment]
Notes (1/14/20)

On implementation:

Code can go in service.go (best wrapped as it's own package similar to usrmgmt)
Code can go in deploy.go at the end of the deploy call 

For both scenarios, need to account for installs in chef-server that might not have iam installed yet.

We will probably not bother with this work, however, bc we'll move straight into using sqitch.

Two branches with the start of work:
https://github.com/chef/automate/pull/2618
https://github.com/chef/automate/tree/auth-2547/fresh-installs-get-iamv2

Notes on tests:

The plethora of failing tests prompted us to close this ticket in favor of addressing test work during the forced upgrade.

Problem, for reference:

The world breaks with this change bc if we have *all* new installs use v2, then all of our buildkite instances will automatically have v2, which means that all tests using v1 (see: diagnostics, authz controls, HA) will fail. We don't want to delete v1 tests bc "people take months to upgrade and you won't find out about bugs until much later and then you'll want the tests to verify fixes" (steven danna).

The short term fix is making all our v2 tests the "norm" which runs on most of our instances, then isolating v1 tests for special bk instances.  In the long term, however, even more work needs to happen as most of our v2 suites aren't as thorough as v1, so some tests need to be ported/duped.

**Comment by susanev** [comment]
from @sdelano 

> We're going to cancel that work. A few (potentially non-related reasons):
> 1. it's a lot of work (definitely more than the small we sized it)
> 2. the work to move / modify the tests would potentially need to be redone for the force-upgrade 
> changes
> 3. the benefit we get from this work is small: we might have a handful of new installs in the month 
> between GA and force-upgrade - which makes it difficult to justify the effort
