### ISSUE TITLE
Bump Angular from 8.x to 9.x

### ISSUE THREAD

**Issue by msorens** [chef/automate#2553]
## User Story

This is a maintenance task to keep Angular up-to-date.
This will bring Angular up to 9.0.

Prior to the actual Angular upgrade there are various maintenance and cleanup tasks that will help smooth the transition.
See the sub-tasks below.

## Definition of Done

Everything still works, but with a cleaner, fresher smell.

**Comment by susanev** [comment]
looks they are holding the release until the new year https://twitter.com/jules_kremer/status/1206645952548720640?s=20

**Comment by susanev** [comment]
this work is currently blocked by https://github.com/angular/components/issues/18507
