### ISSUE TITLE
ui: Waivers - Compliance node detail page displays waived controls

### ISSUE THREAD

**Issue by jonong1972** [chef/automate#2557]
## User Story
As an Automate User, I will use this work when I want to see a waived control on a particular node.

## Problem Statement
We need a way to show which controls were waived at the node level, plus show the reason, expiration date or status if applicable.

## Definition of Done
- A user can navigate to a compliance node detail screen and see which controls were waived.
- A user can see see the reason why a control was waived
- A user can see see the expiration of a waived control if applicable
- A user can see the status of the waived control if it was set to run.
- A user can filter by waived controls

## Mock Ups
Showing a control on the node that had run, but was waived.
![V3 - Compliance - Report - Node Detail](https://user-images.githubusercontent.com/1316587/71296780-aa8fa180-2335-11ea-85a2-134ec478db34.png)

Row showing a control that did not run, but was skipped.
![v3- Component - Compliace - Report - Node Detail - control row - skipped State](https://user-images.githubusercontent.com/1316587/71296751-964ba480-2335-11ea-8961-a1d682aca824.png)

**Comment by vjeffrey** [comment]
this work involves:

- ensure the status logic recognizes "waived" status and applies it to controls with waived status
- show waiver information in the control results section, as shown in designs above
(note: only need the expires and reason details, not the node status ones - the api will not return node status stats)

**Comment by vjeffrey** [comment]
load data by using the load_compliance_reports command from your studio dev env

sample api response for a waived control:
<img width="531" alt="Screen Shot 2020-03-08 at 21 01 58" src="https://user-images.githubusercontent.com/10341541/76249561-36b0b700-6209-11ea-9de1-10476eb6247c.png">
