### ISSUE TITLE
ui: Waivers - Profile detail page displays waived controls

### ISSUE THREAD

**Issue by jonong1972** [chef/automate#2558]
## User Story
As an Automate User, I will use this work when I want to look at the waived controls of a profile.

## Problem Statement
We need a way to show waived controls at the profile view. In addition showing the count of nodes that were waived on the effected control.

## Definition of Done
- A user can go to a Reports Profile detail page and see which controls where waived
- A user can see on the report profile detail page how many nodes where affected by a waived control
- A user can filter by Waived controls

## Mock Ups
![V3 - Compliance - Report - Profile Detail](https://user-images.githubusercontent.com/1316587/71205150-b193b280-2256-11ea-904a-2cf0eaa5d1e6.png)

**Comment by vjeffrey** [comment]
this work involves:
- adding logic to the function that controls the node status column to recognize a waived control and ensure those are displayed correctly

load data with `load_compliance_reports`
information is returned from api:
<img width="1219" alt="Screen Shot 2020-03-08 at 21 07 41" src="https://user-images.githubusercontent.com/10341541/76179602-1210fc80-6181-11ea-817b-6a2203d8457e.png">
