### ISSUE TITLE
Ability to delete profiles with blank titles from the Automate GUI

### ISSUE THREAD

**Issue by sandratiffin** [chef/automate#256]
# User Story

As an Automate User, I would like to be able to delete profiles with blank titles, from the GUI.

# Definition of Done

There is a way to delete profiles with blank titles from the GUI. 
There should probably be trash can icons on the 'Asset Store' page next to downloaded profiles.

# Demo Script / Repro Steps

Upload a profile that has no 'title:' in inspec.yml. 
As there is no title, you cannot click on a title to get to the detail screen for the profile that has a remove button.
(Seen in Chef Automate 20190501153509)

**Comment by vjeffrey** [comment]
yes, implementing some kind of quicker way to delete profiles is definitely on our radar, thanks for opening the issue!
cc @jonong1972 

it might be a bit before we get around to implementing that functionality, so in the meantime, as a workaround, you can:
- take a look at the network response for the asset store page, and find the profile with the missing title.
- the delete profile api looks like `https://a2-url/api/v0/compliance/profiles/admin/cis-aws-foundations-level1/version/1.1.0-7`, the values there being `{owner}/{name}/version/{version}`

so if you can locate the name and version for the profile, that should allow you to do a manual delete

**Comment by susanev** [comment]
we can maybe address this with the content delivery service work, but otherwise, this is deprioritized, so closing.
