### ISSUE TITLE
Applications: add accordion for long health check messages

### ISSUE THREAD

**Issue by danielsdeleo** [chef/automate#2573]
## User Story

#2572 does not include the "accordion" functionality described in #2554

When error messages exceed 3 lines (about 140 characters), the rest of the message should be hidden and a control to "show more" should be presented. When clicked, it reveals the rest of the message.

This is intended to make the UI more "scannable" to see when lots of services all have the same error message; if the error messages are too long, there's too much distance between the different services.

Refer to #2554 for demo script &etc.

Aha! Link: https://chef.aha.io/epics/A2-E-187

**Comment by SEAjamieD** [comment]
@danielsdeleo  -  is there a max character length on this health check messages?  I thought I read that they would never exceed 1024 characters.  Can you confirm?

**Comment by danielsdeleo** [comment]
@SEAjamieD Yes, they are limited to 1024 characters. If you use `applications_populate_database` in the studio you should get some different edge cases, like a message that is 1024 characters with no breaking space type characters.
