### ISSUE TITLE
ui: Waivers - Compliance Node List page shows waived controls in slide out drawer

### ISSUE THREAD

**Issue by jonong1972** [chef/automate#2575]
## User Story

As an Automate user, I will use this work when I want to see which controls were waived on a node and the details about the waiver.

## Problem Statement
With the new feature of waivers, we need to be consistent in showing our data. So we will need to show the state of a control within the side panel.

## Definition of Done

- A user can drill down to the scan results of a node and see the waived control
- A user can expand said control and see the expiration, reason or status if applicable.

## Mock Ups
Showing the slide out drawer with the waived control sorted at the bottom
![V3 - Compliance - Report - Nodes - Test Results Drawer - Controls](https://user-images.githubusercontent.com/1316587/71297306-dad83f80-2337-11ea-850b-6fce9d505b18.png)

Showing the expanded control details.
![Screen Shot 2019-12-20 at 2 49 35 PM](https://user-images.githubusercontent.com/1316587/71297343-fcd1c200-2337-11ea-9c2b-9aab55a4feb1.png)

**Comment by vjeffrey** [comment]
i believe all the scan results logic is in one place, so this may end up being a dup of https://github.com/chef/automate/issues/2546

**Comment by vjeffrey** [comment]
closing this b/c above comment. will re-open if needed
