### ISSUE TITLE
[BETA] Automate API not reporting Habitat Service that appears in UI

### ISSUE THREAD

**Issue by sirajrauff** [chef/automate#2610]
## Describe the bug
A habitat service reporting to Automate is visible in the UI but does not appear in the API at the `/v1/applications/service-groups` or `/v1/applications/services` endpoints.

## To Reproduce
I started a Supervisor in a container with `EVENT_STREAM` enabled, reporting to Automate. I loaded a single service on this instance and was able to see it in Automate UI as well as through the API. I shut down the Supervisor & destroyed the container. I did this 3-4 times in the space of about 20 minutes (Jenkins library testing).

An hour later the Automate UI was displaying 4 disconnected instances of the service (I had opened this tab new, so it was not cached). I started up a new Supervisor in the same scenario; the new Supervisor/service instance appeared in the UI, but was absent in the API at `/services` or `/service-groups`. In fact, _none_ of the service instances for this group, new or old (disconnected), appeared in the Automate API calls. I terminated the Supervisor and destroyed the container & re-tried with the same results; the UI now reported 6 total, 4 disconnected and the API did not show the group in `/service-groups` or the instances in `/services`.

I can see _some_ disconnected instances from other groups, though even those have issues; e.g. for one group that has 6 nodes, 4 disconnected, I can only see 1 out of 4 disconnected services through the API. All of them are visible in the UI and disconnected in the same 1-2 minutes, and I waited a few minutes and retried to see if Automate was cleaning up old nodes.

## Expected behavior
I expect to see the service group appear in `/service-groups`, as the group still exists and is visible in the UI. I also expected the old, disconnected instances appear in `/services` as they were also appearing in the UI.

## Screenshots
Can't post screenshots directly on here due to this being a customer system, but can provide this directly to Chef engineers if required.

## Versions (please complete the following information):
- OS: centos7 based Docker container
- Browser: Chrome
- Automate Build Number: 20191125162734

**Comment by danielsdeleo** [comment]
Thanks for reporting this. 

What the exact URLs (with all parameters) you are using with these APIs? It could be something else but at the moment my hypothesis is that pagination is "hiding" the results on a later page. 

When no pagination parameters are specified, you will only see the first page with a page size of 25 results. The UI uses these default sort and pagination parameters: `?sorting.field=percent_ok&sorting.order=ASC&pagination.page=1&pagination.size=25` (e.g., a full URL like  `https://a2-dev.test/api/v0/applications/service-groups?sorting.field=percent_ok&sorting.order=ASC&pagination.page=1&pagination.size=25` ).

**Comment by sirajrauff** [comment]
@danielsdeleo this was it. I remember seeing docs on pagination at https://automate.chef.io/docs, but I can't seem to find it anymore - this might've been why I hadn't thought of this. I can see these are documented in the Automate repo in the Swagger JSON files, is there anywhere on the online docs these are present?

**Comment by danielsdeleo** [comment]
@sirajrauff the Swagger-based content is being improved and will be published online at some point in the future, but I don't know when that's expected to ship.
