### ISSUE TITLE
Browser console error upon selecting “Sign In”

### ISSUE THREAD

**Issue by msorens** [chef/automate#2662]
## Describe the bug
Once you enter a local user name and password and select “Sign In”, the error shown appears in the browser console log. Since it mentions Okta it might be an internal thing, but merits some investigation.
<img width="442" alt="image" src="https://user-images.githubusercontent.com/6817500/72780303-63662c00-3bd3-11ea-9b27-8112943f9aba.png">

## To Reproduce
- open up an A2 instance (either https://a2-dev.test/ or https://a2-iamv2p1-local-inplace-upgrade-acceptance.cd.chef.co/ or other will do).
- open up browser dev tools (<kbd>cmd</kbd> + <kbd>opt</kbd> + <kbd>i</kbd> on chrome)
- Navigate to Console (1) >> Settings (2) >> Preserve log (3) and enable that setting.
<img width="450" alt="image" src="https://user-images.githubusercontent.com/6817500/72780692-53028100-3bd4-11ea-9bac-9c4151ca076c.png">

- login as a local user
- observe the console output in dev tools.

## Expected behavior
No error should display.

## Versions (please complete the following information):
- OS: macOS
- Browser chrome
- Automate Build Number 20200115001116

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
