### ISSUE TITLE
URL meta-characters not properly escaped in V1 team names

### ISSUE THREAD

**Issue by msorens** [chef/automate#2663]
## Describe the bug
Including an octothorp (`#`) in a V1 team id causes a problem when fetching that team once upgraded to V2. There is no problem creating and using it in V1 because the team is referenced by GUID in V1. But when upgrading to V2, an octothorp in the ID becomes a problem.
In the image, notice the final character where it indicates “the actual ID”. We are just plugging that ID into a URL string, but an octothorp is a meta-character signifying “URL fragment”, which is why it disappears ("what got passed").

<img width="985" alt="image" src="https://user-images.githubusercontent.com/6817500/72781046-331f8d00-3bd5-11ea-8ef6-c806162ce404.png">

This should have been an easy fix in team.requests.ts--changing this…
```
return this.http.get<TeamResponse>(`${env.auth_v2_url}/teams/${id}`);
```
to this...
```
return this.http.get<TeamResponse>(`${env.auth_v2_url}/teams/${encodeURIComponent(id)}`);
```
But that did something very peculiar: duplicating the call, one done the original way and one done the correct way:
<img width="449" alt="image" src="https://user-images.githubusercontent.com/6817500/72781095-5d714a80-3bd5-11ea-980c-7c15cac7e9ac.png">

## To Reproduce
- set to V1 (`chef-automate iam reset-to-v1`)
- navigate to Teams >> Create Team and create a team with an octothorp (or other URL meta-character in it).
- upgrade to V2 (`chef-automate iam upgrade-to-v2`)
- navigate to Teams then select your team name. Observe the error on the team details page.

## Expected behavior
Should be able to fetch the team details for a team with URL meta-characters in the name.

## Versions (please complete the following information):
- Automate Build Number 20200119205143

## Other Notes
- Same issue would probably occur for other URL metacharacters: `?` , `,`, `%`.
` Probably not very high priority since we are trying to get everyone moved to V2.

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
