### ISSUE TITLE
Annotate tokens.proto with API docs

### ISSUE THREAD

**Issue by tylercloke** [chef/automate#2694]
See the parent issue for more details.

# Acceptance Criteria

* API documentation is updated for all endpoints in [tokens.proto](https://github.com/chef/automate/blob/master/components/automate-gateway/api/iam/v2/tokens.proto) and related common / request / response files.
* Link to these new docs and remove the old ones [from here](https://automate.chef.io/docs/iam-v2-api-reference/).

**Comment by susanev** [comment]
closing in favor of #2982
