### ISSUE TITLE
stabilize flaky team_details cypress tests

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#2699]
see epic #2702 for high level description

TLDR; make these [itFlaky tests](https://github.com/chef/automate/blob/master/e2e/cypress/integration/ui/settings/team_details.spec.ts#L180) not flaky!

**Comment by bcmdarroch** [comment]
Did some digging into this. The current tests around updating the team's projects seem to hit a bug when changing the global filter. If you navigate to a team's details page and set the project filter to different projects, you will run see a Not Found error banner come up after each filter is applied, even if the team belongs to the project in the filter.

**Comment by susanev** [comment]
this work has been deprioritized.
