### ISSUE TITLE
Stabilize cypress tests

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#2702]
## User Story

Right now, the flaky test suite fails pretty much every time. :(
Example buildkite run: https://buildkite.com/chef/chef-automate-master-verify-private/builds/8844#21d12828-bb1f-4ac3-adf8-987e8a3e4949

The dream: all Cypress tests pass reliably and there's no need for a `flaky` test suite. 

How we get there: This will require some investigation for each test. It will probably require some combination of improving the deterministic behavior of Automate UI and refactoring Cypress tests to wait for certain conditions to be true before proceeding. 

Note: Since most of these flaky tests pass locally, steps should be taken to more closely match the conditions of buildkite runs: try slowing down the network of your Cypress test browser to `Slow 3G`, or set `CYPRESS_BASE_URL=https://<some dev or acceptance environment>`

## Definition of Done

- [ ] Cypress tests pass consistently both locally and in the buildkite pipeline
- [ ] [stretch] there is no need for a separate `flaky` test suite

**Comment by susanev** [comment]
this work has been deprioritized.
