### ISSUE TITLE
Enforce ID/Name required for CreateToken in v2

### ISSUE THREAD

**Issue by blakestier** [chef/automate#2718]
## User Story

When I try to create a token via cURL in IAM v2, I get an error message if I leave either the "id" field or the "name" field blank.

Current behavior:

If I leave the name blank, I get:

```curl -kH "api-token: $TOK" -X POST -d '{}'  https://a2-dev.test/apis/iam/v2/tokens | jq .
{
  "error": "pq: new row for relation \"chef_authn_tokens\" violates check constraint \"chef_authn_clients_description_check\"",
  "code": 13,
  "message": "pq: new row for relation \"chef_authn_tokens\" violates check constraint \"chef_authn_clients_description_check\"",
  "details": []
}```

If I leave the ID blank, the tokens backend auto-generates a GUUID. 

```curl -kH "api-token: $TOK" -X POST -d '{"name":"GEORGE"}'  https://a2-dev.test/apis/iam/v2/tokens | jq .

{
  "token": {
    "id": "91ec64ea-c801-4172-8f68-0f16cf0abb7a",
    "name": "GEORGE",
    "value": "woAA6f8fdsV_wVlSkENIEiJ5M6w=",
    "active": true,
    "created_at": "2020-01-24T22:14:04Z",
    "updated_at": "2020-01-24T22:14:04Z",
    "projects": []
  }
}```

## Definition of Done


## Demo Script / Repro Steps

**Comment by blakestier** [comment]
Part of the problem here might be how we are attempting to support v1 users

**Comment by bcmdarroch** [comment]
I think this could be merged with this [authn v1 cleanup card](https://github.com/chef/automate/issues/2741), since this behavior is a result of supporting both the V1 and V2 versions of the Tokens API. Once we're ready to drop v1 code in authn-service, we could add proto validations to enforce ID/Name in create requests

**Comment by bcmdarroch** [comment]
merged with https://github.com/chef/automate/issues/2741
