### ISSUE TITLE
remove IAM v1 code from authz-service

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#2739]
## Goal

Remove backend v1/v2 conditional logic from the authz-service.

Note: this work should be split into a few PRs.

## Definition of Done

- [x] remove the [interceptor](https://github.com/chef/automate/blob/master/components/authz-service/server/v2/authz.go#L269-L312)
- [x] remove [version switch](https://github.com/chef/automate/blob/master/components/authz-service/server/v2/authz.go#L30) from authz server state (don't forget the [switching channel](https://github.com/chef/automate/blob/master/components/authz-service/server/v2/authz.go#L314))
- [x] drop the [v1 server implementation](https://github.com/chef/automate/tree/master/components/authz-service/server/v1) (little bit left)
- [x] remove from OPA: 
     - [x] [v1 cache](https://github.com/chef/automate/blob/master/components/authz-service/engine/opa/opa.go#L27)
     - [x] [v1 partial evaluation result](https://github.com/chef/automate/blob/master/components/authz-service/engine/opa/opa.go#L32)
     - [x] v1 authorization checker [IsAuthorized](https://github.com/chef/automate/blob/master/components/authz-service/engine/opa/opa.go#L269)
     - [x] v1 OPA [helpers](https://github.com/chef/automate/blob/master/components/authz-service/engine/opa/opa.go#L217)
     - [x] [v1 introspection rego](https://github.com/chef/automate/blob/master/components/authz-service/engine/opa/policy/introspection.rego) and [v1 authorization rego](https://github.com/chef/automate/blob/master/components/authz-service/engine/opa/policy/authz.rego)
     - [x] [v1 example policies](https://github.com/chef/automate/tree/master/components/authz-service/engine/opa/example)

**Comment by srenatus** [comment]
Ugh misclicked

**Comment by srenatus** [comment]
There's also the _subject purge_ functionality. It's been exposed under `authz/common`, next to `authz/v1` and `authz/v2`. I suppose this could be merged with the one-and-only authz proto service definition now...
