### ISSUE TITLE
Add extended color palette

### ISSUE THREAD

**Issue by apriofrost** [chef/automate#275]
_Feedback from 05/19 backlog grooming: need a technical spike on this. Currently, color definitions exist in different files in the Stencil library as CSS variables, and in SaaS variables in Angular.  Further investigation needed for switching HSL to HEX._

# Problem

Our current color palette has a limited set of greyscales and status colors. It's limited in several ways:

- When designing for hovering/active state style for an element using existing colors, the lack of shades variations make it impossible to do so. We tried solving this problem by using HSL and create the shades mathematically, but the conversion between HSL and HEX can cause inconsistent HEX values when converting back. Besides, some of the shades calculated with HSL could make the color contrast of text and background become not accessible. 

- For the upcoming work for the [mini donut chart in table rows](https://github.com/chef/automate/issues/272), the existing status colors don't perform well enough. All status colors are in similar shades, and their positions are very close when put on a color wheel, making the chart difficult to read when the size is small. 

- A similar situation appears when trying to make the [badge component](https://github.com/chef/automate/issues/262) accessible in color contrast and consistent in styles.

- For the EAS project, we need a status color for an icon to represent `warning` status for services and service groups. The current `chef-major` and `chef-minor` are too similar to `chef-critical`. Previously, we tried to avoid using the conventional yellow or orange colors for `warning`, because of the difficulty to make the color contrast accessible with white text, but that problem can be solved with careful selection of the shades and style design (see example in [badge component](https://github.com/chef/automate/issues/262)). 

- Furthermore, if we take a look at the current greyscales used in Automate, there a quite a few places where we use customized greyscales outside the existing palette, further proves the need for more greyscale colors.

Therefore, we propose adding an extended color palette to the existing one. The only change is to remove `chef-grey` or replace it with another shade in the fog or grey color shades, depending on how we use it today (needs further investigation).

# Definition of Done
- Add a new set of color variables to the existing color palette. 
- Remove any HSL colors, and use HEX values for all colors.
- Share the final color variable names with the design team, so they can update the Sketch master file to match the color variable names in the code. In the future, designers and engineers can refer to colors with the same name to avoid mismatch of colors.

- updating `chef-grey` will be a separate card

# Color Palette Spec
All color names start with `chef` are the existing colors found in the[ UI library](https://ui-library.cd.chef.co/design). The rest color names are auto-generated and can be updated as we see fit.

See palette here: https://chef.invisionapp.com/share/AWRWGIMVMDC#/362080628_Extended_Color_Palette

Note: after the UI team decided on the names for the colors, @apriofrost can export all colors with names and HEX values to a .css file.

**Comment by susanev** [comment]
this work is deprioritized, so closing.
