### ISSUE TITLE
Error alerts styling & behavior in trial license modal

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#2751]
## Describe the bug

There are two main issues with these errors:
**1. The errors in the trial license modal do not have the expected styles.**

![Screen Shot 2020-01-29 at 10 05 20 AM](https://user-images.githubusercontent.com/21015366/73400478-11da3300-429e-11ea-90bf-f2476e960170.png)

They should look like this:
<img width="390" alt="Screen Shot 2020-01-29 at 1 49 14 PM" src="https://user-images.githubusercontent.com/21015366/73400538-30402e80-429e-11ea-9a80-e8ac940e8b41.png">

It looks like the `chef-error` in the modal is not properly inheriting the `.chef-error` class.

`chef-error` element rendered on license-lockout modal
```
<chef-error _ngcontent-qgm-c1="">
           Valid email required.
</chef-error>
```

`chef-error` element rendered on create-user modal
```
<chef-error _ngcontent-iqu-c28="" class="chef-error ng-star-inserted">
            Display name is required.
</chef-error>
```

**2. The errors do not pop up if you tab past them**
I can tab through all of the form fields without getting any error feedback.

The create-user modal component on https://a2-dev.test/settings/users demonstrates the behavior we expect: if a user leaves an input without entering a value, a `Field is required` error should pop up.

## To Reproduce
**1. styling issues**
- start up Automate + UI
- run `chef-automate dev psql chef_license_control_service -- -c "UPDATE licenses SET active=NULL"`
- open the UI or refresh to see the trial license modal
- type a single character in the email field to see the error pop up

**2. tabbing**
- after removing the UI, open the UI or refresh to see the trial license modal
- tab through the input fields

## Versions (please complete the following information):
- Browser: chrome
- Automate Build Number: 20200129212217

**Comment by susanev** [comment]
i noticed this a bit ago, im not sure they ever had these styles though. def good to get them added though.

**Comment by bcmdarroch** [comment]
Yeah I feel like there must be some inheritance issue we need to resolve, since the license lockout modal is at a higher level in the layout than most of our other components 🤔

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
