### ISSUE TITLE
Project dropdown flashes "unassigned" on update

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#2754]
## Describe the bug
When updating projects on a team or token, the project dropdown flashes `unassigned` before showing the correct number of projects.
![unassigned_flash_project_save](https://user-images.githubusercontent.com/21015366/73403536-79937c80-42a4-11ea-8e0a-cb0d926686d0.gif)

## To Reproduce
- start Automate + UI 
- navigate to https://a2-dev.test/settings/projects and create a few projects
- navigate to https://a2-dev.test/settings/teams (or https://a2-dev.test/settings/tokens)
- create a team in a couple projects
- navigate to their details page, then the details tab
- update the projects by adding or removing some, click save
- the project dropdown will briefly flash `unassigned` (you may need to use dev tools to slow your network down to `Slow 3G` to see it clearly)

## Expected behavior
The label on the dropdown should only show the correct number of projects. It should display nothing if it's still loading the number of projects.

## Versions:
- Browser: chrome
- Automate Build Number: 20200129212217

**Comment by susanev** [comment]
nice find, @SEAjamieD do you have thoughts on how to fix this?

**Comment by SEAjamieD** [comment]
Not off the The top of my head but I kind of think this will fix itself
when I move the filter dropdowns to an ngrx pattern - which is my top
priority after this builder card.  If it’s ok to leave this for a few days,
I’ll pick it up at the same time as the ngrx ticket
-- 

Jamie Degnan — Software Development Engineer

jdegnan@chef.io

CHEF

chef.io <http://www.chef.io/>   Blog <https://blog.chef.io/>   Facebook
<https://www.facebook.com/getchefdotcom>   Twitter
<https://twitter.com/chef>   Youtube <https://www.youtube.com/getchef>

619 Western Ave Suite 400, Seattle, WA 98104

**Comment by susanev** [comment]
there is no rush at all on this!

**Comment by SEAjamieD** [comment]
Closing - this has been fixed elsewhere along the way.
