### ISSUE TITLE
Active tab highlight on reports page is inconsistent

### ISSUE THREAD

**Issue by phiggins** [chef/automate#2757]
I noticed two inconsistencies on the compliance reports page around highlighting which tab is active.

To repro:
* From the Automate dashboard, click Compliance in the header.
* On acceptance, as of this writing, choose "22 Jan 2020" in the date selector to have nodes listed.

* Click one of the tabs. It gets a grey background and blue underline to indicate it is active.
![Screen Shot 2020-01-29 at 5 10 41 PM](https://user-images.githubusercontent.com/22962/73411464-4c51c900-42ba-11ea-8bc9-3a56ffbbc52b.png)

* Click anywhere else on the page. The active tab keeps the blue underline but the grey background disappears.
![Screen Shot 2020-01-29 at 5 11 23 PM](https://user-images.githubusercontent.com/22962/73411479-64c1e380-42ba-11ea-8d8e-2bf977558241.png)

* In the search bar, select a filter. The active tab has now lost the grey background and blue underline.
![Screen Shot 2020-01-29 at 5 12 23 PM](https://user-images.githubusercontent.com/22962/73411530-93d85500-42ba-11ea-8d32-01d02afa590d.png)

* If I select a new tab, it gets the grey background but no blue underline.
![Screen Shot 2020-01-29 at 5 13 23 PM](https://user-images.githubusercontent.com/22962/73411560-ad799c80-42ba-11ea-9e15-73b9aab5b222.png)

* Click anywhere else on the page. The active tab does not have a grey background or blue underline.
![Screen Shot 2020-01-29 at 5 14 04 PM](https://user-images.githubusercontent.com/22962/73411591-c5512080-42ba-11ea-9e7a-9a2059655a42.png)

**Comment by susanev** [comment]
some of this is captured in #1810

**Comment by susanev** [comment]
oh nm vj already linked.. ignore me

**Comment by SEAjamieD** [comment]
Note: The blue underline for an active tab has been fixed already.

@susanev - Need some UX guidance here.  The grey background isn't actually a bug.

The Grey Background is applied during a `hover` or a `focus`.  You can recreate by hovering over any of the tabs, you will see the grey background applied.  You well also see the grey background leave a tab when the user clicks outside of the tab.  Another way to view this styling is to use the keyboard controls.  As a user tabs through the various tabs, you'll see the grey background applied.

What type of styling would you like applied here?

**Comment by susanev** [comment]
yah this is fine, we can close this.
