### ISSUE TITLE
fix experience when changing docs page names

### ISSUE THREAD

**Issue by susanev** [chef/automate#2778]
## Overview
In the past, a number of docs page names have been changed which creates 404s when people visit the old pages. This is especially true when people bookmark or when our docs pages are linked in blog posts.

in the past we [added aliases](https://github.com/chef/automate/pull/2276). 

## Pages that have changed and werent aliased
these are just the ones i know about.. there are probably more

- "/docs/authorization/" - > "/docs/iam-v2-overview/"
- "/docs/credentials/" - > "/docs/node-credentials/"
- "/docs/integrations/" -> "/docs/node-integrations/"
- "/docs/integrations-ui/" -> "/docs/node-integrations/"
- "/docs/asset-store/" -> "/docs/profiles/"
- "/docs/users-and-teams/" - > "/docs/users/"
- "/docs/admin/" - > "/docs/users/"
- "/docs/oauth/" -> "/docs/on-prem-builder/"

I had opened a [pr](https://github.com/chef/automate/pull/2777) to address this but closed to give the docs team a chance to strategize a better solution.

**Comment by susanev** [comment]
@kagarmoe wanted to check back in on this, do yall have another solution for adding these aliases? or if not, can i reopen that pr?

**Comment by kagarmoe** [comment]
OK to reopen @mjingle can handle.

**Comment by susanev** [comment]
this has been deprioritized.
