### ISSUE TITLE
Clean up IAM V1 terraform and other infrastructure

### ISSUE THREAD

**Issue by tylercloke** [chef/automate#2782]
Drop the version tags from our terraform files and clean up any associated IAM V1 tf data (should we visit acceptance environments as part of this card?):

* https://github.com/chef/automate/blob/master/terraform/test-environments/scenarios/single_local_iamv2p1_fresh_install.tf
* https://github.com/chef/automate/blob/master/terraform/test-environments/scenarios/single_local_iamv2p1_inplace_upgrade.tf

**Comment by bcmdarroch** [comment]
I think at this point we can drop all the "iam" specific envs
