### ISSUE TITLE
add unit tests for modal close behavior

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#2800]
## Description
This is tiny but it'd be great to have unit tests around these modal behaviors:
- [ ] modal closes if `cancel` button is clicked
- [ ] modal closes if `esc` key is typed
- [ ] modal closes if `x` button is clicked
- [ ] any other key modal behaviors you can imagine!

(so we can take them out of our acceptance test criteria)

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
