### ISSUE TITLE
User ID input does not reset to hidden after closing create modal

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#2801]
## Describe the bug
When I open the Create User Modal, the ID input starts out hidden because the ID gets autogenerated from the display name. You can click `Edit Username` to open the input to edit yourself.

## To Reproduce
- start Automate UI
- navigate to https://a2-dev.test/settings/users
- open the Create User Modal
- click `Edit Username`
- close the modal
- open the modal again
- the Username input will still be open

## Expected behavior
The Username input should always reset to hidden on modal close

## Versions
- Browser: chrome
- Automate Build Number: 20200131232134

**Comment by susanev** [comment]
@bcmdarroch could you add this to #1668 instead?

**Comment by bcmdarroch** [comment]
will be fixed in https://github.com/chef/automate/issues/1668
