### ISSUE TITLE
give more hints to the user when profile being uploaded to automate is not vendored

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#281]
# User Story

If a user tries to upload a profile to Automate, and the profile has dependencies and is not vendored, the user will receive a message like:
```
rpc error: code = Internal desc = InSpec archive failed for /hab/svc/compliance-service/var/tmp/inspec-upload125323500/cis-rhel7-server-l1-wrapper with message: exit status 1

Cannot fetch compliance://admin/cis-rhel7-level1-server because your compliance token has not been
configured.

Please login using

    inspec compliance login https://your_compliance_server --user admin --insecure --token 'PASTE TOKEN HERE' 
```
in the GUI. Unfortunately, this does not mean much to many users. We should add a little line to let the user know they should vendor their profile is we receive this error.

# Definition of Done
Error has better information.

**Comment by sachin-msys** [comment]
@vjeffrey I have tried to reproduce this issue by uploading some profiles but not seen anything like above mention error, Please can you provide a sample profile by which I can reproduce above issue.

**Comment by vjeffrey** [comment]
i'm also having trouble reproducing the issue. 
i created a profile with a dependency.
did not vendor, ran tar on it
profile wasnt recognized structure by inspec when i tried to upload
so then i tried to inspec archive it, and that complained about the lack of login.
so i can't actually create a profile that would cause this failure (anymore)
closing, thanks for looking into it!
