### ISSUE TITLE
Automate api Docs site broken in Chrome

### ISSUE THREAD

**Issue by msorens** [chef/automate#2828]
## Describe the bug

Ensure Chrome is updated to version 80.

Note: not 100% sure Chrome v80 is the culprit but several factors lend credence to the assertion:
(a) Chrome 80 caused other rendering problems in Automate itself (see https://github.com/chef/automate/pull/2825),
(b) docs are working fine in Firefox, and
(c) no one has reported this as a problem previously indicating it is likely very recent and thus coincident with the Chrome 80 update.

Load https://automate.chef.io/docs/api/#operation/Node%20Export in Chrome.
At first glance the page looks OK, but as soon as you try to interact you should see odd behaviors.

Example:
Scroll the main panel a little bit up or down and the navigation panel seems to react properly, changing the current topic indicator. But scroll the main panel up to the top of the Reporting section and the navigation panel goes away. In reality, it has jumped to a fixed position (now offscreen) at the top of the viewport.

Scroll all the way to the top to bring the navigation panel into view. Try expanding items in the navigation panel and it does not respond.

## Expected behavior
Interaction works correctly, as it does in Firefox.

## Versions (please complete the following information):
- OS: macOS
- Browser: Chrome v80

**Comment by susanev** [comment]
@msorens can you add a video? im not able to repro this but also dont fully understand your description.

**Comment by susanev** [comment]
i am able to repro. seems though refreshing fixes this as well. ill add that the api docs are affected as well in the known issues of the release notes.

**Comment by phiggins** [comment]
It sounds like this might have been fixed upstream in redoc. I can investigate tomorrow AM. https://github.com/Redocly/redoc/issues/1168

**Comment by phiggins** [comment]
I've got a PR open to fix this https://github.com/chef/automate/pull/2835
