### ISSUE TITLE
placeholder: ui research spike

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#2878]
https://github.com/chef/platform/issues/36

**Comment by SEAjamieD** [comment]
What date are we hoping to have this research completed by?

**Comment by vjeffrey** [comment]
by end of february

**Comment by vjeffrey** [comment]
in prioritization mtg on monday, we discussed that the work for this card involves linking all the google docs documenting the research the team put together in this card

**Comment by Shadae** [comment]
SaaS UI "Best Practices" Research Spike: https://docs.google.com/document/d/13rNArR8RgKDBOQI82NXcvYhmlSv3rGcLngC4kQnD1TY/edit#

UI Team Thoughts on MicroUIs 2 and Meeting Notes: https://docs.google.com/document/d/1km9Jx5ut-YIAw8FFXZ_UOdJhXKrhLjfyhTaK_uxI-vM/edit#

UI Team Thoughts on MicroUIs 1: 
https://docs.google.com/document/d/1OawDlll2Nonx2_KUQjrurmT2RL0lCf6-XxgODNYuo9U/edit?usp=sharing

**Comment by vjeffrey** [comment]
thank you! i'm going to close this as completed!
