### ISSUE TITLE
Odd text on deletion of admin token

### ISSUE THREAD

**Issue by blakestier** [chef/automate#2879]
If I attempt to delete an admin token, I get an oddly worded message with inconsistent capitalization and spacing.

![Screen Shot 2020-02-13 at 12.50.54 PM.png](https://images.zenhubusercontent.com/5d24fdf9dc67db59a676ebc6/055bbde5-6db9-4b8c-88f7-83a2bc0f12f1)

**Comment by susanev** [comment]
oh, this is because of the token is named that.. this is fixed on v2. im gonna close this.
