### ISSUE TITLE
No permissions on project filter causes odd message

### ISSUE THREAD

**Issue by blakestier** [chef/automate#2882]
When I navigate to a team details page, if I don't have access to the projects filter, I still see a message "Expecting more projects? Try adjusting your filter" 

 ![Screen Shot 2020-02-13 at 1.59.41 PM.png](https://images.zenhubusercontent.com/5d24fdf9dc67db59a676ebc6/4a30eba3-484b-4af4-b173-7d7a176de10f)

**Comment by susanev** [comment]
this work has been deprioritized.
