### ISSUE TITLE
See dropdown/filter when I only can access one project

### ISSUE THREAD

**Issue by blakestier** [chef/automate#2883]
When on the team details page, if I only have one project, I still see a filter projects bar.

![Screen Shot 2020-02-13 at 2.01.40 PM.png](https://images.zenhubusercontent.com/5d24fdf9dc67db59a676ebc6/aed23cc3-0185-41e8-84fb-ac8324c6db8a)

**Comment by susanev** [comment]
deprioritized, so closing.
