### ISSUE TITLE
Clear Selection incorrectly enabled/triggering refresh

### ISSUE THREAD

**Issue by blakestier** [chef/automate#2886]
When i open the "Global Projects Dropdown" and have no projects selected, I see "Clear Selection" enabled. Selecting "Clear Selection" refreshes the page although my selections haven't changed.

Likewise, when i open the "Global Projects Dropdown" and have no projects selected, select a project, and then select "Clear Selection", the page refreshes although my selections haven't changed.

**Comment by susanev** [comment]
this seems to have been fixed, unable to repro so closing
