### ISSUE TITLE
step through setting up saml + azure ad and add to automate docs

### ISSUE THREAD

**Issue by susanev** [chef/automate#2887]
## Overview

step through setting up saml + azure ad and add to automate docs

[how to setup saml with azure ad](https://github.com/chef-cft/chef-examples/blob/master/examples/A2SamlWithAzureAD.md). Let's try it out and confirm that it works and then add it to the [supported list](https://automate.chef.io/docs/saml/#supported-identity-management-systems) along with any information needed for others to set it up.

@mjingle needs to review and edit before merge.

**Comment by jmassardo** [comment]
You'll need to add `name_id_policy_format = "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"` to the saml config for IAMv2 to work properly.

**Comment by srenatus** [comment]
Please note my signing cert concerns in the other github issue.

**Comment by susanev** [comment]
we cannot document this in the automate docs, because even though it will work at the start it will break as soon as azure rotates the keys.

[internal slack thread](https://chefio.slack.com/archives/C61F9HHKK/p1594218269274200)

**Comment by susanev** [comment]
[chef support documentation](https://getchef.zendesk.com/hc/en-us/articles/360045977191)

**Comment by susanev** [comment]
its never ending fun

**Comment by srenatus** [comment]
the magic words are _non-gallery app_ 💡
