### ISSUE TITLE
only display one project banner at a time

### ISSUE THREAD

**Issue by susanev** [chef/automate#2889]
## Overview
Currently, it's possible for a user to be shown both the project update and the project edits pending banners at the same time. Let's change this so that the project edits banner is only shown when an update or a stop is not currently in progress.

**Comment by sdelano** [comment]
We saw this manifest itself in a couple ways during testing last week.

### Race-Condition Style
After clicking the `Update Projects` button in the banner, there's a moment (sometimes many) where both the progress bar banner and the pending updates banner are displayed. Sometimes the pending updates banner eventually disappears, sometimes it doesn't.

### Really Pending Updates Style
When project updates are in progress and a user stages changes to a project, the UI will simultaneously display the progress bar and the pending updates banner at the same time. We'd like to ONLY show the progress bar banner in this scenario.
