### ISSUE TITLE
Event Feed lists "policys" instead of "policies" in guitar-string mouse-overs

### ISSUE THREAD

**Issue by mattray** [chef/automate#2892]
![policys](https://user-images.githubusercontent.com/330023/74704166-72d4a580-5263-11ea-8ee8-750d22e00e8e.png)
Build: 20200131232134

**Comment by SEAjamieD** [comment]
I'll wrap this into whatever ticket I do next

**Comment by SEAjamieD** [comment]
note to self: this is happening in event-feed-guitar-strings and types.ts
