### ISSUE TITLE
investigation: controls list totals

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#2900]
## User Story

we need a count of passed/failed/skipped/waived controls to be able to provide the user with some filter buttons that have accurate counts. 

we noticed those counts are present in the overview - profile status page, but on the environment we looked at, the counts do not match the total count in the tab:
<img width="639" alt="Screen Shot 2020-02-18 at 11 33 11" src="https://user-images.githubusercontent.com/10341541/74766395-7d327780-5242-11ea-9680-58b453fc6978.png">

_other info:
the api for controls list already supports filtering by status (as seen in this [test](https://github.com/chef/automate/blob/master/components/compliance-service/api/tests/010_controls_list_spec.rb#L163), so that's all set!_

## Definition of Done
figure out what's going on with the discrepancy between numbers
document how the ui folks can get the totals needed for the filter boxes (https://github.com/chef/automate/issues/2543)

**Comment by vjeffrey** [comment]
![Screen Shot 2020-03-12 at 12.40.17.png](https://images.zenhubusercontent.com/5cfebc28d99ac71fbfbdcb73/56c255cf-cf15-46f9-9ba4-1014a3de85f5)

i kinda wonder....could it be that for controls list we're counting unique controls and for the controls counts on the overview we're just stating how many controls have been executed, *not* how many unique controls have been executed?

**Comment by rickmarry** [comment]
are we seeing this at customers or just in our own env?  if it's only in our own env, then how is data getting in?  chef_load?

**Comment by vjeffrey** [comment]
https://a2-local-inplace-upgrade-acceptance.cd.chef.co/dashboards/event-feed

not chef load - just ingesting reports sent in via data collector and scan jobs

**Comment by rickmarry** [comment]
I think you're correct about the list showing unique controls and the overview showing total but looking just to make sure.. I think that would be correct behavior btw..

**Comment by vjeffrey** [comment]
ya agreed it’s correct behaviour. but we should make sure to document that behaviour

**Comment by vjeffrey** [comment]
soo if that is true -- then there are two things we need to do:
1) make sure our automate compliance reporting docs call out this difference
2) add totals per status to the controls list response, as this is required for the ui designs

**Comment by rickmarry** [comment]
Keep in mind also that those tabs are meant to show unique values and when the user dives into the control tab, it shows the numbers on each row for each control, all of which will add up to the totals shown on the overview.  The profile tab also shows the unique profile count.

**Comment by vjeffrey** [comment]
https://automate.chef.io/docs/reports/#overview <-- for documenting the difference

**Comment by vjeffrey** [comment]
thanks rick!
