### ISSUE TITLE
Fix permissions related failures in inspec tests

### ISSUE THREAD

**Issue by tylercloke** [chef/automate#2929]
# Description

We have some permissions cfgmgnt related inspec failures in our force upgrade branch:

https://buildkite.com/chef/chef-automate-master-verify-private/builds/9588#4440e1e2-8f6f-4fbe-a285-6c4f54475408/1235-1605

The failures could be related to this default v1 policy being migrated incorrectly / differently than the tests are expecting:

https://github.com/chef/automate/pull/2783/files#diff-586ab1c0cc234c002424a036a86fbf85R204-R211

OR that test is running against a fresh install and no v1 default policies are being migrated, in which case we should verify the migrated behavior is functioning as intended and delete those inspec tests.

**Comment by susanev** [comment]
should be addressed by new force upgrade integration tests
