### ISSUE TITLE
remove v1 authz annotations from all APIs

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#2940]
## Definition of Done

All API protos in gateway only have v2 annotations that look like this: 
```
    option (chef.automate.api.iam.policy).resource = "system:service:version";
    option (chef.automate.api.iam.policy).action = "system:serviceVersion:get";
```
v1 annotations that look like this have been removed:
```
    option (chef.automate.api.policy).resource = "service_info:version";
    option (chef.automate.api.policy).action = "read";
```

**Comment by srenatus** [comment]
Should we also remove all traces of v1 from out protoc plugin (`protoc-gen-policy`)? I suppose so -- is there another card for it or would this be wrapped into this one?

**Comment by tylercloke** [comment]
I think it makes sense to do now as part of this card.
