### ISSUE TITLE
Notifications page empty state

### ISSUE THREAD

**Issue by susanev** [chef/automate#302]
## Overview
Currently, when there are no notifications on the _Notifications_ page we show an empty table, instead, we would like to follow the empty state pattern.

## Design Details
* Hide the command bar and table when there are zero notifications
* Show the empty state message and primary button when there are zero notifications
    * Message: Create the first notification to get started!
    * Primary button label: Create Notification

<img width="1308" alt="notifications-empty-state" src="https://user-images.githubusercontent.com/5489125/57486989-3a2f8680-7264-11e9-8c59-99f6379be1a1.png">

### Visual Design
* Message: semantically a paragraph, font-size: 18px; font-weight: 400;
* For white space, please reference the projects empty state page, it should match exaclty

## References
* Projects empty state: https://a2-iamv2-local-fresh-install-dev.cd.chef.co/settings/projects

**Comment by susanev** [comment]
## Overview
Currently, when there are no notifications on the _Notifications_ page we show an empty table, instead, we would like to follow the empty state pattern.

## Design Details
* Hide the command bar and table when there are zero notifications
* Show the empty state message and primary button when there are zero notifications
** Message: Create the first notification to get started!
** Primary button label: Create Notification

### Visual Design
* Message: semantically a paragraph, font-size: 18px; font-weight: 400;
* For white space, please reference the projects empty state page, it should match exaclty

## References
* Projects empty state: https://a2-iamv2-local-fresh-install-dev.cd.chef.co/settings/projects
<img width="1308" alt="notifications-empty-state" src="https://user-images.githubusercontent.com/5489125/57486989-3a2f8680-7264-11e9-8c59-99f6379be1a1.png">

**Comment by vinay033** [comment]
This issue is the same as https://github.com/chef/automate/issues/303, I will create PR for this today.
