### ISSUE TITLE
after first signing in, projects banner only shows up after navigating to projects list page

### ISSUE THREAD

**Issue by susanev** [chef/automate#3031]
## Overview
If there are pending edits, and you first sign in to automate the banner does not show up until you navigate to the projects list page.

## Repro steps
- Be on iam v2.1
- Sign in, make an edit to a project rule
- Notice the pending edits banner
- Sign out
- Sign back in
- Notice no banner shows
- Navigate to projects list, notice the banner shows up

can also repro by making an edit, then navigating to any non project list page and refreshing

**Comment by bcmdarroch** [comment]
I wonder if this is a consequence of this fix: https://github.com/chef/automate/pull/3007

**Comment by susanev** [comment]
what happens when you edit a rule from the command line? does the ui pick up that change?
