### ISSUE TITLE
Remove compliance label icons

### ISSUE THREAD

**Issue by alexpop** [chef/automate#307]
Based on feedback from @jonong1972 here: https://github.com/chef/automate/pull/254#issuecomment-490140929

We have a few more screens to remove the icons that are in front of the labels.

**1. Asset Store > Profiles / Available > SELECT A PROFILE. You will see the icons in the header in front of the labels.**

![Screen Shot 2019-05-10 at 10 28 31 AM](https://user-images.githubusercontent.com/107378/57517645-36a50980-730f-11e9-83df-7062c2e358c3.png)

---------

**2. Compliance > Profiles > SELECT A PROFILE**

![Screen Shot 2019-05-10 at 10 29 42 AM](https://user-images.githubusercontent.com/107378/57525803-9b6a5f00-7323-11e9-950c-3ec8ef002c8e.png)

---------

**3. Compliance > EXPAND Report Metadata section**

![Screen Shot 2019-05-10 at 10 30 09 AM](https://user-images.githubusercontent.com/107378/57525929-f4d28e00-7323-11e9-9002-7608a5b5d05e.png)

**Comment by vinay033** [comment]
we can close https://github.com/chef/automate/issues/307 this one :)
