### ISSUE TITLE
Automate Application Tab: Margin Error

### ISSUE THREAD

**Issue by jhonari** [chef/automate#3073]
## Describe the bug
When viewing Service Group details under the Applications tab in Automate, the package/release info is going beyond the margins of the right side pane. 

## To Reproduce
- Click Service Group under Applications tab in Automate

## Expected behavior
package/release details should text should wrap or fit within the margins

## Screenshots
![image (6)](https://user-images.githubusercontent.com/31141550/76354083-34715a00-62e8-11ea-9848-b95ad18b3cc1.png)

## Versions (please complete the following information):
- OS: Windows 10
- Browser: Chrome 80.0.3987.132
- Automate: Build Number 20200303183409

## Additional context
Reach out to me directly with further questions/clarifications and I can connect you with

**Comment by apriofrost** [comment]
Thanks for reporting the issue @jhonari We have a similar one reported in here: https://github.com/chef/automate/issues/2150
The recommended solution is to wrap the text.

**Comment by sachin-msys** [comment]
@susanev this issue got fixed in #3767. Also I have tested the changes on my end looking good to me. So now can we close this issue ?
