### ISSUE TITLE
Replace membership_id with user's id

### ISSUE THREAD

**Issue by tylercloke** [chef/automate#3096]
### Description

The membership APIs for teams still use the GUIDs that were used as the V1 IDs for users to associate users with a team. In v2, they are called membership_ids. A migration is required to replace the GUID use in the `user_team_assocation` table with user IDs. We also need to update association APIs to use the normal IDs, including their use in the UI. We can then drop the membership_id field (or deprecate it and return the normal ID in that field for now for backwards compatibility). 

### Acceptance Criteria

- [ ]  Migrate user_team_assocation table to replace v1 user GUIDS with v2 user IDs. We'll need to list all users to map the GUIDs to IDs. We should drop any GUID that doesn't map to an ID.
- [ ] Update APIs, validation, and docs around team user association APIs as needed.
- [ ] Update the UI to use the ID as the input to the team user association APIs (remove `VersionizeTeam` helpers, etc).
- [ ] Drop the membership_id field from the user APIs or deprecate it and return the normal ID if we are uncomfortable removing it.

**Comment by susanev** [comment]
this work has been deprioritized.
