### ISSUE TITLE
new skeleton page in automate (for desktop offering)

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#3107]
## User Story

We need a new page in automate to house the beautiful ui components and valuable data that make up the automate portion of the desktop offering.

This should be a new top-level page, but it will be hidden for now. This means no top-nav link to get to the page, no feature flag -- let's just stick it at `automate-url/desktop` for now, and those who are working on these features can visit that part of the automate site by visiting the url directly.

There's no content for the page yet, so it should just be a skeleton page ready do display data from the apis we are creating.

## Definition of Done
New page in Automate, at `automate-url/desktop`. Hidden page, no top-nav link to get to it or feature flag.

**Comment by susanev** [comment]
would dashboards/desktop make sense here? i know it will be hidden from any navs but wondering where it's eventual home will be.

**Comment by vjeffrey** [comment]
> wondering where it's eventual home will be

that's undecided for now -- we'll figure it out as we get closer to done
