### ISSUE TITLE
Don't show 0 count while loading

### ISSUE THREAD

**Issue by alexpop** [chef/automate#311]
# User Story

As an Automate User, I would like the following UI pages not to show a value of 0 for counts while data from the backend in pulled in order to render them. It creates a situation where the page is visited and for a few seconds, the user will see 0 counts and then as data is rendered, the counts change.

**1. Asset Store > `Profiles` and `Available` counts**

![Screen Shot 2019-05-10 at 1 34 53 PM](https://user-images.githubusercontent.com/107378/57540472-b8fbf080-7344-11e9-9662-e80f0214e080.png)

------------

**2. Scan Jobs > `Scan jobs` and `Nodes added` counts**
<img width="908" alt="Screen Shot 2019-05-10 at 5 05 08 PM" src="https://user-images.githubusercontent.com/107378/57541028-03ca3800-7346-11e9-862b-6bfba167bd93.png">

-----------

This issue is not showing on the Compliance page for the `Nodes` and `Profiles` counts.

**Comment by susanev** [comment]
@msorens created a pattern for page loading with an overlay.. i wonder if that might be useful here.
https://github.com/chef/a2/pull/4165
