### ISSUE TITLE
Telemetry UI console log error

### ISSUE THREAD

**Issue by lancewf** [chef/automate#3130]
## Describe the bug
When filtering with a project with the global filter on the client runs page ( https://a2-dev.test/infrastructure/client-runs) and error is displayed in the console log. 

## To Reproduce
1. Add an infra node with `send_chef_run_failure_example`
1. Create a project with a rule that matches the org = "chef_delivery"
1. Apply the rule. 
1. Go to the client runs page https://a2-dev.test/infrastructure/client-runs
1. Filter the nodes by the new project created. 
1. When the project filter is applied the error should appear. 

## Expected behavior
No errors in the console

## Screenshots
Below is the error seen in the console.
![image](https://user-images.githubusercontent.com/1679247/76891720-b280b400-6846-11ea-9863-d4387274602b.png)

## Versions (please complete the following information):
- OS: ubuntu 18.04
- Browser chrome
- Automate Build Number 20200317181619 - this was master at the time

**Comment by susanev** [comment]
(1) verify that it is not user impacting, and then close
(2) or if it is user impacting, fix
