### ISSUE TITLE
ingest-service is not logging Elasticsearch 4XX response bodies

### ISSUE THREAD

**Issue by thomascate** [chef/automate#3152]
## Describe the bug
Currently if ElasticSearch is overloaded and is rejecting messages, the only indication that ingest-service gives is that the queue is full. This could be an indication of several different things, and doesn't give a system admin much to go on.

```
Mar 18 16:00:38 node.example.com hab[1234]: ingest-service.default(O): time="2020-03-18T11:00:38-05:00" level=warning msg="All elasticsearch publishers are full" number_of_publishers=10
```

However, if you are running compliance scans at the same time, you will see errors similar to this. A 429 error indicating exactly which shard isn't being written to and that it was the was write pool that is overloaded. Indicating that disk I/O isn't keeping up, and in a cluster pointing out exactly which member is failing to keep up.

```
Mar 18 15:56:49 node.example.com hab[1234]: compliance-service.default(O): time="2020-03-18T10:56:49-05:00" level=error msg="Message failure" error="rpc error: code = Internal desc = InsertInspecReport: elastic: Error 429 (Too Many Requests): rejected execution of processing of [106225694][indices:data/write/bulk[s][p]]: request: BulkShardRequest [[comp-7-r-2020.03.18][0]] containing [index {[comp-7-r-2020.03.18][_doc][12345678-90ab-cdef-0123-abcdef012345], source[n/a, actual length: [163.9kb], max length: 2kb]}], target allocation id: 1234567890-abcd, primary term: 1 on EsThreadPoolExecutor[name = 64izRMp/write, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@0a1b3c4d[Running, pool size = 8, active threads = 8, queued tasks = 201, completed tasks = 30035248]] [type=es_rejected_execution_exception] InsertInspecSummary: elastic: Error 429 (Too Many Requests): rejected execution of processing of [106225693][indices:data/write/bulk[s][p]]: request: BulkShardRequest [[comp-7-s-2020.03.18][0]] containing [index {[comp-7-s-2020.03.18][_doc][12345678-90ab-cdef-0123-abcdef012345], source[n/a, actual length: [5.6kb], max length: 2kb]}], target allocation id: 1234567890-abcd, primary term: 1 on EsThreadPoolExecutor[name = 0a1b3c4d/write, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@0a1b3c4d[Running, pool size = 8, active threads = 8, queued tasks = 201, completed tasks = 30035248]] [type=es_rejected_execution_exception]"
```

## To Reproduce
Start chef-load with a mix of compliance and converges. 
Use something like bonnie++ to use up all of your disk i/o.
Verify that write rejects are happening
```
curl localhost:10144/_nodes/stats?pretty | grep -A 4 \"write\"
        "write" : {
          "threads" : 8,
          "queue" : 0,
          "active" : 0,
          "rejected" : 2444,
```

Check journald logs and verify that only compliance-service is logging 429 errors.

## Expected behavior
When receiving a 4XX error code, ingest-service should log the response body similar to how compliance-service behaves.

## Additional context
This may be tricky to replicate with standalone A2, reach out to me if you need any further testing or help reproing.

**Comment by thomascate** [comment]
This should be logged at the error level as well.

**Comment by lancewf** [comment]
When the ingest-service logs the message "All elasticsearch publishers are full" ElasticSearch is not rejecting messages the ingest-service's internal queues are full. To increase the internal queues either increase the max number of bundled run messages (max_number_of_bundled_run_msgs) or add more run message publishers (number_of_run_msg_publishers). When the number of max_number_of_bundled_run_msgs is too high the error from Elasticsearch should be message size is too large. If the number_of_run_msg_publishers number is too high the error will be similar to compliance with a "Too Many Requests". I would first increase the number_of_run_msg_publishers until the "All elasticsearch publishers are full" message goes away. 

```
[ingest.v1.sys]
number_of_run_msg_publishers = 7
max_number_of_bundled_run_msgs = 2000
```
