### ISSUE TITLE
confirm restores still work after force upgrade

### ISSUE THREAD

**Issue by susanev** [chef/automate#3165]
## Overview
If a user creates a backup on a version of automate before the force upgrade, and then restores will everything just work?

default restore path: should always work since we always restore to the version we took the backup with

question: do folks need to take a new backup after being force upgraded?

**Comment by stevendanna** [comment]
The upgrade path I would potentially be worried about here is the "upgrade restore" path; however, that path is never guaranteed to work.  Further, if the automate service knows how to upgrade the V1 data, that path should also work as expected.  

The backup/restore tests cover most of what we care about, but I think it is probably good to do one manual test starting from a very old version doing a backup, upgrading, and then trying to restore the old backup via both the normal restore and the upgrade restore.

**Comment by bcmdarroch** [comment]
might be able to keep this super simple by adding the [a2-iam-legacy-integration inspec suite](https://github.com/chef/automate/tree/force-upgrade/inspec/a2-iam-legacy-integration ) to the post-upgrade set of tests run on https://github.com/chef/automate/blob/master/integration/tests/deep_upgrade_backup_restore.sh or https://github.com/chef/automate/blob/master/integration/tests/backup.sh

**Comment by susanev** [comment]
if upgrade restore does not work, document it and put it in the release notes

**Comment by jaym** [comment]
@stevendanna i think this is covered by https://github.com/chef/automate/blob/master/integration/tests/airgap_ow_upgrade.sh

if we break upgrade+restore, i think that test would break.

**Comment by jaym** [comment]
that being said, using a slightly newer version wouldn't be a horrible idea
