### ISSUE TITLE
Expose the chef-automate deploy --product flag

### ISSUE THREAD

**Issue by btm** [chef/automate#3176]
`chef-automate deploy --product` is still a hidden flag. Behind it lies the ability to install an infra server and/or automate, and presumably now on-premises hab depot.

We're expecting Chef Desktop users to have separate Infra Server and Automate infrastructure, being a different department in most enterprises. We'd like them to start by using the Automate Infra Server rather than a separate instance.

Acceptance Critiera:
* Add 'infra-server' as a product. Can be aliased to 'chef-server' or vice versa. But we want to promote the newer more specific Chef Infra server name.
* The 'chef-server' product continues to work without any changes. Must not break OWCA.
* `chef-automate deploy --help` shows `--product` and valid options.
* docs updated to use `infra-server` instead of `chef-server`. #2851

**Comment by btm** [comment]
Q: are there still `--enable-chef-server` hidden flags? Should they be? in #5011 there were.

**Comment by yzl** [comment]
@btm 
> Q: are there still `--enable-chef-server` hidden flags? Should they be? in [chef/a2#5011](https://github.com/chef/a2/pull/5011) there were.

Those are intentionally hidden; `--enable-chef-server` was the precursor to `--product chef-server`, so we prefer people not use it now, but afaik want to leave it there in case someone is still using it.
