### ISSUE TITLE
Long project name causes policy problem

### ISSUE THREAD

**Issue by msorens** [chef/automate#3198]
## User Story

Project ids can be up to 64 characters.
Policy ids can be up to 64 characters.
That presents an integration problem: Creating a project `x` begets three policies, `x-project-owners`, `x-project-viewers`, and `x-project-editors`.
So if x is longer than 48 characters then you cannot fetch the project.

On the command-line:
```
$ curl -sSkH "api-token: $TOK" -H "" "https://a2-dev.test/apis/iam/v2/policies/p123456789p123456789p123456789p123456789p123456789p123456789-project-viewers"
{
  "error": "invalid GetPolicyReq.Id: value does not match regex pattern \"^[a-z0-9-_]{1,64}$\"",
  "code": 3,
  "message": "invalid GetPolicyReq.Id: value does not match regex pattern \"^[a-z0-9-_]{1,64}$\"",
  "details": [
  ]
}
```

On-screen:
![image](https://user-images.githubusercontent.com/6817500/77483153-b1bac580-6de4-11ea-93b5-1cbc3115842f.png)

## Definition of Done
Perhaps limit project names to 48 characters...?

**Comment by susanev** [comment]
oh jeez, good catch!

**Comment by susanev** [comment]
we should probably do this with team names too, since we will be auto-generating the teams as well soon.

**Comment by susanev** [comment]
notes from standup 04/06
- verify that we can update project names with more than 64 characters
- limit project ids to 48 characters
- re-think validation on fetch
- do not worry about anyone who has already created a project id with more than 48 characters
