### ISSUE TITLE
desktop offering: given a status and timeframe, return list of machines that match

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#3217]
## User Story

this is a follow up to the check in counts api 

we need an API that, given:
- a status ("unknown" or "checked-in")
- a timeframe ("last 24 hrs", "last 3 days")

returns a list of desktops that, based on the request params,
- did not check in ("unknown") during that timeframe, and the machine details (for now, let's just stick to the same stuff we already return with the cfgmgmt list nodes api)
or
- checked-in during that timeframe, and the machine details (for now, let's just stick to the same stuff we already return with the cfgmgmt list nodes api)

## Definition of Done
we establish that we have an api that will return the above info, or we create the api if needed. if we already have the api, please document in this issue what the request params and response look like

**Comment by vjeffrey** [comment]
https://chef.invisionapp.com/share/E9W3TEFXV87#/screens/410934035

pagination: start out with 10 per page

**Comment by vjeffrey** [comment]
"show me the list of desktops that have checked in over last 24 hrs"
"show me the list of desktops that have NOT checked in over last 24 hrs"
"show me all desktops that have not been deleted in last 24 hrs"

**Comment by lancewf** [comment]
I think the last one "show me all desktops that have not been deleted in last 24 hrs" should be show me all the desktops that have not been deleted.

**Comment by lancewf** [comment]
Have the backend API updated next is adding this functionality to the UI.
