### ISSUE TITLE
desktop offering: error detail API

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#3219]
## User Story

this is a follow up to the to errors api: https://github.com/chef/automate/issues/2996

we need an API that, given:
- an error message + type 

returns a list of desktops that 
- failed their latest chef client run with that error 
- basic details of each machine should also be returned (for now, let's just stick to the same stuff we already return with the cfgmgmt list nodes api)

## Definition of Done
we establish that we have an api that will return the above info, or we create the api if needed. if we already have the api, please document in this issue what the request params and response look like

**Comment by vjeffrey** [comment]
https://chef.invisionapp.com/share/E9W3TEFXV87#/screens/410946309

**Comment by lancewf** [comment]
@vjeffrey Do we need a timeframe added with the desktop error filtering? I think the timeframe got removed and we only need to filter on the error message and error type. We already have a way to filter on the error message, so I was going to add a way to filter on the error type.

**Comment by vjeffrey** [comment]
you're right -- no timeframe on this one! thanks for noticing, ill update the description!
