### ISSUE TITLE
desktop offering: list desktops that have been unknown for x or more days

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#3220]
## User Story
Users of the desktop offering want to know about the machines that have been missing for a long(er) time period. 

To support this, we need an API that, given:
- a timeframe (last 3 days, last 1 wk, last 2 wks, more than a month)

returns:
- a list of desktops that have *not* checked in during that time period

## Considerations
new api that just returns desktops that have been unknown for the timeframes listed above so that we don't need 4 api calls for this graph? how should we do this?

## Definition of Done
given a time period (days/wks/months ago), return list of desktops that have not checked in to automate during that time period
<img width="448" alt="Screen Shot 2020-03-26 at 16 16 59" src="https://user-images.githubusercontent.com/10341541/77702060-3f311d80-6f7d-11ea-9c86-537e187313ce.png">

**Comment by vjeffrey** [comment]
https://chef.invisionapp.com/share/E9W3TEFXV87#/screens/410934035

**Comment by lancewf** [comment]
Below is the request and response for the API I am proposing. 

request/
ranges: ["3d", "1w", "2w", "1m", "3m"]
response/
[ 
    {range: "3d", count: 11},
    {range: "1w", count: 8},
    {range: "2w", count: 6},
    {range: "1m", count: 2},
    {range: "3m", count: 1},
]
