### ISSUE TITLE
desktop offering: node detail

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#3221]
## User Story

when a user wants to know more information about a specific desktop, that user will select the desktop.
upon selection, the view presented will be something like the following:
![Screen Shot 2020-04-06 at 12.38.24.png](https://images.zenhubusercontent.com/5cfebc28d99ac71fbfbdcb73/1fdf60f0-ff4f-49a8-b99a-df9b48be0ab8)

([full design](https://chef.invisionapp.com/share/E9W3TEFXV87#/screens/411696110_-Slice_1_Release-Desktop_Dashboard-Desktop_Detail-Experimental)

this design will require a new API for the top status portion.
for the first iteration, the statuses for a single desktop will be: 
unknown
checked in and succeeded
and checked in but failed the run
**we will address the "unchanged" status in the next iteration.**

so the API can take a node id and timeframe (2 wks ago) 
and return the latest status for that node for the day: 
checked in (success), checked in (failed), unknown (did not check in that day)

after that, we will need to ensure that we are returning all the required ohai data on the node read API call, namely  the ones found on the right hand side of this sheet: https://docs.google.com/spreadsheets/d/1E-t6kksoAQA3FQ6RZx1ak6ucLQBq6MQ7/edit#gid=2076053478

![Screen Shot 2020-04-06 at 12.41.44.png](https://images.zenhubusercontent.com/5cfebc28d99ac71fbfbdcb73/aa061afd-4595-446b-aef6-84a40cbf2dad)

## Definition of Done
- new API to return latest status of node per day
- node details returns all required fields as shown in the design

**Comment by vjeffrey** [comment]
https://docs.google.com/spreadsheets/d/1E-t6kksoAQA3FQ6RZx1ak6ucLQBq6MQ7/edit#gid=2076053478

**Comment by vjeffrey** [comment]
request will need to take a node id and timeframe
response will need to return the ohai data as specified above as well as the last run status per day in the provided timeframe for the node

**Comment by vjeffrey** [comment]
https://github.com/chef/chefdesktop/issues/23#issuecomment-610112335

**Comment by vjeffrey** [comment]
* make sure we include run id on new api section

**Comment by lancewf** [comment]
What if we have an endpoint that returns a time-series of 24 hours buckets with the number of runs that have converged, unchanged, and failed. 

request:
node_id
days - number of days back. Currently 14. 

response:
```
[
    {
        "start": "2020-04-21T01:00:00Z",
        "end": "2020-04-22T01:00:00Z",
        "converged": 0,
        "unchanged": 1,
        "failed": 0
    },
    {
        "start": "2020-04-21T01:00:00Z",
        "end": "2020-04-22T01:00:00Z",
        "converged": 0,
        "unchanged": 0,
        "failed": 0
    },
    {
        "start": "2020-04-22T01:00:00Z",
        "end": "2020-04-23T01:00:00Z",
        "converged": 3,
        "unchanged": 1,
        "failed": 3
    },
...
]
```

I am still trying to figure out how to get a run ID for each bucket.

**Comment by vjeffrey** [comment]
oooh that's nice - so then we can show the user everything that happened over the day. and would wemreturn only the latest run id per 24 hrs?

**Comment by apriofrost** [comment]
Add the definition of the daily status for a desktop here:

For any given day (in the first release, it should be every 24 hours chunk of data)

- failed and converge has the same weight, they trump all the rest status in the day.
- if both failed and converged exist, use the latest one among the two as the daily status
- if neither failed nor converged exist, when checked-in, use unchanged; otherwise, use unknown.

Whichever run that is chosen as the status of the day is the run that we link from the status icon in the hovering tooltip.

Linking behavior demo video: https://drive.google.com/open?id=1nfGs5SH9RUHGBGdjBtYB96LtKRlMY135

**Comment by lancewf** [comment]
The "new API to return latest status of node per day" is complete, but the "node details returns all required fields as shown in the design" is not.

**Comment by lancewf** [comment]
To get the node details for one node use the "api/v0/cfgmgmt/nodes" API. This API is the same one used to list all the nodes on the client runs page. 

To see this locally, run this command to add the node. `generate_chef_run_example | jq '.entity_uuid = "832e3d1c-8e3e-11ea-bc55-0242ac130003" | .run_id = "9574da6c-8e3e-11ea-bc55-0242ac130003" | .id = "9574da6c-8e3e-11ea-bc55-0242ac130003"' | send_chef_data_raw.`

Run this command to see test the API. `curl -f --insecure -H "api-token: $(get_api_token)" "https://localhost/api/v0/cfgmgmt/nodes?filter=node_id:832e3d1c-8e3e-11ea-bc55-0242ac130003" | jq`
Below is what will be returned.
```
[
  {
    "checkin": "2020-04-29T02:39:13Z",
    "chef_tags": [
      "slave",
      "supermarket",
      "builder"
    ],
    "chef_version": "12.6.0",
    "cloud_provider": "ec2",
    "created_at": "2020-05-04T19:39:13.203913440Z",
    "deprecations_count": 6,
    "dmi_system_manufacturer": "Xen",
    "dmi_system_serial_number": "ec2e0f80-06cc-d659-e439-34147116b49f",
    "domain": "us-west-2.compute.internal",
    "environment": "B",
    "fqdn": "ip-127-208-184-141.us-west-2.compute.internal",
    "has_deprecations": true,
    "has_runs_data": true,
    "hostname": "ip-127-208-184-141",
    "id": "832e3d1c-8e3e-11ea-bc55-0242ac130003",
    "ip6address": "fe80::3f:b5ff:fe7e:adff",
    "ipaddress": "127.208.184.141",
    "kernel_release": "3.10.0-229.el7.x86_64",
    "kernel_version": "#1 SMP Thu Jan 29 18:37:38 EST 2015",
    "last_ccr_received": "2020-04-29T02:39:13Z",
    "latest_run_id": "9574da6c-8e3e-11ea-bc55-0242ac130003",
    "macaddress": "02:3F:B5:7E:AD:FF",
    "memory_total": "3689604kB",
    "name": "insights.success.16",
    "organization": "chef_delivery",
    "platform": "redhat 8.9",
    "platform_family": "rhel",
    "platform_version": "8.9",
    "source_fqdn": "chef-server.insights.co",
    "status": "success",
    "uptime_seconds": 12342607,
    "virtualization_role": "guest",
    "virtualization_system": "xen"
  }
]
```
