### ISSUE TITLE
desktop offering: deployment specifics 

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#3244]
## User Story

general
- desktop offering will be top level nav link (automate-url/desktop) - DONE (in scott's branch)
- we do not need to hide other automate views
- only show the desktop view when installed with the --desktop flag

flag
- introduce flag to install automate in desktop mode (--desktop bool)
- use of this flag sets default configuration to never delete nodes and never mark nodes as missing
- do not install the compliance-profiles package when flag is true. the desktop sku is not entitled to the majority of them (btm) see https://github.com/chef/automate/blob/master/components/compliance-service/habitat/plan.sh#L42-L48 for an example of not installing profiles
- use of the flag enables the desktop nav link
 
documentation
   - document that users should not change these settings missing nodes config/delete nodes config
   - document recommendations for retention settings (to explain and try to avoid the "no data" case)
   - document that we are not supporting project filtering on these views
   - document liveness agent issue: the desktop APIs are currently counting liveness agents as desktops. this shouldn't be a problem since we don't expect a desktop user to have nodes with liveness agents contacting automate

questions
- could the desktop offering flag also force automate to default open to the desktop page?
- could we disable the checkboxes for setting missing nodes threshold and delete missing nodes threshold in the ui when they have desktop enabled?

other
- make sure we're not passing project information in the api when calling config mgmt nodes list via the desktop offering pages
- add instance to terraform for this

**Comment by vjeffrey** [comment]
- do not need to hide other automate views
- probably top nav link (liz will confirm with ux team/mark) -- revisit url with this decision
- deleting nodes stuff will be addressed in documentation
- marking nodes as missing does not work well with unknown status for desktop
- config: do not set nodes as missing ever when using desktop - superteam to document this and share with jessica -- also never any automatic deletion of nodes
https://a2-local-inplace-upgrade-acceptance.cd.chef.co/settings/node-lifecycle default to "never" for both. document it.

**Comment by vjeffrey** [comment]
https://github.com/chef/automate/issues/3338#issuecomment-613033858

**Comment by vjeffrey** [comment]
document that we aren't doing project filtering on these apis

**Comment by lancewf** [comment]
Here is the order I am starting to look into this task

1. Add a backend desktop mode flag.
2. Send the flag to the UI. (look into how the workflow flag works)
3. Look into defaulting to the UI desktop page
4. Look into disabling UI data lifecycle controls.
5. Update the default data lifecycle
6. Do not install the compliance-profiles (https://github.com/chef/automate/blob/master/components/compliance-service/habitat/plan.sh#L42-L48)

Below are a few questions I have: 
- Do we need to hide other automate views?
    * We do want to see the Infrastructure tab also since we are linking to the node details page. 
    * I also see a use for the compliance tab, if desktop users are entitled to using that. 
    * The Applications tab would not be useful until we get effortless working with desktop 
    * The Dashboard/Event feed would be useful to see Policyfile and other Chef Server events.
- What is the “add instance to terraform for this” task?

**Comment by vjeffrey** [comment]
we do not want to hide other automate views -- jessica wants to leave all things up and available
add instance to terraform is adding a new scenario here: https://github.com/chef/automate/tree/master/terraform/test-environments/scenarios

**Comment by lancewf** [comment]
Breaking this up into multiple tasks. 

- [ ] Add the install flag with the products.meta file updates. currently in work (https://github.com/chef/automate/pull/3648)
- [ ] Update defaults for ingest job scheduler [here](https://github.com/chef/automate/blob/8be23bfeeb98b550e36c8f348575e41d6cee2d19/components/ingest-service/config/old_job_config.go#L54) based off automate desktop or not.
* Need to add new configs the Running variable for DeleteNodes, NodesMissing, and MissingNodesForDeletion.
* Add the below function in the ingest-service config [here](url) to set the correct defaults. 
```
func (c *ConfigRequest) ConfigureProduct(productConfig *shared.ProductConfig) {
	if len(productConfig.Products) > 0 {
		c.V1.Sys.StaticConfig.Products = make([]string, len(productConfig.Products))
		copy(c.V1.Sys.StaticConfig.Products, productConfig.Products)
	}
}
```
- [ ] Update the UI for Desktop
* Below are links on how to know if automate UI has Desktop view on or not.
https://github.com/chef/automate/blob/0acafd7a607f74524e0d7a2110ba934e3f112d23/components/automate-ui/src/app/entities/layout/layout-sidebar.service.ts#L6
https://github.com/chef/automate/blob/0acafd7a607f74524e0d7a2110ba934e3f112d23/components/automate-ui/src/app/entities/layout/layout-sidebar.service.ts#L59
* Hide and display the Desktop nav link
* Open desktop page by default
* Disable/Remove the missing node and deleting node controls from the data lifecycle
- [ ] Look into how to disable the compliance-profiles.

**Comment by lancewf** [comment]
Waiting for the new AWS server and the automate-cli to be updated to test installing Automate with desktop. 
https://bldr.habitat.sh/#/pkgs/chef/automate-cli/0.1.0. We need one older than chef/automate-cli/0.1.0/20200526122350

**Comment by lancewf** [comment]
We now have a new AWS server with Automate and the Desktop Offering. 

https://a2-local-desktop-fresh-install-dev.cd.chef.co/

**Comment by vjeffrey** [comment]
🏆 🎉
