### ISSUE TITLE
change project clear selection button behaviour

### ISSUE THREAD

**Issue by susanev** [chef/automate#3249]
## Overview
We are a bit worried about the button label not clearly indicating the action and folks blowing away 100s of selections by accident, so lets adjust this button behaviour. This work is ui only work.

## Design Details
- [ ] change clear selection button to do just that, clear the selection, not apply changes or refresh the page; after a user uses the clear selection button the apply changes button should become enabled and they will need to use that to apply the changes and refresh the page
- [ ] hide the clear selection button if nothing is selected
    - add some kind of animation please, anything works
- [ ] add a selection count parenthetical to the button that indicates how many items are currently selected, maxing out at 99, and using 99+ if they have more than 99 projects selected; width of dropdown will need to be increased to support this
    ![projects-global-filter](https://user-images.githubusercontent.com/5489125/78037978-1c0dc180-7321-11ea-9989-257f6b8ef25b.png)

_ignore the create and edit buttons in that img, those were cut_

## Acceptance

1. create a bunch of projects
2. open the menu, observe there is no clear selection button because nothing is selected
3. select 2 projects, observe the apply changes button becomes enabled and the clear selection button appears with count of 2
4.  apply changes, notice the menu closes and page refreshes
5. open menu back up, observe the clear selection button with count of 2
6. use the clear selection button, watch the button disappear and the selected items become unselected and the apply changes button become enabled
7. close the menu, notice changes are lost and not applied
8. do step 6 again but this time apply changes

**Comment by msorens** [comment]
<kbd>Clear selection</kbd> will clear both newly selected (unapplied) projects as well as previously selected (applied) projects.  Thinking about how to clear the newly selected projects only--i.e., want to go back to the same state as before opening the dialog. Would that be just by closing the dialog, or do dialog changes persist (remaining unapplied in the dialog) even if they are not yet applied?

**Comment by susanev** [comment]
closing the menu before applying changes will return you to ur original state, they do not persist unless changes are applied.
