### ISSUE TITLE
wildcard searching for compliance reporting

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#325]
# User Story

Users would like to be able to perform wildcard searches when using the compliance reporting searchbar. This functionality is already supported in the client-runs searchbar, and has been well-received by our customer base.  This will also help us drive parity across the searchbars, which is a long-term goal we've had to make the user experience better.

# Definition of Done
Wildcard searching is supported when using the compliance searchbar. This means a user can search for node name `angry-*` or environment `pro*`.  This should be available on all search fields if possible.

**Comment by lancewf** [comment]
This task is mostly done with the https://github.com/chef/automate/pull/559 PR. There are a few things missing. 
* The filters are case sensitive
* Can not perform wildcard searching on version number. For example the platform version number or profile version number.

**Comment by vjeffrey** [comment]
once #607 merges, let's open a new issue to track the platform version number and profile version number work
