### ISSUE TITLE
client-runs node detail Is it possible to make run_id as optional?

### ISSUE THREAD

**Issue by vsingh-msys** [chef/automate#3261]
While exploring the possibility of making `run_id` as optional for client-runs node detail page found a couple of improvement area

- Manually navigating to `https://a2-dev.test/infrastructure/client-runs/NODE_ID/missing-runs` it is saying node has no client run data hold on but it has.

![client-runs-missing-runs](https://user-images.githubusercontent.com/44496937/78150303-bd496480-7454-11ea-801c-7e33ab9f0514.png)

- `Client-runs` breadcrumbs should navigate to the client-runs page but it seems it gets redirected to root page.

![client-runs-missing-runs](https://user-images.githubusercontent.com/44496937/78151824-a0ae2c00-7456-11ea-8ad6-60f76f42154e.png)

#### A possible improvement would be:

- Navigate to client node detail page only with `node-id` by making `run-id` as optional
ie. `https://a2-dev.test/infrastructure/client-runs/NODE_ID` redirect it to:

   a) if the node has run history fetch the `last_run` detail as it's stored in `nodemanager`'s nodes table.

   b) if node does not have run history redirect to missing-runs page.

Note: This is what it needed for mapping automate infra views node to client-runs node.

**Comment by lancewf** [comment]
We could change the https://github.com/chef/automate/blob/9af5125bbf2ecfcc1841b296ef37424575f24539/components/automate-ui/src/app/services/node-details/node-details-resolver.service.ts#L9 `NodeDetailsResolverService` to find the latest run if one is not passed to it. This line https://github.com/chef/automate/blob/e0df48ceb8776085b432e2eeeb11351ad4f8d714/components/automate-ui/src/app/app-routing.module.ts#L229 would also have to be updated to have the run_id optional. 

The user is directed to the https://a2-dev.test/infrastructure/client-runs/NODE_ID/missing-runs page when there are no run data for the node from the NodeDetailsResolverService.

**Comment by vsingh-msys** [comment]
@lancewf thanks for the insights will look and revert you back accordingly!
