### ISSUE TITLE
auth middleware in the gateway iam v2 force upgrade cleanup

### ISSUE THREAD

**Issue by susanev** [chef/automate#3272]
## Deets

- [ ] if there's time, remove the [switching mechanism](https://github.com/chef/automate/blob/master/components/automate-gateway/gateway/middleware/auth_interceptor.go#L40-L99) since we'll only have one way to authorize now
- [ ] double-check the service for any remaining v1/v2 conditional handling

**Comment by srenatus** [comment]
The card so far doesn't take introspection into account. The same switching logic had been baked in there.
