### ISSUE TITLE
Problem deleting chef server with attached orgs

### ISSUE THREAD

**Issue by msorens** [chef/automate#3294]
## Describe the bug
There is a problem deleting a chef server that has one or more organizations attached. I am not sure what is supposed to happen, but a fix is needed either way.

## To Reproduce

Create a server:
```
$ curl -sSkH "api-token: $TOK" -X POST \
-d '{"name": "SERVER_NAME2", "description": "SERVER_DESCRIPTION2", "fqdn": "example.com", "ip_address": "127.0.0.1"}' \
https://a2-dev.test/api/v0/infra/servers?pretty
{
  "server": {
    "id": "d31e49ce-608b-46d4-b8b5-a819d19222ad",
    "name": "SERVER_NAME2",
    "description": "SERVER_DESCRIPTION2",
    "fqdn": "example.com",
    "ip_address": "127.0.0.1",
    "orgs_count": 0
  }
}
```
Grab the `id` value from above and plug in here to add an organization:
```
$ curl -sSkH "api-token: $TOK" -X POST \
-d '{"name": "ORG_NAME2", "admin_user": "ADMIN_USER", "admin_key": "KEY"}' \
https://a2-dev.test/api/v0/infra/servers/d31e49ce-608b-46d4-b8b5-a819d19222ad/orgs?pretty
{
  "org": {
    "id": "956c1773-d5ba-471b-8e0d-ceb37603e271",
    "name": "ORG_NAME2",
    "admin_user": "ADMIN_USER",
    "admin_key": "e2ac8d74-b419-42b3-b96c-aa2f738e8f18",
    "server_id": "d31e49ce-608b-46d4-b8b5-a819d19222ad",
    "projects": [
    ]
  }
}
```
Attempt to delete the server and it fails with, at a minimum, the wrong error message:
```
$ curl -sSkH "api-token: $TOK" -X DELETE \
https://a2-dev.test/api/v0/infra/servers/d31e49ce-608b-46d4-b8b5-a819d19222ad?pretty
{
  "error": "no server found with id \"d31e49ce-608b-46d4-b8b5-a819d19222ad\"",
  "code": 5,
  "message": "no server found with id \"d31e49ce-608b-46d4-b8b5-a819d19222ad\"",
  "details": [
  ]
}
```
Delete org first:
```
$ curl -sSkH "api-token: $TOK" -X DELETE \
https://a2-dev.test/api/v0/infra/servers/d31e49ce-608b-46d4-b8b5-a819d19222ad/orgs/956c1773-d5ba-471b-8e0d-ceb37603e271?pretty
{
  "org": {
    "id": "956c1773-d5ba-471b-8e0d-ceb37603e271",
    "name": "ORG_NAME2",
    "admin_user": "ADMIN_USER",
    "admin_key": "e2ac8d74-b419-42b3-b96c-aa2f738e8f18",
    "server_id": "d31e49ce-608b-46d4-b8b5-a819d19222ad",
    "projects": [
    ]
  }
}
```
Now try to delete the server again and it works:
```
$  curl -sSkH "api-token: $TOK" -X DELETE https://a2-dev.test/api/v0/infra/servers/d31e49ce-608b-46d4-b8b5-a819d19222ad?pretty
{
  "server": {
    "id": "d31e49ce-608b-46d4-b8b5-a819d19222ad",
    "name": "SERVER_NAME2",
    "description": "SERVER_DESCRIPTION2",
    "fqdn": "example.com",
    "ip_address": "127.0.0.1",
    "orgs_count": 0
  }
}
```

The same incorrect error occurs in the UI:
<img width="1446" alt="image" src="https://user-images.githubusercontent.com/6817500/78617983-00794e00-782e-11ea-8a4a-54b7c4c733df.png">

## Expected behavior

I am not sure what is supposed to happen, but a fix is needed either way.

### Scenario 1: User should **NOT** be allowed to delete a chef server if it has orgs

Fix needed: Error message should say
```
"cannot delete server _<server-guid>_ because it still has organizations attached"
```
instead of
```
"no server found with id _<server-guid>_"
```

### Scenario 2: User **should** be allowed to delete a chef server if it has orgs

Fix needed: process the delete of the server (and presumably its associated orgs)
and present a success message instead of the incorrect error message.

**Comment by vsingh-msys** [comment]
@msorens Thanks for reporting the issue, this should be supposed to the expected to work expected behavior, User should not be allowed to delete a chef server if it has orgs, but seems error message is wrong.

**Comment by susanev** [comment]
itd be rad if we can follow the same design pattern for a project that has ingest rules, on project delete it opens a modal with more details on what they need to do in order to delete. am attaching the modal for project.

<img width="720" alt="project-delete" src="https://user-images.githubusercontent.com/5489125/78628526-35df6500-7849-11ea-94f5-901e1eade8c3.png">

**Comment by jonong1972** [comment]
Yup. I we should follow our current pattern as @susanev mentioned above
