### ISSUE TITLE
Fields for chef servers and orgs should disallow whitespace-only values

### ISSUE THREAD

**Issue by msorens** [chef/automate#3296]
## To Reproduce
Create a server:
```
$ curl -sSkH "api-token: $TOK" -X POST \
> -d '{"name": "SERVER_NAME2", "description": "SERVER_DESCRIPTION2", "fqdn": "example.com", "ip_address": "127.0.0.1"}' \
> https://a2-dev.test/api/v0/infra/servers?pretty
{
  "server": {
    "id": "b900bfa6-c699-4bb3-bb4e-146901de1162",
    "name": "SERVER_NAME2",
    "description": "SERVER_DESCRIPTION2",
    "fqdn": "example.com",
    "ip_address": "127.0.0.1",
    "orgs_count": 0
  }
}
```
Grab the `id` value from above and plug in here to add an organization (notice the name field is all blanks):
```
$ curl -sSkH "api-token: $TOK" -X POST \
-d '{"name": "      ", "admin_user": "ADMIN_USER", "admin_key": "KEY"}' \
https://a2-dev.test/api/v0/infra/servers/b900bfa6-c699-4bb3-bb4e-146901de1162/orgs?pretty
{
  "org": {
    "id": "fdb262cc-a60a-44f6-bc8f-bef4a9b040b8",
    "name": "      ",
    "admin_user": "ADMIN_USER",
    "admin_key": "8a367010-1f5b-4cf1-8d8d-24a51ce39565",
    "server_id": "b900bfa6-c699-4bb3-bb4e-146901de1162",
    "projects": [
    ]
  }
}
```
Note that an empty field correctly triggers an error; it is only a problem for a non-empty value consisting of just whitespace.

## Expected behavior
The operation should fail, and report preferably this text
(it is being introduced in PR #3197):
_"an org name is required and must contain at least one non-whitespace character"_

Note that you can see how such checks are being introduced across many resources in PR #3197.

**Note the same fix is needed for every field the user may provide.**

**Comment by vsingh-msys** [comment]
Yes, As of now this is pending to add the proto3 buff side validation. I have the plan to tackle in https://github.com/chef/automate/issues/3240

**Comment by msorens** [comment]
@vsingh-msys Please note that I am actually not suggesting protobuf validation. We had been using that for all auth services but have started to move away from it with the PR I mentioned above, #3197. 

The reason is that the error messages from protobuf validation were NOT user friendly. With protobuf validation we had either:
(A) The rather esoteric "runes" term used here (when using `min_len`):
_value length must be at least 1 runes_
(B) The strange-looking regex for "not whitespace" (when using regex `\\S+`):
_value does not match regex pattern `\"\\\\S\"`"_

So we instead let the service handle it with the message I indicated: _an org name is required and must contain at least one non-whitespace character_

**Comment by vsingh-msys** [comment]
Ohh, I was misunderstood it, but adding validation at service level looks interesting will look and revert you accordingly thanks
