### ISSUE TITLE
proposal: allow user to select from a list of already existing credentials when creating org for chef-server

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#3310]
## User Story

On the new, unreleased organization create page in automate, we ask users to input their admin key. 
<img width="1388" alt="Screen Shot 2020-04-07 at 15 45 51" src="https://user-images.githubusercontent.com/10341541/78722515-e18ac280-78e6-11ea-8e49-bc026539699a.png">

While in standup this morning, @vsingh-msys suggested it might be nice to allow the user to select a credential from a list of already created, appropriately typed credentials.
This feature would also allow the user to see that a credential is attached to the object when updating the object (since we don't want to return the key in the api).
We do this on the node create/edit page, e.g.:
<img width="1398" alt="Screen Shot 2020-04-07 at 15 48 53" src="https://user-images.githubusercontent.com/10341541/78722725-4f36ee80-78e7-11ea-8411-3e7f5d506417.png">

_**pls add your thoughts!**_

**Comment by jonong1972** [comment]
Questions that I have are:

Are the org credentials something that people share?
Are the org credentials re-usable? e.g. using one set of credentials across multiple orgs?

**Comment by vjeffrey** [comment]
this was eventually answered in slack -- we don't want to encourage re-use, so we don't want to do this
