### ISSUE TITLE
desktop offering: make important desktop information available on nodes list 

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#3320]
## User Story

We would like to allow the user to be able to see some additional information about desktops from the context of the list view, as well as filter the nodes list by these additional fields.
The following attributes have been identified as details important to the list view:
```
platform, domain, tag, chef version, ip address, ip 6 address, mac address, uptime, memory total, virtualization system, virtualization role, kernel release, kernel version, hostname, timezone, last checkin time, dmi system manufacturer, dmi system serial number, cloud provider
```

Let's get those indexed in es so we can allow the user to see them from the context of the nodes list view as well as filter by them.
Here are some reports that can be used for gathering the data: https://github.com/chef/chefdesktop/issues/23#issuecomment-610112335

## Definition of Done
The following information:
```
platform, domain, tag, chef version, ip address, ip 6 address, mac address, uptime, memory total, virtualization system, virtualization role, kernel release, kernel version, hostname, timezone, last checkin time, dmi system manufacturer, dmi system serial number, cloud provider
```
is available from the nodes list api, and the nodes list can be filtered by these field.

## Considerations

is this too much to add to the message size? is there a negative side effect to indexing all these additional fields?

**Comment by vjeffrey** [comment]
make this into subtask to 3344

**Comment by lancewf** [comment]
platform - done
last checkin time - done
tag - is this chef tags? 
chef version - need to check

domain - need to find
ip address - need to find 
ip 6 address - need to find
mac address - need to find
uptime - need to check
memory total - need to find
virtualization system - need to find
virtualization role - need to find
kernel release - need to find
kernel version - need to find
hostname - need to find
timezone - need to find 
dmi system manufacturer - need to find
dmi system serial number - need to find
cloud provider - need to find

**Comment by vjeffrey** [comment]
@btm @johnmccrae @phiggins do you know the matching report values for the above ones marked with "need to find" ?

**Comment by lancewf** [comment]
@vjeffrey I am finding them now. I was using the above to write down my progress.

**Comment by lancewf** [comment]
I don't know where to find the "cloud provider" and "timezone".

**Comment by phiggins** [comment]
I answered this in slack:

```
Ohai has that info, does that help?
Petes-MBP:ohai pete$ ./bin/ohai | jq ".time.timezone"
"PDT"
```

**Comment by btm** [comment]
For everyone's entertainment, here's the syntax built into ohai, and the wordy result I get on my windows desktop:

```
$ ohai time/timezone
[
  "Eastern Daylight Time"
]
```

**Comment by lancewf** [comment]
This task is ready to start adding all the new fields to the node-state index and ingestion. I moved on to a more risky task for now.
