### ISSUE TITLE
Team user table shows only removed user

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#3327]
##  Describe the bug
When I remove a user from a team, the list of users on the team details page gets replaced by the single removed user. The user **is** removed from the team at the API level.

## To Reproduce
- navigate to a team detail's page: https://a2-dev.test/settings/teams/a-new-team
- add a few users
- remove a user (remember their ID)
- you'll see the user table update to a single row with the removed user
- navigating away from page fixes it.

## Expected behavior
When I remove a user from a team, the team's user table should immediately update to remove only the removed user.

## Versions (please complete the following information):
- Browser: chrome
- Automate Build Number: 20200408145843

**Comment by susanev** [comment]
i added the emergent label and put this in the current sprint at the top of ready
