### ISSUE TITLE
Policy member Type column misaligned

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#3328]
## Describe the bug
`Type` column on policy members table is misaligned:

<img width="989" alt="Screen Shot 2020-04-08 at 4 22 12 PM" src="https://user-images.githubusercontent.com/21015366/78845840-a1970e80-79be-11ea-90ae-937b8c8cfec5.png">

https://a2-dev.test/settings/policies/administrator-access#members

## Versions (please complete the following information):
- Browser: chrome
- Automate Build Number: 20200408145843

**Comment by susanev** [comment]
@SEAjamieD is already on this one

**Comment by SEAjamieD** [comment]
yep! this is already being captured in https://github.com/chef/automate/issues/2064

**Comment by susanev** [comment]
gonna go ahead and close this one then, thanks jamie!
