### ISSUE TITLE
create 2 scripts for support: (1) list legacy policies, (2) list custom policies and custom roles that use infra:* 

### ISSUE THREAD

**Issue by blakestier** [chef/automate#3330]
We have a request from support to have a script that will help them easily query v2 policies that contain `infra:*` so that they can debug/proactively address any issues.

The query can be made via cURL and parsed with jo/jq. Python or ruby are also fine.

They like to see at least the names of the policies (the id is fine in addition).

**Comment by susanev** [comment]
i had a different understanding of this, i was under the impression that they only wanted a list of legacy policies.. @moutons can you confirm your needs?

**Comment by moutons** [comment]
it would be good to know 2 things:

- a list of policies flagged as migrated from v1, name & ID sufficient, not the policy content
- a list of any v2 policies containing `infra:*` so we can bring them up as potentially undesirable

the intention is to use these IAM API queries to output files to the gather-logs bundle similar to how we do for Elasticsearch:
https://github.com/chef/automate/blob/master/components/automate-deployment/pkg/server/gather-logs.go#L142:L154

**Comment by susanev** [comment]
updated the title, @blakestier feel free to adjust the issue content
for (2) pretty sure we only want to include custom policies and custom roles and not chef-managed ones

**Comment by msorens** [comment]
The following two shell commands (using just `curl` and `jq`) will identify all policies with actions of `infra:*`, whether inline actions or contained within a role. It ignores any system policies (via `type`) as well as system-generated-project-policies.
```
roles=$(curl -sSkH "api-token: $TOK" "https://a2-dev.test/apis/iam/v2/roles" | \
jq -r '[ .roles[] | select( .actions[] | contains("infra:*") ) | .id ] | unique | .[]')

curl -sSkH "api-token: $TOK" $TARGET_HOST/apis/iam/v2/policies | \
jq --arg roles "$roles" '.policies[] |
  (
    select (.type == "CUSTOM") |
    select (.id | endswith("-project-owners") or endswith("-project-viewers") or endswith("-project-editors") | not) |
    select (.statements[].role != "") |
    select( [.statements[].role] | inside($roles | split("\n")) )
  ),
  (
    select( .statements[].actions[] | contains("infra:*") )
  ) |
  { id, name }'
```
