### ISSUE TITLE
desktop access management questions

### ISSUE THREAD

**Issue by susanev** [chef/automate#3338]
## Overview
To help provide the auth team context and so they can support as needed, wed love if someone from the desktop team documented the answers to these questions.
## Desktop Access Management

1. Will this page be displayed to admins only?
    1. If not admin only, describe the experience for editors.
    1. If not admin only, describe the experience for viewers.
    1. If editors/viewers as we know them do not exist, what roles do need to exist?
1. What are the actions associated with desktop?
1. Will this work require a change to either the editor or viewer chef managed roles?
1. Will we need a new chef-managed role related to this work?
1. Will we need a new chef-managed policy related to this work?
1. Will desktop related resources be project-aware?

## References
[IAM Documentation](https://automate.chef.io/docs/iam-v2-overview/)

**Comment by susanev** [comment]
@vjeffrey @apriofrost could yall document the answers to these questions in this issue or link to a doc, reach out in the auth team channel if yall have any questions about these questions.

**Comment by vjeffrey** [comment]
1) no, not admins only. experience for editors and viewers should be same as anyone - they can see all the things. there are no actions that require create perms or anything. it's all read
2) we're mostly re-using infra apis, the ones that are new are read
3) no
4) no
5) no
6) no

pls correct me if you disagree with any of that @apriofrost

**Comment by apriofrost** [comment]
I agree with @vjeffrey wrote.

**Comment by susanev** [comment]
do we think the action structure will be infra:desktop:*? or will desktop be a top-level?

**Comment by vjeffrey** [comment]
the new APIs are all here: https://github.com/chef/automate/blob/master/api/external/cfgmgmt/cfgmgmt.proto#L139
that one, the geterrors one too and getmissingnodedurationcounts

**Comment by vjeffrey** [comment]
the action on all of them is `infra:nodes:list`

**Comment by susanev** [comment]
ah okay, so anyone with infra:nodes will see both the client runs page and the desktop page?

**Comment by vjeffrey** [comment]
yupp!
