### ISSUE TITLE
desktop offering: figure out the filters

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#3344]
## User Story

as part of the desktops list (insight) view in the desktop offering, there are multiple filters listed at the top, and a menu for users to select more filters.
next to each filter, there is a count of machines that currently match that filter.

we need to figure out if this is feasible and how to implement this.
![Screen Shot 2020-04-13 at 10 13 40](https://user-images.githubusercontent.com/10341541/79137280-ac132880-7d6f-11ea-9269-affc1327b1f3.png)

## Desired Filters
![Screen Shot 2020-04-13 at 20.58.22.png](https://images.zenhubusercontent.com/5cfebc28d99ac71fbfbdcb73/abd5f0c0-b272-44f1-951c-3aebd24b8aec)

platform, domain, tag, chef version, ip address, ip 6 address, mac address, uptime, memory total, virtualization system, virtualization role, kernel release, kernel version, hostname, timezone, last checkin time, dmi system manufacturer, dmi system serial number, cloud provider

## Things to think about
we don't have an api that currently gives us this information. we will probably need a new api, "top attributes" or something like that, maybe a req/resp something like:
```
request\
time range
platform, memory total, domain, virtualization system (i.e. a list of fields)

response\
[ { field: [ {match, match_count}, {match, match_count} ] } ]
(e.g. [{"platform": [ {"ubuntu 16.04", 12}, {"ubuntu 14.04", 20} ] } ]
```

then when a user selects a filter, we need to apply that filter to the api call and return the correct list of desktops

**Comment by vjeffrey** [comment]
related to https://github.com/chef/automate/issues/3320

**Comment by vjeffrey** [comment]
https://github.com/chef/chefdesktop/issues/23#issuecomment-610112335

**Comment by lancewf** [comment]
To collect the for each field we can use the same procedure as the compliance-service's GetStatsFailures (link below). 
https://github.com/chef/automate/blob/307e3ff4293b3dddd879a128eaa252936c520aac/components/compliance-service/reporting/relaxting/stats.go#L156
