### ISSUE TITLE
Fix branding: "Chef Client" -> "Chef Infra Client"

### ISSUE THREAD

**Issue by tas50** [chef/automate#3346]
## Overview
Automate is behind on the branding for Chef Infra Client, we need to update all labels to reflect current branding.

## Design Details
Fix it in all these places...
- [ ] Radial graph heading on client runs
- [ ] Node detail label
- [ ] data lifecycle settings
- [ ] subheading on client runs page
- [ ] subheading on notifications
- [ ] Dropdown on notifications
- [ ] Related documentation

### Describe the bug
In the Client Runs view you can filter on many things including "Chef Client Version" which needs to be "Chef Infra Client Version" to match the current branding of the client.

### To Reproduce
- Go to /infrastructure/client-runs
- Filter

### Expected behavior
Matches current branding

### Screenshots
![Screen Shot 2020-04-13 at 12 33 05 PM](https://user-images.githubusercontent.com/1015200/79153782-46309c00-7d83-11ea-8dc5-62be50ec4d44.png)

**Comment by susanev** [comment]
we haven't updated this branding in automate yet. there are a bunch of places we should update it. @tas50 do you mind if a hijack this card and add all the places it needs to be updated?

**Comment by tas50** [comment]
Go for it:

Under Infrastructure, the description of the Client runs needs to be "Chef Infra Client" and not "chef-client". We're trying to consistently use the brand name instead of the cli name. We shouldn't mention "chef-client" unless we're telling a person to type that in their shell.

![Screen Shot 2020-04-13 at 1 01 17 PM](https://user-images.githubusercontent.com/1015200/79156108-269b7280-7d87-11ea-9097-3f9b94c785f1.png)
