### ISSUE TITLE
inspec report size reduction: part two

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#3353]
## Definition of Done

_follow up to: https://github.com/chef/automate/issues/3087_

- create change in audit cookbook that coincides with profile metadata api that was added in automate
- audit cb, scan jobs: limit inspec result messages to 2k characters, include note in control results that full result was truncated for size
- audit cb, scan jobs: limit array of results to <number> : include message that array results were truncated on the control level

**Comment by vjeffrey** [comment]
https://github.com/chef-cookbooks/audit/issues/422

**Comment by alexpop** [comment]
This can be closed now as https://github.com/chef-cookbooks/audit/issues/422 has been shipped along with the changes in automate for the scan jobs initiated inspec execs. Cheers!
