### ISSUE TITLE
[Desktop UI] Customizable attributes to display in Insights panel

### ISSUE THREAD

**Issue by apriofrost** [chef/automate#3362]
### Problem
Different customers choose different attributes from Ohai to store information about their desktops. When comparing the attributes to identify the common attribute values that could potentially contribute to a problem, they need to be able to identify what attributes to account for.

### Solution
Provide customizable attributes to display in the table showing the desktop data, and the count numbers for the top 3 most common attribute values.

The screenshot below provides an example of three customized attributes to display in the table and the top 3 common values and their counts:

![image](https://user-images.githubusercontent.com/9401459/79286171-9fc4c380-7e74-11ea-804b-59d93a8dff57.png)

The screenshot below shows how a user could potentially select the attributes from a pre-defined list:

![image](https://user-images.githubusercontent.com/9401459/79286516-b7507c00-7e75-11ea-8c9d-cda0a83c52c7.png)

### Acceptance criteria (open for discussion)
The following acceptance criteria are sorted by importance from high to low, we can discuss the feasibility of accomplishing them by ChefConf:

1. Users can select 0 - 5 attributes from the available attributes listed in the following screenshot:

![image](https://user-images.githubusercontent.com/9401459/79287157-b7517b80-7e77-11ea-95cf-b0b8402fd42f.png)

2. Each card on the desktop view can have its own default attribute settings. For example, the "daily check-in" card can have different default attributes to display from "time since last check-in"  card like below:
![image](https://user-images.githubusercontent.com/9401459/79287039-5d50b600-7e77-11ea-88e1-a7613a0befa3.png)

3. Users can save the currently selected attributes as the default attributes to display in their local storage, but the customized default will be reverted once browser sessions expired (resource: https://coderwall.com/p/ewxn9g/storing-and-retrieving-objects-with-localstorage-html5)

4. Users can save the currently selected attributes as the default attributes to display no matter where and when then log in, the customizable default is tied to a user account.

**Comment by SEAjamieD** [comment]
@apriofrost  - thanks for putting this together!

>Users can save the currently selected attributes as the default attributes to display in their local storage, but the customized default will be reverted once browser sessions expired (resource: https://coderwall.com/p/ewxn9g/storing-and-retrieving-objects-with-localstorage-html5)

How much do we care about saving to their local storage?  I feel like the value add here is minimal in the sense that, we will very likely be storing this in the application state, so the values will persist as long as the application is still alive.  This is of course shorter/different than a browser session but once we get into number 4
>Users can save the currently selected attributes as the default attributes to display no matter where and when then log in, the customizable default is tied to a user account.
I see us making an api call, and storing this in a database tied to the user account.

I guess the short of what i'm getting to is that #3 and #4 feel like they are accomplishing _almost_ the same thing as #4 alone, while adding extra overhead to the development work.

**Comment by apriofrost** [comment]
@SEAjamieD From a UX design perspective, as long as the values are persistent during the time users interacting with Automate, that's a big win in comparison to losing all the attributes they've selected with a page refresh. 
You are right, the ultimate goal is to get to no.4. If 4 is not achievable, anything we can do to enable the ability mentioned above this paragraph will be good.
From what I see now in Automate - Infra - Client Runs, the customized table columns are reset every time the page refreshes.

**Comment by apriofrost** [comment]
After the discussion about the attributes data with @lancewf , we decided to iterate on the design further to differentiate the attributes whose values are unique per desktop, therefore showing the top 3 values don't apply. 

> We are pulling 14 of the below fields out of the Ohai and placing them in the node-state. The first set make sense to me to allow filtering on them, but the second set are unique values to the node. Do it make sense that a user would filter on them? I would think they would only get one node.
> name - where in the CCR "example"
> **First Set**
> timezone - .node.automatic.timezone "EDT"
> cloud provider - .node.automatic.cloud.provider "ec2"
> dmi system manufacturer - .node.automatic.dmi.system.manufacturer "Xen"
> virtualization system - .node.automatic.virtualization.system "xen"
> virtualization role - .node.automatic.virtualization.role "guest"
> kernel release - .node.automatic.kernel.release "3.10.0-229.el7.x86_64"
> kernel version - .node.automatic.kernel.version "#1 SMP Thu Jan 29 18:37:38 EST 2015"
> **Second Set**
> domain - .node.automatic.domain "us-west-2.compute.internal"
> hostname - .node.automatic.hostname "ip-127-208-184-141"
> dmi system serial number - .node.automatic.dmi.system.serial_number "ec2e0f80-06cc-d659-e439-34147116b49f"
> memory total - .node.automatic.memory.total "3689604kB"
> ip address - .node.automatic.ipaddress "127.208.184.141"
> ip 6 address - .node.automatic.ip6address "fe80::3f:b5ff:fe7e:adff"
> mac address - .node.automatic.macaddress "02:3F:B5:7E:AD:FF"

**Comment by vjeffrey** [comment]
completed as part of https://github.com/chef/automate/pull/4083
