### ISSUE TITLE
Mirror latest validation strategy from authz to teams, authn, and users

### ISSUE THREAD

**Issue by msorens** [chef/automate#3371]
Per PR #3312, we made this change to authz-service (so policies, rules, roles, projects):
Validation on policy Get requests (and, while I was in there, all other resource requests that didn't create the id) no longer validate on length. Instead, validation confirms the required field is present and has more than whitespace characters.

Would be nice to do the same for teams-service and authn-service (teams, tokens, users).

**Comment by susanev** [comment]
closing, this work has been deprioritized.
