### ISSUE TITLE
allow optional assign to policy on create token modal

### ISSUE THREAD

**Issue by susanev** [chef/automate#3385]
## Overview
In the UI, after creating a token it has zero permissions. Folks then have to navigate to policies to assign it to a policy. This puts a lot of extra effort on the user and requires folks to have this knowledge. This also changed from IAM v1, where creating a token automatically had ingest permissions. Let's make this better!

## Design Details
_Note: sections have been cut from this issue, and will be done in #3439_
- Add a multi-select dropdown of current policies, that folks can add the token to on token creation
- Policies should be order alphabetically
- ~Two sections, chef-managed and custom~
    - ~chef managed order: Ingest, Administrator, Editors, Viewers~
    - ~custom order: alphabetical~
    - ~if they are filtering and there are no results in a section, the section header should be hidden~
- The list of policies should display the policy name 
- Front-end filtering capabilities, same as the project assignment dropdown
- This should be optional, so folks can still create a token without assigning a policy
- If nothing is selected, the top should display _None_, if 1 policy is selected the top should display that policies name, if multiple are selected it should display _n policies_, this is the same behaviour as the project assignment dropdown
- Only folks with permissions to assign tokens to policies should see this dropdown, more than likely only admins unless they have some custom policies that give more access to creating tokens and managing policies
- If they are filtering and there are zero results, display _No policies found.   You don't have access to any policies that match your search._

### Visual Design
- Reuse the project assignment styles
- Update the projects label and this new policies label to have `padding-bottom: .75em;` which all the other labels have
- ~Section headers use chef-dark-gray, and font-size 11px, and should be h3s~
- ~24px between the chef-managed and custom sections~
- ~10px between the section label and the first checkbox~

### Closed, 0 selected
<img width="718" alt="closed-zero-selected" src="https://user-images.githubusercontent.com/5489125/79643450-dbeb7300-8157-11ea-8c2d-02917986a60b.png">

### Open, 0 selected
![policy-assignment-open](https://user-images.githubusercontent.com/5489125/79644120-b6f8ff00-815b-11ea-8068-e4925b171ca7.png)

### Open, no results
![policy-assignment-no-results](https://user-images.githubusercontent.com/5489125/79644146-e0198f80-815b-11ea-9751-da790668d61f.png)

**Comment by susanev** [comment]
i moved the section stuff to #3439, but im not gonna update the screenshots

**Comment by msorens** [comment]
Micro-requirements:


1. Upon opening token modal
-	shows a policy dropdown if user has permission to assign tokens to policies
-	does not show a policy dropdown if user does not have permission to assign tokens to policies
2. With no filter and no custom policies
-	displays 4 system policies by name
-	order of policies is fixed: Ingest, Administrator, Editors, Viewers
3. With no filter and some custom policies
-	displays 4 system policies plus custom policies
-	order of policies is system policies in fixed order (Ingest, Administrator, Editors, Viewers), then custom policies alphabetically
4. With filter applied
-	list should be reduced; system or custom policies treated the same
-	if list is reduced to zero entries, should see a "No policies found..." message
5. Create Token
-	is successful without selecting any policies
-	is successful when selecting one policies and token is added to the policy
-	is successful when selecting some policies and token is added to those policies
-	is successful when selecting all policies and token is added to those policies
-	with no policies selected displays "None"
-	with one policy selected displays the policy name
-	with more than one policy selected displays "n policies"
