### ISSUE TITLE
update docs command chef-automate iam reset-to-v1 no longer available 

### ISSUE THREAD

**Issue by ericcalabretta** [chef/automate#3395]
## Describe the bug
`chef-automate iam reset-to-v1` is not longer an available cli command. It is not possible to downgrade to IAMv1 once upgraded to the current Automate version. 

Docs URL
https://automate.chef.io/docs/cli-chef-automate/#chef-automate-iam-reset-to-v1

## Versions (please complete the following information):
Automate 2
Build: 20200408145843

**Comment by susanev** [comment]
looks like upgrade is still there as well

**Comment by ericcalabretta** [comment]
Maybe keep them since customers could still be on a previous version via backup or air-gap install, but mark as no longer valid after a specific version?

**Comment by yzl** [comment]
fwiw, these docs are generated from the `automate-cli` package. I don't see code for an `iam reset-to-v1` command or an `iam upgrade-to-v1` command, so my guess is that either the docs aren't being generated correctly, or they are being generated but they're not being published.

**Comment by susanev** [comment]
i wonder if this is related to the cli docs error we were getting related to how it interacts with the api docs generation, @chef/auth-team thoughts?

**Comment by yzl** [comment]
If I remove the contents of the`automate-chef-io/data/docs/cli_chef_automate` directory and regenerate the docs by running `make docs` in `automate-cli` in the studio (I might have had to install some stuff first), then I get a set of iam docs that do not include the yaml pages for `reset-to-v1` and `upgrade-to-v2`. I wonder if the process we have in the build pipeline doesn't handle removing pages for deprecated commands, so we might have to `git rm` them manually?

**Comment by srenatus** [comment]
See #3405 and #3403, please. :)
