### ISSUE TITLE
Fix API docs URL paths

### ISSUE THREAD

**Issue by srenatus** [chef/automate#3401]
Previously, our proto files' http annotations had **not** been carrying the complete path -- they were omitting the prefix (`/api/v0`). Additonally, introducing a versioning scheme that hasn't caught on, all new IAM endpoints are under `/apis/iam/v2`, which also doesn't show in the proto files. As a result, our API docs URL paths are wrong.

The work spiked in #3419 showed that it's a better idea to put the *correct path* into the proto files, so we don't have to worry about mismatches.

To finish this, we need to
- [X] adapt the IAM protos
- [X] adapt the IAM introspection requests
- [x] adapt the other protos
- [x] adapt their introspection requests
- [x] fix routing
- [ ] deal with the test fallout 

For more notes, please see #3474.

<details><summary>previous issue body</summary>

The IAM endpoints use a versioning scheme that hasn't caught on. As a result, their API prefix (`/apis/iam/...`) doesn't appear properly in the generated API docs.

To keep the present prefix (for compatibility), but also to make the docs **correct**, we could investigate adding another set of endpoints, either

1. by fiddling with the serve mux in automate-gateway, or
2. by adding a rewrite to automate-load-balancer.

Then, we need to ask ourselves how we want to test the added endpoints. Do we want to treat both sets of endpoints as proper ones; or keep our tests as is (testing `/apis/iam`), or rewrite them to test `/api/v0` etc.
</details>

**Comment by susanev** [comment]
as a note, this will only fix part of the path that is broken in the api docs
currently, all the api docs use `https://automate.chef.io/api` with no version

**Comment by susanev** [comment]
this should probably not be linked to #3418 because that merge will not fix this issue

**Comment by srenatus** [comment]
I think the work started (or drafted) in #3419 is the right way to go. :)
