### ISSUE TITLE
Change the error response for the duplicate data feed.

### ISSUE THREAD

**Issue by vinay033** [chef/automate#3434]
## Describe the bug

I have  noticed if we trying to create the duplicate feed object then we are getting error response like
```
{
  "error":"pq: duplicate key value violates unique constraint \"destinations_name_key\"",
  "code":2,
  "message":"pq: duplicate key value violates unique constraint \"destinations_name_key\"",
  "details":[]
}
```
but in case of other places, we are getting more human-readable error responses, for example in case of server we are getting the error response like
```
{
   "error":"server with that name \"chef server test\" already exists",
   "code":6,
   "message":"server with that name \"chef server test\" already exists",
   "details":[]
}
``` 

## To Reproduce
- create data feed with any name and try to create one another data feed with the same name.

## Expected behavior
we need error response like
``` 
{
   "error":"Data feed with that name \"test\" already exists",
   "code":6,
   "message":"Data feed with that name \"test\" already exists",
   "details":[]
}
```

**Comment by satellite15** [comment]
What do you want the error messages to be?

Using "My DataFeed" as the example name, for create I have

"A data feed destination already exists with name \"My DataFeed\""

and for update

"Cannot update name, a data feed destination already exists with name \"My DataFeed\""

```
{"error":"Cannot update name, a data feed destination already exists with name \"My DataFeed\"","code":3,"message":"Cannot update name, a data feed destination already exists with name \"My DataFeed\"","details":[]}
```

**Comment by susanev** [comment]
@vinay033 can we close this?

**Comment by vinay033** [comment]
> @vinay033 can we close this?

yes
