### ISSUE TITLE
Error if `membership_id` isn't a GUID

### ISSUE THREAD

**Issue by blakestier** [chef/automate#3437]
from an SA:

> Hi Everyone
> Another api question.  When I run the following command, I get no error, but the user is not added to the team.  It works when I add via the UI fine.  Do I have the api command wrong ?  Thanks
> curl https://${var_automate_hostname}/apis/iam/v2/teams/editors/users:add --insecure -H "api-token: ${var_automate_token}" -d '{"membership_ids": ["workstation-1"]}'

from @susanev:

> all right, the path and curl look good. my guess is that is not really the users membership id. users have user ids and membership ids. to get the membership id of a user you can use...
> curl "api-token: ${var_automate_token}" https://${var_automate_hostname}/apis/iam/v2/users/workstation-1

Customers continue to add the user id over the membership id. Another small fix would be to return an error if the "membership_id" is not a guuid. not a failsafe as user ids might be guuids?

**Comment by susanev** [comment]
this work has been deprioritized.
