### ISSUE TITLE
count of control failure/pass/skip/waived on reports list does not match report fetch

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#3448]
## Describe the bug
https://github.com/chef/automate/issues/3277

the totals on the reports list do not *always* match the actual report

## To Reproduce
- load_compliance_reports
- look at the results for osx(2)-omega-pro1(f)-pro2(w)-failed - *node details page*
![Screen Shot 2020-04-21 at 08 53 21](https://user-images.githubusercontent.com/10341541/79880690-945e2480-83ad-11ea-88d6-3873617e67b2.png)

![Screen Shot 2020-04-21 at 08 53 51](https://user-images.githubusercontent.com/10341541/79880739-a50e9a80-83ad-11ea-986f-55b58c5d4375.png)

## Expected behavior
counts should match list

**Comment by rickmarry** [comment]
I have reopened #3277.
I think this is a frontend issue

**Comment by vjeffrey** [comment]
thank you @rickmarry !!
