### ISSUE TITLE
Timestamp fields in IAM APIs

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#3471]
## Description

Up for discussion: How do we want to standardize on `updated_at` and `created_at` in our APIs? Only tokens and teams have those fields. Tokens are the only ones that bubble them up to the API response. Do we want them or not?

If we do want them, let's add them to all of our APIs. Let's also add triggers to handle updating `updated_at`
(per this [comment](https://github.com/chef/automate/pull/3414/files#diff-baca5c726bab1ad3b3fc60b41324f295R416))

**Comment by susanev** [comment]
this work has been deprioritized.
