### ISSUE TITLE
Automate Infra Manage Shared Modals

### ISSUE THREAD

**Issue by btm** [chef/automate#3479]
# Automate Infra Manage
####  (Chef Manage in Automate)

For [Automate Infra Manage [read/write]](https://github.com/chef/automate/issues/3384) there are two common modals that we need to recreate from Chef Manage. These items were previously part of #3384 but have been split out.

- [ ] run list editor modal
- [ ] json [attribute] editor

### Run List Editor shared modal
The existing run list editor in Chef Manage provides a drag and drop interface for creating an ordered run list composed of roles and recipes. This interface is used both for nodes and roles.

Recipes are described as either "cookbook_name" or "cookbook_name::recipe_name", when a recipe name is not provided, it implies the "default" recipe (i.e. cookbook/recipes/default.rb).

![image](https://user-images.githubusercontent.com/4381/79460840-65b60780-7fc3-11ea-921d-d70e6f997205.png)

### JSON Editor shared modal
There is a simple modal needed for a number of objects that displays a JSON object, allowed the user to edit the contents, and saves it. Ideally the object would be linted for correctness (to the JSON spec only) either automatically or when the user clicks the create/save button.

Attributes are the most common use of this modal, and they have a 'precedence' which is convenient to display (e.g. normal, override, default). There could be some additional specialization on this modal for attributes, but it is also needed for data bag items.

![image](https://user-images.githubusercontent.com/4381/79462124-1a9cf400-7fc5-11ea-923a-544128c0b96f.png)

**Comment by btm** [comment]
This is pending UX help, will be after ChefConf.

**Comment by vjeffrey** [comment]
![shared-modal](https://user-images.githubusercontent.com/10341541/94480561-b5644600-0193-11eb-9b58-66a079108842.png)
missing some helper text; also want to support mouse dragndrop functionality
