### ISSUE TITLE
Drop IAM V1 policies table after we feel confident in force-upgrade migration

### ISSUE THREAD

**Issue by tylercloke** [chef/automate#3480]
Add a migration that drops the policies table once we feel comfortable doing so

**Comment by susanev** [comment]
hold on this until at least 09/14/2020

**Comment by susanev** [comment]
still wanting to hold on this

**Comment by susanev** [comment]
closed this, see [internal slack convo](https://chefio.slack.com/archives/C61F9HHKK/p1600443799002000)
