### ISSUE TITLE
[Desktop UI] Download filtered list of desktop data as JSON or CSV

### ISSUE THREAD

**Issue by apriofrost** [chef/automate#3503]
## User Story
Allow users to download the filtered desktop data in the current view in a JSON or CSV format.

## Solution
Reuse the same API for downloading node data in Infrastructure, follow the new UI pattern.
### UI Mockup
https://chef.invisionapp.com/share/7ZWRC1GNQ2P#/412590751_-Slice_1_Release-Desktop_Dashboard-Daily_Unknown-Lg 

_Use the "inspect" feature at the bottom right of the mockup screen to see the UI implementation details_

Click on the "Download" button
![image](https://user-images.githubusercontent.com/9401459/80267089-46b71580-8654-11ea-8f04-608068261d64.png)

## Acceptance Criteria

1. Reuse the same API for downloading node data in Infrastructure
2. Use the Carbon design system `dropdown/default without label`, restyle it to match with the mockup
3. Reuse the file generating UI modal (pending state) in Infrastructure.

**Comment by vjeffrey** [comment]
the api for this is the same one used here:
![Screen Shot 2020-04-27 at 13.41.46.png](https://images.zenhubusercontent.com/5cfebc28d99ac71fbfbdcb73/a8da83fa-cc54-44bb-bc2c-b45a8bdfdd55)

api looks something like:
```
curl https://a2-dev.test/api/v0/cfgmgmt/nodes/export -d'{"output_type":"csv","filter":[],"sorting":{"field":"name","order":0}}'
```
