### ISSUE TITLE
refactor team server and tests

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#3512]
## Definition of Done

There's a few odd things about our team server setup and especially in the test setup, probably relics of how long ago we wrote it.

One particular opportunity for refactoring:
- unexport `TeamServer` in team.go 
- refactor team_test.go setup so we don't depend on the exported server (look to policy_test.go for reference)

Feel free to make other improvements as you see fit!

**Comment by susanev** [comment]
this work has been deprioritized.
