### ISSUE TITLE
automate-ui/projectsFilter: deleted projects still live in localstorage, are sent with requests

### ISSUE THREAD

**Issue by srenatus** [chef/automate#3530]
### Reproduction steps

1. observe localstorage's `projectsFilter.option` for an a2 instance with no projects: there's no such key
2. create a project, "asdf" -- still no key in localstorage
3. pick both "(unassigned)" and "asdf", _Apply Changes_: we now have a setting:
```
[{"label":"(unassigned)","value":"(unassigned)","type":"CHEF_MANAGED","checked":true},{"label":"asdf","value":"asdf","type":"CUSTOM","checked":true}]
```
4. go to projects, delete the "asdf" project
5. notice that localstorage still has the same content
6. reload the page
7. same content in localstorage
8. in the network tab, notice that requests are sent with the old project id:
```
projects: (unassigned), asdf
```

## Definition of Done

localstorage is in sync with deleted projects

**Comment by srenatus** [comment]
Q: Why do we need to use localstorage at all?

**Comment by msorens** [comment]
> Q: Why do we need to use localstorage at all?
That provides the convenience of having the same set of projects selected the next time you open A2.

**Comment by srenatus** [comment]
I think I dislike treating localStorage as a giant global variable. Could we thread it through ngrx' stuff? It's like a request, except that it's not sent to a backend.

**Comment by srenatus** [comment]
I'll accept!

✅ Deleting a project via the UI, it disappears from localstorage.
✅ Deleting a project from the API, reloading the page, I don't find the project in localstorage or request headers.
