### ISSUE TITLE
automate-ui/telemetry warning

### ISSUE THREAD

**Issue by susanev** [chef/automate#3531]
## overview
the console error is fixed in #3529 
but there's a warning now that we should also fix
![80578289-82f9c580-8a08-11ea-92b7-8b0add914a8b](https://user-images.githubusercontent.com/5489125/80600467-4a92c100-89e1-11ea-99f1-05e094acc538.png)

**Comment by srenatus** [comment]
I'm not 100% certain, but it could be that the cookie is sent from segment.com -- if that's the case, there's nothing we can do about this except using something else, or routing stuff through one of our telemetry services...

**Comment by susanev** [comment]
this work has been deprioritized.
