### ISSUE TITLE
create token multi-select dropdown issues

### ISSUE THREAD

**Issue by susanev** [chef/automate#3533]
## overview
when creating a token if a user opens the projects dropdown and then the policies dropdown the policies dropdown appears behind the projects dropdown.

## repro steps
1. navigate to settings > tokens
2. use the create token button
3. open the projects dropdown
4. open the policies dropdown
5. notice that the policies dropdown displays behind the projects dropdown

## what it should be
there's click outside functionality that is supposed to close the dropdown, so if the user opens the projects one first and then clicks outside to open the policies one the projects one should close. something is not working.

**Comment by SEAjamieD** [comment]
I'm moving this back into on deck - After I realized the action that is being looked for, having the last item clicked always remain on top - it will require a little more logic and the desktop needs priority for now

**Comment by susanev** [comment]
@SEAjamieD i wrote this quick and need to think more about it. i think that might not be the right approach. but either way i dont think this is ready for ur work yet, sorry about the miscommunication.

**Comment by susanev** [comment]
@SEAjamieD updated...
>there's click outside functionality that is supposed to close the dropdown, so if the user opens the projects one first and then clicks outside to open the policies one the projects one should close. something is not working.
