### ISSUE TITLE
create token with same id and assign to policy issue

### ISSUE THREAD

**Issue by susanev** [chef/automate#3537]
## repro steps
- navigate to settings > tokens
- create a token named test
- create another token named test and assign it to a policy
- watch the token creation fail but the policy assignment succeed

[video in slack](https://chefio.slack.com/archives/C61F9HHKK/p1588170808445700)

## what it should be
- policy assignment should not happen if the token could not be created

**Comment by susanev** [comment]
moved to #3535

**Comment by msorens** [comment]
After writing up additional notes in #3535 re-instating this as a useful win as low-hanging fruit.
