### ISSUE TITLE
Automate infra views UI changes 

### ISSUE THREAD

**Issue by vsingh-msys** [chef/automate#3538]
Minor UI changes as in #1544 
```
Note in both cases the relevant information should not be viewable in the UI
if you lack permissions.
For example, a normal user could see the list of Chef Servers,
but the "Add Chef Server" (rename to "Connect Chef Server") button would not be visible.
```
#### Changes required in UI

- [ ] Rename `Add Chef Server` to `Connect Chef Server`
- [x] Chef Server detail page input padding.
- [x] Rename "org" with "organizations" for cookbooks list, orgs detail page.
- [x] Rename "Add Chef Org" with "Add Chef Organization" modal and rename button to.
- [x] Rename "Org Name" with "Name" on orgs list page.

- [x] Make Admin Key field optional on Org detail page until we will remove it.

- [x] Padding issue on Add Org modal between form fields.

- [x] Loading spinner on chef servers list and orgs list page

- [ ] Org "admin_key" is being removed from org responses need changes in UI models as well.

- [x] Wrap buttons with the `app-authorized` component show it get hidden if user lacks permission. [Here's an example](https://github.com/chef/automate/blob/master/components/automate-ui/src/app/modules/team/team-management/team-management.component.html#L32-L34)

Screenshots:

![server-detail](https://user-images.githubusercontent.com/44496937/80636351-f3d9c580-8a7a-11ea-9db6-0be0820185aa.png)

![create-org](https://user-images.githubusercontent.com/44496937/80636356-f5a38900-8a7a-11ea-830b-19f7ec314caf.png)

![org-detail](https://user-images.githubusercontent.com/44496937/80636360-f5a38900-8a7a-11ea-969f-bfa21c92856b.png)

**Comment by btm** [comment]
All of this work was done in #3616 except:
- the 'connect chef server' item came from an errant comment of mine and doesn't need to be done
- the reset key flow will be done separately and is tracked in #3450.
