### ISSUE TITLE
[Desktop API] Download individual desktop historical data as JSON or CSV

### ISSUE THREAD

**Issue by apriofrost** [chef/automate#3544]
## User story
Allow users to download the individual desktop historical data, including all the run happened in the selected time span and the attributes data, in a JSON or CSV format.

## Solution
Reuse the `report_export` API and add the extra Ohai attributes that are included in the desktop details view, the time span is defined by the currently selected value in the dropdown in the UI (2 weeks or 4 weeks)
### Infra node report export API details
https://github.com/chef/automate/blob/42fb0448535b9df5a8b1acc1b29000ab836875c6/components/config-mgmt-service/grpcserver/report_export.go#L28-L57
### Desktop specific data to include
Name | Example Value(s) | Explanation
-- | -- | --
platform | windows, ubuntu | Name of operating system as derived by Chef/us
platform_version | 10.0.18362, 16.04 | Numeric/comparible version of the operating system.
chef_packages/chef/version | 16.0.158 | version of Chef Infra Client installed
ipaddress | 192.168.5.30 | our best guess at the most meaningfull IP address to the user
ip6address | fe80::20c:29ff:fe2a:76e5 | our best guess at the most meaningfull MAC address to the user
macaddress | 00:0C:29:2A:76:E5 | our best guess at the most meaningfull IPv6 address to the user
uptime | "6 days 05 hours 55 minutes 05 seconds" | uptime is already formatted, use uptime_seconds if we want to format ourselves, but not both
memory/total | 16645660kB | system memory, with the unit, probably needs UI converstion to GB every time.
virtualization/system | vmware | primary relevant virtualization system
virtualization/role | guest, host | Is this a host, guest, or nothing detected (empty)
kernel/release | 10.0.18362 |  
kernel/version | 10.0.18362  Build 18362 | not duplicative on linux, but kernel/release is most important.
hostname | btm-thinkpad, chef-server | skip machinename, just hostname
domain | ninjr.org | doesn't always exist but useful when it does
time/timezone | GMT, Eastern Daylight Time | Timezone as presented by the operating system
ohai_time (Liz: matches with last run end time in the UI)| 1581547279 | When Chef Infra Client (technically ohai) last run. convert from "unix time" for display
dmi/system/manufacturer | LENOVO, VMware Inc. | not working on windows
dmi/system/serial_number | R90QS96N | service tag, not working on windows
chef infra server (Liz: not sure about the actual name) | chefserver.eastus.cloudapp.azure.com
node id (Liz: note sure about the actual name) | 62cfc16b-c07d-4f2e-8bdc-49df1db61777

### UI Mockup
Note: the current UI only displays the latest attributes data and the most meaningful status per day. But the exported JSON and CSV include all the historical attributes that identified with each historical run in the selected time span. It'll be great if we can match the sequence of the data in the API with that in the UI.

![image](https://user-images.githubusercontent.com/9401459/80660729-63cb5a00-8a41-11ea-8465-e9380ce6378e.png)

#### Mockup link
https://chef.invisionapp.com/share/7ZWRC1GNQ2P#/414257682_Desktop_Dashboard-Daily_Unknown-Desktop_Detail-2

**Comment by lancewf** [comment]
Below are the fields that need added. 
hostname
ip6address
macaddress
memory/total
virtualization/system
virtualization/role
kernel/release
kernel/version
domain
time/timezone
ohai_time
dmi/system/manufacturer
dmi/system/serial_number
