### ISSUE TITLE
[Desktop UI] Download individual desktop historical data as JSON or CSV

### ISSUE THREAD

**Issue by apriofrost** [chef/automate#3545]
## User story
Allow users to download the individual desktop historical data, including all the run happened in the selected time span and the attributes data, in a JSON or CSV format

## Solution
Add a download button, same as https://github.com/chef/automate/issues/3503, using the new API in https://github.com/chef/automate/issues/3544
![image](https://user-images.githubusercontent.com/9401459/80661917-de49a900-8a44-11ea-8a14-daa053c2797f.png)

## Mockup 
sm:
https://chef.invisionapp.com/share/7ZWRC1GNQ2P#/415174051_Desktop_Dashboard-Daily_Unknown-Desktop_Detail-2-Sm
Half screen - xlg:
https://chef.invisionapp.com/share/7ZWRC1GNQ2P#/414257682_Desktop_Dashboard-Daily_Unknown-Desktop_Detail-2
Full screen - xlg: https://chef.invisionapp.com/share/7ZWRC1GNQ2P#/415415417_Desktop_Dashboard-Daily_Unknown-Desktop_Detail-2-Enlarged

**Comment by vjeffrey** [comment]
this isn't actually blocked on the api work, so i'm moving it to prioritized

**Comment by vjeffrey** [comment]
endpoint sample is:
```
curl 'https://a2-local-inplace-upgrade-dev.cd.chef.co/api/v0/cfgmgmt/reports/export' \
-d '{"output_type":"csv","sorting":{},"node_id":"43589d3e-f1bb-45b5-8789-03508ed37891","filter":[],"start":{"seconds":1591488000},"end":{"seconds":1591660799}}' 
```
