### ISSUE TITLE
Event feed: Users can tab outside of grouped actions side panel

### ISSUE THREAD

**Issue by magwalk** [chef/automate#355]
# User Story
![tab-outside](https://user-images.githubusercontent.com/7217000/57800290-e8747980-7705-11e9-9ac5-2e99c2ea9c0a.gif)

Currently when a user opens the grouped events panel by clicking on a link of grouped events and continues to tab through the panel and close button, the user can tab outside of the side panel without closing the side panel. Ideally this would return focus to the grouped events link so users can go back to the place in the list where they were previously.

# Demo Script / Repro Steps
Start up the UI and run `chef_load_actions 500` (or some other large number - it can be tricky to get grouped events in dev so I usually do it by loading an absurd amount of events). Click on one of the grouped actions, tab around the side panel.

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
