### ISSUE TITLE
investigate report validation errors with BadRequest status

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#3554]
GRPC provides a [BadRequest error message type](https://github.com/googleapis/googleapis/blob/master/google/rpc/error_details.proto#L164-L180) that can be populated with details on what fields failed validation.

[This post](https://jbrandhorst.com/post/grpc-errors/) provides a good example on how to use the BadRequest error.

review the infra proxy validation code and figure out if the auth team wants to adopt it as our position

**Comment by msorens** [comment]
Might mention how validation errors are currently reported. Do they just use a different error code? Or are there inconsistencies depending on the call or the service...?

**Comment by susanev** [comment]
closing, this work has been deprioritized.
