### ISSUE TITLE
make project_ids validation consistent with authz

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#3559]
Right now `validateProjectAssignments` depends on [proto validation](https://github.com/chef/automate/blob/master/api/interservice/authz/v2/authz.proto#L89-L98). So creating a team with an empty string/or unassigned project will result in this error:
```
[18][default:/src:0]# curl -kH "api-token: $TOK" -X POST -d '{"id": "foo", "name": "foo", "projects": [" ", "(unassigned)"]}' https://a2-dev.test/apis/iam/v2/teams | jq
{
  "error": "invalid ValidateProjectAssignmentReq.NewProjects[0]: value does not match regex pattern \"^[a-z0-9()-_]{1,64}$\"",
  "code": 3,
  "message": "invalid ValidateProjectAssignmentReq.NewProjects[0]: value does not match regex pattern \"^[a-z0-9()-_]{1,64}$\"",
  "details": []
}
```

doing the same thing with a role or policy, which depends instead on authz-service's server validation, results in a different error:
```
[9][default:/src:0]# curl -kH "api-token: $TOK" -X POST -d '{"id": "foo", "name": "foo", "actions": ["do:the:thing"], "projects": [" "]}' https://a2-dev.test/apis/iam/v2/roles | jq
{
  "error": "projects must contain at least one non-whitespace character",
  "code": 3,
  "message": "projects must contain at least one non-whitespace character",
  "details": []
}
```

To make these consistent, we can add the same server-level validation to [ValidateProjectAssignment](https://github.com/chef/automate/blob/master/components/authz-service/server/authz.go#L165)

**Comment by susanev** [comment]
closing, this work has been deprioritized.
