### ISSUE TITLE
Project update & filtering in the UI

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#3594]
## Overview
Add cypress tests for project filtering.

- [ ] create a project, create some rules for that project
- [ ] Update Projects
- [ ] Cancel the update
- [ ] retry the update
- [ ] add some resources to a project (teams, tokens)
- [ ] load some client/compliance data with specific attributes that the project rules will map to
- [ ] add a user to the project's Project Owner policy 
- [ ] log in as that user and verify they see the expected data in their project

NOTE: this card cares most about testing the Project Update UI interactions. Some calls, like adding resources to projects and loading node data, can be done via the API for expediency

## Resources
- [Acceptance testing script, projects & rules section](https://docs.google.com/spreadsheets/d/1mV8dAARhBFxxMZR6gEm1yDXnPqHb9U2mPhZ-zhHLajw/edit#gid=218075547)

**Comment by susanev** [comment]
this work has been deprioritized.
