### ISSUE TITLE
Image URL included in Slack integration returns 404

### ISSUE THREAD

**Issue by jasonwbarnett** [chef/automate#3602]
## Describe the bug

When using the Slack integration, the `icon_url` provided returns a 404.

URL: https://docs.chef.io/_static/chef_logo_v2.png

## To Reproduce

- Setup Slack integration
- See the JSON body includes a URL to a missing image

## Expected behavior

- Expect the url provided in `icon_url` to actual resolve to an image that is accessible.

**Comment by jasonwbarnett** [comment]
If someone can point me to the right URL, I'd gladly submit a fix.

**Comment by susanev** [comment]
was just looking, we dont seem to have a hosted version of only the logo without the text. im adding one now.

**Comment by susanev** [comment]
@jasonwbarnett thanks for reporting this! we got a new image added. it wont make it into the next release but will be in the one after that which should happen on monday, may 18th if everything stays on schedule.

pr: #3604

**Comment by susanev** [comment]
should be fixed in the release on monday may 18th
