### ISSUE TITLE
Expose the API documentation on the customer deployed A2 server again

### ISSUE THREAD

**Issue by sam1el** [chef/automate#3607]
# Redirect Alert!

## Submit your feature request via the [Chef Ideas Portal](https://chef-software.ideas.aha.io/)
This documentation is a wonderful reference for customers.

**Comment by vjeffrey** [comment]
@sam1el i'm not sure which documentation you're talking about? could you expand?

**Comment by vjeffrey** [comment]
are you talking about the swagger api docs?  we were hoping the api docs that we're providing on automate.chef.io would be enough to support folks. are there specific items missing?

**Comment by susanev** [comment]
more context in [internal slack convo](https://chefio.slack.com/archives/C6UKR7SHZ/p1588778424402800)

but he wants https://AUTOMATE_URL/api/v0/openapi/ui/# to work again

someone recently in [success slack](https://chef-success.slack.com/archives/C071VQUP5/p1587660849177100?thread_ts=1587660518.176600&cid=C071VQUP5) also asked for this

**Comment by vjeffrey** [comment]
@chef/docs-team @krasnow any thoughts/opinions on this request?

**Comment by susanev** [comment]
@chef/docs-team @krasnow @nfisher-chef @vjeffrey can we close this?
