### ISSUE TITLE
Postgres service doesn't spawn as 127.0.0.1

### ISSUE THREAD

**Issue by rwc** [chef/automate#3610]
## Describe the bug
When following the instructions here: https://automate.chef.io/docs/configuration/#postgresql to set the address the postgres service spawns as, entering `127.0.0.1` or `localhost` causes service failures. It expects `0.0.0.0` or the ip of the host.

## To Reproduce
```
$ vi postgres.toml
[postgresql.v1.sys.service]
host = "127.0.0.1"
[postgresql.v1.sys.pg]
[postgresql.v1.sys.logger]
[postgresql.v1.sys.superuser]

$ chef-automate config patch postgres.toml
```

## Expected behavior
I would expect a host setting of `localhost` or `127.0.0.1` to spawn the postgres service successfully.

## Versions (please complete the following information):
- OS: Ubuntu 18.04
- Automate Version: 
```
> chef-automate version
Version: 2
  CLI Build: 20200429142522
  Server Build: 20200429153636
```

**Comment by stevendanna** [comment]
I believe this is fixed as of 215bbeb19ab7d5bda4285123746e777546343e75
