### ISSUE TITLE
Chef Automate Apps tab capitalizes all channels 

### ISSUE THREAD

**Issue by ericcalabretta** [chef/automate#3626]
## Describe the bug
Habitat channels can be uppercase and lowercase. The Automate Application tab dashboard uppercases all channels even if their real value us lowercase. 

for example channel `rb_prod` is changed to `RB_PROD`

This causes Automate to report the incorrect channel in the web interface & you could potential mix up a lower & uppercase channel. 

## To Reproduce
Create a channel with a lower case value and configure reporting to the Automate applications tab

```
hab pkg channels eric/national-parks/8.0.0/20200509192449
» Retrieving channels for eric/national-parks/8.0.0/20200509192449 (x86_64-linux)
unstable
rb_prod
```

## Expected behavior
Automate should respect the case of the channel. Lowercase and uppercase characters are both valid for channels & should be reported correctly in Automate.  

## Screenshots

The channel in this example actually is `rb_prod` but is reported as `RB_PROD`

<img width="374" alt="screenshot" src="https://user-images.githubusercontent.com/22911544/81483294-c91e0880-9202-11ea-88dd-d4ac3be417d5.png">

## Versions (please complete the following information):
- Browser chrome
- Automate Build Number: 20200429153636

**Comment by susanev** [comment]
@ericcalabretta thanks for reporting this! our ux design standard is to not change the capitalization of user named objects so this was prolly an oversight. @apriofrost can you confirm?

**Comment by apriofrost** [comment]
hi @ericcalabretta , thanks for reporting the issue. We're going to update the design spec for the UI component to reflect what you suggested.

### UI Implementation Note
Bump the font size for the badge component from 10px to 11px. Instead of automatically capitalize on all the content inside, keep the channel name style as it is.
