### ISSUE TITLE
duplicate `profiles` label on Chef Automate Compliance tab 

### ISSUE THREAD

**Issue by ericcalabretta** [chef/automate#3642]
## Describe the bug
Duplicate uses of `profiles` on the compliance tab. The navigation panel on the left has a `profiles` header which refers to the profile storage within Automate 

The middle of the page as has a `profiles` tab that will sort the compliance reports by `profile`. 

The duplicate use of the same word for two different meanings is confusing for new users. 

## To Reproduce
Login to Chef Automate and navigate to the compliance tab

## Expected behavior
Use unique labels for each function. The `profiles` label on the left could be titled `profile storage` or something more descriptive to the function. 

## Screenshots
![screenshot](https://user-images.githubusercontent.com/22911544/81624035-c2d28c80-93ba-11ea-8c82-b33579ee53df.png)

## Versions (please complete the following information):
- Automate Build Number Build: 20200506172513

**Comment by susanev** [comment]
i agree. i dont think we will be able to fix this anytime soon though. it will be fixed with the new incoming content library.
