### ISSUE TITLE
Can no longer create data feeds with IP based URLs

### ISSUE THREAD

**Issue by trickyearlobe** [chef/automate#3691]
## Describe the bug

Since we introduced validation and testing of data feed parameters in #3476 we can no longer use IP addresses in data feed URL's and must now use FQDN's.

It's not super obvious in the UI why the validation fails since the actual connection test succeeds, and it's probably valid that we should allow IP addresses anyway.

![image](https://user-images.githubusercontent.com/3001322/82044640-9f069380-96a5-11ea-8438-c493db4650e6.png)

## To Reproduce
- Create some kind of listening service to receive Automate data (Kafka, splunk, logstash or similar)
- Set up a data feed to SNOW
- Set the URL to point by IP to the listening service similar to `https://34.77.151.245:8080`
- Fill out the other params (UID,PW etc)
- Test the connection and note that it passes just fine
- Note the greyed out button to create the feed.

## Versions (please complete the following information):
- OS: CentOS7
- Browser: Chrome 81.0.4044.138 (Official Build) (64-bit)
- Automate Build Number: 2020051320542

## Additional context
Several large customers are trialling the BETA data feed for SNOW to send data to alternate tools like Splunk, Kafka, logstash etc. They sometimes struggle to get DNS names for ephemeral machines in test environments (I know, sad in this day and age).

We are also starting to show other customers how to use this BETA feature in environments where SaaS data targets don't automagically get public DNS records.

CC @devopslifter @lhasadreams @satellite15

**Comment by susanev** [comment]
@trickyearlobe ill get this fixed today, but it wont be released to current until tuesday, may 26th (if we stay on schedule). since its frontend validation only they could inspect the button and remove the disabled information to enable the button if they need a workaround now.
