### ISSUE TITLE
node credentials consistency improvements

### ISSUE THREAD

**Issue by susanev** [chef/automate#3716]
## overview
consistency improvements for node credentials

## design details
[figma designs](https://www.figma.com/file/xcxzqOeyDfknSgx4R7Ke4p/automate-consistency?node-id=41%3A0)

### list
- 3 columns, Name, Credential Type, and Last Modified
![credentials-list](https://user-images.githubusercontent.com/5489125/82235774-0875e480-98e8-11ea-8b74-fa28e9fa8910.png)

### detail
- summary information: Credential Type, Last Modified
- 2 tabs: Details, Reset Credentials
- Details should have only name for ssh and winrm, and for sudo it has name and command line options
- Reset Credentials will be different for each type
- they cannot change the type after it is created, if they want to change the type they will create a new credential

#### ssh
![credentials-detail-page-details-tab-ssh](https://user-images.githubusercontent.com/5489125/82235829-1a578780-98e8-11ea-9d14-0f3e369e026e.png)

- ssh has a dropdown for password or rsa key, since only 1 is required not both
![credentials-detail-page-reset-tab-ssh-password](https://user-images.githubusercontent.com/5489125/82239944-6d343d80-98ee-11ea-8385-9a4c9ef24580.png)

![credentials-detail-page-reset-tab-ssh-rsa-key](https://user-images.githubusercontent.com/5489125/82239952-6f969780-98ee-11ea-9355-7eb19f15f5df.png)

#### winrm
![credentials-detail-page-details-tab-winrm](https://user-images.githubusercontent.com/5489125/82235857-23e0ef80-98e8-11ea-9f6b-23f0af9a256c.png)

![credentials-detail-page-reset-tab-winrm](https://user-images.githubusercontent.com/5489125/82235876-26dbe000-98e8-11ea-9eda-5c55915487ed.png)

#### sudo
![credentials-detail-page-details-tab-sudo](https://user-images.githubusercontent.com/5489125/82235882-2b07fd80-98e8-11ea-9307-aa64c3c3a09e.png)

![credentials-detail-page-reset-tab-sudo](https://user-images.githubusercontent.com/5489125/82235893-2e9b8480-98e8-11ea-8d6c-607b06b43449.png)

### create
- based on type, the form below type will change, use an animation to make this a smooth transition, reach out to @SEAjamieD if you need ideas or help
- everything is required except for sudo command line options

##### password
![credentials-create-ssh-password](https://user-images.githubusercontent.com/5489125/82239910-5e4d8b00-98ee-11ea-9381-ef29eb7c57a3.png)

##### rsa key
![credentials-create-ssh-rsa-key](https://user-images.githubusercontent.com/5489125/82239919-61e11200-98ee-11ea-876d-2e6a6c553b0e.png)

#### winrm
![credentials-create-winrm](https://user-images.githubusercontent.com/5489125/82235941-3d823700-98e8-11ea-9427-9b96d283a52c.png)

#### sudo
![credentials-create-sudo](https://user-images.githubusercontent.com/5489125/82235951-4115be00-98e8-11ea-9f0c-dd6c5b8cfe87.png)

**Comment by jonong1972** [comment]
Its been a while since I wrapped my head around all the fields needed for each type of credential, but looks good using the fields we have in acceptance.

👍

**Comment by vjeffrey** [comment]
there's been some confusion in the past about the ssh creds (need to have wither password or rsa key) -- is there any way to address that as part of this work?

**Comment by jonong1972** [comment]
Oh yeah. I knew there was something nagging me about something was off. its either/or for the password or rsa.

**Comment by susanev** [comment]
oh right! yes, ill include that here and prolly ask for yalls review again tomorrow

**Comment by jonong1972** [comment]
Looks good to me! 👍

**Comment by vjeffrey** [comment]
yaaaa that's nice! 🎉
