### ISSUE TITLE
[NON-RELIANT]: Question Mark Hover Actions

### ISSUE THREAD

**Issue by SEAjamieD** [chef/automate#3745]
There is a hover action that will need to be created for the Question Marks on each heading.

![Screen Shot 2020-05-19 at 1.33.22 PM.png](https://images.zenhubusercontent.com/5d7aa5d5d4249c0001cab607/0bf94f64-6640-47ee-a2a4-6a57fba6efe6)

![Screen Shot 2020-05-19 at 1.21.30 PM.png](https://images.zenhubusercontent.com/5d7aa5d5d4249c0001cab607/6ab97558-ef04-4feb-9c70-12407095a08c)

Default Mockup: https://chef.invisionapp.com/d/main#/console/19726898/412590750/preview
Find specific tooltips in Tooltips and dropdown section: https://chef.invisionapp.com/d/main#/projects/prototypes/19726898

**Comment by apriofrost** [comment]
Attached the mockup screenshot here:
![image](https://user-images.githubusercontent.com/9401459/83922084-9b11e280-a734-11ea-8c9b-af4706102c8a.png)

The spec can be inspected here in Sketch Cloud here:  https://www.sketch.com/s/133f1f0f-a3e8-4d09-bcc6-f00385057bad/a/kPJQdl
