### ISSUE TITLE
[NON-RELIANT]: Desktop Pagination Styling

### ISSUE THREAD

**Issue by SEAjamieD** [chef/automate#3747]
The Pagination on Desktop needs to be transformed into the new design.

![Screen Shot 2020-05-19 at 1.38.17 PM.png](https://images.zenhubusercontent.com/5d7aa5d5d4249c0001cab607/811fce7c-7ebf-4ddf-9ab5-5c3cd05ad6a8)

Partial Mockup: https://chef.invisionapp.com/d/main#/console/19726898/412739655/preview

**Comment by susanev** [comment]
if its easy to do, i think this is something wed want across automte.

**Comment by apriofrost** [comment]
## Acceptance Criteria

1. - [ ] Using the [Pagination component from the Carbon Design system](https://www.carbondesignsystem.com/components/pagination/usage/), restyle it to fit the new Automate design language.
2. - [ ] The default Carbon pagination is non-responsive, we would like to make it so by adding two additional states for smaller panel sizes (medium and small).
3. - [ ] Making the default value to be "20 items per page", the other options are 30, 40, 50.

## Design Spec
### Large panels 
This is the default Carbon pagination component.

[Design Spec Link in InVision - Large](https://chef.invisionapp.com/d/main#/console/19726898/414257680/inspect)

![image](https://user-images.githubusercontent.com/9401459/82963682-5b9b0780-9f78-11ea-8b4f-7567d1b7d629.png)

### Medium panels 
This is the additional style we are adding to the Carbon pagination component. Hide the control for adjusting "items per page". Once the medium panel is enlarged" to the large size, show the control again.

[Design Spec Link in InVision - Medium](https://chef.invisionapp.com/d/main#/console/19726898/412590751/inspect)

![image](https://user-images.githubusercontent.com/9401459/82964197-b2551100-9f79-11ea-956a-f7ea22a2632f.png)

### Small panels 
This is the additional style we are adding to the Carbon pagination component. Hide the control for adjusting "items per page", same as the medium panel.

[Design Spec Link in InVision - Small](https://chef.invisionapp.com/d/main#/console/19726898/413626156/inspect)

![image](https://user-images.githubusercontent.com/9401459/82965473-0f05fb00-9f7d-11ea-8ea5-62fefb8276b2.png)
