### ISSUE TITLE
hide available profiles page when desktop flag is used

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#3749]
## User Story

since desktop users are not entitled to any premium profiles, they are not included in the desktop install
which leads to a view like this:
![image](https://user-images.githubusercontent.com/10341541/82382065-920cdb80-99e8-11ea-839e-333be6a08081.png)

let's hide the entire "available" profiles tab when in desktop mode

## Definition of Done
automate installs in desktop mode hide the available profiles tab

**Comment by susanev** [comment]
lets also have this empty message be dynamic, if desktop is enabled

## no desktop
<img width="1176" alt="no-desktop" src="https://user-images.githubusercontent.com/5489125/82382733-591d3880-99e1-11ea-9fb0-e066a62b8396.png">

## with desktop
<img width="1183" alt="desktop" src="https://user-images.githubusercontent.com/5489125/82382737-5c182900-99e1-11ea-95c3-55e290e9a4e9.png">


oh wait, we should update this to the standard empty message pattern while we are here, ill update these designs later tonight.

**Comment by susanev** [comment]
## empty state with desktop
<img width="995" alt="profiles-empty-state-with-desktop" src="https://user-images.githubusercontent.com/5489125/82947033-3dbbab80-9f54-11ea-961e-7fe1a4ac4db8.png">

## empty state without desktop
<img width="995" alt="profiles-empty-state-with-desktop" src="https://user-images.githubusercontent.com/5489125/82947039-401e0580-9f54-11ea-840a-c30497c10377.png">

ping @susanev if anyone has questions when this work begins

**Comment by lancewf** [comment]
@susanev What should be the text if the user does not have permissions to upload a profile?

**Comment by susanev** [comment]
@lancewf good call! weve got a general pattern on some other pages, so lets go with...

```
It looks like no one has uploaded any profiles yet and you don't have permission to upload them.

  If this is a mistake, then reach out to your administrator.
```

see comments on #3736 for what it should look like visually

**Comment by lancewf** [comment]
@susanev Is it correct that you want the search bar removed for the case of Desktop with empty state?

**Comment by susanev** [comment]
@lancewf yes

**Comment by lancewf** [comment]
@susanev For the "compliance viewer" users, they do not have permission to upload profiles or get the available profiles. Should we show them the available profiles if they can not get/install them? Should we at least hide the "Get" button on the available profiles tab?

**Comment by susanev** [comment]
@lancewf there was an old issue to hide the get buttons (i think).. but yah ideally. we would hide those buttons but still allow them to view the page.

**Comment by lancewf** [comment]
Ok, I will leave it alone then. Maybe we can pull that old issue in.

**Comment by susanev** [comment]
i cant find it, so you could do it now if you wanted. but also i can write up another issue. i think it will slow down the profiles page load even more though to have a guard on each of those buttons. and its already soooo slow.

**Comment by lancewf** [comment]
I don't want to make the PR any larger. I will write up the issue if you have not already. 

I had a question about the case where the user does not have permission to upload a profile and does not have any profiles installed. The wording below does not seem correct because installed profiles are pre user and not globally shared. For example, if the admin user installs profile A this does not install profile A for other users. 
```
It looks like no one has uploaded any profiles yet and you don't have permission to upload them.

  If this is a mistake, then reach out to your administrator.
```
It seems like the "X Profiles" tab should be removed and only the "X Available" tab should be shown for reference.
