### ISSUE TITLE
dont allow folks to remove the admin from the admins team

### ISSUE THREAD

**Issue by susanev** [chef/automate#3758]
currently, in the ui we allow folks to take the remove admin from admins team action and they get an error back. instead, lets prevent them from being able to take that action by hiding that menu item, and since its the only one in the 3-dot menu also hide the 3-dot menu.

**Comment by msorens** [comment]
Looks like there is not currently an error being returned to the UI, so this needs some back-end work, too. 
First, should disallow on the back-end so (a) operation is denied from an API call (curl) and (b) UI does report an error.
Then, should do the UI change to make the operation impossible to even attempt.
