### ISSUE TITLE
Easily Allow Disabling Airgap Mode

### ISSUE THREAD

**Issue by susanev** [chef/automate#3797]
## overview
its come up a few times in [internal slack](https://chefio.slack.com/archives/CARK1CBNX/p1588692698233100) and in success slack. folks sometimes have a need to move from air-gapped to not air-gapped. currently that involves...

    turning automate off, removing /hab/svc/deployment-service/data/airgap/manifest.json and then turning automate back on

lets instead create a solution that allows customers to do this easily without incurring downtime

**Comment by kagarmoe** [comment]
We may want to let the success team keep this in their KB. Moving a machine out of airgap has a very unique set of security concerns. For example, in some types of airgap, machines moved out of airgap have to be immediately destroyed. I'd rather have the success team advise customers.

**Comment by susanev** [comment]
alright, @jaym do you have any more to add about this command?
i added this issue because a few customers have asked for it, and i think folks would rather give them a command instead of those steps. but we could maybe hide it and not document it if we have concerns.

**Comment by susanev** [comment]
ill ask the product managers too

**Comment by sdelano** [comment]
I love the idea of allowing customers to do this. There's no practical reason that changing the deployment mechanism from a airgap bundle-based install to one that fetches content over the Internet needs to result in downtime. Let's find a solution to help here, and let the customers decide what they want to do with their machines (re: un-airgapping) instead of forcing downtime and hiding functionality.

**Comment by trevorghess** [comment]
I think it's fine to add the command, we just need to have sufficient warnings in place about what taking the action does in both the process of execution and in the documentation. Something like "By running this command and updating the config, Automate will now attempt to reach public Chef services, this may require firewall changes to fully enable, and your Automate instance will be out of airgapped mode"

**Comment by susanev** [comment]
@chef/docs-team where are we on this one? is it possible to do something in the docs? or do you want me to close?

**Comment by kagarmoe** [comment]
@susanev We're not going to add this to the public documentation.
