### ISSUE TITLE
improve error logging in inspec runner

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#3800]
## User Story

would be nice to log more of the errors in the inspec runner code to make it easier to debug what is going on when things aren't working!

## Definition of Done
improved error logging in: https://github.com/chef/automate/blob/master/components/compliance-service/cmd/inspec_runner/inspec_runner.go

**Comment by teknofire** [comment]
Specifically, there are several errors that can be returned from `changeToUser` and the error message tends to be a generic OS error like `operation not permitted` and it's not clear if that happened during user lookup, or the UID/GID change or even somewhere else.

It would help with troubleshooting if we can add more debug messages about what it's trying to do: "Found nobody with UID/GID 12345/12345", "Changing GID to 12345", etc...

**Comment by vjeffrey** [comment]
just noticed this ticket as well https://github.com/chef/automate/issues/674
