### ISSUE TITLE
Policyfile view in Automate

### ISSUE THREAD

**Issue by samshinde** [chef/automate#3864]
# What

Represent and visualize the information stored about policyfiles in policyfile.lock.json and other relevant files on Infra Server in Automate UI.

# Why

Significant usage of policyfiles to define and manage run\_lists which are executed in each client run propel a need to represent such information in Automate UI.

# How

Considering that Infra Servers can now communicate with Automate Server, we should develop utility APIs to fetch information stored in policyfiles across multiple Infra Servers connected to an Automate Server and represent it in Automate UI.

# Requirements

Some key requirements are as follows:

- See policyfile details in Automate UI - policyfile name, policy group name, revision ID, number of revisions, time stamp of latest revision,
- View details of included/nested policies, run list details with ordering, cookbook detail along with source paths and dependencies, attribute details and software dependencies in Automate UI
- (Ability to compare policyfiles by revision ids, time stamp of revision, etc.)
- Ability to export details in readable formats (csv, json, png - for graphs)
- Details of nodes running a particular policy - name, id, OS, etc.
- (Ability to see changes of run list over time in a friendly UI)
- ...

# Resources

- Policyfile view doc: [ https://progresssoftware.sharepoint.com/:w:/s/ChefCoreC/EVppF0pBms9JgC0R2IqTtJsBkLXbNpEbShV-Btkx2jvoTA?e=R1uiQ5](https://progresssoftware.sharepoint.com/:w:/s/ChefCoreC/EVppF0pBms9JgC0R2IqTtJsBkLXbNpEbShV-Btkx2jvoTA?e=R1uiQ5)
- Design mockups: [ https://lucid.app/lucidchart/ef53a0e6-280a-4324-af75-a6954e0cf852/edit?page=0\_0#](https://lucid.app/lucidchart/ef53a0e6-280a-4324-af75-a6954e0cf852/edit?page=0_0#)
- ...

# Related concerns

- Replace un-used (default) Environment with useful policy-name and policy-group.
- Dependency graph view to see policies and cookbooks mapping. Ability to export is useful as well.
- Show policy name in top level node list (Client Runs page add an option)

Aha! Link: https://chef.aha.io/epics/AUTO-E-19

**Comment by btm** [comment]
The team needs wireframes for create + update.

**Comment by btm** [comment]
I believe this work is complete, with the scope limited to listing Policyfiles and showing their content for whatever APIs already existed on the Infra Server. 

I don't see any policyfiles listed on the systems in our CI/CD pipelines, but they don't have a good sample data set.

![image](https://user-images.githubusercontent.com/4381/135148795-b15c6e2c-5552-470b-9dcd-1b02baef3d2d.png)
