### ISSUE TITLE
“get content” SaaS CDS files in Automate

### ISSUE THREAD

**Issue by lancewf** [chef/automate#3906]
## User Story
When a user selects to “get content” on a content item from the UI, that item will be downloaded from the SaaS CDS. This will also update the status of the content item in postgresql to "downloaded". This new status will be seen in the UI. After this action is complete, the user will be able to download and install this content. 

## Demo Script / Repro Steps
* Open the UI to http://a2-dev.test/cds
* Add a CDS credential.
* Wait until the content is displayed in the UI. 
* Click "get content" on one of the content items. 
* After the install, ensure the status has changed in the UI to "downloaded"
* Ensure the item can not be downloaded or install (if a package or profile). 
* Celebrate!:fireworks: :fireworks: :fireworks: :fireworks: :fireworks:

**Comment by vjeffrey** [comment]
no need for this due to requirements change. there is no "get content" anymore
