### ISSUE TITLE
User details page should accommodate longer user names

### ISSUE THREAD

**Issue by msorens** [chef/automate#3908]
## Describe the bug

The user details page confines the user name and id in a narrow horizontal space and that leads to rendering issues when dealing with very lengthy values: 
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/6817500/84216461-71332580-aa7e-11ea-8c2b-942e9ba1ebee.png">

Seems like there is plenty of real-estate to widen that space a bit to alleviate this issue.

## To Reproduce
- Navigate to Settings >> Users >> Create User
- Add a user with a very long name and id.
- Select that user from the users list to open user details.

## Expected behavior
Screen should accommodate the values.

**Comment by susanev** [comment]
both should use ellipses instead of wrap on the overflow

**Comment by susanev** [comment]
this work has been deprioritized.
