### ISSUE TITLE
Long names in dropdown components should be wrapped

### ISSUE THREAD

**Issue by msorens** [chef/automate#3916]
## Describe the bug
Long values in dropdowns should be truncated with an ellipsis, and with the full value in a tooltip, instead of just running to the edge. As shown, this will occur wherever the dropdown is used, both in a details page and in a create modal.

![image](https://user-images.githubusercontent.com/6817500/84346344-a0bc5d80-ab64-11ea-9719-b1bfe8197602.png)

Note that the fix should apply to the parent dropdown component, ResourceDropdownComponent, so that all dropdowns are corrected.

## To Reproduce
 - Navigate to Settings >> Projects >> Create Project.
 - Create a project with a long name.
 - Navigate to Settings >> Teams >> Create Team
 - Open the Projects dropdown.

## Expected behavior
Long name should wrap ~appear properly truncated with an ellipsis~.

**Comment by susanev** [comment]
these should wrap not truncate
