### ISSUE TITLE
Action buttons should not overlap scrolling list

### ISSUE THREAD

**Issue by msorens** [chef/automate#3917]
## Describe the bug
The action buttons at the lower right are overlapping the scrolling list but they should be below the list without overlap.

<img width="979" alt="image" src="https://user-images.githubusercontent.com/6817500/84346656-538cbb80-ab65-11ea-9ab3-d0c7c027839c.png">

## To Reproduce
Navigate to Settings >> Teams >> team >> Add Users

## Expected behavior
Buttons should not overlap.

**Comment by susanev** [comment]
this is already a documented issue #2752
