### ISSUE TITLE
License status should influence license modal

### ISSUE THREAD

**Issue by msorens** [chef/automate#3918]
## Describe the bug
When a license is active and it reaches expiry (or is in any other way removed), the user will be asynchronously notified within 5 minutes that there is no valid license, popping up the license lockout modal. That's well and good, but only half the job. If the admin then applies a new license, any other user with the license lockout modal showing will not see the new license status asynchronously; one has to manually refresh the browser.

## Expected behavior
When a new license is activated, the periodic license status check should close the license lockout or license apply modals, if visible.

**Comment by srenatus** [comment]
Accepted! :)
