### ISSUE TITLE
Are "Sign in" assets properly cached?

### ISSUE THREAD

**Issue by srenatus** [chef/automate#3920]
Whenever I refresh the signin form in one of our acceptance machines, there's a a noticeable blink second where the form fields are shown, but their labels, "Username", "Password", are **not**. I believe this might be because the fonts used for these haven't been retrieved yet.

❓Those fonts never change, how are they not cached?

I'm afraid I know too little about this. I've once played with nginx' support for http2 server push -- that may help here, but I think basic caching would do the trick just as well.

**Comment by susanev** [comment]
this has been deprioritized.
