### ISSUE TITLE
CDS new users get previously installed profiles

### ISSUE THREAD

**Issue by lancewf** [chef/automate#3923]
## User Story

New users created in Automate or SAML logins should have all the CDS profiles that have been previously installed. This includes all prior versions.  

## Demo Script / Repro Steps
1. As admin install a few profiles
1. Create a new user
1. Open the compliance profile page and ensure all the install profiles are available.

**Comment by vjeffrey** [comment]
no need for this due to requirements change (only installing to current user's profiles)
