### ISSUE TITLE
clarify project update wording OR hide project update for unaffected users

### ISSUE THREAD

**Issue by blakestier** [chef/automate#3939]
Reported by @teknofire 

> Only the owner needs to see the progress bar when projects are being changed. Currently when an admin/owner makes a change on the project people can see the progress bar show up, even if they don’t have access to the projects being added/changed.

Source of confusion is around a user being able to see the project update when 1) They haven't run the update/changed the project and 2) Do not have permissions on the project(s) that are affected.

We can hide the project update banner for people whose projects are unaffected. 
Alternately, we can be more explicit with the update ("Heads up! Your data might be moving during this project update")

## Definition of Done
Users are not confused by the banner.

**Comment by susanev** [comment]
this work has been deprioritized.
