### ISSUE TITLE
Queries: Chef Automate

### ISSUE THREAD

**Issue by Doltair** [chef/automate#3965]
Hi @vjeffrey ,

I am currently using Chef Automate API documentation and trying to dig in more. Do you mind coursing me to the proper endpoint? I want to query all the *Profile identity owners* before pushing profiles and validate it exists first. 

Anyhow having a bit of challenge since it returns 200 anyhow if data exists or not.

Thank you very much!

**Comment by vjeffrey** [comment]
hi @Doltair I'd be happy to help you - I am not actually sure which api call you're referring to? could you describe it a bit more? or reference the ui?  i'm also happy to help you in slack! i'm @vj in both the community and success channels

**Comment by Doltair** [comment]
Gotcha! Posted it on Slack Community#general :) Thank you!

**Comment by susanev** [comment]
@Doltair since i think you got an answer over in community slack, do you mind if we close this?
