### ISSUE TITLE
control menu not growing in width

### ISSUE THREAD

**Issue by susanev** [chef/automate#3983]
## overview
the control menus should grow in width so all labels fit, right now labels are being cut off with an ellipsis
![image](https://user-images.githubusercontent.com/5489125/85767336-c3a25200-b6cc-11ea-8381-96985c90acce.png)

**Comment by SEAjamieD** [comment]
@susanev Any Idea if there is a specific page or browser this is coming from?  I'm not able to reproduce this yet. 

I've checked settings>projects, but i've also checked several of the other control menus.

**Comment by msorens** [comment]
@SEAjamieD 
Here is a reproducible scenario.
Visit https://a2-local-inplace-upgrade-acceptance.cd.chef.co/settings/projects and open the control menu on any row.
 - Problem occurs only on the Projects page.
 - Problem does **not** occur on any other resource page under Settings.
 - Problem occurs in Chrome.
 - Problem does **not** occur in Firefox.
 - Problem occurs equally whether browser is full screen or resized to be narrow horizontally.

And here is the kicker:
 - Problem occurs when logged in as a SAML user.
 - Problem does **not** occur when logged in as a local user.

**Comment by msorens** [comment]
Hmm... seems to be more convoluted than that. I went through various choices again, and this time when logged in as a SAML user the issue was not present! 🤔

**Comment by msorens** [comment]
Now I am seeing it logged in as a local user (admin, Chrome) or Settings > Policies > <policy details>
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/6817500/87726983-ea582380-c774-11ea-93b4-f1310b34d5b9.png">
And in the same session, now again on the original Settings > Projects page:
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/6817500/87727036-0c51a600-c775-11ea-9044-f9453807752f.png">
