### ISSUE TITLE
compliance date picker woes

### ISSUE THREAD

**Issue by susanev** [chef/automate#4015]
## overview
the data picker on the compliance page has issues when set in Australian eastern time, and prolly others. also seems to be a problem on the event feed.

## repro steps
- around the utc day change over set your system time to Australian eastern time
- go to the compliance reports page, and use the date picker
- notice when you pick a date it sets to the previous date

## expected behaviour
- the date you select is shown in the selector and that data is shown

**Comment by SEAjamieD** [comment]
Can we confirm that - as of today, we would like the date picker to display UTC date?

**Comment by jonong1972** [comment]
@SEAjamieD Yes. We would like the date picker to display UTC date.
