### ISSUE TITLE
Event Feed can be filtered by organization, but organization is not present in the JSON or UI output

### ISSUE THREAD

**Issue by mattray** [chef/automate#4016]
Running a query like 
```
curl --insecure -s -H "api-token: $TOKEN" https://AUTOMATE/api/v0/eventfeed?collapse=true\&filter=organization:MYORG\&page_size=10000 | jq > org.json
```
will produce JSON output properly filtered by the `organization`, but the `organization` is not a field in the output. This means that if you query without the organization you'll never know which organization events are tied to, and this needs to be exposed in the UI for customers with hundreds of organizations, potentially with duplicated chef server names and user names.

## Versions (please complete the following information):
20200617215626

No Chef Server or Organization in the UI:
![Screen Shot 2020-07-01 at 4 01 57 pm](https://user-images.githubusercontent.com/330023/86208645-4d15c080-bbb4-11ea-8fc8-708860cf2e40.png)

**Comment by lancewf** [comment]
Is it enough to add the organization to the JSON download and this request https://AUTOMATE/api/v0/eventfeed? Or do we want to add it to the UI also?

**Comment by vjeffrey** [comment]
it would certainly be nice to have it on the ui as well. if that needs some ux then we can always do backend first and open an issue for the ui stuff

**Comment by mattray** [comment]
Organizations in the UI are essential. I have a customer with over a thousand organizations, they need as much detail as possible.
