### ISSUE TITLE
Report on Erred InSpec Runs

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#4023]
## **What problem are we solving?**

_Should be a few sentences. Describe the user stories and the target market._

Today, if an InSpec scan fails to run due to an internal error (e.g. bad characters in a resource), you would get a stack trace of the error in the CLI. In the case of running the scan either via Automate or audit cookbook, however, nothing is reported; nothing is reported as InSpec itself failed. Customers need to know if internal failures like this occur as it could provide a quick triage point they can use to fix their InSpec profile or resource. Additionally, when it comes to InSpec runs kicked off from Audit Cookbook, there should be a linkage between what nodes report their Infra client runs as well as their Compliance reports.

- As an IT Operator

    - I need to know if an audit report failed to execute so that I can resolve the issue and restore visibility into the compliance state of my node.

## **Objective and Key Results**

_What's the ideal outcome? How will we measure that we're successful?_

**Objective** | **Key Results**
-|-
Allow for internal, runtime errors for audit runs to be bubbled up to the user|- Increased visibility to operational failures in the audit run process
- Reduced time spent triaging user errors that deflect from resolving compliance issues
- Eliminate confusion for I&O and InfoSec operators who think their nodes are non-compliant when its really that the audit run itself failed

## **Acceptance Criteria**

_How will we know when we're done?_

- User can discern whether a node is non-compliant versus its audit run failed
- User can understand why an audit run failed
- User can resolve audit configuration issues based on audit run failure details

#### **Test Scenario:**

- create a profile with a control that tests a resource that contains garbage characters in it
- run an `inspec exec` with the profile and send report to Automate
- check Compliance > Reports for failure
- review failure details and make corrections
- rerun `inspec exec`
- refresh Compliance > Reports and review latest audit report and show failure is fixed

## **Dependencies**

_What other work needs to come first? What will block us from success?_

- InSpec - we do not return internal/runtime errors as reports today in InSpec. We would need to look at scoping the different exceptions that occur and shaping that into the report format so that we could send the errors to Automate.

## **Out of Scope**

What problems are not included in this epic?

## **Open Questions**

_What questions still need to be addressed?_

Aha! Link: https://chef.aha.io/features/SH-155

**Comment by alexpop** [comment]
The Automate change that adds support in the ingestion & reporting for InSpec reports with failed status has merged: https://github.com/chef/automate/pull/4046

In order for users to benefit from it, this InSpec change needs to merge and then be rolled into a release of Inspec and Chef Infra: https://github.com/inspec/inspec/pull/5128

There's another Automate change that @rickmarry is working on to accept a minimal failed report. Such a report is not provided by InSpec, so we need the following change in the audit cookbook: https://github.com/chef-cookbooks/audit/pull/430

**Comment by kekaichinose** [comment]
@alexpop InSpec team merged in inspec/inspec#5128 last week. Anything else you need to continue the effort for Automate?

**Comment by vjeffrey** [comment]
@kekaichinose the automate work is close, just delayed by the urgent customer issue that came up and trumped this one

**Comment by alexpop** [comment]
https://github.com/chef/automate/pull/4131 completes the backend work for **failed inspec runs**. UX/UI work is still needed to display the failed report message. This is different than the failed profile message which currently is displayed as a tooltip text.

Once ^ is released, we can merge and release https://github.com/chef-cookbooks/audit/pull/430

**Comment by vjeffrey** [comment]
an mvp ui change has been merged and audit cb released, closing as complete!
