### ISSUE TITLE
Automate Compliance Documentation update

### ISSUE THREAD

**Issue by jonong1972** [chef/automate#4024]
https://automate.chef.io/docs/reports/#nodes

We will need to update the compliance node detail report screenshots to reflect the new filters. 

The existing screenshot shows the "Critical" "Major" Minor" etc. filters above the table.

Currently we removed the "critical" "major" "minor" because they were only showing failed. We merge the 3 buttons into one "Failed" button. Temporarily, a user will have to sort the table to see the the impact scores. or via the overview tab to get counts of failed controls.

We would like to fix this problem in the future to make it more easily accessible.

**Comment by vjeffrey** [comment]
i've heard from some field facing folks that the ability to filter by control impact was actually really important to them. is there already a plan/design for allowing folks to filter by control impact again?

**Comment by jonong1972** [comment]
There was a plan a year ago, but new features took precedence. I had this documented here: https://github.com/chef/automate/issues/433#issuecomment-497032930

I can create a new issue to get those design elements in.

**Comment by vjeffrey** [comment]
i'm taking this off the superteam board  to avoid confusion but we'll be happy to review when it's ready!

**Comment by mjingle** [comment]
Closing this issue as it has been addressed in https://github.com/chef/automate/pull/4250
