### ISSUE TITLE
Deselecting all columns on Client Runs makes reselecting impossible

### ISSUE THREAD

**Issue by msorens** [chef/automate#4033]
## Describe the bug
The client runs page allows you to configure what the table shows by opening the "column picker", then checking or unchecking column names.
As the video shows, if you select or deselect some, it works fine. 
You can make a selection, close the column picker, and come back later, do it again, etc.
This works fine until you deselect all columns and close the column picker.
Now, if you re-open it, you can no longer reselect any columns.

## Expected behavior
Should still be able to select columns when none are selected.

## Workaround
Since the column settings are not persisted, refreshing the page will restore the default set.

## Screenshots
![client runs columns](https://user-images.githubusercontent.com/6817500/86418830-48b9d800-bc86-11ea-9399-ba710da64a4e.gif)

## Versions (please complete the following information):
- OS: macOs
- Browser chrome
- Automate Build Number 20200701215317

**Comment by susanev** [comment]
great find, thank you!!

**Comment by Shadae** [comment]
Bug not repeatable:

https://chefio.slack.com/archives/CBSQQBK19/p1595903787438500
