### ISSUE TITLE
Create Token behaviors with limited permissions

### ISSUE THREAD

**Issue by msorens** [chef/automate#4034]
## Describe the bug
Creating a token requires permissions not just for tokens but for tokens, policies, and projects. If the user does not have permissions for policies and projects, errors will show up. One wonders if that is the best UX to present, or should we just trim down the capabilities of what "Create Token" will do based on the user's permissions?

## To Reproduce
For the accompanying video I set up the following policy for Sweeney Todd:
```
{
  "name": "sweeney policy",
  "id": "sweeney-policy",
  "members": [
    "user:local:sweeney"
  ],
  "statements": [
    {
      "effect": "ALLOW",
      "actions": [
        "iam:tokens:*"
      ],
      "projects": [
        "*"
      ]
    }
  ],
  "projects": []
}
```
The actual command:
```
curl -sSkH "api-token: $TOK" -X POST -d '{ "name": "sweeney policy", "id": "sweeney-policy", "members": [ "user:local:sweeney" ], "statements": [ { "effect": "ALLOW", "actions": [ "iam:tokens:*" ], "projects": [ "*" ] } ], "projects": [] }' $TARGET_HOST/apis/iam/v2/policies?pretty
```

I then went to Settings >> Tokens.
Upon selecting <kbd>Create Token</kbd> you will observe the error banner appears behind the modal
and that no policies are loaded into the policy dropdown.
One still can go ahead and press the <kbd>Create</kbd> button within the modal though to attempt to create the token. That closes the modal and reports an error that the token could not be created because of no permissions on projects (the top-most error banner).

## Expected behavior
Here are some suggestions; there are certainly others:
```
Permissions for                Option 1                    Option 2     
Token  Project  Policy 
  X       X        X           Create token works
  X       X                    Suppress policy dropdown    Hide CreateToken button on main page
  X                            Suppress project dropdown   Hide CreateToken button on main page
```

## Screenshots
![create token](https://user-images.githubusercontent.com/6817500/86420540-cf24e880-bc8b-11ea-9f50-58871ef46762.gif)

## More Details
A second scenario of the same problem is when viewing token details. Just selecting a token to view its details manifests this error, again because project permissions are absent.

<img width="961" alt="image" src="https://user-images.githubusercontent.com/6817500/86504231-e7b80000-bd6a-11ea-9f52-71347331dd11.png">

## Versions (please complete the following information):
- OS: any
- Browser: any
- Automate Build Number: 20200701215317

**Comment by susanev** [comment]
i dont think we will be able to prioritize working on this.
also, i dont know of any users that are giving token permissions to folks besides admins.

**Comment by susanev** [comment]
this work has been deprioritized.
