### ISSUE TITLE
Cannot toggle token status without project permission

### ISSUE THREAD

**Issue by msorens** [chef/automate#4035]
## Describe the bug
A user with all permissions on tokens (`iam:tokens:*`) should be able to toggle a token active/inactive.
From the token list page, however, observe that it also requires project permissions:
<img width="959" alt="image" src="https://user-images.githubusercontent.com/6817500/86504199-8f80fe00-bd6a-11ea-9d57-38598b29a61c.png">

## To Reproduce
I set up the following policy for Sweeney Todd:
```
{
  "name": "sweeney policy",
  "id": "sweeney-policy",
  "members": [
    "user:local:sweeney"
  ],
  "statements": [
    {
      "effect": "ALLOW",
      "actions": [
        "iam:tokens:*"
      ],
      "projects": [
        "*"
      ]
    }
  ],
  "projects": []
}
```
The actual command:
```
curl -sSkH "api-token: $TOK" -X POST -d '{ "name": "sweeney policy", "id": "sweeney-policy", "members": [ "user:local:sweeney" ], "statements": [ { "effect": "ALLOW", "actions": [ "iam:tokens:*" ], "projects": [ "*" ] } ], "projects": [] }' $TARGET_HOST/apis/iam/v2/policies?pretty
```
I then went to Settings >> Tokens, opened the control menu for a random token, and selected <kbd>Toggle Status</kbd>.

The same error occurs when trying to switch Active/Inactive on the token details page.

## Expected behavior
A user with permissions for tokens should be able to toggle it.

## Versions (please complete the following information):
- OS: any
- Browser: any
- Automate Build Number: 20200701215317

**Comment by susanev** [comment]
this work has been deprioritized.
