### ISSUE TITLE
Data lifecycle form fields only shows at most 2 digits when values may have 3 or more

### ISSUE THREAD

**Issue by teknofire** [chef/automate#4040]
## Describe the bug
Form fields for the data lifecycle settings are too short and only show 2 digits at most. Some fields could reasonably have 3 digits like the compliance reports settings. 

For example, if the number number of days to keep compliance reports is set to 120 you will only see 12 in the form field unless you click in the field and use the arrow keys to scroll over to the right.

Where this becomes more of a problem is when the user enters the values incorrectly and types in something like 900 or 1200 instead of the desired 90 or 120 days and it won't be immediately obvious that it has been entered incorrectly.

## To Reproduce
1. Login as Admin
2. Browser to Settings -> Data Lifecycle
3. Go down to the compliance lifecycle settings and type in 900
4. See that the field only shows 90 without clicking in it and scrolling the field to the right.

## Expected behavior
A description of what you expected to happen.
The form field should auto-resize to show the entire value of the input.

## Versions (please complete the following information):
- Browser: Chrome
- Automate Build Number: 20200617215626

**Comment by SEAjamieD** [comment]
thanks @teknofire!

@vjeffrey - While working on this, Do you know if there is a max number we'd like to set for something like this?

**Comment by susanev** [comment]
@SEAjamieD is there a reson to have a max? can you grow and shrink that box to adjust to the number supplied?

**Comment by vjeffrey** [comment]
i don't think there's really a need for a max. we could do a nice thing where if they enter something large like 900 we warn them and tell them to go look at docs re: space reqs but also can just let them enter what they enter

**Comment by SEAjamieD** [comment]
@susanev - was asking about max since i'm unfamiliar with the use case.  I'm not _sure_ about growing and shrinking the box as the numbers are supplied, though I have seen text shrink as the number gets larger.  I'll play around with it and provide some options.

**Comment by susanev** [comment]
something like this would be rad
https://css-tricks.com/auto-growing-inputs-textareas/
