### ISSUE TITLE
token details: state toggling after save leads to surprising "all changes saved" message

### ISSUE THREAD

**Issue by srenatus** [chef/automate#4044]
## Describe the bug

When toggling a token's status after having changed it, the "All changes saved." message comes back when the token status that was saved has been selected again.

## To Reproduce
1. create a token
2. go to its token details
3. select "inactive"
4. press save ➡️ it'll say "All changes saved", the save button is disabled
5. click "active" ➡️ the save button will be enabled again
6. click "inactive" ➡️ the save button is disabled again and *the "All changes saved" message reappears*:

    ![image](https://user-images.githubusercontent.com/870638/86915920-12b3a280-c123-11ea-879c-393264357e20.png)

## Expected behavior

I'd expect the button to become disabled, but the message should *not* reappear.

**Comment by susanev** [comment]
im going to work with the ui team for this one

**Comment by SEAjamieD** [comment]
@susanev - just wanted to investigate what was going on, Not merging, but updated with a 1.5 second flash of the "All changes saved" message for the time being.  Whenever its decided how this should actually look moving forward, i'll update accordingly.

![Token state changes](https://user-images.githubusercontent.com/16737484/89593068-13fbec00-d803-11ea-819a-9070e6af7aab.gif)

**Comment by susanev** [comment]
@SEAjamieD the all changes saved should only appear next to the button after interacting with the button and the save being successful, if they make another change on the page before leaving that text should go away and not reappear until they use the save button again.
