### ISSUE TITLE
Automate deploy fails when the linux hab user comes from external auth instead of local accounts

### ISSUE THREAD

**Issue by teknofire** [chef/automate#4105]
## Describe the bug

Automate is unable to complete the deployment step if `hab` the hab user is coming from an external auth like LDAP in Linux instead of as a local account in `/etc/passwd`.

Initially, we saw errors from `useradd` complaining that the user already completed and a workaround was added #4078 to get past this.  

After the workaround, we now see the following error when running `CHEF_AUTOMATE_SKIP_HAB_USER=true chef-automate deploy`

```
Jul 20 17:57:26 HOSTNAME.com hab[30310]: deployment-service.default(O): failed to start server: failed to initialize secret store: user lookup: user: unknown user hab
```

The underlying problem appears to be caused by GoLang not using libc to query for user and group UID/GIDs and instead only pulling them from `/etc/passwd` and `/etc/group`. This will cause the deploy to fail as it can't find the `hab` user and attempts to create it via `useradd`. Which will then fail as it already exists in LDAP, also any other code that attempts to fetch the `hab` UID/GID` will have problems as it won't get a valid ID.

## To Reproduce

1. configure Linux to use external LDAP user accounts (via /etc/nsswitch.conf)
2. create a `hab` user in LDAP
3. Attempt to install Automate `chef-automate deploy`, latest current version will throw an error 
    
    ```
    Creating Habitat user and group
    Error: setup failed: creating hab user failed: "useradd: user 'hab' already exists\n": exit status 9  
    DeployError: Unable to install, configure and start the
    ```

4. If using a version from the dev channel `CHEF_AUTOMATE_SKIP_HAB_USER=true chef-automate deploy` to skip the `useradd` error and get the error about the `secret store` and `hab`.

    ```
    Jul 20 17:57:26 HOSTNAME.com hab[30310]: deployment-service.default(O): failed to start server: failed to initialize secret store: user lookup: user: unknown user hab
    ```

## Expected behavior
Automate will complete the deployment successfully.

## Versions (please complete the following information):
- OS: RHEL 7
- Browser: N/A
- Automate Build Number: latest current and dev builds

**Comment by thomascate** [comment]
For some context, it looks like deployment-service uses the Go user implementation that relies on the user existing in /etc/passwd and /etc/group. However in this case the user actually exists on an ldap server. If we used the cgo implementation go would call out to libc and should be able to find the user.
https://golang.org/pkg/os/user/
