### ISSUE TITLE
a2-local-inplace-upgrade-acceptance has bad Infra Server credentials

### ISSUE THREAD

**Issue by btm** [chef/automate#4180]
https://a2-all-local-fresh-install-acceptance.cd.chef.co/ - I can browse fine to Infrastructure -> Chef Servers -> auto-deployed-chef-server -> test

https://a2-local-inplace-upgrade-acceptance.cd.chef.co/ - Going to Infrastructure -> Chef Servers -> chef-test -> 4thcoffee I see an error briefly and then I am logged out.

![Screenshot from 2020-08-04 11-04-48 (copy)](https://user-images.githubusercontent.com/4381/89310423-abfea780-d642-11ea-9cd8-a639ea6159af.png)

The logout is being fixed in #4137, but I don't know why that environment has bad credentials. Did someone change them? Will they get fixed automatically on the next deploy by resetting the credentials?

**Comment by vsingh-msys** [comment]
@btm a2-local-inplace-upgrade-acceptance.cd.chef.co - seems it contains old admin key data which got modified somehow. Updating admin key for org 4thcoffee working fine. 

PR #4137 contains fixes so that get can retain the infra view and reset the key.

Safely we can close this issue?
