### ISSUE TITLE
Support customized message on login page

### ISSUE THREAD

**Issue by msorens** [chef/automate#419]
# User Story

As an Automate admin I want to be able to specify a custom message shown on the login page to meet legal requirements. (Real example: a customer needs a message saying "User acknowledges by logging in to this software that...").

Details:
- Needs to support arbitrary length text message customizable by customer admin (particular customer mentioned 7000+ characters)
- Should show scroll bars when text is of sufficient length to warrant it.
- If no text is specified by customer admin, then the box should not appear at all.

# Definition of Done

![image](https://user-images.githubusercontent.com/6817500/58382910-02734f00-7f85-11e9-9cc9-405a4425b39c.png)

# Demo Script / Repro Steps

**Comment by susanev** [comment]
This should go through the product and ux team process before anyone picks up this task. Adjusting labels to fit with that.

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
