### ISSUE TITLE
Feature flags entry

### ISSUE THREAD

**Issue by kagarmoe** [chef/automate#4209]
The beta/legacy/features flag entry has changed subtly. They're also hard to find. We need to:

* decide if/how to express this nuance
* add a flags entry somewhere in reference to make the instructions discoverable

Something along the lines of (Drafty): 
"Legacy, Beta, and Feature Flags: Use the `beta`, `lega`, or `feat` flags to turn on or off beta, legacy, or in-development features by turning the services. Select somewhere Automate screen--but not in an input box--and enter "feat", "lega", or "beta", to open the option box."

https://github.com/chef/automate/pull/4202

**Comment by mjingle** [comment]
Closing this issue since https://github.com/chef/automate/pull/4288 was merged.
