### ISSUE TITLE
"Patents" link needs to be added to Automate

### ISSUE THREAD

**Issue by jonong1972** [chef/automate#4220]
## User Story
Legal wants us to have a link to our Patents within our Products.

## Definition of Done
Within Automate a link needs to added to the user drop down menu.

Link:
Chef Patents

-->  https://www.chef.io/patents

## Demo Script / Repro Steps

1. Sign into Automate
2. Click on your profile image to access the drop down menu
3. Link should be below "Licenses"

![Screen Shot 2020-08-12 at 10 36 32 AM](https://user-images.githubusercontent.com/1316587/90048058-ca3e5600-dc87-11ea-8c07-10c7d5fb83c8.png)

**Comment by susanev** [comment]
@jonong1972 can we put this into about instead? or could they link to it from license? seems excessive to have this and license and about in this menu. what do you think?
