### ISSUE TITLE
Node Credential create API backend response changes

### ISSUE THREAD

**Issue by samshinde** [chef/automate#4225]
## changes required for Node credential create API backend response 

needed changes for https://github.com/chef/automate/issues/3716
right now we are getting below response from creating API
```
{
  "id": "string"
}
```
but we needed to create API response like mentioned below

1. response for ssh, sudo, winrm
```
{
  "id": "16b81834-a118-401d-9190-cbc32b94859f",
  "name": "cw secret",
  "type": "ssh",
  "last_modified": "2020-08-10T04:28:36.251Z",
  "tags": [
  ],
  "data": [
  ]
}
```

**Comment by vjeffrey** [comment]
@samshinde you can get the kind of data you list above from list, is there a reason you would need it on create? we can't modify api responses like that (it's a breaking change), and it is standard to return the id of the object on create and not the entire object

**Comment by samshinde** [comment]
@vjeffrey  Yes, when I create a node it only gives me Id as a response and after that, I am not able to perform my sorting in the table as we required name for it.
![create-node](https://user-images.githubusercontent.com/10369422/90493215-b3a06f00-e15f-11ea-9a09-dcf17c482dc7.png)

**Comment by vjeffrey** [comment]
@samshinde the information needed for sorting should come from the list api call. the list endpoint can be caller after create to refresh the list data if you need

**Comment by samshinde** [comment]
@vjeffrey OK will take this approach
