### ISSUE TITLE
getEnvironmentsFailure -> getClientsFailure copy-paste error

### ISSUE THREAD

**Issue by btm** [chef/automate#4243]
@vinay033 it looks like this is supposed to be `getClientsFailure$`, yeah?

https://github.com/chef/automate/blob/238c56ce9da428a81ab7d71a5f1daabe2ed4aa16/components/automate-ui/src/app/entities/clients/client.effects.ts#L39

**Comment by vinay033** [comment]
yeah, I checked with code and I will create PR for this today.
