### ISSUE TITLE
add "last 24 hrs" selection to compliance reporting searchbar

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#4263]
## User Story
we are modifying the backend logic to support showing the last 24 hrs of data when no end time has been provided.  for the ui portion of things, the plan is to default to the "last 24 hrs" selection, allowing a user to select a specific date if desired.

more details in the original card, https://github.com/chef/automate/issues/4027

API specifics: 
- when requesting last 24 hrs, do NOT provide end date
- when requesting specific date, send date the same way we do today

## Definition of Done
ui has option to select 24 hrs instead of just specific days

**Comment by alexpop** [comment]
@scottopherson something else I want to highlight: For data in the past, `end_time` is always needed now, even for API calls that before didn't need it, like filtering for a `job_id`, suggestions or getting a report by just providing the report id. All these calls now will only search the last 24h worth of data unless end_time is specified.
