### ISSUE TITLE
chef-server-ctl doesn't support external PG with cleanup-bifrost and grant-server-admin-permissions subcommands

### ISSUE THREAD

**Issue by teknofire** [chef/automate#4285]
## Describe the bug
The `chef-server-ctl cleanup-bifrost` and `chef-server-ctl grant-server-admin-permissions` commands don't support using external PostgreSQL with Chef Automate.

When attempting to use one of these commands you will get and error similar to

```
[root@ip-10-30-30-177 ~]# chef-server-ctl cleanup-bifrost
/hab/pkgs/chef/chef-server-ctl/14.0.22/20200812153852/vendor/bundle/gems/bundler-1.17.2/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
bundler: failed to load command: /hab/pkgs/chef/chef-server-ctl/14.0.22/20200812153852/omnibus-ctl/binstubs/chef-server-ctl (/hab/pkgs/chef/chef-server-ctl/14.0.22/20200812153852/omnibus-ctl/binstubs/chef-server-ctl)
PG::ConnectionBad: could not connect to server: Connection refused
        Is the server running on host "127.0.0.1" and accepting
        TCP/IP connections on port 5432?
```

## To Reproduce
* Install Automate with embedded Chef Infra Server
* Configure Automate to use an external PG database
* Run `chef-server-ctl cleanup-bifrost`

## Expected behavior
The command should complete successfully

## Versions (please complete the following information):
- OS: Centos7
- Browser: N/A
- Automate Build Number: 20200816214709 

## Additional context
This problem impacts all Automate Cluster installations

Aha! Link: https://chef.aha.io/epics/SH-E-771

**Comment by Kmaralla** [comment]
Did you find any update on this bug, i am hitting this now...@teknofire

**Comment by eric51893** [comment]
We are experience this bug also when trying to grant-server-admin-permissions to a user on our chef-automate server.  

Any update or way to pile on to give this more priority?

We do have a support request for the same open at chef.io id: 27626

[root@chef-dev ~]# chef-server-ctl grant-server-admin-permissions eric
/hab/pkgs/chef/chef-server-ctl/14.1.0/20210225010004/vendor/bundle/gems/bundler-1.17.2/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
bundler: failed to load command: /hab/pkgs/chef/chef-server-ctl/14.1.0/20210225010004/omnibus-ctl/binstubs/chef-server-ctl (/hab/pkgs/chef/chef-server-ctl/14.1.0/20210225010004/omnibus-ctl/binstubs/chef-server-ctl)
PG::ConnectionBad: could not connect to server: Connection refused
Is the server running on host "127.0.0.1" and accepting
TCP/IP connections on port 5432?

**Comment by nagendr48** [comment]
I am facing the same issue. Any update ?

**Comment by Kmaralla** [comment]
@eric51893 could you point me to the url of your Ticket, if there is any update...Also i assume, you are using external postgres with chef-automate

**Comment by eric51893** [comment]
@Kmaralla https://getchef.zendesk.com/hc/en-us/requests/27626 and yes, we are using AWS Aurora Postgres with chef-automate.

**Comment by Kmaralla** [comment]
@eric51893 Hey do you mind sending me organization invite. I created my own and logged in, this page doesn't work for me and shows no data.

**Comment by Kmaralla** [comment]
Hi @eric51893 Did you get any update on this error?

**Comment by jimbrayDel** [comment]
We are experiencing this as well is there any way to up the priority for fixing as this makes your organizations completely unmanageable.

**Comment by btm** [comment]
A few `chef-server-ctl` commands need postgresql access as there isn't an Infra Server API for what they're doing.

```
btm@btm-thinkpad:~/src/chef-server/src/chef-server-ctl (main)$ git grep ::PG::C
plugins/cleanup_bifrost.rb:  @erchef_db ||= ::PG::Connection.open(::ChefServerCtl::Config.erchef_sql_connuri)
plugins/cleanup_bifrost.rb:  @bifrost_db ||= ::PG::Connection.open(::ChefServerCtl::Config.bifrost_sql_connuri)
plugins/filtered-dump.rb:  conn = ::PG::Connection.open(::ChefServerCtl::Config.erchef_sql_connuri)
plugins/server_admins.rb:  ::PG::Connection.open(::ChefServerCtl::Config.erchef_sql_connuri)
```

This list aligns with the commands people are reporting, particularly the `chef-server-ctl grant-server-admin-permissions` and `chef-server-ctl cleanup-bifrost` commands.

The chef-server-ctl wrapper here is hardcoded to connect directly to the local postgresql server at `postgresql://automate@127.0.0.1:5432`.

https://github.com/chef/automate/blob/main/components/automate-cs-nginx/cmd/chef-server-ctl/ctl.go#L34-L35

However when external postgresql is configured, it is done though the automate-pg-gateway service, which is essentially HAproxy configured to proxy to either the local postgresql server, or the configured external postgresql server.

The automate-pg-gateway service runs on local port 10145.

https://github.com/chef/automate/blob/main/components/automate-pg-gateway/habitat/default.toml#L3 

I believe the fix here is a matter of changing the port from 5432 to 10145 in `automate-cs-nginx/cmd/chef-server-ctl/ctl.go`

I've looked at the ssl configurations a little and I don't see any obvious ssl issues standing out but we'd need a build to be sure.

**Comment by lbakerchef** [comment]
It appears as if vanilla chef server in external postgresql configuration is not affected:
```
root@ip-10-0-10-50:~# chef-server-ctl status
-------------------
 Internal Services
-------------------
run: bookshelf: (pid 18928) 204s; run: log: (pid 18548) 226s
run: elasticsearch: (pid 18901) 205s; run: log: (pid 18373) 267s
run: nginx: (pid 18888) 205s; run: log: (pid 18741) 212s
run: oc_bifrost: (pid 18790) 206s; run: log: (pid 18271) 282s
run: oc_id: (pid 18885) 206s; run: log: (pid 18286) 272s
run: opscode-erchef: (pid 18950) 204s; run: log: (pid 18672) 220s
run: redis_lb: (pid 18783) 207s; run: log: (pid 18991) 203s
-------------------
 External Services
-------------------
run: postgresql: connected OK to 10.0.6.208:5432
root@ip-10-0-10-50:~# chef-server-ctl cleanup-bifrost
Installing tracking tables into bifrost database: 0.00432309
Sleeping 50 seconds to account for in-flight requests not captured by tracking table
Fetching initial opscode_chef clients and user list: 0.008362423
Fetching count from bifrost auth_actor: 0.000655716

----------------------------------------
 Total chef users+clients: 1
Total bifrost auth_actors: 1
Deletion Candidates (est): 0
----------------------------------------
Estimated deletion count 0. Aborting
Removing tracking tables from bifrost databaseNOTICE:  table "cleanup_known_auth_actors" does not exist, skipping
: 0.001676871
```

**Comment by vivekshankar1** [comment]
It has been solved in https://github.com/chef/automate/pull/6643
