### ISSUE TITLE
add support for suggestions on inspec version in compliance reporting

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#431]
# User Story

We recently exposed the Chef InSpec version used to generate compliance reports on the node details page. 
This issue covers the work to add a field to the compliance searchbar for inspec version, so users can easily filter their nodes to see which inspec version they are running.

# Definition of Done
Can filter by `Chef InSpec Version` (let's talk to ux about naming) in the compliance reporting searchbar. This will include backend and a small amount of ui work.

**Comment by jonong1972** [comment]
`InSpec Version` makes the most sense to me. I would say roll with it.

**Comment by vjeffrey** [comment]
remaining work for this card is to :
- support suggestions for inspec version (https://github.com/chef/automate/compare/vj/suggest-inspec-version)
- add the option in the ui

**Comment by vjeffrey** [comment]
i'm having trouble with this branch:  https://github.com/chef/automate/compare/vj/suggest-inspec-version -- that should work but it is not. i'm not sure if that's because of the `.` in the version numbers?

**Comment by lancewf** [comment]
It looks like this is a problem for all the current search types. If I add reports with the organization field with version numbers like 3.0.2. I see the same problem. 

I am looking into why it is like that.

**Comment by lancewf** [comment]
I found the problem we need to add the term 'punctuation' to the mapping here https://github.com/chef/automate/blob/master/components/compliance-service/ingest/ingestic/mappings/comp-rep-date.go#L25. 

Without 'punctuation' term the tokenizer will create tokens for each number between the period. Since our version (3.1.0) only has one number between each period no tokens will be created because the minimum token size is two characters. 

Below are the tokens for version "3.0.10"
```
{
  "_index": "comp-3-r-2019.06.21",
  "_type": "_doc",
  "_id": "4b3f975d-d162-4772-a496-cf4c66c07b9d",
  "_version": 1,
  "found": true,
  "took": 1,
  "term_vectors": {
    "version.engram": {
      "field_statistics": {
        "sum_doc_freq": 5,
        "doc_count": 1,
        "sum_ttf": 5
      },
      "terms": {
        "3.": {
          "term_freq": 1,
          "tokens": [
            {
              "position": 0,
              "start_offset": 0,
              "end_offset": 2
            }
          ]
        },
        "3.0": {
          "term_freq": 1,
          "tokens": [
            {
              "position": 1,
              "start_offset": 0,
              "end_offset": 3
            }
          ]
        },
        "3.0.": {
          "term_freq": 1,
          "tokens": [
            {
              "position": 2,
              "start_offset": 0,
              "end_offset": 4
            }
          ]
        },
        "3.0.1": {
          "term_freq": 1,
          "tokens": [
            {
              "position": 3,
              "start_offset": 0,
              "end_offset": 5
            }
          ]
        },
        "3.0.10": {
          "term_freq": 1,
          "tokens": [
            {
              "position": 4,
              "start_offset": 0,
              "end_offset": 6
            }
          ]
        }
      }
    }
  }
}
```
`curl $ELASTICSEARCH_URL/comp-3-r-2019.06.21/_doc/4b3f975d-d162-4772-a496-cf4c66c07b9d/_termvectors?fields=version.engram`

**Comment by vjeffrey** [comment]
i wonder if this is the same issue that we are hitting on https://github.com/chef/automate/issues/633 ?

**Comment by lancewf** [comment]
@vjeffrey I think that is another problem. The version number is a separate field. I will confirm.

**Comment by lancewf** [comment]
Suggestion tokens are currently built with letters and digits. Punctuation is used as a separator for tokens. This works well for name/label-type fields, but for version number fields, suggestion tokens are not created. Below shows the differences between tokens for name fields vs version fields with punctuation added (a user needs to type the full token for the node to be added to the suggestions list).

#### Name example
"RedHat(2)-beta-nginx(f)-apache(s)-failed"
##### With punctuation added 
"re", "red", "redh", "redha", "redhat", "redhat(", "redhat(2", "redhat(2)", "redhat(2)-", "redhat(2)-b", "redhat(2)-be", "redhat(2)-bet", "redhat(2)-beta", "redhat(2)-beta-", "redhat(2)-beta-n", "redhat(2)-beta-ng", "redhat(2)-beta-ngi", "redhat(2)-beta-ngin", "redhat(2)-beta-nginx"
##### With only letters and digits
"ap", "apa", "apac", "apach", "apache", "be", "bet", "beta", "fa", "fai", "fail", "faile", "failed", "ng", "ngi", "ngin", "nginx", "re", "red", "redh", "redha", "redhat"

#### Version example 
"3.0.10"
##### With punctuation added 
"3.", "3.0", "3.0.", "3.0.10"
##### With only letters and digits
no suggestions. 

We might want to build tokens in two ways depending on the field type. 
For fields that are primarily version numbers, add punctuation, and leave out punctuation for label/name-type fields.

**Comment by vjeffrey** [comment]
> We might want to build tokens in two ways depending on the field type.
For fields that are primarily version numbers, add punctuation, and leave out punctuation for label/name-type fields.

I think this ^^ sounds like the most reasonable approach

**Comment by vjeffrey** [comment]
will this change require a migration?

**Comment by lancewf** [comment]
@vjeffrey Without a migration of the existing indexes only the reports ingested after this change will have InSpec Version numbers show up in the search bar suggestions.
