### ISSUE TITLE
upgrade local chef server to work with es7.9

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#4312]
## User Story
es index on automate side:
https://github.com/chef/automate/blob/master/components/automate-cs-oc-erchef/habitat/config/elasticsearch-index-init.json

talk to folks in #chef-server if you have questions

https://github.com/chef/automate/issues/4165

**Comment by lancewf** [comment]
Below is a link to a slack discussion about upgrading Chef Servers Elasticsearch to 7. 
https://chefio.slack.com/archives/C07JP2K7F/p1600905229021900

Below is an overview of the discussion. 
The file below needs the mapping updated to remove the "object" type. 
https://github.com/chef/chef-server/blob/e4e47e604b2403ed936b7cf245faa5f923188868/omnibus/files/private-chef-cookbooks/private-chef/libraries/helper.rb#L117

Look into the below files to see if the "type" is being used in the request.
https://github.com/chef/chef-server/blob/master/src/oc_erchef/apps/chef_index/src/chef_index_expand.erl
https://github.com/chef/chef-server/blob/master/src/oc_erchef/apps/chef_index/src/chef_elasticsearch.erl#L112-L127

**Comment by tas50** [comment]
The embedded Chef Infra Server in Automate now supports ES 7
