### ISSUE TITLE
Display version and build in UI, CLI, Release Notes, and Downloads page

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#432]
## User Story

This is a requirement for some customers. We publish the build number but in order to meet the upgrade requirements set by certain companies, we need to also call out the major version of Automate.

### UI
* Add major version number in the user menu
* Label the build number in the user menu

<img width="214" alt="add-version-label-build" src="https://user-images.githubusercontent.com/5489125/58572717-0efbdf80-81f1-11e9-9208-6e51b69ec6e4.png">

### CLI
* When checking the version with `chef-automate version` display the major version, CLI build number, and Server build number 

```
Version: 2
CLI Build: 20190528210257
Server Build: 20190528210257
```

### Release Notes Page
* Change left-nav to say _Build_ instead of _Version_
* Change the h1's on the pages to say `Version: 2 Build: <build number>`

<img width="1029" alt="docs-changes" src="https://user-images.githubusercontent.com/5489125/58573454-9564f100-81f2-11e9-8109-e517aabab0c3.png">

### Downloads Page
* Update the paragraph text describing automate to list the major version number

<img width="483" alt="downloads-page" src="https://user-images.githubusercontent.com/5489125/58573675-17551a00-81f3-11e9-9a83-98b51c9357a5.png">

## Related Resources
https://chef-internal.ideas.aha.io/ideas/A2-I-44

**Comment by btm** [comment]
> Downloads Page
> * Update the paragraph text describing automate to list the major version number

I can make this change. However, it used to say Automate 2, but when we made the last round of changes for the licensing changes we tried to make it more "the one and only automate you should use, except if... " instead of there being v1 and v2. So we should discuss if there's a better way to do that and not have the [marketing] product name be "Chef Automate 2".

**Comment by kagarmoe** [comment]
Automate 1 EOLs in December, doesn't it? We may have a problem with "Version: 2" because it isn't how we handle versioning in the docs. (As @btm mentioned, there is only one Automate. It is a marketing & metaphysical position) Even if we settle on versioning, we may not be able to get the build ID on the same line as the version number. OK to stack them?

**Comment by kagarmoe** [comment]
Also, you use "provide" 2x in your paragraph.

**Comment by susanev** [comment]
@kagarmoe that's the current copy.. all I added was the _Version 2_

**Comment by btm** [comment]
@kagarmoe yes, we're targeting an EOL of A1 for 12/31.

Version 2 is only useful relative to Version 1.y.z existing or having existed. Every day we get closer to only caring about the build version though. The difference in version formats (x.y.z versus a timestamp) makes it clear to a technical person which is which, is that enough?

**Comment by vjeffrey** [comment]
release notes and downloads page changes will be handled by @schisamo 's team

**Comment by vjeffrey** [comment]
i will take care of the user menu and cli change (i might need a bit of help with css but i can get the basics going)

**Comment by schisamo** [comment]
@vjeffrey Ok my two assigned tasks are complete!

- This change is live in `dev` and will go live on automate.chef.io the next time we promote automate to `acceptance` (and then `current`):

![Release_Notes](https://user-images.githubusercontent.com/6164/59125213-ad91ea00-892f-11e9-824d-56215a5490a4.png)

- This change is already live on downloads.chef.io

![Chef_Downloads](https://user-images.githubusercontent.com/6164/59125285-d4502080-892f-11e9-8a2f-28800268871d.png)

**Comment by vjeffrey** [comment]
NICE!! thank you!! 🎉

**Comment by vjeffrey** [comment]
i merged https://github.com/chef/automate/pull/502 , so we're good to go on this. it just needs to run through our pipeline now.
