### ISSUE TITLE
add a button to download historical reports on compliance node details

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#4344]
## User Story
we want to add a button to download historical reports on compliance node details

we already have this in client runs ui:
![Screen Shot 2020-09-15 at 08 56 25](https://user-images.githubusercontent.com/10341541/93227230-64833500-f731-11ea-8999-d930aaad119a.png)

https://github.com/chef/automate/issues/1923

let's talk to ux about the design for the compliance side, since the scan history sidebar has slightly modified styling from the client runs one

**Comment by Shadae** [comment]
Backend done with #1765

**Comment by shaik80** [comment]
Do we have any UX design..?
