### ISSUE TITLE
hide sign in as local user button

### ISSUE THREAD

**Issue by susanev** [chef/automate#4365]
## overview
there has been a customer request
to be able to hide the sign in as a local user button

it should not be hidden by default, or just because saml or ldap is configured

but only when a specific deployment does not want that button

## the plan
- [ ] hide the sign in as a local user button on the sign in page
- [ ] investigate the eng effort to also hide the users page, teams page, and local option in the member expression flow
- [x] no public documentation

**Comment by srenatus** [comment]
I believe we could disable local users in dex completely. That would make the button disappear, too.

**Comment by susanev** [comment]
@srenatus is there any concern around disabling the local admin user?

**Comment by srenatus** [comment]
well it would be gone. there's dragons here, but you could still change the config to re-enable local users.

**Comment by srenatus** [comment]
This line decides if dex "knows" local users or not: https://github.com/chef/automate/blob/afbd5604c7d5966b24e0676f3df6e55c11c232f0/components/automate-dex/habitat/templates/config.yml#L6

**Comment by blakestier** [comment]
@srenatus this is done, right?

**Comment by msorens** [comment]
I attached it to the issue and closed.

**Comment by srenatus** [comment]
@blakestier Yeah as described in the issue, it's resolved. However if you disable local users this way, the UI will still show your local users and local teams, although they're not usable anymore.
