### ISSUE TITLE
Compliance summary doesn't match trend data as waived node and controls are missing

### ISSUE THREAD

**Issue by alexpop** [chef/automate#4382]
## Describe the bug

When compliance reports have waived nodes or waived controls, the summary stats don't match the values in the trend graphs. As can be seen here:

![trend_no_waivers_data](https://user-images.githubusercontent.com/107378/94481768-29bcda80-01d0-11eb-925b-9e51889d648d.png)

This is because the trend graphs have not been updated to add a value of waived nodes or controls, depending on the trend graph.

## To Reproduce
Ingest compliance reports with waived nodes or controls. Examples can be found here:
https://github.com/chef/automate/tree/master/components/compliance-service/test_data/audit_reports

## Expected behavior
Trend graphs have waived nodes and waived controls lines.

**Comment by SEAjamieD** [comment]
This is currently in progress by @vivekshankar1 - PR: https://github.com/chef/automate/pull/4456
