### ISSUE TITLE
downloads link on automate.chef.io redirects to https://www.chef.io/get-chef/

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#440]
# User Story

@susanev noticed the downloads link on automate.chef.io redirects to https://www.chef.io/get-chef/, which only displays habitat and workstation in the list of downloads.
This is a little confusing, since it's the downloads button found on automate.chef.io

Could we change this instead to navigate users to the downloads.chef.io site?  or should it go somewhere else?

**Comment by vjeffrey** [comment]
https://github.com/chef/automate/blob/master/components/automate-chef-io/config.toml#L46 is the line that needs changing if we want to change this

**Comment by susanev** [comment]
There's a lot of redirecting around related to downloading Automate and from what I can tell there isn't any actual download you can make happen from the browser. So, I argue that we should remove that Download link entirely.

**Comment by susanev** [comment]
this was addressed, on the downloads page.
