### ISSUE TITLE
Actionable Events on Automate Charts

### ISSUE THREAD

**Issue by jonong1972** [chef/automate#441]
# User Story

As a Automate User, I want to click on a graph or chart and the action of that will take me to the data with the applied filters so that I can see the data in a table format.

# Definition of Done
Currently only select charts need to be updated with a click event, since Automate's filter bar may not have the necessary filters yet to accommodate the click action or there  may not be a page (yet) to go to.

Also, the click events should adhere to the accessible guidelines. e.g. able to navigate and take action via keyboard

## Chef Client Runs  
Page: `/client-runs`
<img width="614" alt="Screen Shot 2019-05-29 at 10 11 21 AM" src="https://user-images.githubusercontent.com/1316587/58577034-808c5b80-81fa-11e9-8bae-49f5aa2a6f9e.png">

When clicking on the charts respective status within the radial chart, it should apply the status filter to the table below. 

## Compliance
Page: `/compliance/reports/overview`

Skip these charts for now:
- **Node Status Chart** 
- **Severity Status Chart**
- **Control Status Chart** 
- **Severity of Control Failure Chart** 

### Node Status Tab

**Node Status Over Time Trend Graph Chart**
<img width="1167" alt="Screen Shot 2019-05-29 at 10 37 18 AM" src="https://user-images.githubusercontent.com/1316587/58578485-c565c180-81fd-11e9-917f-1fa945a5c33b.png">

When clicking on a date point, this should apply the date in the search filter, and refresh page.

**Top Platform Failures Chart**
<img width="589" alt="Screen Shot 2019-05-29 at 10 33 14 AM" src="https://user-images.githubusercontent.com/1316587/58578247-3193f580-81fd-11e9-9bed-b39f8579efe7.png">

When clicking and item within the bubble chart, the filter by that _platform_ will be applied, and the user taken to the _Nodes tab_ (`/compliance/reports/nodes`).

**Top Environment Failures Chart**
<img width="587" alt="Screen Shot 2019-05-29 at 10 33 39 AM" src="https://user-images.githubusercontent.com/1316587/58578269-3f497b00-81fd-11e9-87d1-5b88f57313f5.png">

When clicking and item within the bubble chart, the filter by that _Environment_ will be applied, and the user taken to the _Nodes tab_ (`/compliance/reports/nodes`).

### Profile Status Tab

**Controls Status over Time Trend Graph Chart**
<img width="1184" alt="Screen Shot 2019-05-29 at 10 36 45 AM" src="https://user-images.githubusercontent.com/1316587/58578456-b3841e80-81fd-11e9-841d-695a2524e915.png">

When clicking on a date point, this should apply the date in the search filter, and refresh page.

**Top Profile Failures Chart**
<img width="592" alt="Screen Shot 2019-05-29 at 10 35 42 AM" src="https://user-images.githubusercontent.com/1316587/58578400-8e8fab80-81fd-11e9-845f-72d3228812ce.png">

When clicking and item within the bubble chart, the filter by that _profile_ will be applied, and the user taken to the _Nodes tab_ (`/compliance/reports/nodes`).

**Top Control Failures Chart**
<img width="591" alt="Screen Shot 2019-05-29 at 10 36 13 AM" src="https://user-images.githubusercontent.com/1316587/58578426-9c453100-81fd-11e9-993a-327359317634.png">

When clicking and item within the bubble chart, the filter by that _control_ will be applied, and the user taken to the _Nodes tab_ (`/compliance/reports/nodes`).

**Comment by susanev** [comment]
We should make these interactive by using a keyboard only as well, not just for pointing devices.

**Comment by susanev** [comment]
@jonong1972 can we talk about this in more detail at one of our ux meetings this week? id like to see this align with the work @apriofrost has been doing on tooltips if possible.

**Comment by vjeffrey** [comment]
@jonong1972 given that most of the items in this issue are complete, can you pls open a separate issue for the remaining one(s), so we can close this one?

**Comment by susanev** [comment]
some of this work is done, the rest has been deprioritized, so closing.
