### ISSUE TITLE
Add Status Filters to Compliance Reporting  Profile Details View

### ISSUE THREAD

**Issue by jonong1972** [chef/automate#443]
# User Story

As a Automate User, I want to filter my controls on the Compliance Reporting Profile detall view so that I may see which controls are failing.

# Definition of Done
The Profile Details page within a compliance report will have our standard filter buttons above the table.

For now we will just limit to:
All Controls | Failed Controls | Skipped Controls

# Demo Script / Repro Steps
1. User navigates to Compliance > Profiles Tab
2. Click on any profile
3. User can then click on a status filter above the Controls data table
4. System filters controls within table

**Comment by vjeffrey** [comment]
related: #328

**Comment by vjeffrey** [comment]
this is old; we are doing something different here; closing
