### ISSUE TITLE
Event Feed as a separate new service

### ISSUE THREAD

**Issue by lancewf** [chef/automate#444]
As an Automate developer, I would like to be able to expand the event-feed to include events from other parts of the system.

The event feed is currently an aggregation between the config-mgmt-service and compliance-service. Most of the logic is spread between these two services and also the automate-gateway. The automate-gateway is the aggregator between these two services. When a request comes in for 100 of the most recent events, requests are made to the compliance-service and config-mgmt-service for 100 events. Then in the automate-gateway, these events are merged together and only 100 combined events are returned. 

The problem with the current system is adding new events would involve calling the third service to collect the events. This third service would have to store and implement the same event feed API and logic. This means the current approach is not easily expandable.

The suggested change is to pull the compliance-service's event feed code out of the compliance-service into its own service. Then have the config-mgmt-service's events be added this new service through the event-service. 

These changes would allow the below expansion of the event feed:
* Habitat Application events. 
* New event string with errors. This would allow Automate errors to be displayed in the event feed.
* notifications-service events. 
* Deployment-service events Automate upgrades and backups.  

The PR steps to accomplish this task would be:
1. Pull the compliance-service's event feed code out of the compliance-service into its own service called the event-feed-service
1. Push config-mgmt-service's events to the event-feed-service. Prevent the config-mgmt-service from returning events. 
1. Move all the automate-gateway event-feed code into the event-feed-service.

#### PRs
- [x] Create event-feed-service habitat package - https://github.com/chef/automate/pull/652
- [x] Add event-feed-service to automate-deployment-service - https://github.com/chef/automate/pull/671
- [x] Move event feed code from the compliance-service to the event-feed-service - https://github.com/chef/automate/pull/707
- [x] Direct events in the event-service to the event-feed-service - https://github.com/chef/automate/pull/732
- [x] Add the Event feed data lifecycle - https://github.com/chef/automate/pull/778
- [x] Migrate compliance-service data, backup, and redirect automate-gateway requests; delete compliance event feed - https://github.com/chef/automate/pull/784
- [x] Add project filtering for GetFeed - https://github.com/chef/automate/pull/4059
~~- [ ] Break up the "eventfeed-2-feeds" index into daily indexes~~
- [x] Add project filtering for GetFeedSummary - https://github.com/chef/automate/pull/4071
- [x] Add project filtering for GetFeedTimeline - https://github.com/chef/automate/pull/4072
- [x] Chef Server and Chef Server Orgs filtering - https://github.com/chef/automate/pull/4076
- [x] Add IAMv2 project updating - https://github.com/chef/automate/pull/4090
- [ ] ingest-service create event for ingested actions, migrate actions to event-feed-service - https://github.com/chef/automate/pull/4108
~~- [ ] Move all the automate-gateway event-feed code into the event-feed-service~~ - https://github.com/chef/automate/issues/4154
~~- [ ] Update Docs https://automate.chef.io/docs/configuration/#data-retention with data life cycle config~~ - https://github.com/chef/automate/issues/4155

**Comment by susanev** [comment]
There would be some icon work for the UI for these new event types right?

**Comment by lancewf** [comment]
PRs
- [ ] Create event-feed-service habitat package
- [ ] Add event-feed-service to automate-deployment-service
- [ ] Direct events in the event-service to the event-feed-service
- [ ] Add the Event feed data lifecycle
- [ ] Migrate compliance-service data and redirect automate-gateway
- [ ] Delete compliance event feed
- [ ] Push config-mgmt-service's events to the event-feed-service
- [ ] Move all the automate-gateway event-feed code into the event-feed-service
