### ISSUE TITLE
[CMFA: Node View (read, edit)] Chef Automate supports managing Infra Server Nodes

### ISSUE THREAD

**Issue by vsingh-msys** [chef/automate#4535]
The data on the Infra Server has been historically considered to represent the "desired state" while the data returned by the Infra Client and displayed in Automate is the "current state" (at least at that point in time).

There's a separate related by out of scope long-standing desire to separate the node object on the infra server into two objects, one representing the settings the user desires for the node (desired state), and the other much larger representing the node object that is saved back to the Infra Server that contains all of the attributes created by Ohai (current state).

Automate needs a place to view the node object on the Infra Server, and to edit parts of it. The current options on Chef Manage for a node are:
- Manage Tags
- Edit Run List
- Edit Attributes
- Reset Key
- Delete [Node]

Aha: https://chef.aha.io/features/SH-169

**Comment by AnkurMundhra** [comment]
Completion of this should have the following features:

Node view: complete​
- Read view of node: list, details, attributes​
- Edit view of nodes: delete, change environment, edit node run list, edit node attributes​
- Node view: Manage tags​
- Node view: reset key
