### ISSUE TITLE
[Chef manage global objects] organizations list & detail API

### ISSUE THREAD

**Issue by vsingh-msys** [chef/automate#4547]
### User story
- Chef server global object organizations list API. https://docs.chef.io/server/api_chef_server/#get-1

Response
```
{
  "org_name1": https://url/for/org_name1",
  "org_name2": https://url/for/org_name2"
}

```
- Chef server global object organization detail API. https://docs.chef.io/server/api_chef_server/#get-2

```
{
  "name": "chef",
  "full_name": "Chef Software, Inc.",
  "guid": "f980d1asdfda0331235s00ff36862"
     ...
}
```

**Comment by kalroy** [comment]
We will handle it differently.
