### ISSUE TITLE
add support for additional habitat packages on managed supervisor

### ISSUE THREAD

**Issue by skylerto** [chef/automate#455]
# User Story

As an Automate User, I will use this work when I want to run effortless config/effortless compliance.

Currently when running Automate 2, it manages its own supervisor and rejects any additional habitat packages. A requirement of our organization is that we have our effortless config (chef-client habitat package) managing the node that Automate is running on.

This causes a conflict as Automate will immediately unload the effortless habitat package.

# Definition of Done

Have the ability to specify, or manually override the removal of habitat packages.

# Demo Script / Repro Steps

Spin up Automate 2, try to `hab svc load ...`

**Comment by stevendanna** [comment]
We think this is a good idea and agree that we want to support people who want to use Habitat for other services (effortless config, log gathering services etc) on the same machine as Habitat.

Addressing this requires that we answer a few questions:

- [ ] Are users OK with Chef Automate maintaining control of the hab-sup and hab-launch versions? Currently, we carefully manage these versions as Chef Automate requires specific Habitat behavior.

- [ ] Are users OK with Chef Automate potentially restarting their other services on upgrade?  Right now, we control the systemd unit file for hab-sup and occasionally need to restart the entire hab-sup process tree when updates to the unit file are required:  https://github.com/chef/automate/blob/master/components/automate-deployment/pkg/target/local_target.go#L62-L84

- [ ] Proxy variables.  Right now we set our HTTP_PROXY variables in the systemd unit file to ensure they are universally applied and to ensure that hab-sup itself always respected those variables.  My guess is that users who need an HTTP proxy for automate would also need it for other services so perhaps this isn't much of an issue.

- [ ] How would we handle users who want to join their hab-sup to a larger habitat ring?

**Comment by skylerto** [comment]
These are all great points, likely boils down to accepting the level of risk of running A2 anyways.

I can't answer for the team, but I can provide insight into the organizations that I've worked with in engagements where habitat is heavily used. 

For the first two, some level of support would definitely be appreciated especially for the orgs that I've worked with. Anytime we need to run agents on A2 right now, we have to do some horrific templating of a systemd service where we wrap the packages run hook as the ExecStart -- something I would never want to maintain.

As for proxies, in most cases I've deployed A2 in environments where we use the air-gap bundle as opposed to opening up the proxy we rarely have to deal with that. However, a well written no_proxy should take care of most proxy related issues.

Finally, ring is very interesting and perhaps controlled with deployment config?

**Comment by skylerto** [comment]
@stevendanna has there been anything else determined/designed on this?

**Comment by stevendanna** [comment]
@skylerto Unfortunately not.  I'll try to bring this up internally to get some movement on it.

**Comment by susanev** [comment]
transferred to [aha idea](https://chef-software.ideas.aha.io/ideas/A2-I-111)
