### ISSUE TITLE
End to end testing of Chef Manage Read mode

### ISSUE THREAD

**Issue by vivekvardwaz** [chef/automate#4608]
End to end testing of Chef Manage Read mode

**Comment by AnkurMundhra** [comment]
Completion of this should have the following things out of feature flag:

- Read view of cookbooks: list, details, content​
- Read view of roles: list, details, attributes​
- Read view of environments: list, details, attributes​
- Read view of data bags: list, data bag item list​
- Read view of client: list, details (with key)

**Comment by kalroy** [comment]
All the issues associated to this EPIC are addressed in the build **20210217163248**
