### ISSUE TITLE
Add node credentials bug in compliance

### ISSUE THREAD

**Issue by vivekshankar1** [chef/automate#4655]
## User Story

Unable to add new credentials in compliance tab while trying to add a new node. It opens a blank page.

## Definition of Done

When clicking on add new credentials it should open up a view to add credentials, instead of blank page

## Screenshot
![Screenshot 2021-01-25 at 9.36.47 PM.png](https://images.zenhubusercontent.com/5fce5354d8b7b4766d18a979/3831eae7-ba6a-4e10-bf82-a1899103fdf7)
![Screenshot 2021-01-25 at 9.30.23 PM.png](https://images.zenhubusercontent.com/5fce5354d8b7b4766d18a979/f70fef5a-ff54-44d5-b676-1669c4cb9463)

**Comment by SEAjamieD** [comment]
@jong-progress - Do we know what we would like clicking this button to open?

**Comment by jong-progress** [comment]
@SEAjamieD Originally it was suppose to go to the "Create Credentials" under Node Credentials.
https://a2-local-inplace-upgrade-acceptance.cd.chef.co/settings/node-credentials

But a better solution would to have the create modal dialogue open while adding a node. So a user wont change context and break their flow of adding a node.

**Comment by SEAjamieD** [comment]
> @SEAjamieD Originally it was suppose to go to the "Create Credentials" under Node Credentials.
> https://a2-local-inplace-upgrade-acceptance.cd.chef.co/settings/node-credentials
> 
> But a better solution would to have the create modal dialogue open while adding a node. So a user wont change context and break their flow of adding a node.

@jong-progress 
Thanks!  I agree.  I'm going to route this to the original path for now so that its not a dead end for current customers and will open a new ticket to make that a create-modal.
