### ISSUE TITLE
Search box for Cookbooks in item detail part

### ISSUE THREAD

**Issue by chaitali-mane** [chef/automate#4666]
## Describe the bug
Add search bar UI in cookbooks item detail page as per new design. 

## To Reproduce
if you have sample data for the infra servers than
go to >> infrastructure tab >> click on Chef server on left side navigation bar >> Organizations >> Cookbooks >> admins (any item)

Search box missing in item details page

**Comment by kalroy** [comment]
This issue is not valid as Cookbooks tab does not have search box. Closing it.
