### ISSUE TITLE
one node view ui: list view

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#468]
# User Story

As an Automate user, I'd like to have a way to quickly understand which of my nodes are failing the compliance scans but passing their client runs, which nodes just started failing compliance scans or client runs when they were previously passing, which nodes failed a scan during a timerange, etc.
We've done the work to answer these questions via api (https://github.com/chef/automate/blob/master/components/automate-chef-io/content/docs/nodes.md#examples).

**Now we need to build a list view to help our users out.**

sample request and response from api:
```
➜  compliance-service git:(master) curl -s --insecure -H "api-token: token-val" https://a2-url/api/v0/nodes/search -d '{
  "filters": [
    {"key": "last_run_status", "values": ["PASSED"]},
    {"key": "last_scan_status", "values": ["FAILED"]}
  ]
}' | jq
```
```
{
  "nodes": [
    {
      "id": "ef530be5-2a0e-4968-9d64-60693238c46c",
      "name": "chefdk-rhel-6-tester-11555e.cd.chef.co",
      "platform": "redhat 6.9",
      "platform_version": "6.9",
      "manager": "",
      "tags": [
        {
          "key": "chef-tag",
          "value": "chefdk"
        },
        {
          "key": "chef-tag",
          "value": "slave"
        },
        {
          "key": "chef-tag",
          "value": "tester"
        }
      ],
      "last_contact": "2019-05-31T19:16:36Z",
      "status": "unknown",
      "last_job": null,
      "target_config": null,
      "manager_ids": [],
      "connection_error": "",
      "state": "RUNNING",
      "name_prefix": "",
      "projects": [],
      "run_data": {
        "id": "7139d6eb-3df9-4b16-a953-d570735f3012",
        "status": "PASSED",
        "penultimate_status": "PASSED",
        "end_time": "2019-05-31T19:16:36Z"
      },
      "scan_data": {
        "id": "22ffdea1-d5d9-499b-b4ef-c4683c117fa9",
        "status": "FAILED",
        "penultimate_status": "UNKNOWN",
        "end_time": "2019-05-14T20:36:33Z"
      }
    },
    {
      "id": "8907a72f-c589-4e6d-b222-86ef606a9446",
      "name": "chefdk-rhel-7-tester-a3a252.cd.chef.co",
      "platform": "redhat 7.3",
      "platform_version": "7.3",
      "manager": "",
      "tags": [
        {
          "key": "chef-tag",
          "value": "chefdk"
        },
        {
          "key": "chef-tag",
          "value": "slave"
        },
        {
          "key": "chef-tag",
          "value": "tester"
        }
      ],
      "last_contact": "2019-05-31T19:45:03Z",
      "status": "unknown",
      "last_job": null,
      "target_config": null,
      "manager_ids": [],
      "connection_error": "",
      "state": "RUNNING",
      "name_prefix": "",
      "projects": [],
      "run_data": {
        "id": "c052ac64-2e75-42b9-8ae9-25a5c864916e",
        "status": "PASSED",
        "penultimate_status": "PASSED",
        "end_time": "2019-05-31T19:45:03Z"
      },
      "scan_data": {
        "id": "009d582d-fbd5-4079-8730-001ecee40896",
        "status": "FAILED",
        "penultimate_status": "UNKNOWN",
        "end_time": "2019-05-14T20:41:31Z"
      }
    }
  ],
  "total": 2,
  "total_unreachable": 2640,
  "total_reachable": 21,
  "total_unknown": 1595
}
```

**Mock Up of List Page**
![V3 - Node List](https://user-images.githubusercontent.com/1316587/72649569-e74db900-3932-11ea-9666-043722c4cdae.png)

# Definition of Done
Under feature flag, we will have a temporary link in the top navigation listed as "Nodes" where you can access this page. This will change when we merge all the infrastructure items together under one top nav item.

**Filters Buttons:**
There will be 4 actions:
1. Show all Nodes
2. Show all nodes that contain client runs (if they also have compliance scans - include those as well)
3. show all nodes that contain compliance scans (if they have client runs - include those as well)
4. show all missing nodes (this is when a node gets marked as missing) and when there is no data on compliance scans as well.

**Searchbar:**
- can search by node name, platform, environment
- search for values by using the functionality introduced in https://github.com/chef/automate/issues/667

**Sortable Columns:**
- Node Name
- Platform
- Environment
- Last Infra Run
- Last InSpec Scan

**Action Items within Table:**
Last Client Run Link:  Will go to the Client Run Node Details page
e.g. `/client-runs/b39584f3-82f8-46f3-8bac-7a963dc90638/runs/048ea4f9-5f16-4a25-9d43-5f295e0be558;end_time=2019-06-20T22:20:46Z`

Last Scan Job Link: Will go to the Node Details page via the Compliance page.
e.g. `/compliance/reports/nodes/8dc5a451-d3f0-4b06-957a-d6bd06f51bec`

**Comment by vjeffrey** [comment]
i have a few questions:

- why is there a "no data" placeholder on a couple of the nodes/when does that apply?   
even if the node is now "missing", wouldn't it have a last client run?
<img width="551" alt="Screen Shot 2019-06-20 at 19 27 07" src="https://user-images.githubusercontent.com/10341541/59891193-6d9c1f80-9391-11e9-854f-352614f5887f.png">

- is this list (including unchecked items) just the same list that's on client runs? do we need all that information? why does this view require all that info? what about things like "node state" (running/stopped/terminated/missing/unknown) - do we want to show that?
<img width="638" alt="Screen Shot 2019-06-20 at 19 38 31" src="https://user-images.githubusercontent.com/10341541/59891675-49d9d900-9393-11e9-8d71-8c164123d61c.png">
 
- what fields should the user be able to search by in the searchbar?

- in client runs, you can only delete the missing nodes if you are an admin - does the same logic apply here?

**Comment by vjeffrey** [comment]
all the fields listed here: https://github.com/chef/automate/blob/master/components/nodemanager-service/pgdb/nodes.go#L593 + tags are filterable for nodes. we'll need to do a small amount of backend work to "suggest" field values (we already support this to some degree, need to make sure we can "suggest" on all the fields we support for filtering)

**Comment by vjeffrey** [comment]
ah yes, we can search on all the filterable fields and return suggest field values by adding to https://github.com/chef/automate/blob/master/components/nodemanager-service/pgdb/nodes.go#L890

**Comment by jonong1972** [comment]
> i have a few questions:
> 
>     * why is there a "no data" placeholder on a couple of the nodes/when does that apply?
>       even if the node is now "missing", wouldn't it have a last client run?
> 
> 
> <img alt="Screen Shot 2019-06-20 at 19 27 07" width="551" src="https://user-images.githubusercontent.com/10341541/59891193-6d9c1f80-9391-11e9-854f-352614f5887f.png">
> 

Im not sure when that occurs. I saw this on dev, and the little info icon mentions that there is no client run data in there, yet it still pulls in.  I just threw that in there to cover for that case. Also, looks like a good talking point to get a better understanding.

>     * is this list (including unchecked items) just the same list that's on client runs? do we need all that information? why does this view require all that info? what about things like "node state" (running/stopped/terminated/missing/unknown) - do we want to show that?
> 
> 
> <img alt="Screen Shot 2019-06-20 at 19 38 31" width="638" src="https://user-images.githubusercontent.com/10341541/59891675-49d9d900-9393-11e9-8d71-8c164123d61c.png">
> 

Yes. This is just the same list pulled from Client Runs for parity.  As for do we need all this?  Is a good question. I know some things like client version was an ask. But I threw all the things on the table. Ideally, if we can track which items through telemetry, we can know which items are useful or not.

As for Node state, I thought a while on this. Originally I had that node status in there which combined if it was missing (client runs) and stopped,terminiated, unknown, etc. (compliance) For simplicity for first round I decided to remove it.  We can totally add it back in if we want, but I think this is another talking point I would like to discuss and figure out.

>     * what fields should the user be able to search by in the searchbar?
> 
I thought it was going to be the combination of both search field items from both Client Runs and Compliance?

>     * in client runs, you can only delete the missing nodes if you are an admin - does the same logic apply here?

Yes.

**Comment by lancewf** [comment]
I would suggest not adding the "Remove Nodes" button functionality to this view. I think it would make sense to only allow the user to be able to delete nodes from the Client Runs page for now. 

For the "No Data" label. I would say not to bring that label to this view. The backend does still store the last Client Run date-time if there is no client runs data. It would be better to display the date-time.

**Comment by vjeffrey** [comment]
i'm +1 on the suggestions from @lancewf

**Comment by vjeffrey** [comment]
Note: we currently support filtering on this list of fields: https://github.com/chef/automate/blob/master/components/automate-chef-io/content/docs/nodes.md#filtering-nodes

**Comment by jonong1972** [comment]
Sweet. I will remove the 'Remove  Nodes'

**Comment by jonong1972** [comment]
> Note: we currently support filtering on this list of fields: https://github.com/chef/automate/blob/master/components/automate-chef-io/content/docs/nodes.md#filtering-nodes

Oh. wow. would we be able to pull in other searchable items in the future like the Client Version, cookbooks, profiles, environments etc?

If this is all we can search, we may be able to remove some of the configurable columns then.

**Comment by vjeffrey** [comment]
> Oh. wow. would we be able to pull in other searchable items in the future like the Client Version, cookbooks, profiles, environments etc?

Yes -- I think it would probably be a good idea to figure out what the most important/relevant fields are to filter on there. Then we can look at adding that data in the call to nodemanager

> If this is all we can search, we may be able to remove some of the configurable columns then.

👍

**Comment by jerryaldrichiii** [comment]
How do we feel about renaming `Last Client Run` to `Last Infra Run`?

**Comment by vjeffrey** [comment]
^^^ yes, good point!!

**Comment by jonong1972** [comment]
@jerryaldrichiii ah yeah. funny you mentioned that. This just came up in our UX meeting about how we are going to integrate the new Infra terminology into Automate. I think we are reconvening next week on it after we get time with product managers

**Comment by Stromweld** [comment]
Love the combined look and simplicity of combining compliance and client run views. Is this going to be carried forward to the individual node as well when clicked? Simply adding a new tab next to attributes that shows the scan controls in a similar way the resources tab does would make things alot cleaner and more intuitive.

The node view you could also bring back the graphical ring from the client runs and add next to it the graphical ring from compliance view to get a quick overview of entire infrastructure status in this new nodes view. You could also do the same when clicking on an individual node add the graphic ring with compliance info along side the client run info ring.

**Comment by jonong1972** [comment]
@stromweld

> Love the combined look and simplicity of combining compliance and client run views. Is this going to be carried forward to the individual node as well when clicked? Simply adding a new tab next to attributes that shows the scan controls in a similar way the resources tab does would make things alot cleaner and more intuitive.
> 
> The node view you could also bring back the graphical ring from the client runs and add next to it the graphical ring from compliance view to get a quick overview of entire infrastructure status in this new nodes view. You could also do the same when clicking on an individual node add the graphic ring with compliance info along side the client run info ring.

Yes, there are designs for that, but not sure when it will get out. I am still working out concept, exploring different charts, etc for comparing all the data.

**Comment by rogueautomation** [comment]
I like the idea of combining the view - it's kind of rough looking at client run vs. compliance result pages separately.

**Comment by seththoenen** [comment]
I think combining "Client Runs" and "Compliance" tabs to have a unified view is going to make for a better user experience in the long run. Just yesterday I had to explain what the difference was in those two tabs to someone who is relatively new to Automate.

This might be a little bit outside of the scope of this particular topic, but one item that we struggle with is seeing what has caused client/infra runs to fail at scale. Our automate instance has 10,000+ nodes checking into it, so, naturally, when something fails it will fail across many nodes. If we see a spike in failed nodes, let's say an additional 50, the only way to know if all of those 50 are failing due to the same problem is to look into each node individually. The latest release of A2 has helped in this scenario with the ability to filter based on `Error`, but having aggregation for each error would assist in determining where we need to focus on resolving failed client/infra runs.

**Comment by vjeffrey** [comment]
@jonong1972 are there more finalized designs that account for the feedback given in the issue that you could post?  
that way i can check if there's any remaining backend work to complete for this

**Comment by vjeffrey** [comment]
just cleaning up a bunch of old comments that have been addressed

**Comment by vjeffrey** [comment]
closing this; we'll be doing something for the ui, but it won't be this list ui. stay tuned!
