### ISSUE TITLE
Code coverage tool needs migration (front-end)

### ISSUE THREAD

**Issue by msorens** [chef/automate#4701]
## Describe the issue
automate-ui uses the `karma-coverage-istanbul-reporter` or generating code coverage reports. That package is deprecated, though, so we need to migrate to `karma-coverage`.

Note: Need to first investigate how and where this is being used in the system so that we can compare results before and after the migration.

## To Reproduce
From components/automate-ui run `make unit` and this warning appears:
```
'karma-coverage-istanbul-reporter' usage has been deprecated since version 11.
Please install 'karma-coverage' and update 'karma.conf.js.' 
For more info, see https://github.com/karma-runner/karma-coverage/blob/master/README.md
```

## Expected behavior
Using `karma-coverage` for code coverage.

**Comment by SEAjamieD** [comment]
From what I can gather It appears to me that this is, for all intents and purposes, the same as using `karma-coverage-istanbul-reporter`.  The main reasoning for moving away is that it was no longer being maintained appropriately for wide open source usage.  Either way, the migration has shown to be pretty straightforward.
