### ISSUE TITLE
Better tooltip and pop-up

### ISSUE THREAD

**Issue by apriofrost** [chef/automate#473]
## User Story

As an Automate application's page user, when I can see a tooltip bubble for an element with more information, I would like to be able to mouse over the text and click on the link if there is any.

## Current issue demo
![tooltip interaction demo](https://user-images.githubusercontent.com/9401459/58739093-651d7e00-83bd-11e9-820d-c3b4b8be611c.gif)

## Proposed solution
Creating two types of tooltips, named as tooltip and pop-up.

### Definition
Tooltip and Pop-up are similar components in that they provide informative content around an element when users hover over, focus on it. The element can be a button, an icon, a badge, etc. 

When the content only contains plain text, use a tooltip.
When then content contains any element that users can interact with, use a pop-up. 

### Example of Tooltip
![image](https://user-images.githubusercontent.com/9401459/60838377-66da1e80-a17f-11e9-8bda-8d4797c0b7e9.png)

#### Example 1.
![image](https://user-images.githubusercontent.com/9401459/60838391-76596780-a17f-11e9-8293-3533bafd255f.png)
#### Example 2.
<img src="https://user-images.githubusercontent.com/9401459/60838409-8113fc80-a17f-11e9-9206-9803ff5aca62.png" width="400">

### Accessibility
Add an `aria-describedby` or use the title attribute, so that info is accessible.
(https://inclusive-components.design/tooltips-toggletips/)

## Tooltip Design Specification
![image](https://user-images.githubusercontent.com/9401459/60838897-ae14df00-a180-11e9-9008-c7d543158aa5.png)

### Interactivity
When users hover over, focus on an element, show the tooltip. When users exit the hover or focus state, dismiss the tooltip.

## Pop-up Design Specification
![image](https://user-images.githubusercontent.com/9401459/60839032-06e47780-a181-11e9-9943-338b5238e948.png)

### Interactivity
When users hover over, focus on an element, show the pop-up. When users hover over or focus on the container, the pop-up should stay static to allow users to interact with the content. When users exit the hover or focus state, dismiss the pop-up.

## Mockup and design specification
https://chef.invisionapp.com/share/59SKVC0QUP4#/369503826_tooltip_And_Pop-Up

**Comment by apriofrost** [comment]
The tooltip needs style update after discussion in the UX team. We'd like to segment the current tooltip into two types: one simple tooltip with only text for further explanation; another pop-up tooltip with richer content (links, images, etc). In this case, we will use the pop-up version. More details to be added for the design spec.

**Comment by apriofrost** [comment]
The issue is updated with the latest description with the feedback mentioned above incorporated.

**Comment by SEAjamieD** [comment]
I think we may be able to consider this one complete.

There is not a separate component, but there is an attribute that can be passed in to `chef-tooltip` named "interactable" created by @scottopherson here: https://github.com/chef/automate/pull/3792

@apriofrost  -  what are your thoughts on this as opposed to a whole new component?

**Comment by apriofrost** [comment]
yes, I agree. Thanks @SEAjamieD !
