### ISSUE TITLE
Session Valid after Logout

### ISSUE THREAD

**Issue by vivekvardwaz** [chef/automate#4763]
**Issue description:**
After logging out of the application the server side session bearer token is still available on the server after logout.  For a period of time the session token can still be used after the user has logged out of the application.

**Expected Behaviour:**
When a user logs out of an application all authentication cookies and tokens need to be invalidated on the server immediately

**Comment by emo3** [comment]
Our security team found the following issue:
Risk: High
Corrective Action:
The application needs to invalidate the session ID after the idle timeout period of 20 minutes. This is typically done on the server.
Details:
The application uses session IDs that continue to be valid after 20 minutes. The cookie may be deleted at 20 minutes, but the ID can be reused.
Targets Affected:
Chef Automate
NIST Control=AC-12
Tech Mapping=CWE-613
Found on:
chef-automate version
Version: 2
CLI Build: 20210218020951
Server Build: 20210219171521

**Comment by kalroy** [comment]
This should be fixed with #5313
