### ISSUE TITLE
Delete or any update actions should not be accessible for viewer user role 

### ISSUE THREAD

**Issue by vsingh-msys** [chef/automate#4809]
## Describe the bug
- Automate infra views by default add/updates action should be accessible to admin/editor role only not for viewer user role.

## To Reproduce
- Login with admin user role.
-  Navigate to Infrastructure -> Chef Servers
-  `Add Chef Infra Server` and  `Add Chef organisation` records 
- Open another browser window
- Login automate with `viewer` user role.
- Navigate to Infrastructure -> Chef Servers 
-  In Chef Servers list select row "..." and "Delete" action is visible.
-  Click on delete chef server it raises an error similar for other operation like chef organization, roles, environments clients  etc.

## Expected behavior
- Login as `viewer` user role
- Navigate to Infrastructure -> Chef Servers 
- In Chef Servers list  option to delete under "..." should not be shown

## Screenshots

![Delete Org](https://user-images.githubusercontent.com/44496937/110490070-f3d43880-8115-11eb-8255-60eb81df57e7.png)

![Environment Delete](https://user-images.githubusercontent.com/44496937/110490406-4ada0d80-8116-11eb-9155-7fe726860aa5.png)

## Additional context
- Solution would be similar `Add Chef Server ` is being wrapped.
https://github.com/chef/automate/blob/57e53aba0da121f564f6428732e646e42476b5cc/components/automate-ui/src/app/modules/infra-proxy/chef-servers-list/chef-servers-list.component.html#L33-L35

## Definition of Done

- Developed according to UX wireframe/Requirement Document
- Demoed the feature to UX 
- Unit test cases (coverage at least 70%)
- Ensure compatibility with all supporting browser
- Smoke Testing is done
- All Review Comments are resolved
- At least 2 PR approvals required
- Code should pass and clear linting
- Code is Optimized/Refactored as necessary and observed
- Screen shot of the feature developed is provided in the issue
- Cypress Testing is included and covers all the scenarios.
- Documentation of the feature needs to be completed.
- Buildkite pipeline should be green

Aha! Link: https://chef.aha.io/epics/SH-E-298

**Comment by kalroy** [comment]
Closing as this is handled in User Management
