### ISSUE TITLE
Checking the health of added chef infra servers

### ISSUE THREAD

**Issue by vsingh-msys** [chef/automate#4812]
## User Story

- While adding the entry of Chef Infra Server into Automate Infra Views it would be adding the values to the user to validate the provided FQDN/IP Address is correct or not.
- Expose the Chef Infra Server https://docs.chef.io/server/api_chef_server/#_status

Response:

```
{
  "status": "pong",
  "upstreams":
    {
      "service_name": "pong",
      "service_name": "pong",
      ...
    }
  "keygen":
    {
      "keys": 10,
      ....
    }
 }

```

Aha! Link: https://chef.aha.io/epics/SH-E-305

**Comment by gscho** [comment]
Ran into this myself today. It seems you can add any FQDN and IP address you want without validation.
![Screen Shot 2021-03-24 at 9 28 30 AM](https://user-images.githubusercontent.com/3594838/112318747-c219b080-8c83-11eb-9269-634171789902.png)
