### ISSUE TITLE
[infra-proxy-service] retry all request of chef server API in case of failure

### ISSUE THREAD

**Issue by vsingh-msys** [chef/automate#4822]
## Describe the bug
- Chef Infra Server rest API is not much reliable to handle the request, in the knife tool we have added the retry options 5 times in cases API does not respond properly.

## To Reproduce
- While adding data into bulk sometimes expected objects not creating due to API does not respond reliably.

## Expected behavior
- In case of failure try at least 5 times to avoid API breakout.

Aha! Link: https://chef.aha.io/epics/SH-E-317

**Comment by kalroy** [comment]
We will handle it differently.
