### ISSUE TITLE
Date/Time Format: Global Time Settings

### ISSUE THREAD

**Issue by tarablack01** [chef/automate#4840]
Epic: https://github.com/chef/automate/issues/4745

## User Story
As a user, I want to globally set a time zone, that I want to be used across the application for my user session.

## Definition of Done
1. Provide a way to set the time zone in UI globally.
2. Default the time zone to UTC

Discussed options:
1. User’s preferences page
2. Config file
3. General settings

Aha! Link: https://chef.aha.io/epics/SH-E-330

**Comment by SEAjamieD** [comment]
@jong-progress - Do we have a list of which timezones we'd like to have in our dropdown list for the user to select from?  Technically we can do all of them, but I know a lot crossover each other and displaying 600 options probably isn't something we're planning to do.

**Comment by jong-progress** [comment]
@SEAjamieD Not really, we haven't really had any standard to work off of until now. Lets just start off with whatever coded component you use? does that come with a default list? and if people ask we can add in future.

**Comment by SEAjamieD** [comment]
> @SEAjamieD Not really, we haven't really had any standard to work off of until now. Lets just start off with whatever coded component you use? does that come with a default list? and if people ask we can add in future.

@jong-progress it doesn't come with a default list but I'll go through and populate at least one for each geographic area to start.

**Comment by kalroy** [comment]
Working on this in issues #5393 #5392
