### ISSUE TITLE
Arbitrary host header accepted

### ISSUE THREAD

**Issue by vivekvardwaz** [chef/automate#4850]
The application appears to be accessible using arbitrary  http Host headers. This is a serious issue if the application is not externally accessible or uses IP-based access restrictions. Attackers can use DNS Rebinding to bypass any IP or firewall based access restrictions that may be in place, by proxying through their target's browser. Note that modern web browsers' use of DNS pinning does not effectively prevent this attack. The only effective mitigation is server-side:  https://bugzilla.mozilla.org/show_bug.cgi?id=689835#c13. Additionally, it may be possible to directly bypass poorly implemented access restrictions by sending a Host header of 'localhost'

The bscan Scanner Report for this finding lists two sets of Request/Respsonse pairs.  In both cases, an error page was returned.  Nothing in the Response is highlighted or noted, only the generic 301 HTML repsonse:      HTTP/1.1 301 Moved Permanently   Server: nginx   Date: Thu, 29 Oct 2020 13:53:33 GMT   Content-Type: text/html   Content-Length: 162   Connection: close   Location: https://chefauto.abc.gov:443/      `<html>   <head><title>301 Moved Permanently</title></head>   <body>   <center><h1>301 Moved Permanently</h1></center>   <hr><center>nginx</center>   </body>   </html> `

The vulnerability will appear if there are security rules based on the host header.  A lot of times changing the host header to localhost will bypass rules that limit what IPs are allowed to interact the application.  To protect against the user changing the host header, the server should not allow a user to change the host header in the first place. It should error out, rather than the 301 redirect that is the normal action."

Aha! Link: https://chef.aha.io/epics/SH-E-336

**Comment by kalroy** [comment]
The load balancer currently redirects any request on port `80` and with Host Header set to `localhost` to the correct server url.


```
server {
    {{#if cfg.ngx.http.ipv6_supported ~}}
    listen [::]:{{ cfg.service.http_port }} ipv6only=off;
    {{else ~}}
    listen {{ cfg.service.http_port }};
    {{/if ~}}
    server_name {{ cfg.service.external_fqdn }};
    # TODO: I hate redirecting to https://host:443/ but handlebars has its limits :(
    return 301 https://$server_name:{{ cfg.service.https_port }}$request_uri;
  }
```
Although we can see the issue but we need to understand how to reproduce it? Getting a curl command to hit the server which will return 301 and redirect would be the ideal way to go ahead.

**Comment by kalroy** [comment]
We have added the logic to check if the configured fqdn entry is matching the value in host header for http request. For https, the validation is based on CN associated with the certificate and the header should match the CN. We consider having a proper CN in the certificates is a fundamental requirement.
