### ISSUE TITLE
Browser cross-site scripting filter misconfiguration

### ISSUE THREAD

**Issue by vivekvardwaz** [chef/automate#4851]
Cross-site scripting (XSS) filters in browsers check if the URL contains possible harmful XSS payloads and if they are reflected in the response page. If  such a condition is recognized, the injected code is changed in a way, that it is not executed anymore to prevent a succesful XSS attack. The downside of these filters         is, that the browser has no possibility to distinguish between code fragments which were reflected by a vulnerable web application in an XSS attack and these which are         already present on the page. In the past, these filters were used by attackers to deactivate JavaScript code on the attacked web page. Sometimes the XSS filters itself are vulnerable in a way, that web applications which were protected properly against XSS attacks became vulnerable under certain conditions. It is considered as better practice to instruct the browser XSS filter to never render the web page if an XSS attack is detected.

No X-XSS-Protection header was set in the response. This means that the browser uses default behavior that detection of a cross-site scripting attack never prevents rendering.

All 8 occurrences of this finding were on a Error page (in this case, 301).
Need to add HTTP Security Headers to Error Pages.

Aha! Link: https://chef.aha.io/epics/SH-E-337

**Comment by kalroy** [comment]
We definitely need to know how to reproduce it in local. 

But having said it, we can add the header to `301` redirection in the nginx server block below:
```
server {
    {{#if cfg.ngx.http.ipv6_supported ~}}
    listen [::]:{{ cfg.service.http_port }} ipv6only=off;
    {{else ~}}
    listen {{ cfg.service.http_port }};
    {{/if ~}}
    server_name {{ cfg.service.external_fqdn }};
    # TODO: I hate redirecting to https://host:443/ but handlebars has its limits :(
    return 301 https://$server_name:{{ cfg.service.https_port }}$request_uri;
  }
```
like this:
```
add_header x-xss-protection "1; mode=block" always;
```

**Comment by kalroy** [comment]
Hit http://a2-dev.test and check the network tab for 301

**Comment by Venkatesh-rengasamy** [comment]
@kalroy 
Code changes are tested. "x-xss-protection" added in response header. FYI - Response header of http://localhost, it redirects to https://a2-dev.test. 

> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Server: nginx
< Date: Wed, 07 Jul 2021 12:44:44 GMT
< Content-Type: text/html
< Content-Length: 162
< Connection: keep-alive
< Location: https://a2-dev.test:443/
< Strict-Transport-Security: max-age=63072000; includeSubDomains
< x-xss-protection: 1; mode=block
< X-Content-Type-Options: nosniff

**Comment by Venkatesh-rengasamy** [comment]
Added x-xss-protection in Response header #5286
