### ISSUE TITLE
Content Sniffing not disabled

### ISSUE THREAD

**Issue by vivekvardwaz** [chef/automate#4852]
There was no "X-Content-Type-Options" HTTP header with the value nosniff set in the response. The lack of this header causes that certain browsers,  try to determine the content type and encoding of the response even when these properties are defined correctly. This can make the web application vulnerable against Cross-Site Scripting (XSS) attacks. E.g. the Internet Explorer and Safari treat responses with the content type text/plain as HTML, if they contain HTML tags.

Set the following HTTP header at least in all responses which contain user input: X-Content-Type-Options: nosniff

All 9 occurrences of this finding were on a Error page (in this case, 301). Need to add HTTP Security Headers to Error Pages.

Aha! Link: https://chef.aha.io/epics/SH-E-338

**Comment by kalroy** [comment]
We definitely need to know how to reproduce it in local. 

But having said it, we can add the header to `301` redirection in the nginx server block below:
```
server {
    {{#if cfg.ngx.http.ipv6_supported ~}}
    listen [::]:{{ cfg.service.http_port }} ipv6only=off;
    {{else ~}}
    listen {{ cfg.service.http_port }};
    {{/if ~}}
    server_name {{ cfg.service.external_fqdn }};
    # TODO: I hate redirecting to https://host:443/ but handlebars has its limits :(
    return 301 https://$server_name:{{ cfg.service.https_port }}$request_uri;
  }
```
like this:
```
add_header X-Content-Type-Options "nosniff" always;
```

**Comment by kalroy** [comment]
Hit http://a2-dev.test and check the response for `X-Content-Type-Options` header

**Comment by Venkatesh-rengasamy** [comment]
@kalroy 
Code changes are tested. "x-content-type-options" added in response header. FYI - screenshot.

**Comment by Venkatesh-rengasamy** [comment]
Added x-content-type-options in Response header #5286
