### ISSUE TITLE
Database Error Pattern Found

### ISSUE THREAD

**Issue by vivekvardwaz** [chef/automate#4854]
Replication steps:
1) Cookie WASPostParam added to request:
GET /dex/approval?req=etsk5jfjfq2ao7s2pfthls72m HTTP/1.1

2) Cookie session removed from request: DNZkSRHfXF_8ahtRkdNXcG08Nny__79LmjsEUUq4vgY
Parameter req manipulated from: rnmq6p7efw35k6243lfz7yp7e to:
/../../../../../../../../../../../../boot.ini%00.html

3) Parameter req manipulated from: wfjx3m3p6nbg54dnrebfyvjmr to: ProbePhishing

In all 3 cases, the Response included:
<h2 class="theme-heading">Internal Server Error</h2>
<p>Database error.</p>

This suggests that the test managed to bypass any application input filtering and reach the database. Need to sanitize hazardous characters correctly on user input

Aha! Link: https://chef.aha.io/epics/SH-E-340

**Comment by kalroy** [comment]
- We should be returning more appropriate error message.
-  We will check how to validate the input.
