### ISSUE TITLE
Missing or insecure "Content-Security-Policy" header

### ISSUE THREAD

**Issue by vivekvardwaz** [chef/automate#4856]
The "Content-Security-Policy" header is designed to modify the way browsers render pages, and thus to protect from various cross-site injections, including Cross-Site Scripting. It is important to set the header value correctly, in a way that will not prevent proper operation of the web site. For example, if the header is set to prevent execution of inline JavaScript, the web site must not use inline JavaScript in it's pages.

To protect against Cross-Site Scripting, Cross-Frame Scripting and clickjacking, it is important to set the following policies with proper values:
Both of 'default-src' and 'frame-ancestors' policies, *OR* all of 'script-src', 'object-src' and 'frame-ancestors policies.
For 'default-src', 'script-src' and 'object-src', insecure values such as '*', 'data:', 'unsafe-inline' or 'unsafe-eval' should be avoided.
For 'frame-ancestors', insecure values such  as '*' or 'data:' should be avoided.

Configure your server to send the "Content-Security-Policy" header.

For Apache, see:
http://httpd.apache.org/docs/2.2/mod/mod_headers.html

For IIS, see:
https://technet.microsoft.com/pl-pl/library/cc753133%28v=ws.10%29.aspx

For nginx, see:
http://nginx.org/en/docs/http/ngx_http_headers_module.html
Need to add the HTTP Content-Security-Policy response header

Aha! Link: https://chef.aha.io/epics/SH-E-342

**Comment by kalroy** [comment]
We will test by setting header in the nginx configuration:
`add_header Content-Security-Policy "frame-ancestors 'self';"`
`add_header Content-Security-Policy "default-src 'self';"`

**Comment by kalroy** [comment]
As per the latest discussion, the `Content-Security-Policy` will be enabled as per configuration in `config.toml`. This may not work for SAML users. The doc should explicitly mention that.

**Comment by kalroy** [comment]
Content Security Policy header is not enabled by default.
It can be enabled in Automate by patching the following configuration

[load_balancer.v1.sys.ngx.http]
  enable_csp_header = true
