### ISSUE TITLE
Missing or insecure "X-Content-Type-Options" header

### ISSUE THREAD

**Issue by vivekvardwaz** [chef/automate#4857]
The "X-Content-Type-Options" header (with "nosniff" value) prevents IE and Chrome from ignoring the content-type of a response.
This action may prevent untrusted content (e.g. user uploaded content) from being executed on the user browser (after a malicious naming, for example).

Configure your server to send the "X-Content-Type-Options" header with value "nosniff" on all outgoing requests.

For Apache, see:
http://httpd.apache.org/docs/2.2/mod/mod_headers.html

For IIS, see:
https://technet.microsoft.com/pl-pl/library/cc753133%28v=ws.10%29.aspx

For nginx, see:
http://nginx.org/en/docs/http/ngx_http_headers_module.html
Add the "X-Content-Type-Options" header (with "nosniff" value)

Aha! Link: https://chef.aha.io/epics/SH-E-343

**Comment by kalroy** [comment]
Automate is set to pass this header in all the responses:
`add_header X-Content-Type-Options "nosniff" always; `

Is there any request response which does not have the header?

**Comment by kalroy** [comment]
/automate.conf.js is the route to check this

**Comment by Venkatesh-rengasamy** [comment]
@kalroy 
Code changes are tested. "x-content-type-options" added in response header. Please see the screenshot FYI.

![Screenshot from 2021-07-07 11-23-50](https://user-images.githubusercontent.com/84014872/124706996-d7a2a580-df15-11eb-819f-be921091f9e2.png)

**Comment by Venkatesh-rengasamy** [comment]
Added x-content-type-options in Response header #5286
