### ISSUE TITLE
Missing or insecure "X-XSS-Protection" header

### ISSUE THREAD

**Issue by vivekvardwaz** [chef/automate#4858]
The "X-XSS-Protection" header with value '1' forces the Cross-Site Scripting filter into Enable mode, even if disabled by the user.

This filter is built into most recent web browsers (IE 8+, Chrome 4+), and is usually enabled by default. Although it is not designed as first and only defense against Cross-Site Scripting, it acts as an additional layer of protection.

Configure your server to send the "X-XSS-Protection" header with value "1" (i.e. Enabled) on all outgoing requests.

For Apache, see:
http://httpd.apache.org/docs/2.2/mod/mod_headers.html

For IIS, see:
https://technet.microsoft.com/pl-pl/library/cc753133%28v=ws.10%29.aspx

For nginx, see:
http://nginx.org/en/docs/http/ngx_http_headers_module.html

Add the HTTP X-XSS-Protection response header

Aha! Link: https://chef.aha.io/epics/SH-E-344

**Comment by kalroy** [comment]
Nginx is configured to set the header and should respond with every header:
`    add_header x-xss-protection "1; mode=block" always;`

Is there any particular request where we can see the behavior?

**Comment by kalroy** [comment]
/automate.conf.js is the route to check

**Comment by Venkatesh-rengasamy** [comment]
@kalroy 
Code changes are tested. "x-xss-protection" added in response header. Please see the screenshot FYI.

![Screenshot from 2021-07-07 11-20-40](https://user-images.githubusercontent.com/84014872/124706729-64009880-df15-11eb-872a-ddc5fcf937df.png)

**Comment by Venkatesh-rengasamy** [comment]
Added x-xss-protection in Response header #5286
