### ISSUE TITLE
Missing or insecure HTTP Strict-Transport-Security Header

### ISSUE THREAD

**Issue by vivekvardwaz** [chef/automate#4859]
HTTP Strict Transport Security (HSTS) is a mechanism which protects secure (HTTPS) websites from being downgraded to non-secure HTTP. This mechanism enables web servers to instruct their clients (web browsers or other user agents) to use secure HTTPS connections when interacting with the server, and never use the insecure HTTP protocol.

It is important to set the 'max-age' to a high enough value to prevent falling back to an insecure connection prematurely.

The HTTP Strict Transport Security policy is communicated by the server to its clients using a response header named "Strict-Transport-Security". The value of this header is a period of time during which the client should access the server in HTTPS only. Other header attributes include "includeSubDomains" and "preload".

Aha! Link: https://chef.aha.io/epics/SH-E-345

**Comment by kalroy** [comment]
Nginx is configured as :
`add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;`

Is there any particular instance the header is not included?

**Comment by kalroy** [comment]
Hit automate.conf.js

**Comment by Venkatesh-rengasamy** [comment]
@kalroy 
Code changes are tested. "strict-transport-security" added in response header. FYI - screenshot.

![Screenshot from 2021-07-07 16-42-12](https://user-images.githubusercontent.com/84014872/124780287-1a896b00-df60-11eb-92bd-3879f8f2f005.png)

**Comment by Venkatesh-rengasamy** [comment]
Added Strict-Transport-Security in Response header #5286
