### ISSUE TITLE
Telemetry is failing to send due to CORS errors

### ISSUE THREAD

**Issue by tas50** [chef/automate#4903]
## Describe the bug

At least for a new demo installation of Automate telemetry data is not being sent due to CORS errors in the application.

## To Reproduce

Steps to reproduce the behavior: - Install automate - Login - Check the network console in your browser's dev tools

## Expected behavior

Telemetry data should be sent

## Screenshots

[https://user-images.githubusercontent.com/1015200/113443292-875ff880-93a6-11eb-9a53-bee95c8ed2e5.png](https://user-images.githubusercontent.com/1015200/113443292-875ff880-93a6-11eb-9a53-bee95c8ed2e5.png)

## Versions (please complete the following information):

- OS: macOS 11
- Browser: Firefox and Chrome
- Automate Build Number: 20210324172345

Aha! Link: https://chef.aha.io/epics/SH-E-369

**Comment by tas50** [comment]
This change lines up with the time we stopped getting telemetry data from customers: https://github.com/chef/automate/commit/baa64657033a7aa5f9972e201b60ed4912dad30c

**Comment by SEAjamieD** [comment]
Note: The specific point of failure is happening when we attempt to get the api keys from Segment.
https://github.com/chef/automate/blob/6e80bd9328a8aae17fa5fab8df7e64beebbb48f2/components/automate-ui/src/app/services/telemetry/telemetry.service.ts#L267-L270

**Comment by SEAjamieD** [comment]
> This change lines up with the time we stopped getting telemetry data from customers: [baa6465](https://github.com/chef/automate/commit/baa64657033a7aa5f9972e201b60ed4912dad30c)

@tas50 - Appreciate you sharing this file change.  Given when this change is made, I think the failure is unrelated to the change attached, however it helped lead to the same date as a change in Chrome at the exact same time: https://bugs.chromium.org/p/chromium/issues/detail?id=1014207

**Comment by tas50** [comment]
Oh yep that'd do it. Can we get a referrer header set to allow this then?

**Comment by SEAjamieD** [comment]
@tas50 working on it now 👍  - I think that should solve it

**Comment by kalroy** [comment]
A solution can be to call the /segment/api_keys from the backend instead of the UI. CORS is a browser feature which makes sure requests across origins can be made in secured and authorized way.

This branch talks about the same by moving the call to the backend:
https://github.com/chef/automate/tree/kallol/fix_telemetry_cors

The next step would be to make changes in UI to use the api data and verify data flowing into Segment.

**Comment by tas50** [comment]
While there is value in sending *additional* telemetry data from the backend a very large number of automate clusters are heavily firewalled or do not have access to the Internet so we can't make this our primary telemetry sending setup. This was setup on the client side out of necessity and needs to stay that way.

**Comment by kalroy** [comment]
This setup is to get the `segment api_key` from the telemetry server. The telemetry data will be still pushed by UI from the client side. Having said that, if the backend is in a heavily firewalled environment it won't get the key too.

**Comment by tas50** [comment]
That's not a solution we can take then. Our data shows nearly half of the Automate servers cannot contact the Internet.

**Comment by tas50** [comment]
I'm not sure I see the value in collecting data for 50% of our customers.  Telemetry needs to always be built with the assumption that the server cannot get to the Internet and our goal as an organization is to collect data on nearly 100% of data where enabled. We cannot create solutions that won't get us to that goal.

**Comment by Venkatesh-rengasamy** [comment]
@kalroy @vinay033 
This issue is fixed and able to get response data from telemetry services.

**Comment by kalroy** [comment]
This issue is fixed. But there are some other issues in Automate which needs to be fixed for the Telemetry to work seamlessly. We are tracking those issues here:
https://github.com/chef/automate/issues/5271

So closing this issue as CORS issue is fixed.
