### ISSUE TITLE
Add the External Load Balancer

### ISSUE THREAD

**Issue by punitmundra** [chef/automate#4932]
Will try setting up Lb using haproxy and nginx .

Aha! Link: https://chef.aha.io/epics/SH-E-249

**Comment by punitmundra** [comment]
We have to set up the external Load balance instead of the standard one. 
Setting up the external LB, we need to document the steps for documentation.

**Comment by FaizanSRE** [comment]
I have setup our own LB using haproxy and its working fine .And below is the configuration file used.
![configuration of Haproxy ](https://user-images.githubusercontent.com/60912283/114130504-55a6de80-991e-11eb-8ef8-a81354940064.png)

**Comment by punitmundra** [comment]
As a external LB we will try with HA and Nginx

**Comment by FaizanSRE** [comment]
Tried nginx as a LB  and the configuration will look like ![configuration of nginx.png](https://images.zenhubusercontent.com/5e4e272973431a684370fef0/dc5dd5db-30e2-404c-9116-e9aec843ece5)

**Comment by FaizanSRE** [comment]
Doc: https://progresssoftware.sharepoint.com/:w:/s/ChefCoreC/Ecya84U819tLsvT3zmyrA7gBKjfjPHKXqpaM50YeUIdDSg?e=VXfD1S
https://progresssoftware.sharepoint.com/:w:/s/ChefCoreC/Ednqh8RimdtFrIltdoibphsBk05_RqvNb-qtZ5iYDN5I3A?e=wYp40V
