### ISSUE TITLE
Show Warning Banner on Login

### ISSUE THREAD

**Issue by kalroy** [chef/automate#4934]
#### Feature
Customers are required to have a warning banner where they can state a custom message that displays information about the system the user is logging into such as the kind of information that can be put into the system (ie data classifications).

#### Expectations
1. The banner needs to be shown before the user logs in.
3. The user should be able to set the message to be shown on the banner.
4. The environment should determine the colour of the ribbon at the top of the banner.
5. These should be part of the configurations.

#### Related
More details can be found in the AHA idea: https://chef.aha.io/ideas/ideas/A2-I-92
Disclosure splash page: https://github.com/chef/automate/issues/4974

Aha! Link: https://chef.aha.io/epics/SH-E-250

**Comment by SEAjamieD** [comment]
Updated expectations to include that the text warning should be done as a splash page, not a popup.
