### ISSUE TITLE
Infra views requiring the IP of the chef server breaks many use cases

### ISSUE THREAD

**Issue by tas50** [chef/automate#4945]
## Describe the bug

We currently require both the FQDN and the IP address of the chef server. This is really problematic for two different types of users:

1) User with multiple chef front ends behind an ELB where the underlying IP addresses change frequently
2) User that wants to be able to use DNS to migrate from 1 chef server to another or to failover to a new node they restore from a backup

## To Reproduce

- Log into Automate
- Go to Infrastructure Tab
- Click Chef Server
- Click Add Chef Server

## Expected behavior
Only the FQDN should be required

## Screenshots
![image](https://user-images.githubusercontent.com/1015200/114216889-5d658380-991c-11eb-9ddc-1426267ce257.png)

## Versions (please complete the following information):
- OS: macOS 11
- Browser: Firefox
- Automate Build Number: 20210324172345

Aha! Link: https://chef.aha.io/epics/SH-E-261

**Comment by rgjoshi24** [comment]
@AnkurMundhra , do you have any updates on this? We have customers wanting to know any update.

**Comment by AnkurMundhra** [comment]
This has been tagged as an improvement on existing Infra Server views. Can be evaluated after the on-going planned activity on Infra Server view is complete.
