### ISSUE TITLE
Chef Automate server not able to reach AWS api via proxy

### ISSUE THREAD

**Issue by kalroy** [chef/automate#4958]
## Describe the bug
Chef Automate server when configured in a private cloud environment has outbound internet access via proxy. While setting up compliance scans for AWS, Automate is not able to connect to the AWS

Error:
``
Error details in compliance scan:
Failed to open TCP connection to iam.amazonaws.com:443 (Connection refused - connect(2) for "iam.amazonaws.com" port 443).
``

Customer Bug Issue:
[233](https://github.com/chef/customer-bugs/issues/233)

## To Reproduce
- Setup Automate in airgapped environment
- Setup a proxy and configure
- Try to setup compliance scan

## Expected behavior
The compliance scan should run properly

## Additional context

Aha! Link: https://chef.aha.io/epics/SH-E-267

**Comment by vivek-yadav** [comment]
https://github.com/chef/automate/pull/5905 resolved in this PR
