### ISSUE TITLE
allow the suppression of the license expiration warning in the web UI

### ISSUE THREAD

**Issue by karlamrhein** [chef/automate#496]
I am the admin/operator of our chef-automate server.  I use the web UI several times per day.

i am well aware that i have the annual chef renewal, and my chef account rep is working on it.  also, it will take a long time for the purchase to make its way through our org, and i don’t want to see this and click to close it several times per day for the next 80 days.

can we have a flag file to touch to suppress this warning?  or a snooze button?  or a config option?  

i am wincing at the prospect of looking at this, and then clicking to close, 3-5 times per day for the next 80 days.    

thank you for all your work on an excellent product!!!!

**Comment by susanev** [comment]
Thanks for creating an issue @karlamrhein and sharing some of your pains!

We will discuss some of the details on improving this user experience with our product and user experience folks and get back to you soon.

**Comment by karlamrhein** [comment]
Thank you so much!  

I'm searching through the source code because I would have loved to do a PR instead of an issue, but at least wanted to get my request out there.  if i find the code i'll see if i can do a PR.

**Comment by msorens** [comment]
In the interests of helping minimize your pain, @karlamrhein , until we get to it you could take a look at `expiringSoonMessage` in license.effects.ts to do your own patch.

**Comment by karlamrhein** [comment]
Thanks for letting me know about that!

Karl

**Comment by sdelano** [comment]
Notes from triage meeting:
- often times the users that are seeing this message are not the ones that can actually impact the speed of the license renewal

Technical notes:
- feels similar in scope to the welcome modal issues that we're trying to fix

**Comment by susanev** [comment]
converted to [Aha idea](https://chef-software.ideas.aha.io/ideas/A2-I-113).
feel free to add your vote or more user needs there.
