### ISSUE TITLE
UI_Improvements_In_Edit_mode

### ISSUE THREAD

**Issue by chaitali-mane** [chef/automate#4964]
## Describe the bug
- [x] Environment & Clients & Databag Item Create Button is not vertically aligned
- [x]  In Acceptance the font styles are not loading in Environment
- [x]  Environments Cookbook Constraints - Hover on edit button needs to be the light blue, and its overlapping the line.
- [x]  Form elements when they have focus - have a blue border.
- [x]  Databag > Databag Item: when there are no data bag items, reduce the top margin (approximately "top-margin: 5%)
- [x]  In some cases, when creating a data bag item, it doesnt show up?
- [x]  Databag Item > Delete link should be secondary button with the hover of the blue background.
- [x]  Delete modal dialuge text needs to be updated
- [x]  Client Details: Tab bottom border needs to match the other tabs
- [x]  Client Details - reset key - button needs to match styles. (after the click the border remains)
- [x] invalid admin  key message

**Comment by himanshi-chhabra** [comment]
Closing these issues , created different issues from this and added to epic #4965
