### ISSUE TITLE
AzureRM VM node integration unable to discover host 

### ISSUE THREAD

**Issue by kalroy** [chef/automate#4971]
## Describe the bug
After adding the Node Integration, Chef Automate is able to discover all the Virtual Machines in Azure subscription, but it cannot resolve the hostname or network information of the Virtual Machines.

When I try to add the credentials, I get a connect error:
STDERR: Client error, can't connect to 'winrm' backend: You must provide a value for "host".

When I inspect the nodes in Chef Automate, I can see the Host field has a placeholder "hostname". It seems that Chef Automate is not picking out the fqdn or IP address.

## To Reproduce
- Login to Chef Automate
- Go to Settings
- Go to Node Integrations
- Add AzureRM VM Integration
- Go to Compliance
- View VMs

## Expected behavior
Chef Automate automatically adds nodes that can be contacted for compliance scans without any further configuration.

## Additional context
https://github.com/chef/customer-bugs/issues/272

Aha! Link: https://chef.aha.io/epics/SH-E-276

**Comment by vivek-yadav** [comment]
We see this is not an issue, and is working fine if we have WinRM running properly on the Windows Machine.
Ports 3389(RDP), 80(HTTP), 443(HTTPS), 5985(WinRM) and 5986(WinRM) must be open and reachable from Chef Automate.

Use the below script to configure WinRM:
```powershell
winrm quickconfig -q
winrm create winrm/config/Listener?Address=*+Transport=HTTP
winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="1024"}'
winrm set winrm/config '@{MaxTimeoutms="1800000"}'
winrm set winrm/config/winrs '@{MaxShellsPerUser="50"}'
winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="1024"}'
winrm set winrm/config/service '@{AllowUnencrypted="true"}'
winrm set winrm/config/service/auth '@{Basic="true"}'
netsh advfirewall firewall add rule name="WinRM 5985" protocol=TCP dir=in localport=5985 action=allow
netsh advfirewall firewall add rule name="WinRM 5986" protocol=TCP dir=in localport=5986 action=allow
NetSh Advfirewall set allprofiles state off
net stop winrm
sc.exe config winrm start=auto
net start winrm
```
