### ISSUE TITLE
Session Fixation issue in Automate

### ISSUE THREAD

**Issue by kalroy** [chef/automate#4973]
## Describe the bug
Session Fixation: WebInspect has found a session fixation vulnerability on the site. Session fixation allows an attacker to impersonate a user by abusing an authenticated session ID (SID). This attack can occur when a web application: Fails to supply a new, unique SID to a user following a successful authentication. Allows a user to provide the SID to be used after authenticating.

## To Reproduce
-

## Expected behavior
A description of what you expected to happen.

## Additional context

Aha! Link: https://chef.aha.io/epics/SH-E-278

**Comment by Abdul-Az** [comment]
We are renewing SID every minute after successful login.

**Comment by kalroy** [comment]
Closing as per @Abdul-Az issue above.
