### ISSUE TITLE
Infra views with bad client key spins forever in roles / environments

### ISSUE THREAD

**Issue by tas50** [chef/automate#4989]
## Describe the bug
In the infra views feature if you try to view the roles or environment data with an invalid client key you get a warning that appears, but the role and environment spinners continue to load forever. In other views they prompt you to reset your admin key.

## To Reproduce

- Reset your client key on the Chef Infra Server so automate has an invalid key
- Go to the Infrastructure tab
- Click Chef Infra Servers
- Click Roles
- Notice it spins forever

## Expected behavior

- It should stop spinning and tell you to update your key

## Screenshots
![image](https://user-images.githubusercontent.com/1015200/116030763-2d52fb80-a611-11eb-8bdf-7f2d2d501c11.png)

## Versions (please complete the following information):
- OS: macOS
- Browser: Firefox 89
- Automate Build Number: 20210406040048

**Comment by kalroy** [comment]
This issue is acceptance currently and will be part of the 26th April Release.

**Comment by tas50** [comment]
This does appear to be fixed now
