### ISSUE TITLE
Reset Admin key button in Infra Views does nothing / wording is wrong

### ISSUE THREAD

**Issue by tas50** [chef/automate#4990]
## Describe the bug
If you have an invalid client key in infra views and you try to view cookbooks you receive a prompt that you need to reset your admin key. This is wrong on two levels. First off the bottom just load a blank page. Second, the suggestion action here doesn't make sense. You're not resetting the key. If the key that Automate has is wrong then you are updating the admin client key, not resetting the admin key. We need to make sure these words match what a user is familiar with in the Chef Infra Server and our docs. 

![image](https://user-images.githubusercontent.com/1015200/116031393-6d66ae00-a612-11eb-8e7c-7412017291d6.png)

## To Reproduce
- Setup a Chef Infra Server in the infra views
- Reset the client key on the Infra Server
- Try to view the cookbooks for that org
- Click the "Reset Admin Key" button
- Blank page

## Expected behavior

When a user gets into this situation we should help them update the key they use to talk to the server. We should better explain what's happened here as well.

## Screenshots
Blank page after clicking the button

<img width="987" alt="image" src="https://user-images.githubusercontent.com/1015200/116031554-c46c8300-a612-11eb-94fc-1faacda1e872.png">

## Versions (please complete the following information):
- OS: macOS
- Browser Firefox 89
- Automate Build Number: 20210406040048

Aha! Link: https://chef.aha.io/epics/SH-E-292

**Comment by tas50** [comment]
Also because of this bug if the client key gets reset there's no way to get Automate infra views working again other than deleting the org and creating it again.

**Comment by kalroy** [comment]
Hi @tas50 
The issue fix is in acceptance currently and you should be able to check the latest behavior.
The fix removes this button from the screen as 
- The `Reset Admin Key` is not the current wording
- The Tab for `Reset Admin Key` is behind feature flag which we do not want to make available before more considerations.

You can try it out in
https://a2-cs-single-local-inplace-upgrade-acceptance.cd.chef.co/

**Comment by kalroy** [comment]
As of now, we do not have a way to reset the key and one needs to delete and add the organization again. 
This will be possible when we will have the reset admin key feature available.

**Comment by kalroy** [comment]
This was fixed.
