### ISSUE TITLE
Delete organization modal incorrectly capitalizes org names

### ISSUE THREAD

**Issue by tas50** [chef/automate#4993]
## Describe the bug
org names are case sensitive and we should not be capitalizing them for display. The mode to delete an org is capitalizing the org names.

## To Reproduce
- Click the infrastructure tab
- Click Chef Infra Servers
- Select your server
- Click the ... of the org to delete and click delete

## Expected behavior
Lowercase name

## Screenshots
![Screen Shot 2021-04-26 at 8 31 59 AM](https://user-images.githubusercontent.com/1015200/116111097-2bb62180-a66b-11eb-90ee-82d32b98ec43.png)

## Versions (please complete the following information):
- OS: macOS
- Browser Firefox
- Automate Build Number 20210420090302

Aha! Link: https://chef.aha.io/epics/SH-E-296

**Comment by chaitali-mane** [comment]
This issue is not reproducible. Closing issue.
![delete-org](https://user-images.githubusercontent.com/71449322/140695816-044c8a54-9fe4-460f-aed1-e706b37f5292.png)
