### ISSUE TITLE
Data bag create in infra views allows for invalid names

### ISSUE THREAD

**Issue by tas50** [chef/automate#4996]
## Describe the bug
Data bag names are validated under the hood to prevent invalid names from being saved. It doesn't appear that Automate is performing this validation and instead fails with a cryptic message to the user.

## To Reproduce
- Click the infrastructure tab
- Click Chef Infra Servers
- Select your server
- Select your org
- Select data bags
- Select Create Data Bag
- Enter name with space like "foo bar"

## Expected behavior
I should get a validation error directly in the modal that explains what values are allowed

## Screenshots
Error thrown post create:

![Screen Shot 2021-04-26 at 8 56 05 AM](https://user-images.githubusercontent.com/1015200/116114010-d62f4400-a66d-11eb-8803-c60edd5745af.png)

CLI behavior that is still terrible:
![Screen Shot 2021-04-26 at 8 56 14 AM](https://user-images.githubusercontent.com/1015200/116114036-dcbdbb80-a66d-11eb-8f3b-c1965ca5ccc9.png)

## Versions (please complete the following information):
- OS: macOS
- Browser Firefox
- Automate Build Number 20210420090302

**Comment by himanshi-chhabra** [comment]
We are facing this issue inside every create modal (Role/ Environment/ Client/ Data bag/ Data bag item ) so we have already created this issue and working on that #4960

**Comment by tas50** [comment]
Closing it as a dupe then.
