### ISSUE TITLE
Drodpdown css of mat-select inside Run list is overriding css of Delete Drodown

### ISSUE THREAD

**Issue by himanshi-chhabra** [chef/automate#5027]
## Describe the bug
When we open create role pop-up and cancel it then we open the delete role dropdown we see there is a margin-top added and overrides the delete dropdown CSS.
## To Reproduce
1. Steps for Role tab: 
  -  Go To  Infrastructure -> Chef Servers -> click server name->  click org name -> Go to Role tab 
  - click `...`  -> opens a dropdown -> ```there's no gap from top```.
  - Click create role -> add name , description -> click runlist -> click cancel.
  -  Again click `...`  -> opens a dropdown -> ```gap added```

## Expected behavior
The components should not override other components and the gap should not be added.
## Screenshots

https://user-images.githubusercontent.com/61003053/117046447-5587dc00-ad2e-11eb-9232-079392e2986f.mp4

Aha! Link: https://chef.aha.io/epics/SH-E-334

**Comment by vinay033** [comment]
Issue is Fixed.
