### ISSUE TITLE
Editing encrypted data bags will destroy them

### ISSUE THREAD

**Issue by tas50** [chef/automate#5045]
## Describe the bug
We need to not allow users to edit encrypted data bags in their raw format. These data bags can't be edited without the encrypted data bag secret and messing with the encrypted data will destroy the data bag.

## To Reproduce
- Infrastructure -> Chef Infra Servers
- Select the server
- Select the org
- Click data bags
- Select a data bag with an encrypted data bag item
- Select the encrypted data bag items
- Click edit

## Expected behavior
Edit shouldn't be a button on encrypted data bags until we come up with a plan for handling that.

## Screenshots
![image](https://user-images.githubusercontent.com/1015200/117358772-64c07400-ae6b-11eb-882a-01a59750a291.png)

## Versions (please complete the following information):
- OS: macos
- Browser: Firefox
- Automate Build Number: 20210504113343

**Comment by kalroy** [comment]
UX behavior:
1. Don't show the edit button. 
2. Put a note (icon) to identify an encrypted data bag

**Comment by kalroy** [comment]
Question to clear:
How to identify an encrypted data bag?

**Comment by tas50** [comment]
The data bag will included the "cipher" and "encrypted_data" values in the hash if it's encrypted. There may also be a way to identify it via the API, but I'm not sure about that part.
