### ISSUE TITLE
Infra Node view showing incorrect node organizations

### ISSUE THREAD

**Issue by tas50** [chef/automate#5093]
## Describe the bug
The last character of the "Chef Organization" in a node detail page is missing

## To Reproduce
- Click Infrastructure Tab
- Click Chef Infra Servers
- Click the server name
- Click the org name
- Click the nodes tab
- Select a node

## Expected behavior
The correct org name should be displayed

## Screenshots
This should be "tim_smith" not "tim_smit"

![image](https://user-images.githubusercontent.com/1015200/119373079-e0dcf900-bc6c-11eb-9e2c-1b3523877fca.png)

## Versions (please complete the following information):
- OS: macOS
- Browser Firefox
- Automate Build Number 20210518101414

**Comment by chaitali-mane** [comment]
This issue is not reproducible. Closing.
