### ISSUE TITLE
Backup & Restore for HA Cluster

### ISSUE THREAD

**Issue by punitmundra** [chef/automate#5103]

**Comment by punitmundra** [comment]
This backup and restore is for Automate
### Acceptance Criteria
- Need the list of config, credentials files or toml file which are getting store to the automate locally  
- 
### Definition of Done
- Find all the Info which are creating a backup in automate in Cluster mode.
- As per Info we backing up PG, ES and config. 

### Testing
- run the backup command via automate

**Comment by meet58** [comment]
Automate backup command is taking backup of all the services including config.toml file and any custom change. All the services backup is stored under pg_data directory. For all the files individual directory will be created. PostgreSQL backups/restores are handled via chef-automate backup create/restore and doesn't require additional configuration. And for elasticsearch snapshot will be created on a shared file system.
