### ISSUE TITLE
SCA Java Script module  Component- utils-merge

### ISSUE THREAD

**Issue by PratyakshaSinha** [chef/automate#5136]
Component name : utils-merge

Component Path :

file7594629209_1618840106812_html/automate-ui/node_modules:utils-merge

CVE ID : SRCCLR-SID-30533
https://sca.analysiscenter.veracode.com/vulnerability-database/security/sca/vulnerability/sid-30533/summary

Vulnerability description :
Prototype Pollution: utils-merge is vulnerable to prototype pollution. An attacker is able to inject properties into existing construct prototypes and modify attributes such as `__proto__`, `constructor` and `prototype`.

Reference Link : https://analysiscenter.veracode.com/auth/index.jsp#ReviewResultsSCA:11695:1065071:11719780:11694240:11709903:::::3090080:

**Comment by kalroy** [comment]
Already fixed
