### ISSUE TITLE
Sonar Cloud Blocker Issue -1

### ISSUE THREAD

**Issue by PratyakshaSinha** [chef/automate#5160]
- Component : 
components/automate-ui/e2e/helpers/browser_log.js

- Description:
Add the "let", "const" or "var" keyword to this declaration of "filtered_entries" to make it explicit.

- Reference link : 
https://sonarcloud.io/project/issues?id=chef_automate&resolved=false&severities=BLOCKER

**Comment by kalroy** [comment]
We do not ship this to the customer. Closing.
