### ISSUE TITLE
Migration: Chef-server migration to A2HA

### ISSUE THREAD

**Issue by punitmundra** [chef/automate#5198]
## User Story
Chef-server Migration to A2HA Cluster 

### Setup the Infra
> Install the Stand-alone chef-server.
> Setup the A2HA (3 Node Cluster).

**Note :Need to check dependency on the version on ES and PG.**
### Add Data to Chef-Server
>  1. Add the data to the chef-server node like Org, nodes, cookbooks, databag etc. 
    2.  Add at-least 3 Org, with more than 2 node in each org.
         Each org will have number of cookbooks, data-bags etc... 
3. List of the item store in the PG, ES and locally. 

### Testing
>
1. To do the backup (chef-server-ctl / knife) commands.Purpose of both command and difference.  
2. Take the backup either in the zip/tar files.  
3.  Restore the backup to chef-server 
4. Post restore, how the node will get to know the new a2ha-cluster URL. 
5. Populate the new server url to all the node.
6. Make sure that it would received the data from the node.      

note: Is there any way to move data directly from oe machine to another (not to create a zip.tar). 
## Definition of Done
1. List out the stand alone chef-server version to A2HA cluster(what we supports).
2. List out the data will migrate via command. 
3. List out the data need to copy/migrate manually (which are the part of DB).
4. Steps by step guide to do the steps.
5. Capture the error in the FAQ section.(keep the error in text and image both the way separately).
6. Post restore the  
 
## Demo Script / Repro Steps
1. Script to do the task 
2. ReadMe section

**Comment by karunesh-tech** [comment]
Closing this issue, as chef server migration to HA effort is getting tracked in below list of issues:
https://app.zenhub.com/workspaces/the-delta-quadrant-5fc7c4c3922dc10021323fa6/issues/chef/automate/5518
https://app.zenhub.com/workspaces/the-delta-quadrant-5fc7c4c3922dc10021323fa6/issues/chef/automate/5522
