### ISSUE TITLE
Migration: Chef-backend to  A2Ha Cluster

### ISSUE THREAD

**Issue by punitmundra** [chef/automate#5199]

**Comment by punitmundra** [comment]
Chef-Backend Migration to A2HA Cluster 

This task is about how a customer migrate from chef-backend to the A2HA cluster. 

## Definition of Done
1. List out the chef-backend version to A2HA cluster(Migration supports).
2. List out the data will migrate via knife-ec-backup/chef-server-ctl command.
3. List out the data need to copy/migrate manually.
4. ReadMe section
5. Capture the error in the FAQ section.(keep the error in text and image both  separately).
6. Post restore, able to see the data in automate for client run and compliance scans ?. 

## Testing
### Setup the Infra 
> 1.  HA cluster set up for the Chef-Backend (3 Node Cluster).
> 2. Setup the A2HA (3 Node Cluster).

**Note :Need to check dependency on the version on ES and PG.**

### Add the Data to the chef-backend
   1. Add the data to the chef-backend like Org, nodes, cookbooks, databag etc.
       1.1 Add at-least 3 Org, with more than 2 node in each org. 
      1.2 Each org will have number of cookbooks, data-bags etc...   
      1.3. Script to do the task
      1.4. ReadMe section

   2. List of the item store in the PG, ES and locally.
   3. To do the backup (chef-server-ctl / knife) commands.Purpose of both command and difference.
   4. Take the backup either in the zip or tar files.
   5. Is there any way to move data directly from 1 machine to another (not to create a zip.tar).
   6. restore the backup to chef-server
   7. Post restore, how the node will get to know the new server URL.
   8. Populate the new server url to all the node.
   9. Make sure that it would received the data from the node.

**Comment by FaizanSRE** [comment]
We have tried backup on standalone chef-server and chef-backend cluster frontend node chef-server and took restore on chef-automate HA chef-server using knife-ec-backup utility.

**Comment by FaizanSRE** [comment]
And doc for migration: 
https://progresssoftware.sharepoint.com/:w:/s/ChefCoreC/EagZk2yq6YtEuiSxI-Qpj1QB_QkUd6dERzH2K8hL458hlQ?e=vkoCX9

**Comment by FaizanSRE** [comment]
doc for createing data using chef-load https://github.com/chef/a2ha-docs/wiki/Create-data-using-chef-load
