### ISSUE TITLE
Setup the AWS Dev Environment with S3 bucket configured for backup

### ISSUE THREAD

**Issue by punitmundra** [chef/automate#5216]
### What we need
- We need the dev environment setup for A2HA (3Node cluster : 3-Automate, 3-chef-server, 3-PG, 3-ES, 1-bastion*) with AWS deployment procedure.
- Configure S3-bucket for back-up and restore functionality. 
- Populate the data to Chef-server (Org/Nodes/Cookbooks/Policy etc).
- Automate the smoke test run, once the deployment is completed.
- DNS configure like we have for other acceptance environment.
-  Need  the certificate for the DNS 
- [Firewall rules](https://github.com/chef/a2ha-docs/wiki/FireWall-Setting) 
### Why we need
- To test the functionality for new release of automate and chef-server.
- Any commit  to the code, will trigger the build and changes will deploy.
   to all the environment. 
- For every automate/ chef server release either we do upgrade or re-deploy (TBD) 
### How we will achieve this
-  TBD

### Out of Scope
-  
### Topology
![A2HA-Arch-02-topology.png](https://images.zenhubusercontent.com/5fd0dc583f2b4f70a0e16277/e521c56f-12df-4c10-a1c1-d3c570f7c6ae)

### Definition of Done
 - 3-Node cluster for automate+chef-server+PG+ES and bastion host.
 - Configure the S3 bucket for the backup and restore
 - Populate the data in Chef-server (bootstrap a node)/Automate.

**Comment by karunesh-tech** [comment]
End to end testing environment for Automate HA which is part of Automate public repo is provided by the E2E testing team.
Below is the Configuration and deployment setup provided for (3Node cluster : 3-Automate, 3-chef-server, 3-PG, 3-ES, 1-bastion*):

https://progresssoftware.sharepoint.com/:w:/r/sites/ChefReleaseEngineeringTeam/_layouts/15/Doc.aspx?sourcedoc=%7B953C85CA-FF50-458C-A5BA-44F7752F278B%7D&file=A2HA-AWS-deployment.docx&action=default&mobileredirect=true
