### ISSUE TITLE
Create a build pipeline for master code

### ISSUE THREAD

**Issue by punitmundra** [chef/automate#5220]
### What we need
- We need the Pipeline for the like [this](https://buildkite.com/chef/chef-a2-ha-backend-master-verify).
- Current structure is [here](https://github.com/chef/a2-ha-backend/blob/master/.expeditor/verify.pipeline.yml)
### Why we need
- To make things automate 

### Definition of Done
- Post commit, It trigger the build

**Comment by tduffield** [comment]
The Release Engineering team is not responsible for managing verify pipelines. The Automate team will be responsible for adding the necessary tests to their verify pipeline. Any Automate HA tests should be added to the existing verification pipelines (public/private). We should not have a separate verify pipeline for HA tests.

**Comment by tduffield** [comment]
Closing as no new pipelines should be created to handle the verification tests. The existing pipelines should suffice.
