### ISSUE TITLE
Create a pipeline for the hab package build

### ISSUE THREAD

**Issue by punitmundra** [chef/automate#5221]
### What we need
- We need the Pipeline for the like [this](https://buildkite.com/chef/chef-a2-ha-backend-master-habitat-build).
- Current structure is [here](https://github.com/chef/a2-ha-backend/blob/master/.expeditor/build.habitat.yml)

### Why we need
- To make things automate 

### Definition of Done
- Post commit, It trigger the build

### Acceptance Criteria
- Post trigger it will be generate the package.

**Comment by tduffield** [comment]
Closing as no new pipelines are required. 

The Automate team will need to add the desired Habitat packages to their existing [.bldr.toml](https://github.com/chef/automate/blob/master/.bldr.toml) baed on their development requirements. That way the HA packages will be built together with the rest of the packages. We should not have a separate build pipeline for HA packages.

**Comment by tduffield** [comment]
Please feel free to reach request a review from the `chef/eso-releng` team on PRs modifying that `.bldr.toml` file.
