### ISSUE TITLE
Create a build pipeline for docs

### ISSUE THREAD

**Issue by punitmundra** [chef/automate#5222]
### What we need
- We need the Pipeline for the like [this](https://buildkite.com/chef/chef-a2-ha-backend-master-docs).
- Current structure is [here](https://github.com/chef/a2-ha-backend/blob/master/.expeditor/docs.pipeline.yml)
### Why we need
- To make things automate 

### Definition of Done
- Post commit, It trigger the build

### Acceptance Criteria
- Post trigger pdf doc will be generated.

**Comment by tduffield** [comment]
Closing as the @chef/docs-team is responsible for handling the docs automation process. You will need to engage with them to handle the necessary setup to ensure that your docs are building according to their specifications and requirements.
