### ISSUE TITLE
Telemetry needs to sanitize the domain of the URL field

### ISSUE THREAD

**Issue by tas50** [chef/automate#5237]
## Describe the bug
We are sending the URL of the automate server in some telemetry payloads, which we should not be doing. If we need to know the URL we can send a relative URL or replace the domain with a fake domain to keep the format of the URL field the same.

## To Reproduce
- Look at our telemetry data

## Expected behavior
It should be sanitized to not include domains.

## Screenshots
Available upon request

**Comment by kalroy** [comment]
The Segment has these information:
```
 "properties": {
    "install_context": "habitat",
    "instanceId": "4e9430f5-fa63-4393-9b4f-a16b17e33222",
    "licenseId": "7625d7b1-8ef9-4841-9859-8bd50b7343bd",
    "name": "/infrastructure/client-runs?name=wjb4stl809",
    "path": "/infrastructure/client-runs",
    "product": "automate",
    "product_version": "20200506172513",
    "referrer": "https://automate.chef.mastercard.int/dex/auth/ldap?req=sq5iqrbyef6dz6pkfcogicqbc",
    "search": "?name=wjb4stl809",
    "title": "Chef Automate",
    "url": "https://automate.chef.mastercard.int/infrastructure/client-runs?name=wjb4stl809"
  },
```

Since we already have the path and name we can remove `url` and `referrer` from this data.

**Comment by Venkatesh-rengasamy** [comment]
Created PR for this issue - https://github.com/chef/automate/pull/5552
