### ISSUE TITLE
Telemetry preference issues

### ISSUE THREAD

**Issue by Venkatesh-rengasamy** [chef/automate#5271]
## Describe the bug
Scenario: 1) Telemetry preference is saved locally but its not restored in Checkbox when user login again.

Scenario: 2) User should not wait for About popup to start the telemetry service. Expectation is that telemetry service should run when user login and if telemetry preference is enabled.

Scenario: 3) Append the static message with checkbox in the About popup - "For the changes to take effect, please logout and re-login again."

## To Reproduce
- in list form if possible

## Expected behavior
A description of what you expected to happen.

## Versions (please complete the following information):
- OS: [e.g. rhel6]
- Automate Build Number [e.g. 20190701222009]

**Comment by Venkatesh-rengasamy** [comment]
@kalroy 
Scenario 1 & 2 are fixed and PR yet to raise for review.
Fix details:-
Telemetry preference is not restored properly from localstorage. So it cause two issues ( Scenario 1 & 2 ). The fix is restored the preference from localstorage and updated in its binded property.
Code changes needed in "chef-session.service.ts" file.

**Comment by kalroy** [comment]
@Venkatesh-rengasamy Create a draft PR from the branch instead of keeping the changes in local.

**Comment by Venkatesh-rengasamy** [comment]
@kalroy 
Created a draft PR --> https://github.com/chef/automate/pull/5284

**Comment by Venkatesh-rengasamy** [comment]
@kalroy
The following scenarios are tested manually and working as expected in local env.

1) Enable or disable the preference -> close the About popup -> Again open the About popup to see the preference is restored. 

2) Enable or disable the preference -> logout the app -> login again -> open the About popup to see the preference is restored.  

3) Enable the preference -> logout the app -> login again -> telemetry service should track the details and send it to server. 

4) disable the preference -> logout the app -> login again -> telemetry service should not run and its related tracking api should not trigger.  

5) Open the About popup -> see the warning message concate with second checkbox text.
