### ISSUE TITLE
send start_time to the beginning of the day on same day as end_time

### ISSUE THREAD

**Issue by rickmarry** [chef/automate#532]
# User Story

Currently when invoking the export from UI->compliance->export, the UI sends back the end_time and start_time (among the other filters).  start_time is set to the start time of the trend range.. so if we had 10 days in our trend, we would subtract 10 days from end_time, set time to beginning of day, and set start_time to that.. 

What we really want for the UI to send back is the start_time with the same date as the end_time but with it's time set to start of day.. so in other words same as what we do now but don't subtract any days.

As a <role: Automate User, Developer, etc>, I will use this work when I want to <use case>.

# Definition of Done

# Demo Script / Repro Steps

**Comment by vjeffrey** [comment]
when we discussed this in standup, we talked about it needing this for only the export endpoint
