### ISSUE TITLE
User Settings UI for Local Users build up

### ISSUE THREAD

**Issue by kalroy** [chef/automate#5329]
## User Story

As a local user, I should be able to set by personal settings persistently.
Currently, the user settings will be limited to setting the date format.

## Acceptance Criteria
- The settings set should be accessible to the user even if he logs out or move to another browser
- Users who log in for the first time should see the default values in the UI
- Admin specific rights or admin set settings are not available.
- The user settings will be shown in a profile only for local users
- The user settings won't be shown for SAML users

## Definition of Done
	a. Developed according to UX wireframe/Requirement Document
	b. Demoed the feature to UX 
	c. Unit test cases (coverage at least 70%)
	d. Ensure compatibility with all supporting browser
	e. Smoke Testing is done
	f. All Review Comments are resolved
	g. At least 2 PR approvals required
	h. Code should pass and clear linting
	i. Code is Optimized/Refactored as necessary and observed
	j. Screen shot of the feature developed is provided in the issue
	k. Cypress Testing is included and covers all the scenarios.
	l. Documentation of the feature needs to be completed.
        m. Buildkite pipeline should be green

**Comment by Venkatesh-rengasamy** [comment]
Added timeformat field in user details page. PR -  #5378
