### ISSUE TITLE
[infra-proxy-service-API] Get list of nodes for the policyfiles

### ISSUE THREAD

**Issue by vinay033** [chef/automate#5347]
## User Story
We need to add the API for the policy group details node list.

response: 
```
{
  "nodes": [
    {
      "id": "521b4a46-e389-41e2-952d-e11cd9fe4748",
      "name": "node-chef-client",
      "check_in": "1.6021379832725813E+09",
      "uptime": "10 minutes 00 seconds",
      "platform": "ubuntu",
      "environment": "test",
      "policy_group": "",
      "fqdn": "ubuntu-bionic",
      "ip_address": "10.0.2.15"
    },
    {
      "id": "147c19d2-b19d-48a5-985d-8a2eac4750fa",
      "name": "ec2-node-viv",
      "check_in": "1.6188108110484805E+09",
      "uptime": "2 minutes 06 seconds",
      "platform": "ubuntu",
      "environment": "test",
      "policy_group": "test",
      "fqdn": "ip-172-31-3-170.us-west-2.compute.internal",
      "ip_address": "172.31.3.170"
    }
  ],
  "page": 0,
  "total": 2
}
```
## Definition of Done
	a. Developed according to UX wireframe/Requirement Document
	b. Demoed the feature to UX 
	c. Unit test cases (coverage at least 70%)
	d. Ensure compatibility with all supporting browser
	e. Smoke Testing is done
	f. All Review Comments are resolved
	g. At least 2 PR approvals required
	h. Code should pass and clear linting
	i. Code is Optimized/Refactored as necessary and observed
	j. Screen shot of the feature developed is provided in the issue
	k. Cypress Testing is included and covers all the scenarios.
	l. Documentation of the feature needs to be completed.
        m. Buildkite pipeline should be green

**Comment by kalroy** [comment]
We can handle it from nodes/search API. no need of a separate api
