### ISSUE TITLE
 Content Security Policy prevents saml authentication 

### ISSUE THREAD

**Issue by jordan3825** [chef/automate#5366]
## Describe the bug
 Content Security Policy introduced in https://github.com/chef/automate/pull/5286 prevents SAML authentication from succeeding. 

## To Reproduce
- try to login to Automate 2 version 20210713164523 via SAML

## Expected behavior
The login succeeds. 

## Screenshots
Chrome console log
```
saml:12 Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
```

![image](https://user-images.githubusercontent.com/10427597/126220009-683aa0b4-a546-47f8-9387-9836453abc08.png)

## Versions (please complete the following information):
- OS: CentOS 7
- Browser Chrome 91
- Automate Build Number 20210713164523

**Comment by kalroy** [comment]
This issue was fixed as part of [20210720135142](https://docs.chef.io/release_notes_automate/?v=20210720135142) release.
