### ISSUE TITLE
Generation of new HA config for A2HA inside automate

### ISSUE THREAD

**Issue by karunesh-tech** [chef/automate#5401]

**Comment by karunesh-tech** [comment]
## Description
Generate the New -HA config for A2HA : input can be taken from https://app.zenhub.com/workspaces/the-delta-quadrant-5fc7c4c3922dc10021323fa6/issues/chef/automate/5400.

This part of change will be in Go code (automate-cli).

## Acceptance Criteria 

1.Unit Test, Integration Test as per automate code base.
2. Read-me file 
3. Add the docs support for the automate cmd

**Comment by jayvikramsharma1** [comment]
As per requirement we need to generate a wrapper config file for automate HA mode deployment
It contains two type of HA mode deployment either AWS or Existing Nodes, base on argument with init-config-ha command

- **chef-automate init-config-ha existing_node**

- **chef-automate init-config-ha aws**

How to Build and Test the Change

- **rebuild components/automate-deployment/**

- **rebuild components/automate-cli/**

Raised PR

- **https://github.com/chef/automate/pull/5421**
