### ISSUE TITLE
Implementation of changes in automate deploy command for A2HA

### ISSUE THREAD

**Issue by karunesh-tech** [chef/automate#5434]
## Description
# config based check and deploy
as a part of deployment we have use the logic of generating a2ha.rb from config (#5438),
and then based on deploy command bootstrap the environment and generate meta file, and provision infra or deploy directly based on architecture like (aws, existing nodes).

# Acceptance criteria
- install hab
- install a2ha workspace
- generate metafile in a2ha workspace path using automate
- we have to use logic of generating a2ha.rb file from #5438 and generate a2ha.rb for their respective env
- if config.toml is for AWS then
- - and then we have to run provision infra first
- -  and then we have to run deploy
- if config.toml is for existing node
- - we have to simply run deploy as we don't have to take care of infra provisioning.

On Prem:
/chef-automate deploy config.toml
		bootstrap flow:
			Install hab (curl https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh \ | sudo bash)
			Install workspace (hab pkg install chef/automate-backend-deployment --binlink --force)
		generate a2ha.rb file based on config.toml (pulling data from config.toml and adding it to a2ha.rb)
		automate-cluster-ctl deploy

AWS:

/chef-automate deploy config.toml
	automate-cluster-ctl deploy

**TODO (13/09/2021)**
** Note
identify important fields which these important fields deolpyment will be failed, and add validation checks for that fields before generating a2ha.rb file

a2ha.rb file should be getting generated for each and every time deploy command runs.

To identify mode of deployment at every place except deploy need to check if /hab/a2_deploy_workspace directory exists

**Comment by karunesh-tech** [comment]
Effort remaining: 2 days (for PR, review, and merge)

**Comment by jayvikramsharma1** [comment]
https://github.com/chef/automate/pull/5589

Buildkite have some issues, once buildkite start functioning properly, I will check in case if it fail due to code changes

**Comment by jayvikramsharma1** [comment]
**TODO (13/09/2021)**
** Note
identify important fields which these important fields deolpyment will be failed, and add validation checks for that fields before generating a2ha.rb file

a2ha.rb file should be getting generated for each and every time deploy command runs.

To identify mode of deployment at every place except deploy need to check if /hab/a2_deploy_workspace directory exists
