### ISSUE TITLE
Implement chef automate provision infra

### ISSUE THREAD

**Issue by karunesh-tech** [chef/automate#5439]
## Description

- Read config and decide to call bootstrap based on AWS or existing nodes
.................bootstrap flow(should be independent)
..................................Install hab (curl https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh \ | sudo bash)
..................................Install workspace (hab pkg install chef/automate-backend-deployment --binlink --force)

- generate a2ha.rb file based on config.toml (pulling data from config.toml and adding it to a2ha.rb)

Internally it will use new automate-cluster-ctl provision infra command

## Acceptance Criteria 
New automate provision infra should be available

**Comment by karunesh-tech** [comment]
Updated - 8th-Sept:
Remaining Item:
Add new command ./chef-automate provision and map it to automate-cluster-ctl provision(this is already created)
For all command, mapping must add UAT kind of notes in PR and this ticket.
Dependency :
Manifest changes should be deployed first.

**Comment by jayvikramsharma1** [comment]
https://github.com/chef/automate/pull/5713

**Comment by karunesh-tech** [comment]
The changes for this PR has been added to the issue:

https://github.com/chef/automate/pull/5589
