### ISSUE TITLE
A2HA Script changes for automate-cluster-ctl

### ISSUE THREAD

**Issue by karunesh-tech** [chef/automate#5476]

**Comment by karunesh-tech** [comment]
## Description
	Each terraform module have the script - provision Shell script
	smoke testing based on the script changes

**Comment by meet58** [comment]
PR link https://github.com/chef/a2-ha-backend/pull/502

**Comment by FaizanSRE** [comment]
Pr is already merged in provision-deployment branch in a2-ha and we are moving this code in automate as part of components-movement story for their respective components.
