### ISSUE TITLE
[Deploy,Info,SSH]Mapping the existing Ctl commands with automate CLI

### ISSUE THREAD

**Issue by karunesh-tech** [chef/automate#5501]
## Description
As part of this story, we need to cover below commands mapping with chef automate:
                          Command                                                Usage
1.			automate-cluster-ctl deploy                  Deploy Automate cluster
				1.1 deploy --upgrade-frontends
				1.2 deploy --upgrade-frontends --skip-deploy
2. 		automate-cluster-ctl info                  Show Automate cluster resource information
3.		automate-cluster-ctl ssh                  Access cluster resources via SSH

We need to make sure all the possible flags are supported which these commands already have. Same flags will be applicable in newly added automate CLI command as well.

For commands which is common to a2ha and automate, the CLI logic will 1st check the config and based on that will call the regular flow or cluetr ctl command flow.

## Acceptance Criteria 
Able to access deploy, ssh and info commands of automate-cluster-ctl using unified automate CLI.

**Comment by FaizanSRE** [comment]
Pr for info and ssh command: https://github.com/chef/automate/pull/5716
