### ISSUE TITLE
[Gather-logs,Status, Test]Mapping the existing Ctl commands with automate CLI

### ISSUE THREAD

**Issue by karunesh-tech** [chef/automate#5502]
## Description

As part of this story, we need to cover below commands mapping with chef automate:
Command ==================Usage
1.			automate-cluster-ctl gather-logs                  Generate and collect gather-log bundles for nodes in the Automate cluster
2. 		automate-cluster-ctl status                  Show Automate cluster status information
3. 		automate-cluster-ctl test                  Run the smoke tests for the Automate cluster

We need to make sure all the possible flags are supported which these commands already have. Same flags will be applicable in newly added automate CLI command as well.

For commands which is common to a2ha and automate, the CLI logic will 1st check the config and based on that will call the regular flow or cluster ctl command flow.

## Acceptance Criteria
Able to access Gather-logs,Status and Test commands of automate-cluster-ctl using unified automate CLI.

**Comment by jayvikramsharma1** [comment]
https://github.com/chef/automate/pull/5699

**Comment by jayvikramsharma1** [comment]
this changes moved to PR https://github.com/chef/automate/pull/5589
