### ISSUE TITLE
[testing] Provisioning and deployment multi step testing

### ISSUE THREAD

**Issue by karunesh-tech** [chef/automate#5508]
## Dependency:
Testing end to end multi-step provisioning and deployment
All commands which work in a2ha-backend should be tested and listed down in the document with finding

## Acceptance Criteria 
Multi-step provisioning and deployment should be prod demoable at this stage.

**Comment by karunesh-tech** [comment]
Items:
End to end testing of all commands
configuration + deployment
After deployment Automate UI and functionality testing 

Command mapping list to be tested:
https://progresssoftware.sharepoint.com/:x:/s/ChefCoreC/Ee79nSB_KctJh2jVZJjWVjMBc3RYTkD1nVwJWSCoi_IkcQ?e=X3O5Yv

AWS and bare-metal deployment:
https://progresssoftware.sharepoint.com/:w:/s/ChefCoreC/ERti-Vw0gZtIlFmC-_88Ov0BCfK2eBIZsiEdUe-FhXJ4uA?e=gd6d2W

**Comment by FaizanSRE** [comment]
Testing for on-prem on AWS cloud

**Comment by meet58** [comment]
Provision and deployment is working using below doc.

https://progresssoftware.sharepoint.com/:w:/r/sites/ChefCoreC/_layouts/15/Doc.aspx?sourcedoc=%7B07298AC1-7A7C-4662-8633-676F81C618A7%7D&file=Installation%20Steps%20for%20AWS.docx&action=default&mobileredirect=true
