### ISSUE TITLE
[Validation script] HAB package creation for Net-cat utility

### ISSUE THREAD

**Issue by karunesh-tech** [chef/automate#5510]
## Description
HAB package creation for Net cat utility 
Availability of a  shell script which will use Net-cat and check necessary validation

## Acceptance Criteria 
Public-facing chef-automate validate command along with the trigger and HAB package.

**Comment by jayvikramsharma1** [comment]
Discussion is needed with @punitmundra

**Comment by jayvikramsharma1** [comment]
Dev will be done by today EOD

**Comment by meet58** [comment]
Nat-cat utility is added in this PR.
https://github.com/chef/automate/pull/6366
