### ISSUE TITLE
Single VPC change adjustment in config template of automate

### ISSUE THREAD

**Issue by karunesh-tech** [chef/automate#5512]
## Description
As part of security improvement, we have moved from two to single VPC for aws automate setup. As part of this change, we need to add vpc id details in a2ha.rb file. The same needs to be accommodated in config template file as well. This story covers the effort to make these changes.

## Acceptance Criteria 
Should be able to provide vpc id in confg.toml

**Comment by jayvikramsharma1** [comment]
Merged and Released
