### ISSUE TITLE
Existing A2HA customer migration script implementation

### ISSUE THREAD

**Issue by karunesh-tech** [chef/automate#5517]
## Description
This story covers the implementation work for a script that will have the below capabilities:
	Script capability : 
		user should provide username, path, mount path details, S3/other storage details, ssh access
		Using the above params call the backup command and move the data to the storage.
		Restore: - provide username, path, mount path details, S3/other storage details, ssh access

## Acceptance Criteria 
Script should be ready which will take care of migration of data of existing A2HA customer.

**Comment by karunesh-tech** [comment]
Also provide/add the structure of the migration scripts folder here in comment and for a2ha to Automate HA, put the script there.

**Comment by jayvikramsharma1** [comment]
https://github.com/chef/automate/pull/6369
