### ISSUE TITLE
Migration script implementation of existing Chef-backend (HA of chef server)

### ISSUE THREAD

**Issue by karunesh-tech** [chef/automate#5518]
## Description

Migration script implementation for existing Chef-backend (HA of chef-server):
Script capability: knife tidy and all existing commands must be incorporated and come up with a set of the script for backup and restore

To handle and test backup to backup in new HA as well should be tested.

## Acceptance Criteria 
Script should be ready which will take care of migration of data of existing Chef-backend (HA of chef-server).

**Comment by FaizanSRE** [comment]
This ticket has been taken care in https://app.zenhub.com/workspaces/the-delta-quadrant-5fc7c4c3922dc10021323fa6/issues/chef/automate/5199
