### ISSUE TITLE
Migration script for existing Chef-server (standalone)

### ISSUE THREAD

**Issue by karunesh-tech** [chef/automate#5522]
Description
Migration script implementation for existing Chef-server (standalone)
Script capability: knife tidy and all existing commands must be incorporated and come up with a set of the script for backup and restore

Acceptance Criteria
Script should be ready which will take care of migration of data of existing Chef-server (standalone).

**Comment by FaizanSRE** [comment]
This ticket has been taken care in https://app.zenhub.com/workspaces/the-delta-quadrant-5fc7c4c3922dc10021323fa6/issues/chef/automate/5199
