### ISSUE TITLE
Dependabot issue - Upgrade handlebars from 4.5.3 to 4.7.7

### ISSUE THREAD

**Issue by chaitali-mane** [chef/automate#5525]
## User Story
file name: …/automate-workflow-web/package-lock.json 
Upgrade handlebars to version 4.7.7. For example:

"dependencies": {
"tar": ">=4.7.7"
}
or…

"devDependencies": {
"tar": ">=4.7.7"
}
Vulnerable versions: < 4.7.7
Patched version: 4.7.7

## Impact 
Access to prototype properties is forbidden completely by default, specific properties or methods can be allowed via runtime options.  If you are using Handlebars as documented, you should not be accessing prototype properties from your template anyway, so the changes should not be a problem for you. Only the use of undocumented features can break your build.

**Comment by kalroy** [comment]
@chaitali-mane @vinay033 workflow-web is out of our radar and we should not spend any time if fixing issues related to it.

**Comment by kalroy** [comment]
workflow-web is out of our focus.
