### ISSUE TITLE
Automate CLI commands testing

### ISSUE THREAD

**Issue by karunesh-tech** [chef/automate#5529]
## Description
Expectation:

- Come up with the UAT plan - All possible automate CLI commands and their use case

- Check for positive and negative scenarios for all the commands (Existing automate + new commands  )

- Update the UAT plan accordingly

- For negative scenario, all the error handling must be evaluated and updated in UAT

- All possible combinations of aws + existing nodes

## Acceptance Criteria 
Automate CLI should be error-free tested and ready for production user usage.

**Comment by karunesh-tech** [comment]
Command mapping list to be tested:
https://progresssoftware.sharepoint.com/:x:/s/ChefCoreC/Ee79nSB_KctJh2jVZJjWVjMBc3RYTkD1nVwJWSCoi_IkcQ?e=X3O5Yv

**Comment by FaizanSRE** [comment]
Updated sheet for ctl testting: https://progresssoftware.sharepoint.com/:x:/s/ChefCoreC/ERPDyFzstdJImSf1C4z9sqwByC0cwjBRzuqeQeEQDV4JRA?e=3X0TLx&isSPOFile=1

**Comment by meet58** [comment]
We have tested major commands. Remaining commands will be tested in new sprint.
https://app.zenhub.com/workspaces/the-delta-quadrant-5fc7c4c3922dc10021323fa6/issues/chef/automate/5790
