### ISSUE TITLE
Documentation for introduction to Automate HA

### ISSUE THREAD

**Issue by karunesh-tech** [chef/automate#5531]
## Description
Below items will be covered as part of wiki documentation:

- Introduction to Automate HA
    1. On-prep
    2. AWS

- System and hardware requirements (It should have extensive list of all OS and version we support for Automate HA)

## Acceptance Criteria
The WIki page should be ready along with KT given to the documentation team

**Comment by meet58** [comment]
I have upload docs here.
https://progresssoftware.sharepoint.com/sites/ChefCoreC/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FChefCoreC%2FShared%20Documents%2FEngineering%2FAutomate%2FA2%20HA%2FAutomate%2DHA%2DDocuments&p=true&originalPath=aHR0cHM6Ly9wcm9ncmVzc3NvZnR3YXJlLnNoYXJlcG9pbnQuY29tLzpmOi9zL0NoZWZDb3JlQy9Fc3pNTGZoYUN1Tkd1TFdQb296Q1VGZ0JDaXhkVXdRdXJDREdySUJ4M1NueVV3P3J0aW1lPUlDQ3I0VXA0MlVn

**Comment by meet58** [comment]
I have given the KT to the docs team annd here the docs. 
https://progresssoftware.sharepoint.com/:f:/s/ChefCoreC/EszMLfhaCuNGuLWPoozCUFgBCixdUwQurCDGrIBx3SnyUw?e=SKPg59
