### ISSUE TITLE
Documentation on Back up and restore

### ISSUE THREAD

**Issue by karunesh-tech** [chef/automate#5534]
## Description
Below items will be covered as part of wiki documentation:

Chef-server upgrade
		•	Chef-automate -upgrade-backends 
			Chef-automate -upgrade-frontends

## Acceptance Criteria
The WIki page should be ready along with KT given to the documentation team

**Comment by meet58** [comment]
backup and restore - https://progresssoftware.sharepoint.com/:w:/r/sites/ChefCoreC/Shared%20Documents/Engineering/Automate/A2%20HA/Automate-HA-Documents/Backup%20EFS.docx?d=w88f2dda8ca674dafb05a963dde9a4ee4&csf=1&web=1

s3 backup - https://progresssoftware.sharepoint.com/:w:/r/sites/ChefCoreC/Shared%20Documents/Engineering/Automate/A2%20HA/Automate-HA-Documents/S3%20Backup.docx?d=wf0301f343b7646dd8a007976a1bd48e3&csf=1&web=1

s3 efs restore - https://progresssoftware.sharepoint.com/:w:/r/sites/ChefCoreC/Shared%20Documents/Engineering/Automate/A2%20HA/Automate-HA-Documents/S3-EFS-Restore.docx?d=wbe04979445534aa0b6ff189125552649&csf=1&web=1

vpc instruction https://progresssoftware.sharepoint.com/:w:/r/sites/ChefCoreC/Shared%20Documents/Engineering/Automate/A2%20HA/Automate-HA-Documents/Vpc%20Instruction.docx?d=w157fbd37787e420fa9f59d03a63f2199&csf=1&web=1
