### ISSUE TITLE
Documentation on Migration of old A2HA  to new A2HA

### ISSUE THREAD

**Issue by karunesh-tech** [chef/automate#5535]
## Description
Below items will be covered as part of wiki documentation:

- Migration doc for old A2ha to new a2ha

## Acceptance Criteria
The WIki page should be ready along with KT given to the documentation team

**Comment by jayvikramsharma1** [comment]
https://github.com/chef/a2ha-docs/wiki/Migration-A2HA-to-Automate-HA

**Comment by jayvikramsharma1** [comment]
@dkumaras what information you need from us, this ticket was send back to us.
