### ISSUE TITLE
Documentation on Migration of chef-server-ha and standalone to new A2HA

### ISSUE THREAD

**Issue by karunesh-tech** [chef/automate#5536]
## Description
Below items will be covered as part of wiki documentation:

- Migration doc for Chef-server HA to new a2ha

- Migration doc for Chef-server-standalone to new a2ha

## Acceptance Criteria
The WIki page should be ready along with KT given to the documentation team

**Comment by FaizanSRE** [comment]
Doc https://progresssoftware.sharepoint.com/:w:/r/sites/ChefCoreC/_layouts/15/Doc.aspx?sourcedoc=%7B6C9319A8-E9AA-448B-BA24-B123E4298F54%7D&file=Chef-server%20migration.docx&action=default&mobileredirect=true

**Comment by FaizanSRE** [comment]
Walthrough of doc is given to document team
