### ISSUE TITLE
Documentation on troubleshooting guide

### ISSUE THREAD

**Issue by karunesh-tech** [chef/automate#5538]
## Description
Below items will be covered as part of wiki documentation:

Troubleshooting

- Installation (Hardware requirements)

- Backup, restore, and upgrades

- Migration

- Component specific - like ES and PG

## Acceptance Criteria
The WIki page should be ready along with KT given to the documentation team

**Comment by karunesh-tech** [comment]
For each use-case we need to add:

- Text - error message
- Screen shot - with the command run
- Resolution
Add image in :- a2ha docs folder

**Comment by meet58** [comment]
Done with walk through with deepa

**Comment by meet58** [comment]
Walkthrogh is done with Doc team
