### ISSUE TITLE
Generate new HAB package with Updated license name for all the components

### ISSUE THREAD

**Issue by karunesh-tech** [chef/automate#5545]
## Description [Updated]
Come up with the list of components out of 12 which are eligible for license name update.
Update the license name for all the components :
	Elastic search - Already done
	Postgres - Need to check
	HAproxy
	Metricbeat + generalBeat - No need to update as they are using apache 2.0
	Terraform - to be checked
For these components we are currently using a chef-MLSA license, ideally, we should use the actually open-source license name. WIth the change generate the package.

## Acceptance Criteria 
All the HAB packages should be ready with newly named license

**Comment by FaizanSRE** [comment]
License information for all the components
automate-backend-ctl  -- Apache 2.0
automate-backend-curator -- chef-mlsa upstream package core/curator  -- Apache 2.0
automate-backend-deployment -- Apache 2.0 
automate-backend-elasticsearch -- chef-mlsa upstream package chef/elasticsearch-odfe --Apache 2.0
automate-backend-elasticsidecar -- chef-mlsa upstream package chef/elasticsearch-odfe --Apache 2.0
automate-backend-haproxy --chef-mlsa upstream-package core/haproxy  GPL-2.0 LGPL-2.1
automate-backend-journalbeat --chef-mlsa upstream-package chef/journalbeat Apache 2.0
automate-backend-kibana -- chef-mlsa upstream-package APache 2.0
automate-backend-metricbeat -- chef-mlsa upstream-package APache 2.0
automate-backend-pgleaderchk --chef-mlsa 
automate-backend-postgresql --chef-mlsa upstream package core/postgresql11 PostgreSQL
automate-cluster-ctl -- Apache 2.0 
core/terraform --  MPL-2.0
All the packages are under proper licensing , so we don't need to update any license

**Comment by FaizanSRE** [comment]
For packages , automate-backend-deployment and automate-cluster-ctl ; they are under Apache 2.0 which we will change to chef-mlsa

**Comment by FaizanSRE** [comment]
And for changing license of  automate-backend-deployment and automate-cluster-ctl , we will change it in code movement stories https://app.zenhub.com/workspaces/the-delta-quadrant-5fc7c4c3922dc10021323fa6/issues/chef/automate/5545
