### ISSUE TITLE
Ability to pass the Server Admin User name and PEM file

### ISSUE THREAD

**Issue by kalroy** [chef/automate#5556]
## User Story

As a Chef Server Admin, on enabling user migration, I should be able to pass my user name and private key.

![image.png](https://images.zenhubusercontent.com/5fce5352076e6a85b536912d/756f2b7d-2963-48fd-95c1-2c057dd67a08)

**Comment by sonali523** [comment]
We have implemented this to get the server user list by passing server admin key and server admin name.
