### ISSUE TITLE
Automate API should retrieve Chef Server objects using User private key

### ISSUE THREAD

**Issue by kalroy** [chef/automate#5567]
## User Story

As of now, Automate is fetching the Chef Server objects for an organization using the Admin Private key.
This needs to be changed to make sure that it picks up the User private key while sending the request to the chef server.

**Comment by tas50** [comment]
We need to have further discussion on this path forward. This has lots of downsides.

**Comment by kalroy** [comment]
We are moving to WebUI Key. So closing this ticket
