### ISSUE TITLE
Data Feeds UI: S10: New Custom Integration Overlay

### ISSUE THREAD

**Issue by vivekshankar1** [chef/automate#5578]
## User Story

As an Automate User, when I click on New Integration-> Custom:
- I should see a form which will allow me to add Custom Integration details.
- On clicking use headers text box should get enabled and we can add comma separated header values
- Authentication can be "Access Token" or "Username And Password"
- Form Fields will change based on type of Authentication.
- Custom Header: 
  - API Payload: "{\"Authorization\":\"Splunk 6f01b869-c181-4fb2-a74c-b619e6197a85\",\"sds\":\"dsdsd\"}"
  - Sample value:
    - Authorization: Splunk 6f01b869-c181-4fb2-a74c-b619e6197a85
    - sds: dsdsd

**Desired Views:**
![Screenshot 2021-08-24 at 1.18.27 PM.png](https://images.zenhubusercontent.com/5fce5354d8b7b4766d18a979/63a82526-1d90-4c32-b1e6-ebad8bddae91)

On clicking header checkbox
![Screenshot 2021-08-24 at 1.20.00 PM.png](https://images.zenhubusercontent.com/5fce5354d8b7b4766d18a979/dea3a173-e5e5-4e46-86e8-ceea59d8cfd3)

Onclick of Authentication Drop down:
![Screenshot 2021-08-04 at 9.45.41 PM.png](https://images.zenhubusercontent.com/6008075cc8db73075cc33e45/26bf7b91-bf13-40cf-be89-a37227d06d14)

After selecting Username and Password:
![Screenshot 2021-08-04 at 9.45.50 PM.png](https://images.zenhubusercontent.com/6008075cc8db73075cc33e45/c3c51bd1-cab2-47ad-895f-6983b613bff2)

Fill in the Form:
![Screenshot 2021-08-24 at 1.20.27 PM.png](https://images.zenhubusercontent.com/5fce5354d8b7b4766d18a979/e5339821-9f11-4fa4-81be-514f9fb1701c)

CSS and Other UI settings can be found on [Figma Editor](https://www.figma.com/file/FalqUEpYtse01GaT2gwntc/Chef-Data-Feeds?node-id=2025%3A4068)

## Definition of Done
1. Page should have design as shown in the [Figma Preview](https://www.figma.com/proto/FalqUEpYtse01GaT2gwntc/Chef-Data-Feeds?node-id=2028%3A0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=2011%3A127)
2. On change of Authentication UI fields should change.

- All things specified in User Story Acceptance Criteria should be fulfilled. 
- All Exceptions are Handled Properly, with user prompt. 
- Ensure Console has no Errors and not unnecessary logging in Smoke Test. 
- UI should exactly match UX design. 
- Unit Test coverage for every new feature at least 70% 
- Cypress Coverage for new Feature. 
- Smoke Test is done. 
- Ensure Build and Integration Pipelines are Green. 
- PR has 2 approvers. 
- All Code Review Comments are Resolved. 
![Screenshot 2021-08-24 at 1.18.01 PM.png](https://images.zenhubusercontent.com/5fce5354d8b7b4766d18a979/eac0e54e-2b5b-4918-89f5-e45c67ea1507)

**Comment by vivek-yadav** [comment]
@shaik80 @vivekshankar1 @MadhviAtroliya @shivangi-singh1 Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/The-Delta-Quadrant-5fc7c4c3922dc10021323fa6/issues/chef/automate/5578?planning-poker)
