### ISSUE TITLE
Automate code base learning

### ISSUE THREAD

**Issue by karunesh-tech** [chef/automate#5593]
## Description:
List of modules going to cover

- component/automate-cli
- component/automate-deployment

## Acceptance Criteria 
Share the knowledge

**Comment by jayvikramsharma1** [comment]
Learned Items
Golang Cobra commands used in automate CLI
 -- Deploy
 -- Help
 -- Init-config
 -- status
 -- init-config
Automate Deployment-service
-- package installations
-- manifest
