### ISSUE TITLE
[Spike] Migration strategy analysis

### ISSUE THREAD

**Issue by karunesh-tech** [chef/automate#5594]
## Acceptance Criteria

**Comment by punitmundra** [comment]
Initial Docs :https://progresssoftware.sharepoint.com/:w:/s/ChefCoreC/EevHqEmCAIJNgHUyAzs-cpkBuKA9CzGsgJ0AmyOh7ZFnEA?e=tCDiUI
Conclusion:
Few query need to be addressed.
1. How we can find the ES version from snapshot.
2. How do restore snapshot from 5.x -> 7.x
3.  Find the version from running version?
4. How to covert snapshot from ES:2 to restore at ES:7? 
5. Data compatibility (A1/A2/Chef-Backend/Server/chef-Manage/Super-Market) 
6.Old Inspec /compliance / client runs -> New Inspec / compliance / client-runs
