### ISSUE TITLE
Admin name and key In add chef server slider

### ISSUE THREAD

**Issue by chaitali-mane** [chef/automate#5692]
## User Story

As an Automate User, the user can add an admin name and admin key.

## UI Design
![user-mgmt-02](https://user-images.githubusercontent.com/71449322/132510294-8395ba61-d3bd-4a18-8695-8d388de7ebc4.png)

CSS and Other settings can be found here
https://www.figma.com/file/ZIQr9MsixizCIDtDNsDhNB/Chef-Manage-User-Migration?node-id=0%3A1

**Comment by kalroy** [comment]
Closing this ticket as this is no more relevant. We are moving to WebUI key
