### ISSUE TITLE
Add chef Infra server last screen

### ISSUE THREAD

**Issue by chaitali-mane** [chef/automate#5693]
## User Story

As an  Automate User, in the Last screen of add chef infra server, able to download the CSV of the migrated user.

## UI Design
![user-mgmt-03](https://user-images.githubusercontent.com/71449322/132512129-bd96ce01-de1c-47a3-a14a-94144ddcf148.png)

CSS and Other settings can be found here
https://www.figma.com/file/ZIQr9MsixizCIDtDNsDhNB/Chef-Manage-User-Migration?node-id=0%3A1

**Comment by kalroy** [comment]
This is no more relevant.
