### ISSUE TITLE
Slider for Add chef Infra Organisation

### ISSUE THREAD

**Issue by chaitali-mane** [chef/automate#5694]
## User Story
As an Automate User, I want to change Add chef Infra Organisation modal into a slider.

## UI Design
![user-mgmt-04](https://user-images.githubusercontent.com/71449322/132512911-1d7e5202-909f-42c0-87f3-1b28b064240a.png)

CSS and Other settings can be found here
https://www.figma.com/file/ZIQr9MsixizCIDtDNsDhNB/Chef-Manage-User-Migration?node-id=0%3A1

**Comment by kalroy** [comment]
The flow has changed. This is no more relevant
