### ISSUE TITLE
Last screen of Add Chef Organisation

### ISSUE THREAD

**Issue by chaitali-mane** [chef/automate#5695]
## User Story
As an Automate User, in the Last screen of add chef Organisation, able to download the CSV of the migrated user.

## UI Design
![user-mgmt-05](https://user-images.githubusercontent.com/71449322/132513186-ae2eaa81-b679-4ed7-a1cf-0435435a8087.png)

CSS and Other settings can be found here
https://www.figma.com/file/ZIQr9MsixizCIDtDNsDhNB/Chef-Manage-User-Migration?node-id=0%3A1

**Comment by kalroy** [comment]
The flow has changed. This is no more relevant.
