### ISSUE TITLE
aws-RunInspecChecks showing license error

### ISSUE THREAD

**Issue by jasonbellack** [chef/automate#573]
I am attempting to run Chef Inspec controls on a RHEL7 EC2 instance using SSM and continue to get this error:
"/opt/chefdk/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- aws-sdk (LoadError)

from /opt/chefdk/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'

from ./report_compliance:20:in `

'
log writing failed. Broken pipe @ io_write -

failed to run commands: exit status 1"

To address this error, I installed the aws-sdk gem. Once I did that, I received this error:

"/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/json-2.2.0/lib/json/common.rb:156:in `parse': 434: unexpected token at '-06-12T12:12:29+00:00] ERROR: InSpec cannot execute without accepting the license (JSON::ParserError)

'

from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/json-2.2.0/lib/json/common.rb:156:in `parse'

from ./report_compliance:39:in `

'
failed to run commands: exit status 1"

If anyone has experienced this and found a work around, resolved the issue or has any suggestions, please let me know. Thank you in advance!

**Comment by vjeffrey** [comment]
thanks for opening the issue @jasonbellack -- i've communicated the issue/passed this on to our internal contacts that are in touch with our partners at AWS.

the only workarounds I can think of is ensuring the license acceptance file is on disk on the machine you're running the SSM job on (as we discussed in https://github.com/chef/automate/issues/83).

But we need a real solution for it, of course. So hopefully we'll hear back from the AWS folks soon to be able to get a full fix in for this. Thank you!

**Comment by jasonbellack** [comment]
@vjeffrey thank you for taking the time to respond to this. If it helps, here are the details on OS and steps I'm taking to create and then resolve the issue.

1) Launching RHEL7 EC2 instance in AWS
2) Updating the instance and installing the SSM agent
3) Creating the association in SSM with AWS-RunInspecChecks as the Document and running controls from an S3 bucket. All necessary roles, permissions, and policies are properly configured.
4) Receiving a LoadError in Step 2 for the Association: 
      "/opt/chefdk/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- aws-sdk (LoadError)"

At this point, the only way I have found to get the correct version of the aws sdk gem installed is to do the following:

1) Install the  chefdk-4.0.60-1.el7.x86_64.rpm package on the RHEL7 instance
2) Run the following 2 commands to edit the .bash_profile file:
     echo 'eval "$(chef shell-init bash)"' >> ~/.bash_profile
     echo 'export PATH="/opt/chefdk/embedded/bin:$PATH"' >> ~/.bash_profile && source ~/.bash_profile
3) Run 'gem install aws sdk'

If I install the aws sdk gem without first installing the ChefDK and modifying the .bash_profile file, I continue to get the LoadError previously mentioned.

At this point, when I run the association, I receive the licensing error:
   "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/json-2.2.0/lib/json/common.rb:156:in `parse': 434: unexpected token at '-06-12T12:12:29+00:00] ERROR: InSpec cannot execute without accepting the license (JSON::ParserError)"

To fix this, I created the /etc/chef/accepted_licenses/inspec directory. 

Once all of this has been done, the Association reports success and I am able to view the compliance output in AWS Systems Manager. It should also be noted that at this point, if I remove the ChefDK from the instance, I am able to successfully run the Association. However, the only way I have found to get the correct aws sdk gem installed on the RHEL7 instance is to go through the procedure of installing ChefDK and then updating the .bash_profile. 

Sorry that's a a lot to read, but I wanted to be as thorough as possible and provide all the necessary information to get this resolved. I'm happy to set up a web meeting with you and AWS to try and resolve this as I'm sure others will encounter this issue at some point. Thank you again for taking the time!!

**Comment by davymcaleer** [comment]
@mudash fyi

**Comment by sdelano** [comment]
Notes from triage:
- follow up with our AWS partners to get an update on this - @mudash

**Comment by mudash** [comment]
Have reached out to our AWS contact to find if a fix was successfully implemented for this.

**Comment by vjeffrey** [comment]
@mudash have we hears back from AWS about this?

**Comment by mudash** [comment]
Yes, our AWS contacts informed a related fix had gone into production a while back.

**Comment by vjeffrey** [comment]
great thank you! ill close this -- @jasonbellack let us know if you have any more issues!
