### ISSUE TITLE
Api for retrieving list of node ids and timestamp for latest chef client run for the past 24 hours

### ISSUE THREAD

**Issue by rickmarry** [chef/automate#5808]
## User Story
As an Automate User, I will use this api to retrieve an unfiltered list of all nodes that have checked in with a chef client run within the past 24 hours.
This api will return a potentially large list of node ids with their respective run times and should therefore be used sparingly.

## Acceptance Criteria
- Should produce a list of nodeId(obfuscated) and time it was run

## Implementation Details
This will require a single call to elasticsearch with a query that uses an aggregation to retrieve the list of unique node ids 
By using aggregations, we will be able to fetch more than the 10k limit that is imposed by elasticsearch when retrieving non-aggregate results.  This call will only return nodes if they are marked with "exists" flag equal to true

## Definition of Done
- All things specified in User Story Acceptance Criteria should be fulfilled. 
- All Exceptions are Handled Properly 
- Ensure logs have no unnecessary data. 
- Test coverage for the new feature is done to at least 70% 
- If needed raise Docs PR and tag documentation. 
- Swagger Documentation updated 
- Smoke Test done. 
- Ensure Build and Integration Pipelines are Green. 
- PR has 2 approvers. 
- All Code Review Comments are Resolved. 
- README doc should be updated, if needed.

**Comment by kalroy** [comment]
Not required as we handled it by getting the data for last 15 days
