### ISSUE TITLE
Automate should expose an API to UI to report the Compliance node usage data

### ISSUE THREAD

**Issue by kalroy** [chef/automate#5861]
## User Story
Automate should expose an API to report back the count of unique nodes with lastRun in a given time.
The time duration can be between the last time Telemetry data sent and the current date.
If the duration < 15 days --> 15 days
duration > 15 days --> duration

the response should be as follows:
```json
{
    "days_since_last_post":0,  
    "count": 1                           
} 
```
where: 
 `(int) days_since_last_post` is the number of days since telematics was last posted
 `(int) count` the count of nodes in defined timespan.. ****we only need to retrieve `count` if `days_since_last_post >0`**

## Acceptance Criteria
- If the Index does not have 15 days or more data, it should report as much data as available

## Definition of Done
- All things specified in User Story Acceptance Criteria should be fulfilled. 
- All Exceptions are Handled Properly 
- Ensure logs have no unnecessary data. 
- Test coverage for the new feature is done to at least 70% 
- If needed raise Docs PR and tag documentation. 
- Swagger Documentation updated 
- Smoke Test done. 
- Ensure Build and Integration Pipelines are Green. 
- PR has 2 approvers. 
- All Code Review Comments are Resolved. 
- README doc should be updated, if needed.

**Comment by rickmarry** [comment]
api should look like:
`/compliance/reporting/stats/nodes/count`

returns:
`{ "node_cnt": 2}`
