### ISSUE TITLE
Move all the telemetry related APIs to a different namespace and server

### ISSUE THREAD

**Issue by sonali523** [chef/automate#5926]
## User Story
 Needs to move all the telemetry related APIs in a compliance service to a different namespace and server

## Definition of Done
- All things specified in User Story Acceptance Criteria should be fulfilled. 
- All Exceptions are Handled Properly 
- Ensure logs have no unnecessary data. 
- Test coverage for the new feature is done to at least 70% 
- If needed raise Docs PR and tag documentation. 
- Swagger Documentation updated 
- Smoke Test done. 
- Ensure Build and Integration Pipelines are Green. 
- PR has 2 approvers. 
- All Code Review Comments are Resolved. 
- README doc should be updated, if needed.

**Comment by kalroy** [comment]
It's ok to keep telemetry reporting API under reporting services as it is also a reporting utilized by Telemetry service
