### ISSUE TITLE
Do Performance testing and benchmarking to capture the Client Run API response times for different number of nodes.

### ISSUE THREAD

**Issue by kalroy** [chef/automate#5952]
## User Story
As an Automate user, I need to report the telemetry for large amount of nodes:
- 10K Client Run nodes
- 20K Client Run nodes
- 50K Client Run nodes
- 100K Client Run nodes

For each of the counts, we need to capture the API response time.

## Acceptance Criteria
- A fresh installation of Automate should create the ES index
- Upgradation/Migration of Automate should create the ES index

## Definition of Done
- All things specified in User Story Acceptance Criteria should be fulfilled. 
- All Exceptions are Handled Properly 
- Ensure logs have no unnecessary data. 
- Test coverage for the new feature is done to at least 70% 
- If needed raise Docs PR and tag documentation. 
- Swagger Documentation updated 
- Smoke Test done. 
- Ensure Build and Integration Pipelines are Green. 
- PR has 2 approvers. 
- All Code Review Comments are Resolved. 
- README doc should be updated, if needed.

**Comment by sonali523** [comment]
I was facing the issue to load the 50k nodes using ```chef_load_nodes 50000```
Only 33k nodes are inserted after multiple trials,
The response time for 33k nodes is  30ms
