### ISSUE TITLE
handle project rule updates for ingested resources

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#60]
# User Story
when a user updates rules for a project or creates a new project, we need to re-evaluate all ingested nodes and actions to update project tagging.
in the spike, @lancewf demonstrated this could be done by running a painless script in elastic search that takes a list of project rules and evaluates/re-tags ingested nodes according to the new project rules.

that takes care of the actual re-tagging process.

the other thing that needs to be done is event handling around project rule updates.
@lancewf has a design for this:

<img width="679" alt="screen shot 2019-03-06 at 10 25 42 pm" src="https://user-images.githubusercontent.com/10341541/53934163-db307400-405e-11e9-80cf-0ff46522b2c6.png">

so, following the above design + some conversations we've had around message durability, the flow is:
- user creates one or more new projects or updates projects
- auth service triggers `rule update` event
- ingest service and compliance ingestion are listening for the `rule update` event
- upon receipt of the `rule update` event, ingest service and compliance ingestion make a call to elastic to start the painless script. this is an async call that returns a process id for later querying.
- ingest service and compliance ingestion trigger `rule update received` event
- auth is listening for the `rule update received` event. if that event is not received within a timely manner (tbd) after sending the `rule update` event, the auth service should retry
- when ingest service completes the update, it triggers `client runs update complete` event
- when compliance ingestion completes the update, it triggers `compliance update complete` event
- auth is listening for the `compliance update complete` event

_Notes: there will be many gotchas in this implementation. how to handle duplicate messages, what should the auth service do if it never receives a complete event from one of the services, etc. we are expecting these issues to crop up and expect to spend a couple weeks adjusting as needed_

# Definition of Done
a project rule update in auth triggers the event flow to start the painless script

# Demo Script / Repro Steps
update a project or create a new one
ensure the expected data is tagged with the correct projects 

# More Information
there have been concerns about data durability when using the event service. until we can build off the work currently being done in the event service for durability (NATS), we are pushing the data durability problem to the services sending events to the event service. this has been discussed at length with @gpeers and she is on board.

# Sub Tasks
- [x] Add project tag update for client runs nodes
- [x] Add project tag update for compliance reports
- [x] Add an authz-service manager to manage the update process with both compliance and client runs.

**Comment by lancewf** [comment]
Future feature to update indexes individually from the most recent to the oldest. This will allow the system to resume from an elasticsearch restart. This will also allow the user to see changes to most recent data faster.

**Comment by vjeffrey** [comment]
closing this issue; we can open new ones for future enhancements
