### ISSUE TITLE
Remove publicips variable from existing_infra config.toml

### ISSUE THREAD

**Issue by meet58** [chef/automate#6024]
## Description 
Need to remove below variables while generating config.toml using this command. 
`chef-automate init-config-ha existing_infra`

[existing_infra.config]
automate_ips = []
chef_server_ips = []
elasticsearch_ips = []
postgresql_ips = []

## Acceptance_criteria
It should be reflected in a2ha.rb properly.

**Comment by jayvikramsharma1** [comment]
https://github.com/chef/automate/pull/6228/files
