### ISSUE TITLE
Cert is not being generated for elasticsaerch and postgres component

### ISSUE THREAD

**Issue by meet58** [chef/automate#6035]
## Description
Cert is not getting generated for elastic search and PostgreSQL habitat component. So need to fix it.

## Acceptance criteria
After generating cert, need to make sure all services are up

**Comment by FaizanSRE** [comment]
Pr for elasticsearch and postgres : https://github.com/chef/automate/pull/6062

**Comment by FaizanSRE** [comment]
Elasticsidecar is not coming up .
