### ISSUE TITLE
Reverting the automate-backend-elasticsidecar gemlock changes

### ISSUE THREAD

**Issue by punitmundra** [chef/automate#6075]

**Comment by punitmundra** [comment]
For automate-backend-elasticsidecar, we have done the changes. 
**New Packages Changes**
Changes is all about managing the dependency via gemlock file. please refer the PR [link](https://github.com/chef/automate/pull/5462)
**Old Package**   
we are managing the deps in [plan.sh](https://github.com/chef/a2-ha-backend/blob/main/components/automate-backend-elasticsidecar/plan.sh).

In new approach we are doing the bundle install, which place a gems at different location, 
because of that we are getting the error.
please refer the below screenshot
![elastic-side-car-error.png](https://images.zenhubusercontent.com/5fd0dc583f2b4f70a0e16277/186831ab-3989-4a03-94c4-2a11b0600f27)

For a time being we are reverting the changes. we are using previous approach to unblock the testing for now.
And we are creating the ticket in backlog to manage the deps via gem file.

**Comment by FaizanSRE** [comment]
Pr https://github.com/chef/automate/pull/6079
