### ISSUE TITLE
Upgrade scenario e2e testing

### ISSUE THREAD

**Issue by karunesh-tech** [chef/automate#6096]
## Description:

This issue will cover e2e testing team discussion effort from HA side for upgrade scenario.

Agreed approach :
https://progresssoftware.sharepoint.com/:w:/s/ChefCoreC/EdwBOi6GCkZMp6uIwNiz4DoB_DjDDHE08paJJ7ET8jzAzw?e=nOOQL2

## Acceptance Cretria:

Upgrade scenario should be covered as part of e2e testing

**Comment by FaizanSRE** [comment]
I have tested upgrade by downgrading the package to automate version to 20211102170523 and then upgrading it to 20211201164433

**Comment by FaizanSRE** [comment]
And have covered all scenarios for upgrade by using all flags upgrade-frontends, upgrade-backends  and upgrade-airgap-bundles with skip-deploy combination

**Comment by FaizanSRE** [comment]
Only 1 scenario for upgrade which we have observerd is that chef-automate has config of auto-upgrade , which is disabled by default in HA setup. So we will enable it and try if it updates on it own, but that will happen on next release of automate.

**Comment by meet58** [comment]
Auto upgrade part will be tested in new spring. This is the instance details where upgrade scenario was tested. 
ssh -i "cp-a2ha.pem" ubuntu@ec2-13-127-2-206.ap-south-1.compute.amazonaws.com
