### ISSUE TITLE
flaky test: deleting es documents at end of test

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#613]
# User Story

Noticed this in the pipeline:
```
Could not 'clean' ES documents.
--
  | Error: elastic: Error 409 (Conflict)FAIL	github.com/chef/automate/components/compliance-service/integration_test	14.654s
```
https://buildkite.com/chef/chef-automate-master-verify-private/builds/2166#ddcbd52c-62cc-4410-b830-cbf81fc66f3a

# Definition of Done
no more failing test on deleting es docs

**Comment by srenatus** [comment]
Yes please! 😉
