### ISSUE TITLE
tell nodemanager when nodes are marked as missing/marked for deletion

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#616]
# User Story

In Automate today, nodes under the client runs tab are (by default) marked as "missing" when they do not check in for more than one day.  Users have the ability to configure this time period.  Nodes that have been "missing" for x amount of days are then marked for deletion.

In order to ensure congruence of data in our app, we need to make nodemanager aware of these state change when it happens. 

This can be done via a call to nodemanager's ChangeNodeState (https://github.com/chef/automate/blob/master/components/nodemanager-service/api/manager/manager.proto#L28) -- *we'll need to add an additional state of "missing"*. Nodes set as "marked for deletion" should be deleted from the nodemanager.

# Definition of Done
Nodes marked as missing in client runs also have a state of missing in nodemanager.
Nodes marked for deletion in client runs are deleted in nodemanager.

**Comment by lancewf** [comment]
Here is where the nodes are marked missing https://github.com/chef/automate/blob/master/components/ingest-service/backend/elastic/jobs.go#L22. We could return the IDs of the nodes that are marked missing and the update to the nodemanager's ChangeNodeState.

**Comment by vjeffrey** [comment]
Probably a good idea to do the same when missing nodes are deleted: send a msg to the nodemanager communicating that the nodes have been deleted

**Comment by vjeffrey** [comment]
looks like the first thing to do will be to see if we can get the ids changed list returned from these functions:
https://github.com/chef/automate/blob/master/components/ingest-service/backend/elastic/jobs.go#L22
https://github.com/chef/automate/blob/master/components/ingest-service/backend/elastic/jobs.go#L95

**Comment by lancewf** [comment]
I have one more task to complete with this issue. The task of ingest-service multiple node delete.

**Comment by vjeffrey** [comment]
oooh i didn't realize that! thank you!!

**Comment by lancewf** [comment]
There might be another way to delete nodes also. I kind of remember that Kyleen worked a task of when an AWS node is deleted that the ingest-service gets notified and deletes the node. I will have to look for this also.

**Comment by vjeffrey** [comment]
ah ya, iirc that actually relies on nodemanager saying the node was terminated

**Comment by lancewf** [comment]
Deleting from the nodemanager sounds cleaner.

**Comment by vjeffrey** [comment]
ya this kinda makes me think that any time nodemanager knows a know has "terminated" state, we should really just delete it outright...
