### ISSUE TITLE
Show the report generation status

### ISSUE THREAD

**Issue by kalroy** [chef/automate#6194]
## User Story
As an Automate User, I should be able to view the report generation status of a report. 
The report status can be `in process`, `failed`, `successful`

## Definition of Done

- All things specified in User Story Acceptance Criteria should be fulfilled.
- UI should exactly match UX design.
- Cypress Coverage for new Feature.
- All Exceptions are Handled Properly
- Ensure logs have no unnecessary data.
- Test coverage for new feature is done to at-least 70%.
- Docs changes PR is Raised.
- Swagger Documentation updated.
- Smoke Test done.
- Ensure Build and Integration Pipelines are Green.
- PR has 2 approvers.
- All Code Review Comments are Resolved.
- Screen shot of the feature developed is provided in the issue.
- Ensure compatibility with all supporting browser.
- Demo the feature to UX.
- Link to the UX wireframe/Requirement Document.

**Comment by Venkatesh-rengasamy** [comment]
This issue is part of epic #6059. It is done and its PR#6255 got merged. This issue is covered in the sprint: Nov-18 to Dec-1.
