### ISSUE TITLE
Postgres13-contrib package is needed in Habitat

### ISSUE THREAD

**Issue by vivekshankar1** [chef/automate#6221]
## User Story
As a Developer for Chef Automate,
I want to Postgres13-contrib in habitat stable channel so that i can use the pg_upgrade utility

## Implementation Details
- Raise a ticket to the habitat team

## Acceptance Criteria
- Postgres13-contrib package should be available in habitat

## Definition of Done
- Postgres13-contrib package should be available in habitat

**Comment by vivek-yadav** [comment]
Not needed now.
