### ISSUE TITLE
Trigger pg upgrade with required parameters

### ISSUE THREAD

**Issue by vivekshankar1** [chef/automate#6222]
## User Story
As a Developer for Chef Automate,
I want to trigger the upgrade commands when the customer agrees to upgrade in the cli command

## Implementation Details
- Run the pg_upgrade command to migrate the data from old PG version to the new pg 13 version

## Acceptance Criteria
- Upgrade should happen correctly.
- Migration of data should happen
- All data should be correctly migrated along with PG settings

## Definition of Done
- All things specified in User Story Acceptance Criteria should be fulfilled. 
- All Exceptions are Handled Properly 
- Ensure logs have no unnecessary data. 
- Test coverage for the new feature is done to at least 70% 
- Docs changes PR is Raised. 
- Swagger Documentation updated 
- Smoke Test done. 
- Ensure Build and Integration Pipelines are Green. 
- PR has 2 approvers. 
- All Code Review Comments are Resolved. 
- Test upgrade from n-1 version.

**Comment by vivek-yadav** [comment]
Not required as we will now only use automate Backup and Restore commands
