### ISSUE TITLE
Need to ask user for input for upgrade bundles 

### ISSUE THREAD

**Issue by meet58** [chef/automate#6232]
## Description
We need to ask user for press y or n if they have executed upgrade command and they want proceed further. This input should be come from chef=automate cli utility. So it should be handled from go side.
E.g. 
chef-automate upgrade run --upgrade-frontends
chef-automate upgrade run --upgrade-backends
chef-automate upgrade run --upgrade-airgap-bundles

**Comment by jayvikramsharma1** [comment]
https://github.com/chef/automate/pull/6244
