### ISSUE TITLE
public_ip field should be removed

### ISSUE THREAD

**Issue by meet58** [chef/automate#6241]
## Description
We should remove below filed form config.toml

automate_ips = []
chef_server_ips = []
postgresql_ips = []

Final config would look like this
  automate_private_ips []
  chef_server_private_ips []
  elasticsearch_ips []
  elasticsearch_private_ips []
  postgresql_private_ips []

**Comment by jayvikramsharma1** [comment]
https://github.com/chef/automate/pull/6228
