### ISSUE TITLE
Need to automate /mnt/automate_backups creation in On-Prem deployment

### ISSUE THREAD

**Issue by jayvikramsharma1** [chef/automate#6279]
## User Story

While deployment we have to run following command manually in postgresql instance.

- sudo mkdir -p /mnt/automate_backups/postgresql/pg_dump/
- sudo mkdir -p /mnt/automate_backups/postgresql/archive/
- sudo chown -R hab:hab /mnt/automate_backups/

it is need to automate this process for On-Prem deployment.

## Definition of Done

/mnt/automate_backups/postgresql/pg_dump/ and 
/mnt/automate_backups/postgresql/archive/ 

Dir should be created in postgresql instance automatically.

**Comment by meet58** [comment]
PR link: https://github.com/chef/automate/pull/6285
