### ISSUE TITLE
Analysis for ES working without open-distro for ES upgrade to 6.8.14

### ISSUE THREAD

**Issue by karunesh-tech** [chef/automate#6303]
## Description
As part of the elastic search (ES) upgrade from 6.8.6 to 6.8.14 (to align with ES version of Automate), we need to update the ES version. Currently, HA's ES also required open distro as well whose version is not compatible with ES 6.8.14.
As part of this issue, we will remove the open-distro support from automate HA in order to allow ES upgrade to 6.8.14.
This ticket will track the effort on how to drop open-distro and changes needed for same. Also as an outcome we will have tech doc for implementation of the changes and issues to resolve

## Acceptance Criteria 

Implementation plan for dropping open-distro and ES upgrade from 6.8.6 to 6.8.14 for automate HA

**Comment by jayvikramsharma1** [comment]
removed ODFE elasticsearch and added elasticsearch 6.8.14, elasticsearch service is getting up

some of Limitations 

- Security plugin is not supported,
- we have to remove certificates from elasticsearch


More work needed
Elasticsidecar, Metricbeat, Kibana were build with ODFE packages, we need to write new plan.sh using elasticsearch 6.8.14 for each of above services.
-

**Comment by tas50** [comment]
Without the security plugin do we lose auth from automate services to ES?

**Comment by jayvikramsharma1** [comment]
We are planning to use Open search mostly we might not use elasticsearch
