### ISSUE TITLE
implement wildcard search on platform version number and profile version number for compliance

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#633]
# User Story
This is a known issue carried over from https://github.com/chef/automate/issues/325

Let's revisit this when we have some time to give it the special attention it needs.

# Definition of Done
Can filter with wildcard on platform version number and profile version number.

**Comment by vjeffrey** [comment]
let's investigate why this is.
if it's not possible to do the wildcard searching on those fields, then let's go ahead and note that here and close the issue

**Comment by lancewf** [comment]
@vjeffrey The reason that wildcard search does not work with the platform and profile version numbers is that the version numbers are in a separate field. For the client runs page we fixed this problem for the platform field by concatenating the version on to the platform field.

**Comment by vjeffrey** [comment]
changed the issue title to reflect what needs to be done to make this work; sounds like we just need alias fields for both of those where we concatenate the version number onto the text field, as @lancewf mentioned was done for client runs

**Comment by lancewf** [comment]
So we do have a field with the platform name and version combined. 
https://github.com/chef/automate/blob/2e9f37aafb847850da5b5d38a443b9d7c6facfc2/components/compliance-service/ingest/pipeline/processor/report.go#L57

We need to update suggestions to use that field 
https://github.com/chef/automate/blob/72c60c610a100fd8578eb36c419b1e65507a1a10/components/compliance-service/reporting/relaxting/suggestions.go#L32. 

We also need to update filtering to use that field. 
https://github.com/chef/automate/blob/997be2f1f15bb25fea61d315d61a3ac72f83fadf/components/compliance-service/reporting/relaxting/reports.go#L547


I will look to see if profile version will be the same.

**Comment by lancewf** [comment]
We will need to do a migration to switch platform.full field in Elasticsearch to allow wildcards. 
https://github.com/chef/automate/blob/be1cb11c6b66d48896e314f0b46086f9d99bbc4c/components/compliance-service/ingest/ingestic/mappings/comp-rep-date.go#L193
