### ISSUE TITLE
Edit "owner" policy for the admin of infra Server View

### ISSUE THREAD

**Issue by kalroy** [chef/automate#6331]
## User Story
As an Automate Infra Server Admin User with admin permission of the Infra Server, I should be part of the "owner" policy which allows:
- be admin of all the orgs under all the servers
- can view all the servers
- add an infra server
- migrate users from a server
- migrate orgs from a server
- delete an infra server

I should not be able to:
- create/edit/delete server

## Acceptance Criteria
- This should have this api working with these inputs.
- Should produce this output

## Implementation Details
- In this file, add this function.

## Definition of Done
- All things specified in User Story Acceptance Criteria should be fulfilled. 
- All Exceptions are Handled Properly 
- Ensure logs have no unnecessary data. 
- Test coverage for the new feature is done to at least 70% 
- If needed raise Docs PR and tag documentation. 
- Swagger Documentation updated 
- Smoke Test done. 
- Ensure Build and Integration Pipelines are Green. 
- PR has 2 approvers. 
- All Code Review Comments are Resolved. 
- README doc should be updated, if needed.

**Comment by Abdul-Az** [comment]
This issue can be closed as Automate owner itself has all the permissions required for infra admin, we can use automate admin for that, no need of extra policy as infra admin.
