### ISSUE TITLE
Chef Server version update is working in Dev but not in the pipeline

### ISSUE THREAD

**Issue by jashaik** [chef/automate#6338]
## Describe the bug
Chef-server latest hab version is working in the development environment but failing the pipeline.
https://github.com/chef/automate/pull/6183

## To Reproduce
- start_all_services & start_chef_server is working as expected in the development env but same is failing in the pipeline
- Pipeline link - https://buildkite.com/chef/chef-automate-main-verify-private/builds/19476#0faca16b-132a-41bc-bb2d-b9967019b8ab

## Expected behavior
The behaviour should be same in both the environments and all the services should be in healthy state

## Versions (please complete the following information):
- https://github.com/chef/automate/pull/6183

## Additional context
Tried figuring out the reason for it but failied as there is no way to debug more due to continuous restarts in the docker env.

**Comment by kalroy** [comment]
The issue is fixed and the latest PR build was successful
https://buildkite.com/chef/chef-automate-main-verify-private/builds/19714
