### ISSUE TITLE
Add a migration table to keep track of the migrations

### ISSUE THREAD

**Issue by kalroy** [chef/automate#6348]
## User Story
As an Automate User, I should be able to store the migration status for a chef server.
The table should be able to store the status of different activities namely:
- Organisations Migration
- Users Migration

## Acceptance Criteria
- The default value of the status should be `In Progress`

## Implementation Details
![Database ER diagram-Migration table](https://user-images.githubusercontent.com/7055118/147728609-1eb0a592-a30f-4e45-bb7e-27dd245c3461.jpeg)

## Definition of Done
- All things specified in User Story Acceptance Criteria should be fulfilled. 
- All Exceptions are Handled Properly 
- Ensure logs have no unnecessary data. 
- Test coverage for the new feature is done to at least 70% 
- If needed raise Docs PR and tag documentation. 
- Swagger Documentation updated 
- Smoke Test done. 
- Ensure Build and Integration Pipelines are Green. 
- PR has 2 approvers. 
- All Code Review Comments are Resolved. 
- README doc should be updated, if needed.

**Comment by vinay033** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/The-Delta-Quadrant-5fc7c4c3922dc10021323fa6/issues/chef/automate/6348?planning-poker) with ZenHub @sonali523 @YashviJain01 @chaitali-mane
