### ISSUE TITLE
[Spike] Try out external elastic search 7.X with automate

### ISSUE THREAD

**Issue by shivangi-singh1** [chef/automate#6398]
## User Story

As a Automate Developer i want to try out external elasticsearch 7.x in automate

## Definition of Done

All features , services along with backup restore should be working properly.

**Comment by btm** [comment]
Note that there is a long list of breaking changes in Elasticsearch 7.0: https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html
Significant work was completed to account for those in this draft PR https://github.com/chef/automate/pull/4293 which wasn't finished.

We should probably attach this to #5744 or #4527.

**Comment by vivekshankar1** [comment]
Closing since @punitmundra is doing spike with opensearch 1.0
