### ISSUE TITLE
Changes for UX guidance on chef-automate command line

### ISSUE THREAD

**Issue by jayvikramsharma1** [chef/automate#6405]
## Description
We need some changes to user experience better, required changes are...

- provision-infra need to changed to provision-infrastructure 
- All unique HA specific command should have suffix of HA
- Add help Document for all HA commands

**Comment by meet58** [comment]
https://github.com/chef/automate/pull/6445. This changes should be tested dev fistt. After the demo to sprint review team we can merge it in main.
