### ISSUE TITLE
Create command for existing infrastructure  validation

### ISSUE THREAD

**Issue by meet58** [chef/automate#6439]
## Description
Need to create validate command for existing-infra architecture that will validate the necessary port by sending request on remote server where deployment will be happen to check port is open or not.

For that create a command **chef-automate validate-ha-infrastructure**

## Acceptance-criteria
All necessary port should be checked and if any port is blocked then it should give the warning message like please open such port. Otherwise your deployment will be stuck.

**Comment by jayvikramsharma1** [comment]
https://github.com/chef/automate/pull/6493
