### ISSUE TITLE
Testing the minimum node setup for Automate HA

### ISSUE THREAD

**Issue by jayvikramsharma1** [chef/automate#6442]
## Descriptions 
This story will cover the testing and feasibility confirmation for all below use-cases:

**Testing for chef backend customer use case - Customer with very less number of nodes**

**Uses to be tested**

- Existing HA --> 10 nodes
- Mini HA --> 5 nodes
- Mini non-HA --> 4 nodes
- Micro non-HA --> 2 nodes
- Regular Automate - 1 node

Note will do just to test the feasibility
And once the performance issues are fixed by the Automate team, we will test again for benchmarking.

## Acceptance criteria:
Report all the above use-cases and their fesibility.

**Comment by FaizanSRE** [comment]
Document : https://progresssoftware-my.sharepoint.com/:w:/g/personal/ffulara_progress_com/EdbTd6BicE5Hrv64IFpiAhYBUZn41nl38XtOLP6JiptE7Q?e=8Xdf3o

**Comment by jayvikramsharma1** [comment]
Closing this story as per the above document. There are some more config driven use case, Which we need to cover as part of other story.
