### ISSUE TITLE
Pg certificate renewal

### ISSUE THREAD

**Issue by meet58** [chef/automate#6483]
## Description
Need to fix buildkite issue that is coming when we push the renewal changes in the PR. So need to fix it.

**Comment by FaizanSRE** [comment]
Pr: https://github.com/chef/automate/pull/6494

**Comment by FaizanSRE** [comment]
I tried to pin versionof upstream package to core/postgresql11/11.2/20200403150941 and core/postgresql11/11.2/20190311152155 , but build is failing .
