### ISSUE TITLE
Remove Shadow from Text Input Field on Search

### ISSUE THREAD

**Issue by jonong1972** [chef/automate#650]
# Overview
Some consistency clean up.  Currently the filter box text input field has a shadow, whereas, most of our form input fields do not.  In order to be consistent we will want to remove the box-shadow from both the client run and compliance filter text field.

**Client Run Filter** `/client-runs`
![Screen Shot 2019-06-20 at 1 17 57 PM](https://user-images.githubusercontent.com/1316587/59878990-91923d80-935e-11e9-9734-750295442a2d.png)

**Compliance Filter**  `/compliance/reports/overview`
![Screen Shot 2019-06-20 at 1 18 10 PM](https://user-images.githubusercontent.com/1316587/59879026-9fe05980-935e-11e9-80c3-3079bd3c8b36.png)

# Definition of Done
There is no box shadow surrounding the text field.

**Client Runs Filter**
![Screen Shot 2019-06-20 at 1 26 18 PM](https://user-images.githubusercontent.com/1316587/59879269-24cb7300-935f-11e9-9829-2d70aa918eb2.png)

**Compliance Filter**
![Screen Shot 2019-06-20 at 1 26 53 PM](https://user-images.githubusercontent.com/1316587/59879279-2bf28100-935f-11e9-8410-b51155a0e223.png)

**Comment by susanev** [comment]
@jonong1972 could we make the placeholder text use the same color in this task as well?
