### ISSUE TITLE
Test On Prem Automate HA deployment on redhat  8.4

### ISSUE THREAD

**Issue by jayvikramsharma1** [chef/automate#6513]
## Descriptions 

Need to test automate HA deployment on Redhat 8.4 for On Prem env.

## Acceptance 

- In case deployment go without issue, then all commands should work as aspected, there should not be any glitch.

- In case any manual step required to make deployment sucess then it should be documented and will automated if required.

- In case deployment fails then detail analysis of failure should be documented, and also possible solutions  to make deployment successfully should be suggested.

**Comment by meet58** [comment]
Tested with this PR: https://github.com/chef/automate/pull/6555

**Comment by meet58** [comment]
PR for airgap env issue
https://github.com/chef/automate/pull/6555
https://github.com/chef/automate/pull/6540

AutomateHA setup is in this instance. This is the bastion server detail
ssh -i "meetg-canada.pem" ec2-user@ec2-3-98-137-5.ca-central-1.compute.amazonaws.com
