### ISSUE TITLE
loading "available" profiles takes 6 seconds!!!!

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#653]
# User Story

As a user, I'd like to not wait 6 seconds to interact with my profiles in Automate. We're returning the "installed" profiles in just over a second, but loading the "available" profiles list is clocking in at SIX SECONDS :/

<img width="1004" alt="Screen Shot 2019-06-20 at 17 15 20" src="https://user-images.githubusercontent.com/10341541/59887105-3ae92b80-937f-11e9-9bef-2a7751861c39.png">

# Definition of Done
Loading the available profiles list takes less than six seconds

**Comment by vjeffrey** [comment]
it looks like we're currently loading all the profile metadata for each of those profiles in the list call: 
<img width="755" alt="Screen Shot 2019-06-24 at 16 39 04" src="https://user-images.githubusercontent.com/10341541/60058797-ab08f180-969e-11e9-88a5-7ec1c1a0b617.png">

maybe step 1 on the path to perf improvements here is to only return the essentials: profile title, version, name, sha

**Comment by vjeffrey** [comment]
```
curl -H "api-token: hygYwaxPkFgjv8rwgPpVODWr-es=" -w "@curl-format.txt" -o /dev/null -s https://a2-local-inplace-upgrade-acceptance.cd.chef.co/api/v0/compliance/profiles/search -d '{}'

    time_namelookup:  0.005069
       time_connect:  0.152262
    time_appconnect:  0.457522
   time_pretransfer:  0.457546
      time_redirect:  0.000000
 time_starttransfer:  3.332871
                    ----------
         time_total:  3.635783
  

curl -H "api-token: hygYwaxPkFgjv8rwgPpVODWr-es=" -w "@curl-format.txt" -o /dev/null -s https://a2-local-inplace-upgrade-acceptance.cd.chef.co/api/v0/compliance/profiles/search -d '{"owner": "admin"}'

    time_namelookup:  0.004578
       time_connect:  0.157379
    time_appconnect:  0.461259
   time_pretransfer:  0.461319
      time_redirect:  0.000000
 time_starttransfer:  0.671166
                    ----------
         time_total:  0.671279
```

**Comment by vjeffrey** [comment]
https://github.com/chef/automate/issues/2258

**Comment by susanev** [comment]
gonna close this, we may be able to fix this with the content delivery service work, but otherwise, its deprioritized.
