### ISSUE TITLE
description on profile details hidden by buttons

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#654]
# User Story

Looks like profiles with longer descriptions are having a portion of their description overwritten by the buttons on the page..

<img width="1236" alt="Screen Shot 2019-06-20 at 17 11 37" src="https://user-images.githubusercontent.com/10341541/59887151-6c61f700-937f-11e9-9bab-24fb96de7aed.png">

# Definition of Done
Can read the profile description

**Comment by susanev** [comment]
we could set a max-width fo 610px similar to the compliance reporting page (https://github.com/chef/automate/pull/41); note that it should not be a global max-width and only specific to profile pages. as we should ensure the content shifts correctly on the rest of the page if we take this approach.

**Comment by SEAjamieD** [comment]
@susanev - Looking through the titles/headings, some of them are quite long as well.  would you prefer the max-width the contain the title as well?  Or maybe moving the buttons down a tick?

Are we open to using css grid?  We could contain the Heading, Subheading, and buttons in their own containers so we don't have to worry about screen sizes.  Browser support might be limited though.

![Screen Shot 2019-09-16 at 2.22.16 PM.png](https://images.zenhubusercontent.com/5d7aa5d5d4249c0001cab607/8e79dad5-5446-4fc3-8d8e-bb1997db1478)

**Comment by susanev** [comment]
@SEAjamieD good catch! ill leave this design decision up to @jonong1972 though.

**Comment by jonong1972** [comment]
@SEAjamieD Moving the buttons down a tick would be cool.  Then we can have the description and buttons in a container below the Title. Thanks!

**Comment by SEAjamieD** [comment]
@susanev / @jonong1972 - One thing to note with the 610px hard width is that with a screen width of 1024px, we're still seeing a bit of overlap.

![Screen Shot 2019-09-17 at 9.44.18 AM.png](https://images.zenhubusercontent.com/5d7aa5d5d4249c0001cab607/2e256244-56ae-433d-84a7-cecc38e3686f)


We see decent spacing again around 1070px screen width

![Screen Shot 2019-09-17 at 9.50.18 AM.png](https://images.zenhubusercontent.com/5d7aa5d5d4249c0001cab607/5b5d23b2-f07d-4700-b913-8869b812d144)

**Comment by jonong1972** [comment]
@SEAjamieD I would defer to you or @susanev on the math of things.  Best guess? As long as there is a ~10-20px margin between the buttons and text?
