### ISSUE TITLE
Go implementations of airgap upgrade for automate HA

### ISSUE THREAD

**Issue by jayvikramsharma1** [chef/automate#6546]
## Descriptions 
**context**  
> our ruby code of upgrade is not smart enough to determine whether it is offline env or not, it will try to download arigap bundle from internet even though airgap bundle had been passed.

**ToDo**

> we need to take care of all the flags in golang code, we will not paas any flag to ruby code, only deploy command will called if --skip-deploy is not passed.

## Acceptance 
Ruby code will not get flags and bundles should not be downloaded.

**Comment by FaizanSRE** [comment]
Pr: https://github.com/chef/automate/pull/6551
