### ISSUE TITLE
Commands and document changes as part of EAP feedback

### ISSUE THREAD

**Issue by karunesh-tech** [chef/automate#6600]
## Description

* Documentation + pre-deployment
    * Required AWS VPC Setting: DNS hostnames enabled - how to add in pre-deployment check
    * Structure of the toml file, share the sample file.
        * Categorise the keys as per optional| mandatory use case
        * Simple 1 liner for each important key in the document
* Commands and scripts changes
    * Running `chefautomate version` throws TLS error - Proper message - version command should be ran from chef automate node
    * chef automate info command returns new lines for links etc. so that parts of it have to be copied together

**Comment by FaizanSRE** [comment]
PR: https://github.com/chef/automate/pull/6608
for version and info command

**Comment by FaizanSRE** [comment]
changes for VPC in doc https://github.com/chef/automate/commit/90d22ca16a2d033969739761d0708a5e6918ab95#diff-922ff430fbb0c05fd8fb934d02f3fedc441e3397045d1e3b77a765b336955610

**Comment by FaizanSRE** [comment]
https://github.com/chef/automate/blob/automate-ha-preview-doc/dev-docs/%5BDraft%5DAutomate%20HA%20document_Internal_preview.md#this-is-a-chef-automate-aws-ha-mode-configuration-file-you-can-run
