### ISSUE TITLE
chef-server-ctl doesn't support external PG with cleanup-bifrost and grant-server-admin-permissions subcommands

### ISSUE THREAD

**Issue by vivekshankar1** [chef/automate#6611]
## Describe the bug
The `chef-server-ctl cleanup-bifrost` and `chef-server-ctl grant-server-admin-permissions` commands don't support using external PostgreSQL with Chef Automate.

When attempting to use one of these commands you will get and error similar to

```
[root@ip-10-30-30-177 ~]# chef-server-ctl cleanup-bifrost
/hab/pkgs/chef/chef-server-ctl/14.0.22/20200812153852/vendor/bundle/gems/bundler-1.17.2/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
bundler: failed to load command: /hab/pkgs/chef/chef-server-ctl/14.0.22/20200812153852/omnibus-ctl/binstubs/chef-server-ctl (/hab/pkgs/chef/chef-server-ctl/14.0.22/20200812153852/omnibus-ctl/binstubs/chef-server-ctl)
PG::ConnectionBad: could not connect to server: Connection refused
        Is the server running on host "127.0.0.1" and accepting
        TCP/IP connections on port 5432?
```

## To Reproduce
* Install Automate with embedded Chef Infra Server
* Configure Automate to use an external PG database
* Run `chef-server-ctl cleanup-bifrost`

## Expected behavior
The command should complete successfully

## Versions (please complete the following information):
- OS: Centos7
- Browser: N/A
- Automate Build Number: 20200816214709 

## Additional context
This problem impacts all Automate Cluster installations

**Comment by vivekshankar1** [comment]
We need database mapping for below commands from chef-server team to close this issue. 
"cleanup-bifrost"
"filtered-dump"
"reindex"
"add-client-key"
"add-user-key"
"delete-client-key"
"delete-user-key"
"list-client-keys"
"list-user-keys"
"grant-server-admin-permissions"
"list-server-admins"
"remove-server-admin-permissions"
Above commands are run in passthrough mode and chef-server-ctl is called. To process the requests we need to set the svc path correctly as A2_SVC_PATH env.

**Comment by PrajaktaPurohit** [comment]
As explained in https://chefio.slack.com/archives/C07JP2K7F/p1643060459048000?thread_ts=1642756647.043200&cid=C07JP2K7F the database mapping for each of the commands should not be required to fix this issue.

**Comment by vivek-yadav** [comment]
This was resolved with https://github.com/chef/automate/pull/6643  and released in https://docs.chef.io/release_notes_automate/#20220209045542
