### ISSUE TITLE
Automate backup create is failing

### ISSUE THREAD

**Issue by iamazzeez** [chef/automate#6668]
## Describe the bug
Automate backup create is failing with error: 
BackupError: An issue occurred while creating or restoring a backup: Streaming backup events failed: Unable to handle backup event: Backup failed. Check the Chef Automate logs for more information.
when data in automate is more. Data here refers to Nodes inside Chef Infra Server or Compliance reports.
It works fine with less or no data.

## To Reproduce
- Spin up an EC2 instance with automate and load some data of nodes or compliance around 10k nodes will be sufficient.
- Try to take multiple backups of automate (it fails)

## Expected behavior
- Backup create should be successful.

## Screenshots
<img width="1792" alt="Screenshot 2022-02-03 at 6 17 06 PM" src="https://user-images.githubusercontent.com/38317160/152732753-6e9f1977-2c59-4d4b-9580-f23e85144e7b.png">

## Versions (please complete the following information):
- Automate Build Number 20220121191356

## Additional context
Issue in Zendesk https://getchef.zendesk.com/agent/tickets/29555

**Comment by trickyearlobe** [comment]
Possible fix(es) for ZD29555, ZD29807 and ZD29861 in https://github.com/chef/automate/pull/6733

**Comment by iamazzeez** [comment]
Fixed in https://github.com/chef/automate/pull/6733
