### ISSUE TITLE
Move license expiration banner to very top of page

### ISSUE THREAD

**Issue by susanev** [chef/automate#677]
## Overview
Move the license expiration banner to the top of the page to align with original designs and prepare for an additional banner on the bottom of the page for projects. _Note: This is for the expiring license banner only, all other user notifications should stay where they are._

### General
* Move the banner to the very top of the page, all other content should shift down
* Change the content to say: _There are \<n\> days remaining on your license. Apply a license or contact Chef to continue to use Chef Automate._ 
* The x-button should dismiss the banner and shift the rest of the content back up

### Styles
* height: 40px
* font-size: 14px;
* font-weight: 500, except for the day count which should have a weight of 700
* _Apply a license_ should semantically be a button, _Contact Chef_ should semantically be a link, but they will both have an underline style with no change on hover.

## Other Things
* In ur local dev environment you can remove the current license and then apply for a trial to make the banner show up using `remove_dev_license`

### Abstract
https://share.goabstract.com/7fc3e818-8849-4632-a50f-6487efbc9652?mode=build&sha=26b29bbc0fd870c4f1bd403ae6da1585ccc1f386

### Screenshot
![license-expiration-banner](https://user-images.githubusercontent.com/5489125/60301353-ff51e280-98e5-11e9-894c-aa081a9ccb30.png)

**Comment by susanev** [comment]
Alternate text to consider: `There are <strong>59 days</strong> left on your Chef Automate license. To continue to use Automate, apply a license or contact Chef.`

**Comment by stevenoneill-jmfamily** [comment]
As a customer, we disagree with "Move the banner to the very top of the page, all other content should shift down".  Namely, "shift".  This 'jostles' the content, which is undesirable.  The preference would be to have such a message appear in an era of existing static content.   Suggest at the top between "Settings" and the person-icon.  In fact, if this whole section turned a different color with the same license reminder content, we feel it would be better than jostling the UI with a pop-up like element.

**Comment by susanev** [comment]
@stevenoneill-jmfamily

Thanks so much for taking the time to share your feedback and frustrations!

This issue is the first step we are taking to improve the entire experience of user notifications, including the license expiration notification. Afterward, we will be able to improve the dismissal functionality along with the animation, reducing the behavior that you have described. I do want to be honest, however, and communicate that we currently have priorities above this one (such as the identity access and management work), so it will be a bit before we show progress on it. That said, if this is something you would be interested in working on, we welcome contributions.

**Comment by stevenoneill-jmfamily** [comment]
No worries.  As a customer, we would also like to see IAMv2 prioritized over something like this.
