### ISSUE TITLE
enable project filtering for all api calls in cfgmgmt.proto

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#68]
# User Story
in order to return appropriately filtered data to users, each api call exposed in 
**`cfgmgmt.proto`**
must 
- make a function call on the incoming ctx to find out which projects they should filter on
- return the data that matches the project filters

An example of the function to be called on the ctx is:
```
func filterByProjects(ctx context.Context, filters map[string][]string) (map[string][]string, error) {
	projectsFilter, err := auth_context.ProjectsFromIncomingContext(ctx)
	if err != nil {
		return nil, err
	}
	if auth_context.AllProjectsRequested(projectsFilter) {
		return filters, nil
	}

	filters["projects"] = projectsFilter
	return filters, nil
}
```

An example of adding the project filter to the elasticsearch filters is:
```
if len(filters["projects"]) > 0 {
		termQuery := elastic.NewTermsQuery("projects", stringArrayToInterfaceArray(filters["projects"])...)
		query = query.Filter(termQuery)
	}
```

# Definition of Done
all apis in the defined proto make a function call on the incoming ctx to find out which projects they should filter by
all apis in the defined proto accept a []string projects filter and return the correct data based on those project filters
[ "project6", "project9" ] -> return all data tagged with project 6 or project 9 or both
[ "(unassigned)" ] -> return all data tagged with no projects tagged
[ "(unassigned)", "project8" ] -> return all data tagged with no projects tagged and return all data tagged with project8
["*" ] -> return all data

# Demo Script / Repro Steps
set up a project with ingest rules
send in a client run report, action, and compliance report that match the rules of the created project
make a query for resources in created project
expect to see the resources
make a query for resources in a different project
expect to not see the resources

**Comment by lancewf** [comment]
- [ ] GetNodes
- [ ] GetRuns
- [ ] GetNodesCounts
- [ ] GetRunsCounts
- [ ] GetNodeRun
- [ ] GetSuggestions
- [ ] GetOrganizations
- [ ] GetSourceFqdns
- [ ] GetAttributes
- [ ] GetVersion
- [ ] GetPolicyCookbooks
