### ISSUE TITLE
Automate uses port 10128 which is IANA assigned to BMC Patrol

### ISSUE THREAD

**Issue by thomascate** [chef/automate#683]
# User Story

As a system admin maintaining an Automate server I would like to also be able to run bmc patrol agent. IANA has port 10128 documented as reserved by the BMC-PERFORM-SERVICE DAEMON. 
https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.txt

# Definition of Done
teams-service is moved off of port 10128, or ideally is given a configurable port.
# Demo Script / Repro Steps

With this command running on a linux machine
`nc -k -l localhost 10128`
Start Automate and verify it is in a healthy state.

**Comment by stevendanna** [comment]
@thomascate The following is the rest of our ports that overlap with IANA ports based on a quick scan that I did.

```
|  port | automate user            | iana reservation | OK? |
|-------+--------------------------+------------------+-----|
|    80 | automate-load-balancer   | http             |  Y  |
|   443 | automate-load-balancer   | https            |  Y  |
|  2000 | automate-gateway         | cisco-sccp       |     |
|  2001 | automate-gateway         | dc               |     |
|  5432 | automate-postgresql      | postgresql       |  Y  |
|  8989 | automate-workflow-server | sunwebadmins     |     |
| 10100 | pg-sidecar-service       | itap-ddtp        |     |
| 10113 | authn-service            | netiq-endpoint   |     |
| 10115 | session-service          | netiq-endpt      |     |
| 10116 | automate-dex             | netiq-voipa      |     |
| 10117 | automate-dex             | iqrm             |     |
| 10125 | notifications-service    | cimple           |     |
| 10128 | teams-service            | bmc-perf-sd      |     |
| 10129 | data-lifecycle-service   | bmc-gms          |     |
| 10160 | deployment-service       | qb-db-server     |     |
| 10161 | automate-ui              | snmptls          |     |
| 10162 | authn-service            | snmptls-trap     |     |
| 10200 | automate-cs-nginx        | trisoap          |     |
| 10201 | automate-cs-bookshelf    | rsms             |     |
| 14001 | data-feed-service        | sua              |     |
```

**Comment by thomascate** [comment]
Some of these are non-issues, for example we are using 80/443 for http/https.
However I've run into bmc perf on a few enterprise customer installs and had to work around it. Which usually requires getting their security team to move their port. I wouldn't be surprised if we ran into snmptls, snmptls-trap being used for system stats gathering as well.  The rest seem to either be archaic, or services that you wouldn't expect to be a linux server.

Ideally all ports could be configured through the chef-automate config, so an end user could simply move their port in case of a collision.

**Comment by stevendanna** [comment]
@thomascate Theoretically, most ports are already configurable. For instance, you can probably configure the teams-service port using something like the following:

```
[teams.v1.sys.service]
port = 9999
```

Now, I say "theoretically", because I am sure that none of those port configs have been tested so I imagine there are a few bugs related to hard-coding for some services; however, I would expect that most of them "just work."

**Comment by susanev** [comment]
we are deprioritizing this work, but have added a separate issue to include more details in the docs #3062
