### ISSUE TITLE
Re-locate chef server and chef org filters to on page for Event Feed and Client Runs

### ISSUE THREAD

**Issue by susanev** [chef/automate#692]
## Overview
* In the past _global like_ filters were added to the left nav for filtering by chef server or chef org, this work was never finished and the filters are localized to only the event feed and client runs pages
* We have plans to move to a full-left nav instead of the mix of top-nav and left-nav especially because the left-nav space is only being fully utilized on the _Settings_ top-level item
* This task involves removing the filters in the left and adding the filtering capability for chef server and chef org into the filter inputs on those pages

### Event Feed
[Event Feed Designs](https://share.goabstract.com/388237eb-276e-4407-905b-78e9403268f2?mode=design&sha=7560d03efd62d8c22b94750a51d0d157ee4014a4)
- new route `dashboards/event-feed`
- add filter box in the header, which will allow filtering by chef org, chef server, or event (adding it to the header because we are constrained to that location currently due to the compliance page design)
- rename top nav item to _Dashboards_

![dashboards](https://user-images.githubusercontent.com/5489125/60611784-019bbd00-9d7c-11e9-902e-747accd76cd7.png)
![dashboards-filter-open](https://user-images.githubusercontent.com/5489125/60611782-01032680-9d7c-11e9-92e5-44140ca9b60e.png)
![dashboards-filter-open-filter-applied](https://user-images.githubusercontent.com/5489125/60611783-01032680-9d7c-11e9-8574-09fa8b864a2d.png)

### Client Runs
[Client Runs Designs](https://share.goabstract.com/3b920964-e9ae-4d36-861b-81136ae3258f?mode=design&sha=7560d03efd62d8c22b94750a51d0d157ee4014a4)
- new route `infrastructure/client-runs`
- add functionality to filter by chef org or chef server into the filter box already on the page 
- rename top nav item to _Infrastructure_

![infrastrucutre](https://user-images.githubusercontent.com/5489125/60611799-0a8c8e80-9d7c-11e9-8dcb-6004cf9a6a04.png)
![infrastrucutre-filter-open](https://user-images.githubusercontent.com/5489125/60611798-0a8c8e80-9d7c-11e9-9ded-4d25a9697f16.png)

### Event Feed
* Add a top-level item of _Dashboards_ with the _Event Feed_ page under it
* Update all screenshots on the _Event Feed_ page
* Adjust the [Docs Event Feed Filtering Events](https://automate.chef.io/docs/event-feed/#filtering-events) section to be accurate with the changes in this issue

### Client Runs
* Add a top-level item of _Infrastructure_ with the _Client Runs_ page under it
* Update the 1 screenshot on the _Client Runs_ page
* Update the [Docs Client Runs Filtering](https://automate.chef.io/docs/client-runs/#filtering) section with the newly added _Chef Org_ and _Chef Server_ options
* Remove the [Docs Client Runs Sidebar Filter](https://automate.chef.io/docs/client-runs/#sidebar-filter) section

**Comment by lancewf** [comment]
We will also have to update the notification-service message links in sync with the new route changes. 

I am going to start working on adding the chef server and orgs to the client runs's search bar.
