### ISSUE TITLE
Manual Upgrade for Next Release banner is shown when Automate is up to date

### ISSUE THREAD

**Issue by jordan3825** [chef/automate#6983]
## User Story

As a <role: Automate User, Developer, etc>, I expect the Manual Upgrade banner to only show when a new Major upgrade is available. Currently when on the latest Automate version (3.0.49) the "Manual Upgrade for Next Release" banner is shown on every login but no upgrade is available. 

```
$ sudo chef-automate upgrade status
Automate is up-to-date (3.0.49)
```

## Definition of Done

The banner is only shown to the users when a new major upgrade is available. 

## Demo Script / Repro Steps

1. Upgrade to Automate 3.0.49
2. Login to the UI

**Comment by jgh9** [comment]
There is a new release, that requires a manual upgrade, as well. I thought this was odd, too, but this seems to me to not be a bug.
