### ISSUE TITLE
upgrading from 20220329091442 to 3.0.49

### ISSUE THREAD

**Issue by jgh9** [chef/automate#7046]
## Describe the bug
When upgrading from 20220329091442 to 3.0.49, another upgrade was pushed, however command noted in this document didn't supply "--version 3.0.49", so the latest was downloaded 4.x.x.
https://docs.chef.io/automate/major_upgrade/#chef-automate-in-air-gapped-environment-with-embedded-postgresql

## To Reproduce
- perform upgrade from 20220329091442 to 3.0.49 using current docs

## Expected behavior
- downloaded bundle 3.0.49

## Versions (please complete the following information):
- OS: AmazonLinux2
- Firefox
- Automate Build Number: 20220329091442 to 3.0.49

## Additional context
Respectfully, I would suggest adding `--version x.x.x` with explicit versions based on path in each Journey-based upgrade document.

`sudo ./chef-automate airgap bundle create --version 3.0.49`

**Comment by vivekshankar1** [comment]
This has been fixed in:
https://github.com/chef/automate/pull/7030
