### ISSUE TITLE
e2e/cypress: fix "Remove Credential" issue

### ISSUE THREAD

**Issue by srenatus** [chef/automate#722]
#720 should be considered a workaround. For some reason, cypress thinks the "Remove Credential" button wasn't visible; because `chef-dropdown` had `display:none`.

I am not sure why this is happening, and what brought this change about -- digging through git didn't yield anything (for me! please try yourself).

![image](https://user-images.githubusercontent.com/870638/60423144-d1beaf00-9bed-11e9-941b-f764de9ee6e7.png)

What's odd is that when I click on the "..." button in the cypress window, all I see is another "..." button:

![image](https://user-images.githubusercontent.com/870638/60423194-ed29ba00-9bed-11e9-98bb-eee7057454c2.png)

What could be related is this recently released Cypress version: https://docs.cypress.io/guides/references/changelog.html#3-3-2 (but I haven't verified this).

**Comment by vjeffrey** [comment]
are these failures still happening? i haven't noticed them but i haven't been looking closely either
