### ISSUE TITLE
Support for inspec-aws multi-region tests

### ISSUE THREAD

**Issue by davymcaleer** [chef/automate#75]
# User Story

As an Automate User, I want to be able to use the updated multi-region capable [inspec-aws](https://github.com/inspec/inspec-aws) resources to be able to run compliance scans against all of my regions in a single compliance run.

# Definition of Done
We believe this should already be able to handle a version of InSpec that uses the new [inspec-aws](https://github.com/inspec/inspec-aws) resource pack, however it should be tested and we should be allowing Automate customers to make use of the improved multi-region support and ensure the CIS certified AWS Profile can be run correctly within A2

# Demo Script / Repro Steps
Run a compliance scan using the updated CIS Profile for Level 2 AWS Foundation Benchmark

**Comment by vjeffrey** [comment]
talked with @alexpop about this:

need a new version of inspec for the inspec-aws profile, then can go ahead with this work

**Comment by vjeffrey** [comment]
new inspec version/fixes for the plugins are being discussed. should be getting a fix through for that soon

**Comment by vjeffrey** [comment]
https://github.com/inspec/train-aws/pull/8#pullrequestreview-256487053

**Comment by vjeffrey** [comment]
@skpaterson is there a specific version of inspec we should pull in to move forward on this work?

**Comment by vjeffrey** [comment]
https://github.com/chef/automate/compare/ap/use-inspec-4 <-- older wip branch from alex

**Comment by vjeffrey** [comment]
https://github.com/chef/automate/pull/973 bumps the version of inspec used by automate to 4.7.18 https://github.com/chef/automate/pull/973

once that merges, we'll need to coordinate the release of AWS CIS Benchmark v1.2.0 with the automate change for going from creating one node per region -> one node per account
