### ISSUE TITLE
"ZD 18087" - Compliance: Sort by Platform does not work for redhat with release numbers

### ISSUE THREAD

**Issue by vinay033** [chef/automate#752]
# User Story
When trying to sort by the platform in the compliance section, the release numbers for Redhat do not get properly parsed/sorted

# Definition of Done
Sorting by a column will sort correctly

# Demo Script / Repro Steps
have numerous Redhat versions to sort, attempt to sort by platform

**Comment by tmonk42** [comment]
Same problem with sorting Ubuntu versions. Not RedHat specific.

**Comment by susanev** [comment]
@tmonk42 yah, we will be fixing it for all platforms.
in progress: https://github.com/chef/automate/pull/1196

**Comment by susanev** [comment]
@tmonk42 this has merged and should make it into the 09/09 release.
