### ISSUE TITLE
applications view: Collect back-end telemetry data

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#760]
original issue: https://chefio.atlassian.net/secure/RapidBoard.jspa?rapidView=314&modal=detail&selectedIssue=A2-869

# Description
For this card, we want to collect data that will help us understand the scale and performance requirements of the EAS Applications system:

total number of services (ignoring pagination, filtering, etc.)

total number of service groups (likewise ignoring pagination, filtering, etc.)

# Acceptance Criteria
In metabase, we can see the total number of services and service groups in each unique automate instance.

# Implementation Notes

This could be implemented as:
a modification to the welcome page node count tracker
a modification to the GetServiceGroups gRPC call, which adds the data we want
a separate telemetry-centric API call that we hook into when the applications page loads

------
Daniel DeLeo
8 days ago

Where to put scale metrics
Option 1: GetServiceGroups API

Seems nicer to me to have pagination-related info in this API, so total SGs seems natural to have at first glance
Total services isn't totally out of place in this response

Need to add some more DB queries to the API implementation which is already the most performance-limiting part of the UI

Is the API "semantically weird" if we make this _always_ report the total unfiltered counts? Those numbers aren't useful for pagination in the general case. Of course we can include the filtered and unfiltered counts, at the cost of computing both.

Currently the total counts are not anywhere in the UI so we don't need to compute them all the time, but this approach prevents us from using any logic (e.g., keep state in the browser to only report scale metrics once per day) to reduce the load

Doesn't make sense to do the telemetry from a different screen in the UI, will only get numbers if users are visiting the applications page

Option 2: Health Counts API:

The total service groups number is already the full count of service groups
Feels weird to me to tack the total services on this
Feels weird to me that we use this for pagination

If the text filter reduces the number of service groups visible in the view, then the count of total service groups isn't the thing we want to track any more

Doesn't make sense to do the telemetry from a different screen in the UI, will only get numbers if users are visiting the applications page

Option 3: Telemetry-specific API:

It's an extra API call and it doesn't do anything useful for the user (maybe some would like to use the API and graph the number or something? Speculation, tho)

Don't have to worry a lot about the semantics of the API, it's just a collection of interesting stats - don't have to worry about how it might be impacted by any filtering features we might ever implement

Need to make sure we have a good integration test since we won't see it in the UI if it's broken
Does make sense to do the telemetry from a different screen in the UI if we like. Can get data reported when the user visits any part of the application (i.e., from the home page of the app)

Based on this thought process, I’ve decided on option 3

**Comment by kmacgugan** [comment]
Option #3 is now merged!

**Comment by vjeffrey** [comment]
are we good to close this issue then or do you want to keep it open til a question is set up in metabase for it
