### ISSUE TITLE
Update supervisor, deployment and service-group on service update

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#761]
original issue: https://chefio.atlassian.net/secure/RapidBoard.jspa?rapidView=314&modal=detail&selectedIssue=A2-891

# User Story
We are lacking some data update on service health events, currently we only update its health, update strategy and package identifier, but it is missing to update the supervisor, deployment and service-group data, specifically the application name, environment, site and fqdn.

**Comment by afiune** [comment]
Completed with https://github.com/chef/automate/pull/779

**Comment by afiune** [comment]
Waiting for @apriofrost validation.
