### ISSUE TITLE
Confusing description for chef-automate backup restore

### ISSUE THREAD

**Issue by runeabrahamsson** [chef/automate#790]
# Describe the bug
When looking at the chef-automate backup restore help description for --yes it says "Skip bootstrapping the machine with Habitat". While it is actually used for skipping confirmation before performing a restore.

# To Reproduce
- Run `chef-automate backup restore --help`

# Expected behavior
I Expected that the text of the flag would say something about it being used to skip confirmation before performing a restore.

# Versions (please complete the following information):
- OS: any
- Browser N/A
- Automate Build Number: CLI tool for 1.8.96 and others

# Additional context
The issue is in:
[chef-automate_backup_restore.yaml](https://github.com/chef/automate/blob/master/components/automate-chef-io/data/docs/cli_chef_automate/commands/chef-automate_backup_restore.yaml)
Line 33

**Comment by stevendanna** [comment]
Thanks for the report!  This is definitely a bug, the confusing help message is here: https://github.com/chef/automate/blob/master/components/automate-cli/cmd/chef-automate/backup.go#L93
