### ISSUE TITLE
introspect-all on UI init instead of having too many introspect-some calls

### ISSUE THREAD

**Issue by susanev** [chef/automate#793]
## Overview

The API is there but currently isn't used. Might require a refactoring of how we ngrx-store the permission responses.

#### Broad strokes
* Activate caching for introspect_some calls so they normally won't need to call the back-end, getting values out of the ngrx cache.
* Add periodic introspect_all that updates the ngrx cache.

#### Further thoughts
* Do introspect_all upon initial app load then at a regular interval every X minutes, for some small X.
* Change introspect_some so that it first checks if the requested endpoint is already in the store. (A) If so, just use it. (B) If not, proceed with the regular back-end call.
* Back-end calls from introspect_some will then be unusual rather than the norm. They might occur in these instances:
    * A. First page loading, where the introspect_all call has not yet finished.
    * B. Some parameterized introspection call, since those are not included by introspect_all.
    * C. Some unexpected corruption of the store.

Note that this ignores the actual incidence of policy updates. I do not think it is critical that a policy update be reflected immediately in the UI. If it is reflected within say, 2 minutes, I think that would be adequate.

**Comment by msorens** [comment]
Verified network calls for introspection are sharply reduced on v1, v2, and v2.1.
