### ISSUE TITLE
Teams: General UI Fixes

### ISSUE THREAD

**Issue by susanev** [chef/automate#794]
_Note: Please leverage the implementation from Projects and Tokens_

## Overview

In IAMv2 we are making updates to Teams, and this task aligns those updates to the UI. These design updates should only be displayed on v2, not v1.

## Design Details

[UX Designs in Zeplin](https://app.zeplin.io/project/5ba808703eb54372d860c737/dashboard?seid=5c65a8e7488d3b3c17ad9257)

* Team list view has columns Name and ID, in that order
* Create Team action results in a modal leveraging design already implemented for Projects and Tokens
* Team detail updates to heading, and summary
* Remove edit button on team detail pages
* Details tab added where the user can change the team name
* There should be 38px of space between the name input and the Save button
* Admins team name is changed to Admins

* When a team has zero users...
[Designs on Zeplin](https://zpl.io/VQvRE59)
    * Hide the table and command bar
    * Add an empty message of _Add some users to get started!_
        * font-size: 18px; font-weight: 400
        * semantically a paragraph
        * 77px from chef-page-header to paragraph
        * 18px between paragraph and primary button
    * Primary button: _Add Users_

**Comment by srenatus** [comment]
![image.png](https://images.zenhubusercontent.com/5c0b885543d5c44ffa2f8003/089bf6bd-0721-4e9b-ba3b-4099a1552aad)

Looks like the name of the team with ID `admins` is still `admins`. Purposely?
