### ISSUE TITLE
Tokens: General UI Fixes

### ISSUE THREAD

**Issue by susanev** [chef/automate#795]
## Overview

A few general fixes to the UI for the token flows to prepare to add projects to those flows.

## Design Details

[Zeplin](https://app.zeplin.io/project/5ba808703eb54372d860c737/dashboard?seid=5caa837de89d3f33896c7aa3)

### Token List Page
* Add empty state when no tokens, _Create the first token to get started!_
* Add an _ID_ column directly after the _Name_ column on the Tokens list page
* Capitalize _Date_ in the _Created Date_ column on the Tokens list page

### Token Detail Pages
* Change the Save button to always say _Save_.
* After an edit has happened and has been saved a message should be shown: _All changes saved._ next to the button; this should go away if another edit is made.
* Add an input for toggling the status, use `chef-phat-radio`

**Comment by srenatus** [comment]
Much assigning and un-assigning going on here :D

I'll pull it into IA.
