### ISSUE TITLE
Add underscores into API IDs

### ISSUE THREAD

**Issue by srenatus** [chef/automate#800]
## User Story

As a customer who wants underscores (`_`) to be allowed in IDs (projects, specifically), I want to be allowed to do that (IAM v2 only).

## Definition of Done

- The API validation are adjusted to allow for underscores in IDs for the auth entities having IDs.
- The UI error messages are adjusted as well.

## Demo Script / Repro Steps

Create a project (token, team) with an underscore in its ID, and see it work.

**Comment by sdelano** [comment]
Note 2019-07-19: No subtasks needed.

**Comment by srenatus** [comment]
ℹ️Picking this up because it's just the right size for what I can get done today (🤞)

**Comment by srenatus** [comment]
Didn't get to much, ended up working on the merged e2e tests more. Merely bumped some dependencies. Will continue on this tomorrow, if noone beats me to it.

**Comment by srenatus** [comment]
### resources with IDs that should allow `_` now

- [ ] projects
- [ ] tokens
- [ ] policies
- [ ] roles
