### ISSUE TITLE
get projects from headers in gateway handlers that bypass middleware

### ISSUE THREAD

**Issue by susanev** [chef/automate#804]
## Overview

gateway/services.go contains a few request handlers that exercise auth outside the middleware:

https://github.com/chef/a2/blob/master/components/automate-gateway/gateway/services.go#L327

https://github.com/chef/a2/blob/master/components/automate-gateway/gateway/services.go#L419

https://github.com/chef/a2/blob/master/components/automate-gateway/gateway/services.go#L496

https://github.com/chef/a2/blob/master/components/automate-gateway/gateway/services.go#L546

Currently, these handlers hard-code resources/actions on each request. Now that we have projects being passed in project headers on each request, each handler will also need to be updated to take the projects from the project header and pass them on to {‌{IsAuthorized}‌}.

Notes:ProfileCreateHandler: create profile in asset storeProfileTarHandler: download profile from asset storeReportExportHandler: download reports (json/csv) from complianceconfigMgmtNodeExportHandler: download reports (json/csv) from config mgmt

**Comment by srenatus** [comment]
Isn't this done? :smiley: 👉 https://github.com/chef/automate/commit/21e2d9ce3af806ca57459aab77d2af4298dc4cd0#diff-2c556165fbc36774fb10bf9d7737980d

**Comment by susanev** [comment]
🙃 closed cause its already done, dup issues are fun.
