### ISSUE TITLE
only call /introspect_projects on v2.1

### ISSUE THREAD

**Issue by susanev** [chef/automate#805]
@jaym  noticed a panic caused by the introspect_projects call, which is used to populate the global project filter in the UI.

we weren't able to repro the panic locally, but we can at least prevent further unnecessary introspect_projects calls since we only ever see the global project filter while on v2.1

currently, the UI polls https://localhost/api/v0/auth/introspect_projects every 2 minutes regardless of IAM version. it should only poll while on v2.1

**Comment by msorens** [comment]
Confirmed correct on v1, v2, and v2.1
