### ISSUE TITLE
automate-workflow cleanup tasks

### ISSUE THREAD

**Issue by stevendanna** [chef/automate#81]
# User Story

The automate-workflow code base was imported as-is from the old Chef Automate 1 code base.  This feature is provided for users upgrading from Chef Automate 1 who have already invested in workflow.  While we do not expect to do any large-scale feature-work in this code base, it is likely that we have to do ongoing maintenance for this feature until there are no supported users of it.

Towards that end, we should cleanup loose ends that might confuse users and future developers or make maintenance harder.

# New Features

- [ ] HTTP communications between workflow and authn: Workflow communicates with Authn over HTTP rather than HTTPS.  This is currently mitigated by it being a localhost-only communication, but now that the code base is imported it should be easier to support HTTPS.

# Cleanup Opportunities

- [x] Remove dangerous or non-functional automate-ctl commands.  (In progress: https://github.com/chef/automate/pull/59)

- [ ] Remove unused modules from the workflow-server codebase
  - [x] Insights (https://github.com/chef/automate/pull/57)
  - [x] Visibility (https://github.com/chef/automate/pull/57)
  - [ ] Notifications (maybe? I haven't investigated whether we can)

- [ ] Investigate unused code from the workflow-web codebase. I'm not familiar with this project to know if there is unused code in what we imported.

- [x] Removed unused code from workflow-nginx: https://github.com/chef/automate/pull/80

# Test Integration

On merge we added some very basic tests, but there are more tests in the workflow codebases that haven't been hooked up into CI and/or that could be extended.

- [ ] Extend workflow integration test to include creating a pipeline
- [ ] Extend workflow integration test to include creating a runner
- [ ] Unit tests for automate-workflow-ctl
- [ ] Integration tests for automate-workflow-ctl
- [ ] Unit tests for automate-workflow-web
- [ ] e2e tests for automate-workflow-web
- [ ] schema tests for automate-workflow-server
- [ ] dialyzer for automate-workflow-server

**Comment by susanev** [comment]
@stevendanna can we close this? or is there still value in doing this work?

**Comment by stevendanna** [comment]
Given that the plan is to remove workflow from automate in a few months, I think we can close this as the work is incredibly unlikely to happen.
