### ISSUE TITLE
add policy table reference to roles table

### ISSUE THREAD

**Issue by susanev** [chef/automate#820]
## Overview

A policy's Role shouldn't just be a random string - it should actually reference our existing roles in the database.

adding a reference should look something like this:

```
ALTER TABLE iam_roles ADD PRIMARY KEY (id);
ALTER TABLE iam_statements ADD FOREIGN KEY (role) REFERENCES iam_roles;
```

Note: there might already be statements using roles and that means there might be roles in statements that are not valid IDs, so just adding the constraint could cause migrations to fail.

solution: on migration, drop invalid roles if it's the only role in the statement and there are no actions then drop the statement entirely. we might also add a constraint that drops policies with empty statements

though it's not the nicest UX, we are in beta.

### Related issue: [Logically propagate deleted projects within policies](https://chefio.atlassian.net/browse/A2-797)
When a policy loses its last statement because all the statements projects were deleted, the policy should be dropped.

### Potential solution
We could add a constraint or trigger to the policies table that drops policies with empty statements, which could be triggered by any of the various actions that render a policy useless

**Comment by blakestier** [comment]
Closing in favor of #832
