### ISSUE TITLE
Handle empty project list in statement correctly for v2.0 and v2.1

### ISSUE THREAD

**Issue by susanev** [chef/automate#821]
## Overview

In v2.0, users creating policy statements shouldn't need to care about projects, but in v2.1 an empty projects list in a policy statement results in an invalid policy statement (because it would not be applied to anything).

Update the create and update policy APIs to check if the mode is v2.0 or v2.1 and behave the following way:

If not v2.1 (since you can still access the v2.x APIs if v1.0) and there is an empty project list passed to a policy statement, then create or update the policy statement to have a projects list of ["*"].

if v2.1 and there is an empty project list passed to a policy statement, return 400 Bad Request because that is not a valid policy statement in v2.1.

Lastly, we should write a v2 data migration that converts any invalid policy statement that has an empty projects list to  ["*"] so that we don't have any invalid policy statements anymore (and now we can't create invalid policy statements so we are safe).

**Comment by srenatus** [comment]
This was part of the _last_ release. I believe this has been sufficiently acceptance tested in the last round. No idea why the card is still in this column.
