### ISSUE TITLE
Control Tag Search & Filter [Customers can search for nodes by tag]

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#827]
## What problem are we solving?

Users of the Compliance section in Automate need to be able to see if their scan jobs are compliant with a given set of standards. To simplify their search on the scan jobs, Automate needs the ability to search and return with a defined text. For example, if a user wants to only see scan jobs that are related to AC-3, then they should be able to filter the full list of scans on that key.

## Objective and Key Results

**Objective** | **Key Results**
-|-
Ability to filter scan jobs|- Users can filter on scan jobs by tagging assigned in the compliance profiles

## Evidence

- See comments in Aha! for list of customers

## Dependencies

- Tagging capability has been added to compliance profiles
- UX has worked with product to finalize designs of the page

## Acceptance Criteria

- Filter will support autosuggestions and wildcard
- See UX screenshots for returned values
- Filter is respected on all compliance reporting API calls
- **TEST SCENARIO:**

    - create a profile with various control tags
    - run a scan with that profile, reporting to automate (scan job or audit cookbook or InSpec direct)
    - run a scan on a different node with another profile
    - filter by a tag key/value included in the profile: check expected vs actual results

## Open Questions

Aha! Link: https://chef.aha.io/epics/A2-E-118

**Comment by vjeffrey** [comment]
Comment added by Lisa Stidham in Aha! - [View](https://chef.aha.io/comments/6722827126906784652)

End of year for NGA

**Comment by jonong1972** [comment]
https://github.com/chef/automate/issues/1311
this part of this epic?  Wasnt sure how GitHub links issues with Epics. So putting this here for now.

**Comment by vjeffrey** [comment]
ya, 1311 is listed as part of the epic
