### ISSUE TITLE
modify automate code to work with license accept changes from inspec

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#83]
# User Story

InSpec will soon require users to accept the license by using one of the following methods:
```
* Interactively agree to license (not practical here, I think)
* run with the option `--chef-license accept`
* create the file `/etc/chef/accepted_licenses/inspec` or `~/.chef/accepted_licenses/inspec` . The file may be empty.
```

This will be needed for all the inspec commands, such as `json`, `check`, `detect`, and `exec`.

This change will also be modifying the stdout format. Please see https://github.com/chef/license-acceptance/issues/23 for more information.

These changes will affect: profile upload, profile json-ing, detect jobs, and scan jobs.

# Definition of Done
Able to run Automate as always with the new license acceptance functionality.

A gem of the new InSpec functionality is available here: http://artifactory.chef.co:8081/webapp/#/artifacts/browse/tree/General/omnibus-gems-local/gems/inspec-4.0.6.gem

We've requested a hab pkg for testing as well.

**Comment by clintoncwolfe** [comment]
https://github.com/chef/license-acceptance/pull/26 has merged; use the option `--chef-license accept-silent` to accept the license and preserve clean JSON output.

**Comment by alexpop** [comment]
Thank you @clintoncwolfe.
What do you think of [this](https://github.com/chef/automate/pull/95) approach in Automate?

**Comment by vjeffrey** [comment]
we will have to do something for the remote (ssm) jobs as well: https://github.com/chef/automate/blob/master/components/compliance-service/inspec-agent/remote/remote.go

**Comment by vjeffrey** [comment]
https://chefio.slack.com/archives/CGP1CVDAL/p1555522812041400
```
tball [12:51]
@vj Y’all are kicking off the remote `inspec` command, correct? If so could you run `inspec --chef-license accept-no-persist` or `CHEF_LICENSE=accept-no-persist inspec`? Then you don’t have to worry about manually creating that file, and if the format for the file changes it won’t break you


vj [12:51]
oooh interesting. ok ya we could do that — thank you!!

tball [12:52]
`accept-no-persist` also won’t output anything on stdout, so it shouldn’t affect the JSON response
```

**Comment by jasonbellack** [comment]
The required step of accepting the license seems to be interfering with AWS State Manager. When attempting to run aws-RunInspecChecks on an instance, I am receiving this error: 
/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/json-2.2.0/lib/json/common.rb:156:in `parse': 434: unexpected token at '-06-12T12:34:41+00:00] ERROR: InSpec cannot execute without accepting the license (JSON::ParserError)

Is there a way to address this in order to run compliance checks on my instances using Inspec? Thank you!

**Comment by vjeffrey** [comment]
@jasonbellack i am not super familiar with aws-RunInspecChecks -- do you have access to the actual inspec command at all in that scenario?  if so, it should be as easy as adding `--chef-license accept-silent` to the command.

**Comment by jasonbellack** [comment]
@vjeffrey the actual inspec command is baked into the process of using AWS-SSM to run profiles. I was able to create the file /etc/chef/accepted_licenses/inspec on the instance as you suggested and that fixed the issue. I need to now automate that process as part of the compliance checks. Thank you!!
