### ISSUE TITLE
Improve consistency in DB code amongst auth entities

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#830]
## User Story

As a Developer, I will use this work when I want to understand how we filter projects.

Audited where project filtering is handled on each auth entity:

![image-2019-04-29-09-31-57-237.png](https://images.zenhubusercontent.com/5d236338fa967b04b3b34e1d/bb3c959a-156b-4b8d-a196-4dc23634f71b)

Reviewing the above I came up with this set of choices as to how to make the above more consistent and thereby make our code easier to maintain.

![image-2019-04-29-09-32-49-074.png](https://images.zenhubusercontent.com/5d236338fa967b04b3b34e1d/d8ee0955-983e-46b4-a50f-98f18f99d76f)
 
Consensus seemed to be that (a) is most desirable, which entails the following work.

## Definition of Done

Stage 1 – most consistency gains

Roles: Replace `checkIfRoleIntersectsProjectsFilter` with inline calls to `projects_match`. The code includes a check to call `processError` which will generate a 404 appropriately if project is filtered out.

Policies: For `Delete` and `Update` remove calls to `p.queryPolicy` and add inline calls to `projects_match`. 

Stage 2 – fine-tuning: have everyone use RowsAffected instead of relying on `processError`:

This entails adding a check for `RowsAffected` after the DB for get/update/delete for each entity (role/policy/project/team/token), hence a total of 15 sites. Note that projects and tokens partially use `RowsAffected` already. The goal is to do this for all 15 occurrences.

**Comment by srenatus** [comment]
I've got ideas for making this neater that are different from stage 1 and stage 2. Will outline before this comes up.

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
