### ISSUE TITLE
automate-workflow-nginx port is not configurable, not listed in `dev ports list`

### ISSUE THREAD

**Issue by stevendanna** [chef/automate#896]
## Describe the bug

`automate-workflow-nginx` listens on port 10300 (non-TLS!) and 10301 (TLS) but neither of these ports are configurable via `chef-automate config` and neither of these ports show up in `chef-automate dev ports list`.

## Expected behavior

- automate-workflow-nginx should only listen on TLS, thus port 10300 should not be needed by default.
- automate-workflow-nginx's listen port should be configurable
- automate-workflow-nginx's listen port configuration should be annotated so it is properly listed in our dev tools

**Comment by susanev** [comment]
deprioritized, so closing.
