### ISSUE TITLE
CIS AWS Foundations Benchmark Level 1 max password age condition

### ISSUE THREAD

**Issue by bastien-jove-cbp** [chef/automate#908]
## Describe the bug
Control 1.11 is marked as failed if the password max age is 5.

According to the control description:

> It is recommended that the password policy expire passwords after 90 days or less.

I assume the test  `its('max_password_age_in_days') { should be >= 90 }` should have `<=` instead of `>=`
## Versions (please complete the following information):
- Automate Build Number 20190501153509
- Profile version: 1.1.0-7

## Additional context
I know those profiles are under another repo, just a convenient way to surface the issue.

**Comment by stevendanna** [comment]
Thanks for the report!  I've filed this in with the compliance-profiles repository as https://github.com/chef/compliance-profiles/issues/1259

(cc @james-stocks)

**Comment by skpaterson** [comment]
Just to confirm, this issue is resolved in the new CIS AWS v1.0.0 L1 & L2 profiles.

**Comment by vjeffrey** [comment]
closing, thank you!
