### ISSUE TITLE
Waivers in Automate: slice one [Customer can view the controls that have been exempted in a compliance scan report]

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#912]
## What problem are we solving?

Customers of InSpec want the capability to waive certain controls when running compliance reports. They want to do this because sometimes the controls do not necessarily apply to their current process. Users want to understand which controls have been waived and why.

To support this in the Automate UI we will show a control list showing which are waived.

1. What is the difference between waivers and skip?

    1. A waiver lets you still report data on a particular control while preventing it from causing a run failure or affecting your compliance percentages where a skip doesn’t run the control at all. Waivers will show up in reporting where skipped won't appear
    2. When defending in an audit, having the additional metadata (like justification, approver(s), etc.) provides additional evidence that you are doing what you said you would do.
2. How are waivers calculated in the overall scheme of compliance percentage?

    1. They do not impact compliance percentage

## Objective and Key Results

Objective|Key Results
-|-
Enhance InSpec report|User is able to see which controls are waived

## Evidence

- A handful of customers have requested this feature

## Dependencies

- Control that will be waived, End date, Optional text field for justification need to be provided from the InSpec dev team

## Acceptance Criteria

Compliance Tab

- Overview
- - Node status

          - Waiver count is added
          - Node Status over time, add waiver
    - Profile Status

          - Control Status, waiver count is added
          - Control status over time, add waiver
    - Total count of Nodes would count a node even if everything is waived
- Nodes
- - A new box for Waived
    - Scan results under … box, waived items should show
    - Control failures

          - Waived does not impact this count
    - Select a node

          - Control, the icon is the same logic as profiles
          - Top box, for profiles add Waived value
          - Filter boxes add waived
          - Select node

                  - Control, the icon is the same logic as profiles
          - Scan History, waived?
- Profiles
- - Icon next to status name

          - If all waived the icon is a waived icon
          - If skipped plus waived, icon is skipped icon
          - If pass and fail, icon is failed
          - If all passed, icon is passed
    - Select a profile, under Test Results waived would show up there
- Controls
- - Node status there will be a waived node count

          - Hover over waived status, there will be a description on why it was waived and end date if there is one. And the status (if they choose to run it)
- **TEST SCENARIO:**
- - run a scan with a waiver, on the command line

    - send the report into automate
    - take a look at the report
    - ensure the excepted controls did not negatively affect report status
    - ensure the reasons the controls were excepted are visible

## Out of Scope

- Ability to waive controls within the Automate UI
- Ability to search by waived controls

## Open Questions

Aha! Link: https://chef.aha.io/epics/A2-E-148

**Comment by vjeffrey** [comment]
@alexpop what are the cards we can cut for this epic now that we've done some discovery?  maybe a card for the es changes/migrations, a few for the api changes to return the waivers info, and more for filtering by waived status?  thoughts?  it would be awesome to have those cards written out before our next planning meeting on november 12th

**Comment by alexpop** [comment]
1. ElasticSearch data model change, data migration and ingestion logic change

2. API changes to take into account the wavinging of controls, profiles and reports. These need to be paired with the matching UI changes in order to avoid showing inconsistent numbers.

* Stats  Summary
* Stats
* Nodes Trend
* Controls Trend
* Control List
* Nodes
* Profiles
* Reports

Regarding filtering,  are you thinking to filter for waived profiles or waived nodes? Probably worth creating just one card for now on this and breaking it down into multiple cards as we understand better the requirements and possibilities.

**Comment by vjeffrey** [comment]
for the filtering part i was referring to the designs, where there are those little status filtering buttons above the table rows.
"need to be paired with the matching UI changes" <-- i think we can probably be flexible on this. we don't expect many ppl to be using the waivers yet, and can explain away inconsistencies for the few who are.  i don't wanna tie the backend work to the ui work unless the ui work will be done by superteam
