### ISSUE TITLE
IAMv2: fix blind spots in testing (also v2.1)

### ISSUE THREAD

**Issue by srenatus** [chef/automate#932]
I believe these are things we have the means to test, but currently don't test:

1. Upgrades: not tested pre-merge, only implicitly by having the IAM v2 and v2.1 dev/acceptance envs.
2. Backup/restore: not tested with IAMv2 in any way -- we're likely OK, since all that happens is in the database, but that's incidential, we're not testing this.
3. Diagnostics tests don't cover any v2 API for users/teams, also, they're using a v1 admin token. (If tests using the diagnostics framework don't migrate v1 policies, those won't work.)

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
