### ISSUE TITLE
expose SAML NameIDPolicyFormat config option

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#937]
## User Story

As an Automate User, I will use this work when I want to configure Automate authentication with SAML.

Problem: 
From @andy-dufour in slack:
```
Hi all, having some issues getting saml setup with a customer, 
they're having some issues with the name field: 
"We are providing name identifier in the this format: 
urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified 

and Chef Automate is expecting in this format: 
urn:oasis:names:tc:SAML:2.0:nameid-format:persistent. 
We do not have the option to modify it."
```

## Definition of Done
- SAML can be optionally configured with a [NameIDPolicyFormat](https://github.com/dexidp/dex/blob/master/connector/saml/saml.go#L115) with [these input options](https://github.com/dexidp/dex/blob/master/connector/saml/saml.go#L27-L35)

## Demo Script / Repro Steps
1. save the following config in a `test.toml` file
```
[dex.v1.sys.connectors.saml]
name_id_policy_format = "unspecified" // or any other option dex accepts
```
2. run 
``` 
chef-automate config patch test.toml
```
3. If we can get more details about the customer's failing config, we could try to repro their issue and see if this config patch fixes it

**Comment by srenatus** [comment]
Since there's a difference in the SAML version in the URNs [here](https://github.com/dexidp/dex/blob/master/connector/saml/saml.go#L27-L35), I'd prefer we exposed URNs, not the last part of them. So, demo script step 1 would be:
```toml
[dex.v1.sys.connectors.saml]
name_id_policy_format = "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
```
I guess anyone dealing with SAML regularly (i.e. out customers) will not be surprised about these...

**Comment by srenatus** [comment]
Is this a bug or an enhancement? @bcmdarroch
