### ISSUE TITLE
Cypress: Policy UI

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#974]
## User Story

As a Developer, I will use this work when I want to automate acceptance testing.

## Definition of Done
The Policy UI scenarios from the [Acceptance Testing Script](https://docs.google.com/spreadsheets/d/1mV8dAARhBFxxMZR6gEm1yDXnPqHb9U2mPhZ-zhHLajw/edit?usp=sharing) are covered by automated Cypress tests.

- [ ] List view
- [ ] Delete policy
- [ ] Details view
- [ ] Copy policy definition

**Comment by susanev** [comment]
this work has been deprioritized.
