### ISSUE TITLE
Cypress: Policy Member UI 

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#975]
## User Story

As a Developer, I will use this work when I want to automate acceptance testing.

## Definition of Done
The Policy Membership UI scenarios from the [Acceptance Testing Script](https://docs.google.com/spreadsheets/d/1mV8dAARhBFxxMZR6gEm1yDXnPqHb9U2mPhZ-zhHLajw/edit?usp=sharing) are covered by automated Cypress tests.

- [ ] Removing a member to a policy.
- [ ] Adding a policy member.

**Comment by susanev** [comment]
this work has been deprioritized.
