### ISSUE TITLE
Cypress: Projects UI

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#976]
## User Story

As a Developer, I will use this work when I want to automate acceptance testing.

## Definition of Done
The Projects UI scenarios from the [Acceptance Testing Script](https://docs.google.com/spreadsheets/d/1mV8dAARhBFxxMZR6gEm1yDXnPqHb9U2mPhZ-zhHLajw/edit?usp=sharing) are covered by automated Cypress tests.

- [ ] List view
- [ ] Details view
- [ ] Create a project
- [ ] Update a project
- [ ] Delete a project
- [ ] Details view
- [ ] List project rules
- [ ] Create a project rule
- [ ] Update a project rule
- [ ] Delete a project rule
- [ ] Update Projects with latest rule edits

**Comment by susanev** [comment]
this work has been deprioritized.
