### ISSUE TITLE
Cypress: Tokens UI

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#978]
## User Story

As a Developer, I will use this work when I want to automate acceptance testing.

## Definition of Done
The Tokens UI scenarios from the [Acceptance Testing Script](https://docs.google.com/spreadsheets/d/1mV8dAARhBFxxMZR6gEm1yDXnPqHb9U2mPhZ-zhHLajw/edit?usp=sharing) are covered by automated Cypress tests.

- [ ] Add an API Token with a name
- [ ] Copy an API Token
- [ ] Deactivate an API Token
- [ ] Activate an API Token after deactivating
- [ ] Delete an API Token

**Comment by susanev** [comment]
this work has been deprioritized.
