### ISSUE TITLE
authz introspection: add a /whoami endpoint, wire it up in a2-api-integration using different authn methods

### ISSUE THREAD

**Issue by msorens** [chef/automate#985]
_[Migrated from Jira -- originally reported by @srenatus on 2018.07.25]_

With adding service certs for authentication, the authn story became a bit more complicated. To accommodate that, we should add some kind of integration test. This is how it could look like:

1. add a /whoami endpoint which returns the subjects of an incoming request

2. add a2-api-integration tests that call this endpoint using different ways of authenticating:

    a. an id_token
    b. an API token
    c. a cert...
    and verify that the outcome is as expected.

Followup comment, @srenatus, July 27, 2018, 5:09 AM
Jay has already committed some cert-based-authn test, so this isn’t too urgent anymore

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
