### ISSUE TITLE
Create library to re-ruse authz's sql / pq error handling in other auth pg codebases

### ISSUE THREAD

**Issue by msorens** [chef/automate#988]
_[Migrated from Jira -- originally reported by @tylercloke  on 2019.02.01 ]_

Let's pull some of our postgres error handling code into a library and re-use it (API tokens is one spot we've copy-pasta'ed this). Any other pg code we can share?

https://github.com/chef/a2/blob/master/components/authz-service/storage/postgres/postgres.go#L51-L83

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
