### ISSUE TITLE
Improve ID behavior for update functions for local users

### ISSUE THREAD

**Issue by msorens** [chef/automate#989]
_[Migrated from Jira -- originally reported by @tylercloke  on 2018.08.09 ]_

Ok, unfortunately ID is not returned by Dex in UpdatePassword. We currently have ID being returned as part of our update contract for the gateway API. The only way we are currently populating that is by passing back to the user exactly what they gave us. I agree this isn't ideal, but we have a few options that aren't ideal either:

1. Call ListPasswords on every update, find our user, and populate the ID field, then deprecate the ID field as in input into our update APIs.
2. Break our public API (not an option afaik).
3. Wait until my GetPassword API merges into Dex and call that on every update to get the ID, then deprecate the ID field as in input into our update APIs.Regardless, I think this PR is already way too big and we should just keep both update APIs consistent for this PR. If we want to take any of the above actions, we can do so in a separate PR.

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
