### ISSUE TITLE
Protobuf field names with underscore are unreliable

### ISSUE THREAD

**Issue by msorens** [chef/automate#992]
_[Migrated from Jira -- originally reported by @msorens  on 2018.11.24 ]_

With `curl` a name containing an underscore is serialized properly but with `grpcurl` it is not.
Thus, you actually get different output depending on which command you use.

The illustration shows the issue at a glance:
 
![image.png](https://images.zenhubusercontent.com/5d07f7b39943fc312156c891/531f8bef-75ee-4f36-87fb-af22da80a442)

A quick search of the code base revealed that this issue is present in another protobuf field (`created_at`) that has been part of A2 for awhile. This occurs in 4 proto files, 3 of which are under the auspices of the auth team, so I can say that those 3, while present, are not actually being used. I cannot speak to the one in the deployment project. The next illustration shows how the error came about: there are two json specifications in the generated *.pb.go file!

![image.png](https://images.zenhubusercontent.com/5d07f7b39943fc312156c891/2a0da7af-4a71-4191-a8bc-fc0e42a268a2)

### Seth Falcon, November 5, 2018, 8:23 AM

I think the bug title is misleading. The underscore isn't the issue, but rather having duplicated struct tags is unreliable.

**Comment by srenatus** [comment]
If this is a valid UX issue, it's an issue with grpcurl. This has nothing to do with protobuf; the question is whether you using `jsonpb.Marshaler` with `OrigName` true or false, [see here](https://godoc.org/github.com/golang/protobuf/jsonpb#Marshaler). Grpcurl has a different setting then what we configure with grpc-gateway. 🤷‍♂ 😉

**Comment by srenatus** [comment]
Proposed solution: wontfix 😉

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
