### ISSUE TITLE
Client Runs: Run History counts not sync with listed items.

### ISSUE THREAD

**Issue by vsingh-msys** [chef/automate#995]
## Describe the bug
On node detail page run history counts do not match with listed items. As we have total count, success count, and failed count icons but after clicking of respective icon listed item showing correctly but counts showed old one.

## To Reproduce
- Setup Standalone setup of A2 and chef-server.
- Configure the data collector.
- Setup knife with chef-server.
- Add/Bootstrap a node with some run list.
- Go to `client runs` -> `click on any node item` -> `click on Run history`
- Run multiple times `chef-client` on the node.
- Click on count icons.
    
## Expected behavior
It should get refresh once click on the icons as listed items fetched.

## Screenshots
![Screenshot from 2019-07-22 13-03-26](https://user-images.githubusercontent.com/44496937/61615039-bc83f000-ac82-11e9-93ae-24933ee96928.png)
![Screenshot from 2019-07-22 12-39-25](https://user-images.githubusercontent.com/44496937/61615040-bc83f000-ac82-11e9-8cd5-20f90f8d103e.png)

## Versions (please complete the following information):
- OS: Ubuntu 16.04
- Browser: Firefox
- Automate Build Number: 20190711110747

**Comment by vjeffrey** [comment]
we need to check if this is a ui or backend bug

**Comment by vsingh-msys** [comment]
@vjeffrey I have verified it seems this is a UI issue will create PR and update you accordingly. Thanks
